// Generated by Copilot
export {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  StatusBadge,
  ActionButton,
  PrimaryButton,
  TabBar,
  TabItem,
} from "../HRPortal/styles";
