// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { ibpTheme as _theme } from "@ui/ui-lib";

// ─── Drawer Header ─────────────────────────────────────────────────────────────
export const DrawerHeaderRoot = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(2),
    padding: theme.spacing(2, 2.5),
    backgroundColor: theme.palette.background.paper,
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    flexShrink: 0,
}));

export const DrawerAvatarBox = styled(Box)(({ theme }) => ({
    width: 42,
    height: 42,
    borderRadius: theme.shape.borderRadii.medium,
    background: `linear-gradient(135deg, ${theme.palette.secondary.selected}, #1E6FC4)`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
}));

export const DrawerAvatarText = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.sm,
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.palette.neutral.veryLight,
}));

export const DrawerEmpProfileLabel = styled(Typography)(({ theme }) => ({
    fontSize: "9px",
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.text.grey,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
}));

export const DrawerEmpNameText = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.sm,
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.palette.neutral.mediumDark,
    lineHeight: 1.3,
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
}));

export const EnrollStatusChip = styled(Box, {
    shouldForwardProp: (p) => p !== "enrollStatus",
})<{ enrollStatus: string }>(({ theme, enrollStatus }) => {
    const map: Record<string, { bg: string; color: string }> = {
        Enrolled: {
            bg: theme.palette.background.tabsSelected,
            color: theme.palette.secondary.selected,
        },
        Active: {
            bg: theme.palette.background.tabsSelected,
            color: theme.palette.neutral.green,
        },
        Pending: {
            bg: theme.palette.chips.ternary + "30",
            color: theme.palette.text.yellow,
        },
        Expired: {
            bg: theme.palette.chips.secondary + "18",
            color: theme.palette.text.error,
        },
    };
    const s = map[enrollStatus] ?? {
        bg: theme.palette.background.tableHeader,
        color: theme.palette.text.grey,
    };
    return {
        padding: theme.spacing(0.375, 1.5),
        borderRadius: 20,
        backgroundColor: s.bg,
        color: s.color,
        fontSize: theme.typography.fontSizes.xs,
        fontWeight: theme.typography.fontWeights.semiBold,
        whiteSpace: "nowrap" as const,
    };
});

// ─── Enrollment Stepper ────────────────────────────────────────────────────────
export const StepperRoot = styled(Box)(({ theme }) => ({
    padding: theme.spacing(2, 2.5),
    backgroundColor: theme.palette.background.paper,
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    flexShrink: 0,
}));

export const StepperTitle = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.medium,
    marginBottom: theme.spacing(1.5),
}));

export const StepCircle = styled(Box, {
    shouldForwardProp: (p) => p !== "isDone" && p !== "isCurrent" && p !== "stepColor",
})<{ isDone?: boolean; isCurrent?: boolean; stepColor?: string }>(
    ({ isDone, isCurrent, stepColor }) => ({
        width: 28,
        height: 28,
        borderRadius: "50%",
        border: "2px solid",
        borderColor: stepColor ?? "#E5E7EB",
        backgroundColor: isDone ? (stepColor ?? "#CCCCCC") : "#FFFFFF",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        boxShadow: isCurrent ? `0 0 0 3px ${stepColor ?? "#CCCCCC"}30` : "none",
        transition: "all 0.15s ease",
    }),
);

export const StepNumberText = styled(Typography, {
    shouldForwardProp: (p) => p !== "isFuture" && p !== "stepColor",
})<{ isFuture?: boolean; stepColor?: string }>(({ isFuture, stepColor }) => ({
    fontSize: "10px",
    fontWeight: 700,
    color: isFuture ? "#D1D5DB" : (stepColor ?? "#CCCCCC"),
}));

export const StepLabelText = styled(Typography, {
    shouldForwardProp: (p) => p !== "isFuture" && p !== "isCurrent" && p !== "stepColor",
})<{ isFuture?: boolean; isCurrent?: boolean; stepColor?: string }>(
    ({ isFuture, isCurrent, stepColor }) => ({
        fontSize: "8px",
        fontWeight: 600,
        textAlign: "center" as const,
        lineHeight: 1.2,
        maxWidth: 56,
        color: isFuture ? "#9CA3AF" : isCurrent ? (stepColor ?? "#CCCCCC") : "#6B7280",
    }),
);

export const StepConnectorLine = styled(Box, {
    shouldForwardProp: (p) => p !== "isDone" && p !== "fromColor",
})<{ isDone?: boolean; fromColor?: string }>(({ isDone, fromColor }) => ({
    flex: 1,
    height: 2,
    marginLeft: 4,
    marginRight: 4,
    marginBottom: 20,
    borderRadius: 1,
    backgroundColor: isDone ? (fromColor ?? "#CCCCCC") : "#E5E7EB",
    minWidth: 8,
    transition: "background-color 0.15s ease",
}));

// ─── KPI Strip ─────────────────────────────────────────────────────────────────
export const KPIStripRoot = styled(Box)(({ theme }) => ({
    padding: theme.spacing(1.5, 2.5),
    backgroundColor: theme.palette.background.paper,
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    flexShrink: 0,
}));

export const KPICardRoot = styled(Box, {
    shouldForwardProp: (p) => p !== "cardBg" && p !== "cardBorder",
})<{ cardBg?: string; cardBorder?: string }>(({ theme, cardBg, cardBorder }) => ({
    backgroundColor: cardBg ?? theme.palette.background.tableHeader,
    border: `1px solid ${cardBorder ?? theme.palette.neutral.tableBorder}`,
    borderRadius: theme.shape.borderRadii.medium,
    padding: theme.spacing(1.25, 1.5),
    display: "flex",
    alignItems: "flex-start",
    gap: theme.spacing(1),
}));

export const KPICardIconBox = styled(Box, {
    shouldForwardProp: (p) => p !== "iconColor",
})<{ iconColor?: string }>(({ iconColor }) => ({
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: (iconColor ?? "#CCCCCC") + "20",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: iconColor ?? "#CCCCCC",
    flexShrink: 0,
    marginTop: 2,
}));

export const KPICardValue = styled(Typography, {
    shouldForwardProp: (p) => p !== "valueColor",
})<{ valueColor?: string }>(({ theme, valueColor }) => ({
    fontSize: theme.typography.fontSizes.md,
    fontWeight: theme.typography.fontWeights.bold,
    color: valueColor ?? theme.palette.neutral.mediumDark,
    lineHeight: 1.2,
}));

export const KPICardLabel = styled(Typography)(({ theme }) => ({
    fontSize: "9px",
    fontWeight: theme.typography.fontWeights.medium,
    color: theme.palette.text.grey,
    marginTop: theme.spacing(0.25),
}));

export const KPICardSubLabel = styled(Typography)(({ theme }) => ({
    fontSize: "9px",
    color: theme.palette.neutral.lightMedium,
}));

// ─── View Full Profile Button ──────────────────────────────────────────────────
export const ViewProfileButton = styled(Box)(({ theme }) => ({
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(1),
    padding: theme.spacing(1.25),
    marginBottom: theme.spacing(2.5),
    borderRadius: theme.shape.borderRadii.medium,
    border: `1.5px solid ${theme.palette.secondary.selected}`,
    backgroundColor: theme.palette.background.tabsSelected,
    color: theme.palette.secondary.selected,
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    cursor: "pointer",
    transition: "all 0.12s ease",
    "&:hover": {
        backgroundColor: theme.palette.secondary.selected,
        color: theme.palette.neutral.veryLight,
    },
}));

// ─── Section Block ─────────────────────────────────────────────────────────────
export const SectionBlockRoot = styled(Box)(({ theme }) => ({
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape.borderRadii.medium,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    overflow: "hidden",
    marginBottom: theme.spacing(2),
}));

export const SectionBlockHeader = styled(Box)(({ theme }) => ({
    padding: theme.spacing(1.5, 2.5),
    borderBottom: `1px solid ${theme.palette.background.tableHeader}`,
    backgroundColor: theme.palette.background.tableHeader,
}));

export const SectionBlockTitle = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
}));

// ─── Info Row ──────────────────────────────────────────────────────────────────
export const InfoRowRoot = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "flex-start",
    gap: theme.spacing(1.25),
}));

export const InfoIconBox = styled(Box)(({ theme }) => ({
    width: 28,
    height: 28,
    borderRadius: theme.shape.borderRadii.small,
    backgroundColor: theme.palette.background.tableHeader,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 2,
    color: theme.palette.text.grey,
}));

export const InfoFieldLabel = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.text.grey,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
}));

export const InfoFieldValue = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
    lineHeight: 1.4,
    marginTop: theme.spacing(0.25),
    wordBreak: "break-word" as const,
}));

// ─── Dependents ────────────────────────────────────────────────────────────────
export const DependentRowRoot = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing(1.5, 2),
    borderRadius: theme.shape.borderRadii.medium,
    backgroundColor: theme.palette.background.tableHeader,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
}));

export const DependentAvatar = styled(Box)(({ theme }) => ({
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: `linear-gradient(135deg, ${theme.palette.neutral.green}, #065F5A)`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
}));

export const DependentAvatarText = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.palette.neutral.veryLight,
}));

export const DependentName = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
}));

export const DependentMeta = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    color: theme.palette.text.grey,
}));

export const DependentCovLabel = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    color: theme.palette.text.grey,
}));

export const DependentCovValue = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.palette.neutral.green,
}));

// ─── Claims History ────────────────────────────────────────────────────────────
export const ClaimsCardRoot = styled(Box)(({ theme }) => ({
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape.borderRadii.medium,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    overflow: "hidden",
    marginBottom: theme.spacing(2),
}));

export const ClaimsCardHeader = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing(1.5, 2.5),
    borderBottom: `1px solid ${theme.palette.background.tableHeader}`,
    backgroundColor: theme.palette.background.tableHeader,
}));

export const ClaimsCardTitle = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
}));

export const ClaimsTotalLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.text.grey,
}));

export const ClaimTableTh = styled("th")(({ theme }) => ({
    padding: theme.spacing(1.25, 1.5),
    textAlign: "left" as const,
    fontSize: "10px",
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.text.grey,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    whiteSpace: "nowrap" as const,
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    backgroundColor: "#F8FAFC",
}));

export const ClaimTableTd = styled("td")(({ theme }) => ({
    padding: theme.spacing(1.25, 1.5),
    borderBottom: `1px solid ${theme.palette.background.tableHeader}`,
    fontSize: theme.typography.fontSizes.xs,
    color: theme.palette.neutral.medium,
    verticalAlign: "middle" as const,
}));

export const ClaimPolicyNo = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    fontFamily: "monospace",
    color: theme.palette.secondary.selected,
    whiteSpace: "nowrap" as const,
}));

export const ClaimHospitalIconBox = styled(Box)(({ theme }) => ({
    width: 22,
    height: 22,
    borderRadius: theme.shape.borderRadii.small,
    backgroundColor: theme.palette.background.tabsSelected,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
}));

export const ClaimHospitalName = styled(Typography)(({ theme }) => ({
    fontSize: "11px",
    fontWeight: theme.typography.fontWeights.medium,
    color: theme.palette.neutral.mediumDark,
    maxWidth: 80,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
}));

export const ClaimHospitalDisease = styled(Typography)(({ theme }) => ({
    fontSize: "9px",
    color: theme.palette.text.grey,
}));

export const ClaimTypeBadge = styled(Box, {
    shouldForwardProp: (p) => p !== "claimType",
})<{ claimType?: "Cashless" | "Reimbursement" }>(({ theme, claimType }) => ({
    display: "inline-block",
    padding: theme.spacing(0.25, 1.25),
    borderRadius: 20,
    fontSize: "10px",
    fontWeight: theme.typography.fontWeights.semiBold,
    backgroundColor:
        claimType === "Cashless"
            ? theme.palette.kpiColors.purple
            : theme.palette.kpiColors.teal,
    color:
        claimType === "Cashless"
            ? "#7C3AED"
            : theme.palette.neutral.green,
    whiteSpace: "nowrap" as const,
}));

export const ClaimStatusBadge = styled(Box, {
    shouldForwardProp: (p) => p !== "claimStatus",
})<{ claimStatus?: string }>(({ theme, claimStatus }) => {
    const map: Record<string, { bg: string; color: string }> = {
        Paid: { bg: theme.palette.background.tabsSelected, color: theme.palette.neutral.green },
        Outstanding: { bg: theme.palette.kpiColors.yellow, color: theme.palette.text.yellow },
        Pending: { bg: theme.palette.kpiColors.yellow, color: theme.palette.text.yellow },
        Rejected: { bg: theme.palette.chips.secondary + "18", color: theme.palette.text.error },
        Denied: { bg: theme.palette.chips.secondary + "18", color: theme.palette.text.error },
        Closed: { bg: theme.palette.background.tableHeader, color: theme.palette.secondary.selected },
    };
    const s = map[claimStatus ?? ""] ?? {
        bg: theme.palette.background.tableHeader,
        color: theme.palette.text.grey,
    };
    return {
        display: "inline-block",
        padding: theme.spacing(0.25, 1.25),
        borderRadius: 20,
        fontSize: "10px",
        fontWeight: theme.typography.fontWeights.semiBold,
        backgroundColor: s.bg,
        color: s.color,
        whiteSpace: "nowrap" as const,
    };
});

export const ClaimAmountText = styled(Typography)(({ theme }) => ({
    fontSize: "11.5px",
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
    whiteSpace: "nowrap" as const,
}));

export const ClaimSettledText = styled(Typography)(({ theme }) => ({
    fontSize: "11.5px",
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.green,
    whiteSpace: "nowrap" as const,
}));

// ─── Activity Log ──────────────────────────────────────────────────────────────
export const ActivityDot = styled(Box)(({ theme }) => ({
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: theme.palette.secondary.selected,
    flexShrink: 0,
    marginTop: 5,
}));

export const ActivityAction = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.medium,
    color: theme.palette.neutral.mediumDark,
}));

export const ActivityMeta = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    color: theme.palette.text.grey,
}));
