// Generated by Copilot
import React, { useState } from "react";
import { Box, Typography } from "@mui/material";
import {
  TrendingUp,
  TrendingDown,
  Users,
  FileText,
  Building2,
  Shield,
  Download,
  BarChart2,
  Table2,
} from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
  LineChart,
  Line,
  ComposedChart,
} from "recharts";
import {
  ActionButton,
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
} from "./styles";

// ─── Ring Gauge ───────────────────────────────────────────────────────────────
function RingGauge({
  pct,
  color,
  size = 72,
}: {
  pct: number;
  color: string;
  size?: number;
}) {
  const r = (size - 10) / 2;
  const circ = 2 * Math.PI * r;
  const arc = (pct / 100) * circ;
  return (
    <svg width={size} height={size} style={{ transform: "rotate(-90deg)" }}>
      <circle
        cx={size / 2}
        cy={size / 2}
        r={r}
        fill="none"
        stroke="#F3F7FF"
        strokeWidth={8}
      />
      <circle
        cx={size / 2}
        cy={size / 2}
        r={r}
        fill="none"
        stroke={color}
        strokeWidth={8}
        strokeDasharray={`${arc} ${circ}`}
        strokeLinecap="round"
      />
    </svg>
  );
}

// ─── Spark Line ───────────────────────────────────────────────────────────────
const SPARK_DATA = [10, 14, 12, 18, 15, 20, 22, 19, 24];
function SparkLine({ color }: { color: string }) {
  const data = SPARK_DATA.map((v, i) => ({ i, v }));
  return (
    <ResponsiveContainer width="100%" height={36}>
      <LineChart data={data}>
        <Line
          type="monotone"
          dataKey="v"
          stroke={color}
          strokeWidth={1.5}
          dot={false}
        />
      </LineChart>
    </ResponsiveContainer>
  );
}

// ─── Mock Data ────────────────────────────────────────────────────────────────
type RiskId = "people" | "claim" | "hospital" | "policy";
const RISK_CARDS: {
  id: RiskId;
  label: string;
  metric: string;
  metricSub: string;
  pct: number;
  level: "Low" | "Medium" | "High";
  color: string;
  levelColor: string;
  trend: string;
  trendUp: boolean;
  Icon: React.ElementType;
}[] = [
  {
    id: "people",
    label: "People Risk",
    metric: "438",
    metricSub: "Total Claims",
    pct: 72,
    level: "Medium",
    color: "#338CE5",
    levelColor: "#825905",
    trend: "+3.2%",
    trendUp: true,
    Icon: Users,
  },
  {
    id: "claim",
    label: "Claim Risk",
    metric: "13.8%",
    metricSub: "Rejection Rate",
    pct: 68,
    level: "Medium",
    color: "#338CE5",
    levelColor: "#825905",
    trend: "-1.4%",
    trendUp: false,
    Icon: FileText,
  },
  {
    id: "hospital",
    label: "Hospital Risk",
    metric: "48",
    metricSub: "Partner Hospitals",
    pct: 45,
    level: "Low",
    color: "#079F92",
    levelColor: "#079F92",
    trend: "+2.1%",
    trendUp: true,
    Icon: Building2,
  },
  {
    id: "policy",
    label: "Policy Risk",
    metric: "74.7%",
    metricSub: "Avg Utilisation",
    pct: 81,
    level: "High",
    color: "#825905",
    levelColor: "#E15857",
    trend: "+5.8%",
    trendUp: true,
    Icon: Shield,
  },
];

const CLAIMS_VS_LIVES = [
  { m: "Apr", claims: 28, lives: 1080 },
  { m: "May", claims: 35, lives: 1095 },
  { m: "Jun", claims: 42, lives: 1102 },
  { m: "Jul", claims: 38, lives: 1110 },
  { m: "Aug", claims: 51, lives: 1118 },
  { m: "Sep", claims: 44, lives: 1125 },
  { m: "Oct", claims: 60, lives: 1130 },
  { m: "Nov", claims: 55, lives: 1135 },
  { m: "Dec", claims: 48, lives: 1140 },
  { m: "Jan", claims: 66, lives: 1155 },
  { m: "Feb", claims: 59, lives: 1168 },
  { m: "Mar", claims: 72, lives: 1185 },
];
const AGE_BAND = [
  { band: "18–30", c: 95 },
  { band: "31–40", c: 142 },
  { band: "41–50", c: 118 },
  { band: "51+", c: 83 },
];
const RELATION = [
  { rel: "Self", c: 220 },
  { rel: "Spouse", c: 120 },
  { rel: "Child", c: 68 },
  { rel: "Parent", c: 30 },
];
const TENURE = [
  { t: "0–1 yr", c: 48 },
  { t: "1–3 yr", c: 120 },
  { t: "3–5 yr", c: 142 },
  { t: "5+ yr", c: 128 },
];

type DetailTab = "claims" | "age" | "relation" | "tenure" | "high-risk";

const DETAIL_TABS: { id: DetailTab; label: string }[] = [
  { id: "claims", label: "Claims vs Lives" },
  { id: "age", label: "Age Band" },
  { id: "relation", label: "Relation" },
  { id: "tenure", label: "Tenure" },
  { id: "high-risk", label: "High Risk Employees" },
];

const HIGH_RISK_EMP = [
  {
    id: "EMP003",
    name: "Amit Patel",
    dept: "Engineering",
    claims: 5,
    amount: "₹82,400",
  },
  {
    id: "EMP009",
    name: "Rohit Desai",
    dept: "Operations",
    claims: 4,
    amount: "₹71,200",
  },
  {
    id: "EMP001",
    name: "Rahul Sharma",
    dept: "Sales",
    claims: 4,
    amount: "₹64,800",
  },
  {
    id: "EMP008",
    name: "Kavita Iyer",
    dept: "Finance",
    claims: 3,
    amount: "₹58,500",
  },
  {
    id: "EMP006",
    name: "Deepa Menon",
    dept: "HR",
    claims: 3,
    amount: "₹44,200",
  },
  {
    id: "EMP012",
    name: "Anitha Raj",
    dept: "Sales",
    claims: 2,
    amount: "₹32,100",
  },
];

// ─── Component ────────────────────────────────────────────────────────────────
export function HRPortalInsights() {
  const [activeRisk, setActiveRisk] = useState<RiskId>("people");
  const [detailTab, setDetailTab] = useState<DetailTab>("claims");
  const [viewMode, setViewMode] = useState<"chart" | "table">("chart");

  const selectedCard = RISK_CARDS.find((r) => r.id === activeRisk)!;

  return (
    <Box sx={{ pt: 3 }}>
      {/* Page header */}
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-end",
          mb: 3,
        }}
      >
        <Box>
          <Typography sx={{ fontSize: 24, lineHeight: 1.35, letterSpacing: "-0.3px", fontWeight: 700, color: "#111111" }}>
            Risk Watch
          </Typography>
          <Typography sx={{ fontSize: 15, lineHeight: 1.7, color: "#555555", mt: 0.75 }}>
            FY 2025–26 · GMC · GHI-2025-001 · Last updated 02 Mar 2026
          </Typography>
        </Box>
        <Typography sx={{ fontSize: 15, lineHeight: 1.7, color: "#555555" }}>
          Viewing: {selectedCard.label}
        </Typography>
      </Box>

      {/* Risk cards */}
      <Box
        sx={{
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: 2,
          mb: 0,
        }}
      >
        {RISK_CARDS.map((rc) => {
          const isActive = activeRisk === rc.id;
          return (
            <Box
              key={rc.id}
              onClick={() => setActiveRisk(rc.id)}
              sx={{
                backgroundColor: "#FFFFFF",
                borderRadius: "12px",
                border: isActive
                  ? `2px solid ${rc.color}60`
                  : "1px solid #e5e7eb",
                p: 3,
                cursor: "pointer",
                boxShadow: isActive
                  ? `0 4px 16px ${rc.color}18`
                  : "0 1px 3px rgba(0,0,0,0.06)",
                transition: "all 0.2s",
                "&:hover": {
                  boxShadow: `0 4px 16px ${rc.color}18`,
                  borderColor: `${rc.color}60`,
                },
              }}
            >
              {/* Top row: icon + trend */}
              <Box
                sx={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  mb: 1.5,
                }}
              >
                <Box
                  sx={{
                    width: 32,
                    height: 32,
                    borderRadius: "8px",
                    backgroundColor: `${rc.color}18`,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <rc.Icon size={16} color={rc.color} />
                </Box>
                <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
                  {rc.trendUp ? (
                    <TrendingUp size={12} color="#E15857" />
                  ) : (
                    <TrendingDown size={12} color="#079F92" />
                  )}
                  <Typography
                    sx={{
                      fontSize: 15, lineHeight: 1.7,
                      fontWeight: 600,
                      color: rc.trendUp ? "#E15857" : "#079F92",
                    }}
                  >
                    {rc.trend}
                  </Typography>
                </Box>
              </Box>

              {/* Ring + metric */}
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 2, mb: 1 }}
              >
                <Box
                  sx={{
                    position: "relative",
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <RingGauge pct={rc.pct} color={rc.color} size={68} />
                  <Box sx={{ position: "absolute", textAlign: "center" }}>
                    <Typography
                      sx={{
                        fontSize: 15, lineHeight: 1.7,
                        fontWeight: 800,
                        color: rc.color,
                        lineHeight: 1,
                      }}
                    >
                      {rc.pct}%
                    </Typography>
                  </Box>
                </Box>
                <Box>
                  <Typography
                    sx={{
                      fontSize: 24, lineHeight: 1.35, letterSpacing: "-0.3px",
                      fontWeight: 800,
                      color: "#111111",
                      lineHeight: 1,
                    }}
                  >
                    {rc.metric}
                  </Typography>
                  <Typography
                    sx={{ fontSize: 15, lineHeight: 1.7, color: "#555555", mt: 0.75 }}
                  >
                    {rc.metricSub}
                  </Typography>
                </Box>
              </Box>

              {/* Label + badge */}
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  mb: 1,
                }}
              >
                <Typography
                  sx={{ fontSize: 15, lineHeight: 1.7, fontWeight: 600, color: "#444444" }}
                >
                  {rc.label}
                </Typography>
                <Box
                  sx={{
                    px: 1.25,
                    py: 0.25,
                    borderRadius: "20px",
                    fontSize: 15, lineHeight: 1.7,
                    fontWeight: 700,
                    backgroundColor: `${rc.levelColor}20`,
                    color: rc.levelColor,
                  }}
                >
                  {rc.level}
                </Box>
              </Box>

              {/* Spark line */}
              <SparkLine color={rc.color} />
            </Box>
          );
        })}
      </Box>

      {/* Detail section */}
      <SectionCard
        sx={{
          backgroundColor: "#F3F7FF",
          borderRadius: "0 0 12px 12px",
          p: 3,
          mt: 0,
        }}
      >
        {/* Detail header */}
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: 2.5,
            flexWrap: "wrap",
            gap: 2,
          }}
        >
          <Box>
            <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
              <selectedCard.Icon size={18} color={selectedCard.color} />
              <Typography
                sx={{
                  fontSize: 20, lineHeight: 1.4, letterSpacing: "-0.2px",
                  fontWeight: 700,
                  color: selectedCard.color,
                }}
              >
                {selectedCard.label}
              </Typography>
            </Box>
            <Typography sx={{ fontSize: 15, lineHeight: 1.7, color: "#555555", mt: 0.75 }}>
              Risk Level:{" "}
              <span style={{ fontWeight: 600, color: selectedCard.levelColor }}>
                {selectedCard.level}
              </span>
            </Typography>
          </Box>
          {/* Summary stats */}
          <Box sx={{ display: "flex", gap: 3, flexWrap: "wrap" }}>
            {[
              {
                label: "Risk Score",
                value: `${selectedCard.pct}%`,
                color: selectedCard.color,
              },
              {
                label: "Total Claims",
                value:
                  selectedCard.id === "people"
                    ? "438"
                    : selectedCard.id === "claim"
                    ? "438"
                    : selectedCard.id === "hospital"
                    ? "48"
                    : "438",
                color: "#111111",
              },
              { label: "High Risk Employees", value: "6", color: "#E15857" },
              { label: "Avg Claim Amount", value: "₹52,400", color: "#111111" },
            ].map((s) => (
              <Box key={s.label} sx={{ textAlign: "center" }}>
                <Typography
                  sx={{ fontSize: 20, lineHeight: 1.4, letterSpacing: "-0.2px", fontWeight: 800, color: s.color }}
                >
                  {s.value}
                </Typography>
                <Typography sx={{ fontSize: 15, lineHeight: 1.7, color: "#555555" }}>
                  {s.label}
                </Typography>
              </Box>
            ))}
          </Box>
        </Box>

        {/* Tabs + view toggle */}
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: 2.5,
            borderBottom: "1px solid #e5e7eb",
          }}
        >
          <Box sx={{ display: "flex" }}>
            {DETAIL_TABS.map((t) => (
              <Box
                key={t.id}
                onClick={() => setDetailTab(t.id)}
                sx={{
                  px: 2,
                  py: 1,
                  cursor: "pointer",
                  fontSize: 15, lineHeight: 1.7,
                  fontWeight: detailTab === t.id ? 600 : 400,
                  borderBottom:
                    detailTab === t.id
                      ? `2.5px solid ${selectedCard.color}`
                      : "2.5px solid transparent",
                  color: detailTab === t.id ? selectedCard.color : "#555555",
                  whiteSpace: "nowrap",
                }}
              >
                {t.label}
              </Box>
            ))}
          </Box>
          <Box sx={{ display: "flex", gap: 0.75, mb: 0.75 }}>
            <Box
              onClick={() => setViewMode("chart")}
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 0.5,
                px: 1.5,
                py: 0.5,
                borderRadius: "6px",
                cursor: "pointer",
                fontSize: 15, lineHeight: 1.7,
                fontWeight: 500,
                backgroundColor: viewMode === "chart" ? "#FFFFFF" : "transparent",
                border:
                  viewMode === "chart"
                    ? "1px solid #e5e7eb"
                    : "1px solid transparent",
                color: viewMode === "chart" ? "#111111" : "#555555",
              }}
            >
              <BarChart2 size={13} /> Chart
            </Box>
            <Box
              onClick={() => setViewMode("table")}
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 0.5,
                px: 1.5,
                py: 0.5,
                borderRadius: "6px",
                cursor: "pointer",
                fontSize: 15, lineHeight: 1.7,
                fontWeight: 500,
                backgroundColor: viewMode === "table" ? "#FFFFFF" : "transparent",
                border:
                  viewMode === "table"
                    ? "1px solid #e5e7eb"
                    : "1px solid transparent",
                color: viewMode === "table" ? "#111111" : "#555555",
              }}
            >
              <Table2 size={13} /> Table
            </Box>
            <ActionButton
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 0.5,
                fontSize: 15, lineHeight: 1.7,
                cursor: "pointer",
              }}
            >
              <Download size={12} /> Export
            </ActionButton>
          </Box>
        </Box>

        {/* Chart content */}
        {viewMode === "chart" && detailTab === "claims" && (
          <Box>
            <Typography
              sx={{ fontSize: 15, lineHeight: 1.7, fontWeight: 600, color: "#444444", mb: 1.5 }}
            >
              Claims vs Lives
            </Typography>
            <ResponsiveContainer width="100%" height={240}>
              <ComposedChart data={CLAIMS_VS_LIVES}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                <XAxis
                  dataKey="m"
                  tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  yAxisId="claims"
                  orientation="left"
                  tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  yAxisId="lives"
                  orientation="right"
                  tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                  axisLine={false}
                  tickLine={false}
                  domain={[900, 1300]}
                />
                <RechartTooltip
                  contentStyle={{
                    borderRadius: 8,
                    fontSize: 15, lineHeight: 1.7,
                    border: "1px solid #e5e7eb",
                  }}
                />
                <Bar
                  yAxisId="claims"
                  dataKey="claims"
                  fill={selectedCard.color}
                  radius={[4, 4, 0, 0]}
                  opacity={0.8}
                />
                <Line
                  yAxisId="lives"
                  type="monotone"
                  dataKey="lives"
                  stroke="#079F92"
                  strokeWidth={2}
                  dot={{ r: 3, fill: "#079F92" }}
                />
              </ComposedChart>
            </ResponsiveContainer>
          </Box>
        )}
        {viewMode === "chart" && detailTab === "age" && (
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={AGE_BAND}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis
                dataKey="band"
                tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                axisLine={false}
                tickLine={false}
              />
              <YAxis
                tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                axisLine={false}
                tickLine={false}
              />
              <RechartTooltip />
              <Bar
                dataKey="c"
                fill={selectedCard.color}
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        )}
        {viewMode === "chart" && detailTab === "relation" && (
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={RELATION}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis
                dataKey="rel"
                tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                axisLine={false}
                tickLine={false}
              />
              <YAxis
                tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                axisLine={false}
                tickLine={false}
              />
              <RechartTooltip />
              <Bar
                dataKey="c"
                fill={selectedCard.color}
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        )}
        {viewMode === "chart" && detailTab === "tenure" && (
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={TENURE}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis
                dataKey="t"
                tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                axisLine={false}
                tickLine={false}
              />
              <YAxis
                tick={{ fontSize: 15, lineHeight: 1.7, fill: "#555555" }}
                axisLine={false}
                tickLine={false}
              />
              <RechartTooltip />
              <Bar
                dataKey="c"
                fill={selectedCard.color}
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        )}
        {(viewMode === "table" || detailTab === "high-risk") && (
          <Box sx={{ overflowX: "auto" }}>
            <StyledTable>
              <thead>
                <tr>
                  {[
                    "EMP #",
                    "Name",
                    "Department",
                    "Claims",
                    "Total Amount",
                  ].map((h) => (
                    <StyledTh key={h}>{h}</StyledTh>
                  ))}
                </tr>
              </thead>
              <tbody>
                {HIGH_RISK_EMP.map((e) => (
                  <tr key={e.id}>
                    <StyledTd
                      sx={{
                        color: "#338CE5",
                        fontWeight: 600,
                        fontFamily: "monospace",
                      }}
                    >
                      {e.id}
                    </StyledTd>
                    <StyledTd sx={{ fontWeight: 600, color: "#111111" }}>
                      {e.name}
                    </StyledTd>
                    <StyledTd sx={{ color: "#555555" }}>{e.dept}</StyledTd>
                    <StyledTd sx={{ fontWeight: 600, color: "#E15857" }}>
                      {e.claims}
                    </StyledTd>
                    <StyledTd sx={{ fontWeight: 600 }}>{e.amount}</StyledTd>
                  </tr>
                ))}
              </tbody>
            </StyledTable>
          </Box>
        )}
      </SectionCard>
    </Box>
  );
}

export default HRPortalInsights;
