// Generated by Copilot
export {
  SectionCard,
  SectionTitle,
  KPIGrid,
  KPICard,
  KPILabel,
  KPIValue,
  KPIChange,
  TwoColGrid,
  ThreeColGrid,
  ActionButton,
  StyledTable,
  StyledTh,
  StyledTd,
} from "../HRPortal/styles";
