import type { PolicyDetailPolicyId } from "../HRPortalDashboardV2/types";
import type { PolicyDetailPageData } from "./types";

export const POLICY_DETAIL_PAGE_DATA: Record<
  PolicyDetailPolicyId,
  PolicyDetailPageData
> = {
  ghi: {
    header: {
      policyId: "ghi",
      title: "Group Health Insurance",
      status: "Active",
      statusTone: "success",
    },
    primaryStats: [
      {
        id: "lives",
        label: "Total Lives",
        value: "542",
        tint: "#FFFFFF",
        iconTone: "#DBEAFE",
        icon: "users",
      },
      {
        id: "sum-insured",
        label: "Sum Insured",
        value: "₹5L",
        tint: "#FFFFFF",
        iconTone: "#DCFCE7",
        icon: "shield",
      },
      {
        id: "net-premium",
        label: "Net Premium",
        value: "₹98.4L",
        tint: "#FFFFFF",
        iconTone: "#F3E8FF",
        icon: "wallet",
      },
    ],
    secondaryStats: [
      {
        id: "employees",
        label: "Employees",
        value: "186",
        tint: "#FFFFFF",
        iconTone: "#EFF6FF",
        icon: "briefcase",
      },
      {
        id: "dependents",
        label: "Dependents",
        value: "224",
        tint: "#FFFFFF",
        iconTone: "#ECFDF3",
        icon: "dependents",
      },
      {
        id: "active-claims",
        label: "Active Claims",
        value: "24",
        tint: "#FFFFFF",
        iconTone: "#FFF7ED",
        icon: "activity",
      },
      {
        id: "claim-ratio",
        label: "Claim Util.",
        value: "45%",
        tint: "#FFFFFF",
        iconTone: "#F3E8FF",
        icon: "ratio",
      },
      {
        id: "total-claims",
        label: "Total Claims",
        value: "₹38.5L",
        tint: "#FFFFFF",
        iconTone: "#FEF2F2",
        icon: "claims",
      },
      {
        id: "avg-claim",
        label: "Avg Claim",
        value: "₹1.6L",
        tint: "#FFFFFF",
        iconTone: "#EEF2FF",
        icon: "average",
      },
    ],
    tabs: [
      { id: "overview", label: "Overview", active: true },
      { id: "claims", label: "Claims Analytics" },
      { id: "members", label: "Member Analytics" },
      { id: "financial", label: "Financial Insights" },
    ],
    subComponents: [
      {
        id: "base-cover",
        name: "Base Cover",
        summary: "542 lives · 124 claims",
        enrolled: "542 emp",
        coverage: "₹68.0L",
        premiumPerMonth: "₹5.7L",
        claims: "124",
        status: "Active",
        dotColor: "#00C950",
      },
      {
        id: "top-up-cover",
        name: "Top-Up Cover",
        summary: "312 lives · 68 claims",
        enrolled: "312 emp",
        coverage: "₹26.0L",
        premiumPerMonth: "₹2.2L",
        claims: "68",
        status: "Active",
        dotColor: "#2B7FFF",
      },
    ],
    enrollmentProgress: {
      enrolled: 410,
      total: 542,
      enrolledLabel: "410",
      pendingLabel: "132",
      dependentsLabel: "224",
    },
    claimUtilisation: {
      percent: 45,
      subtitle: "of premium utilised",
      breakdown: [
        { label: "Total Claims", value: "₹38.5L" },
        { label: "Avg Claim", value: "₹1.6L" },
        { label: "Outstanding", value: "₹5.07L" },
      ],
    },
    icrByPeriod: {
      periods: [
        { label: "Last Year\nFull", shortLabel: "LY Full", claimsAmount: 32.4, incurredPremium: 95.2, icr: 34, isPredicted: false, claimsColor: "#059669", premiumColor: "#6EE7B7" },
        { label: "Last Year\nSame Period", shortLabel: "LY Period", claimsAmount: 18.6, incurredPremium: 48.1, icr: 39, isPredicted: false, claimsColor: "#D97706", premiumColor: "#FCD34D" },
        { label: "Current Year\nto Date", shortLabel: "Current YTD", claimsAmount: 38.5, incurredPremium: 52.3, icr: 45, isPredicted: false, claimsColor: "#2563EB", premiumColor: "#93C5FD" },
        { label: "Forecast", shortLabel: "Forecast", claimsAmount: 66.0, incurredPremium: 82.6, icr: 52, isPredicted: true, claimsColor: "#7C3AED", premiumColor: "#C4B5FD" },
      ],
      forecast: { expectedIcr: 52, claimsAmount: "est. ₹66.05L", incurredPremium: "est. ₹82.57L" },
    },
    monthlyTrend: [
      { label: "Aug", claims: 12, settled: 9 },
      { label: "Sep", claims: 18, settled: 14 },
      { label: "Oct", claims: 15, settled: 11 },
      { label: "Nov", claims: 22, settled: 18 },
      { label: "Dec", claims: 25, settled: 21 },
      { label: "Jan", claims: 17, settled: 13 },
      { label: "Feb", claims: 21, settled: 16 },
    ],
    topHospitals: [
      {
        id: "apollo",
        label: "Apollo Hospital",
        value: "₹9.2L",
        helper: "48 claims",
        progress: 100,
        color: "#3B82F6",
      },
      {
        id: "fortis",
        label: "Fortis Healthcare",
        value: "₹8.8L",
        helper: "36 claims",
        progress: 79,
        color: "#6366F1",
      },
      {
        id: "max",
        label: "Max Hospital",
        value: "₹5.4L",
        helper: "29 claims",
        progress: 63,
        color: "#8B5CF6",
      },
      {
        id: "medanta",
        label: "Medanta",
        value: "₹4.1L",
        helper: "22 claims",
        progress: 48,
        color: "#EC4899",
      },
      {
        id: "aiims",
        label: "AIIMS",
        value: "₹3.2L",
        helper: "18 claims",
        progress: 39,
        color: "#F59E0B",
      },
    ],
    diseaseBreakdown: [
      {
        id: "orthopedic",
        label: "Orthopedic",
        value: "27%",
        helper: "42",
        progress: 100,
        color: "#3B82F6",
      },
      {
        id: "cardiology",
        label: "Cardiology",
        value: "22%",
        helper: "35",
        progress: 84,
        color: "#8B5CF6",
      },
      {
        id: "general",
        label: "General",
        value: "18%",
        helper: "28",
        progress: 67,
        color: "#10B981",
      },
      {
        id: "dental",
        label: "Dental",
        value: "11%",
        helper: "18",
        progress: 43,
        color: "#F59E0B",
      },
      {
        id: "maternity",
        label: "Maternity",
        value: "9%",
        helper: "14",
        progress: 33,
        color: "#EC4899",
      },
      {
        id: "others",
        label: "Others",
        value: "13%",
        helper: "20",
        progress: 48,
        color: "#6B7280",
      },
    ],
  },
  gtl: {
    header: {
      policyId: "gtl",
      title: "Group Term Life",
      status: "Active",
      statusTone: "success",
    },
    primaryStats: [
      {
        id: "lives",
        label: "Total Lives",
        value: "485",
        tint: "#FFFFFF",
        iconTone: "#FFFFFF",
        icon: "users",
      },
      {
        id: "sum-insured",
        label: "Sum Insured",
        value: "₹10L",
        tint: "#FFFFFF",
        iconTone: "#FEE2E2",
        icon: "shield",
      },
      {
        id: "net-premium",
        label: "Net Premium",
        value: "₹49.2L",
        tint: "#FFFFFF",
        iconTone: "#FCE7F3",
        icon: "wallet",
      },
    ],
    secondaryStats: [
      {
        id: "employees",
        label: "Employees",
        value: "230",
        tint: "#FFFFFF",
        iconTone: "#EFF6FF",
        icon: "briefcase",
      },
      {
        id: "dependents",
        label: "Dependents",
        value: "255",
        tint: "#FFFFFF",
        iconTone: "#ECFDF3",
        icon: "dependents",
      },
      {
        id: "active-claims",
        label: "Active Claims",
        value: "7",
        tint: "#FFFFFF",
        iconTone: "#FFF7ED",
        icon: "activity",
      },
      {
        id: "claim-ratio",
        label: "Claim Util.",
        value: "22%",
        tint: "#FFFFFF",
        iconTone: "#F3E8FF",
        icon: "ratio",
      },
      {
        id: "total-claims",
        label: "Total Claims",
        value: "₹10.8L",
        tint: "#FFFFFF",
        iconTone: "#FEF2F2",
        icon: "claims",
      },
      {
        id: "avg-claim",
        label: "Avg Claim",
        value: "₹0.9L",
        tint: "#FFFFFF",
        iconTone: "#EEF2FF",
        icon: "average",
      },
    ],
    tabs: [
      { id: "overview", label: "Overview", active: true },
      { id: "claims", label: "Claims Analytics" },
      { id: "members", label: "Member Analytics" },
      { id: "financial", label: "Financial Insights" },
    ],
    subComponents: [
      {
        id: "basic-life",
        name: "Basic Life Cover",
        summary: "485 lives · 7 claims",
        enrolled: "485 emp",
        coverage: "₹32.0L",
        premiumPerMonth: "₹2.4L",
        claims: "7",
        status: "Active",
        dotColor: "#FB2C36",
      },
      {
        id: "voluntary-life",
        name: "Voluntary Top Cover",
        summary: "214 lives · 4 claims",
        enrolled: "214 emp",
        coverage: "₹17.2L",
        premiumPerMonth: "₹1.7L",
        claims: "4",
        status: "Active",
        dotColor: "#8B5CF6",
      },
    ],
    enrollmentProgress: {
      enrolled: 428,
      total: 485,
      enrolledLabel: "428",
      pendingLabel: "57",
      dependentsLabel: "255",
    },
    claimUtilisation: {
      percent: 22,
      subtitle: "of premium utilised",
      breakdown: [
        { label: "Total Claims", value: "₹10.8L" },
        { label: "Avg Claim", value: "₹0.9L" },
        { label: "Outstanding", value: "₹1.2L" },
      ],
    },
    icrByPeriod: {
      periods: [
        { label: "Last Year\nFull", shortLabel: "LY Full", claimsAmount: 9.2, incurredPremium: 43.8, icr: 21, isPredicted: false, claimsColor: "#059669", premiumColor: "#6EE7B7" },
        { label: "Last Year\nSame Period", shortLabel: "LY Period", claimsAmount: 5.1, incurredPremium: 22.4, icr: 23, isPredicted: false, claimsColor: "#D97706", premiumColor: "#FCD34D" },
        { label: "Current Year\nto Date", shortLabel: "Current YTD", claimsAmount: 10.8, incurredPremium: 24.6, icr: 22, isPredicted: false, claimsColor: "#2563EB", premiumColor: "#93C5FD" },
        { label: "Forecast", shortLabel: "Forecast", claimsAmount: 19.5, incurredPremium: 44.1, icr: 24, isPredicted: true, claimsColor: "#7C3AED", premiumColor: "#C4B5FD" },
      ],
      forecast: { expectedIcr: 24, claimsAmount: "est. ₹19.5L", incurredPremium: "est. ₹44.1L" },
    },
    monthlyTrend: [
      { label: "Aug", claims: 4, settled: 3 },
      { label: "Sep", claims: 6, settled: 4 },
      { label: "Oct", claims: 5, settled: 4 },
      { label: "Nov", claims: 7, settled: 6 },
      { label: "Dec", claims: 8, settled: 6 },
      { label: "Jan", claims: 6, settled: 5 },
      { label: "Feb", claims: 7, settled: 6 },
    ],
    topHospitals: [
      {
        id: "apollo",
        label: "Apollo Hospital",
        value: "₹2.8L",
        helper: "9 claims",
        progress: 100,
        color: "#3B82F6",
      },
      {
        id: "fortis",
        label: "Fortis Healthcare",
        value: "₹2.1L",
        helper: "7 claims",
        progress: 74,
        color: "#6366F1",
      },
      {
        id: "max",
        label: "Max Hospital",
        value: "₹1.8L",
        helper: "5 claims",
        progress: 61,
        color: "#8B5CF6",
      },
      {
        id: "medanta",
        label: "Medanta",
        value: "₹1.4L",
        helper: "4 claims",
        progress: 50,
        color: "#EC4899",
      },
      {
        id: "aiims",
        label: "AIIMS",
        value: "₹1.1L",
        helper: "3 claims",
        progress: 38,
        color: "#F59E0B",
      },
    ],
    diseaseBreakdown: [
      {
        id: "cardiac",
        label: "Cardiology",
        value: "31%",
        helper: "12",
        progress: 100,
        color: "#8B5CF6",
      },
      {
        id: "critical",
        label: "Critical Illness",
        value: "24%",
        helper: "9",
        progress: 78,
        color: "#3B82F6",
      },
      {
        id: "general",
        label: "General",
        value: "17%",
        helper: "6",
        progress: 56,
        color: "#10B981",
      },
      {
        id: "neuro",
        label: "Neurology",
        value: "11%",
        helper: "4",
        progress: 35,
        color: "#F59E0B",
      },
      {
        id: "others",
        label: "Others",
        value: "17%",
        helper: "7",
        progress: 56,
        color: "#6B7280",
      },
    ],
  },
  gpa: {
    header: {
      policyId: "gpa",
      title: "Group Personal Accident",
      status: "Active",
      statusTone: "warning",
    },
    primaryStats: [
      {
        id: "lives",
        label: "Total Lives",
        value: "542",
        tint: "#FFFFFF",
        iconTone: "#DBEAFE",
        icon: "users",
      },
      {
        id: "sum-insured",
        label: "Sum Insured",
        value: "₹7L",
        tint: "#FFFFFF",
        iconTone: "#FEF3C7",
        icon: "shield",
      },
      {
        id: "net-premium",
        label: "Net Premium",
        value: "₹21.6L",
        tint: "#FFFFFF",
        iconTone: "#FFEDD5",
        icon: "wallet",
      },
    ],
    secondaryStats: [
      {
        id: "employees",
        label: "Employees",
        value: "238",
        tint: "#FFFFFF",
        iconTone: "#EFF6FF",
        icon: "briefcase",
      },
      {
        id: "dependents",
        label: "Dependents",
        value: "304",
        tint: "#FFFFFF",
        iconTone: "#ECFDF3",
        icon: "dependents",
      },
      {
        id: "active-claims",
        label: "Active Claims",
        value: "13",
        tint: "#FFFFFF",
        iconTone: "#FFF7ED",
        icon: "activity",
      },
      {
        id: "claim-ratio",
        label: "Claim Util.",
        value: "35%",
        tint: "#FFFFFF",
        iconTone: "#F3E8FF",
        icon: "ratio",
      },
      {
        id: "total-claims",
        label: "Total Claims",
        value: "₹7.6L",
        tint: "#FFFFFF",
        iconTone: "#FEF2F2",
        icon: "claims",
      },
      {
        id: "avg-claim",
        label: "Avg Claim",
        value: "₹0.6L",
        tint: "#FFFFFF",
        iconTone: "#EEF2FF",
        icon: "average",
      },
    ],
    tabs: [
      { id: "overview", label: "Overview", active: true },
      { id: "claims", label: "Claims Analytics" },
      { id: "members", label: "Member Analytics" },
      { id: "financial", label: "Financial Insights" },
    ],
    subComponents: [
      {
        id: "accidental-death",
        name: "Accidental Death",
        summary: "542 lives · 11 claims",
        enrolled: "542 emp",
        coverage: "₹14.8L",
        premiumPerMonth: "₹1.1L",
        claims: "11",
        status: "Active",
        dotColor: "#F59E0B",
      },
      {
        id: "disability",
        name: "Permanent Disability",
        summary: "318 lives · 9 claims",
        enrolled: "318 emp",
        coverage: "₹6.8L",
        premiumPerMonth: "₹0.7L",
        claims: "9",
        status: "Active",
        dotColor: "#FB2C36",
      },
    ],
    enrollmentProgress: {
      enrolled: 459,
      total: 542,
      enrolledLabel: "459",
      pendingLabel: "83",
      dependentsLabel: "304",
    },
    claimUtilisation: {
      percent: 35,
      subtitle: "of premium utilised",
      breakdown: [
        { label: "Total Claims", value: "₹7.6L" },
        { label: "Avg Claim", value: "₹0.6L" },
        { label: "Outstanding", value: "₹1.8L" },
      ],
    },
    icrByPeriod: {
      periods: [
        { label: "Last Year\nFull", shortLabel: "LY Full", claimsAmount: 6.1, incurredPremium: 18.4, icr: 33, isPredicted: false, claimsColor: "#059669", premiumColor: "#6EE7B7" },
        { label: "Last Year\nSame Period", shortLabel: "LY Period", claimsAmount: 3.4, incurredPremium: 9.6, icr: 35, isPredicted: false, claimsColor: "#D97706", premiumColor: "#FCD34D" },
        { label: "Current Year\nto Date", shortLabel: "Current YTD", claimsAmount: 7.6, incurredPremium: 11.2, icr: 35, isPredicted: false, claimsColor: "#2563EB", premiumColor: "#93C5FD" },
        { label: "Forecast", shortLabel: "Forecast", claimsAmount: 13.8, incurredPremium: 21.6, icr: 38, isPredicted: true, claimsColor: "#7C3AED", premiumColor: "#C4B5FD" },
      ],
      forecast: { expectedIcr: 38, claimsAmount: "est. ₹13.8L", incurredPremium: "est. ₹21.6L" },
    },
    monthlyTrend: [
      { label: "Aug", claims: 5, settled: 4 },
      { label: "Sep", claims: 8, settled: 6 },
      { label: "Oct", claims: 6, settled: 5 },
      { label: "Nov", claims: 9, settled: 7 },
      { label: "Dec", claims: 10, settled: 8 },
      { label: "Jan", claims: 8, settled: 6 },
      { label: "Feb", claims: 9, settled: 7 },
    ],
    topHospitals: [
      {
        id: "apollo",
        label: "Apollo Hospital",
        value: "₹1.8L",
        helper: "11 claims",
        progress: 100,
        color: "#3B82F6",
      },
      {
        id: "fortis",
        label: "Fortis Healthcare",
        value: "₹1.5L",
        helper: "9 claims",
        progress: 82,
        color: "#6366F1",
      },
      {
        id: "max",
        label: "Max Hospital",
        value: "₹1.1L",
        helper: "7 claims",
        progress: 63,
        color: "#8B5CF6",
      },
      {
        id: "medanta",
        label: "Medanta",
        value: "₹0.9L",
        helper: "5 claims",
        progress: 50,
        color: "#EC4899",
      },
      {
        id: "aiims",
        label: "AIIMS",
        value: "₹0.7L",
        helper: "4 claims",
        progress: 39,
        color: "#F59E0B",
      },
    ],
    diseaseBreakdown: [
      {
        id: "trauma",
        label: "Trauma",
        value: "33%",
        helper: "19",
        progress: 100,
        color: "#F59E0B",
      },
      {
        id: "fractures",
        label: "Fractures",
        value: "24%",
        helper: "14",
        progress: 72,
        color: "#3B82F6",
      },
      {
        id: "ortho",
        label: "Orthopedic",
        value: "18%",
        helper: "11",
        progress: 55,
        color: "#8B5CF6",
      },
      {
        id: "general",
        label: "General",
        value: "13%",
        helper: "8",
        progress: 40,
        color: "#10B981",
      },
      {
        id: "others",
        label: "Others",
        value: "12%",
        helper: "7",
        progress: 36,
        color: "#6B7280",
      },
    ],
  },
};

export const isPolicyDetailPolicyId = (
  value: string | undefined
): value is PolicyDetailPolicyId =>
  value === "ghi" || value === "gtl" || value === "gpa";
