// Generated by Copilot
import { useState } from "react";
import { Box, Typography } from "@mui/material";
import { ChevronDown, CheckCircle2 } from "lucide-react";

interface FilterSelectProps {
  value: string;
  onChange: (v: string) => void;
  options: string[];
  icon?: React.ElementType;
}

export function FilterSelect({
  value,
  onChange,
  options,
  icon: Icon,
}: FilterSelectProps) {
  const [_open, _setOpen] = useState(false);

  return (
    <Box sx={{ position: "relative" }}>
      <Box
        component="button"
        onClick={() => _setOpen((o) => !o)}
        sx={{
          display: "flex",
          alignItems: "center",
          gap: 0.75,
          height: 32,
          px: 1.5,
          fontSize: 12,
          color: "#374151",
          bgcolor: "#fff",
          border: "1px solid #e5e7eb",
          borderRadius: 2,
          cursor: "pointer",
          whiteSpace: "nowrap",
          "&:hover": { borderColor: "#9ca3af" },
          transition: "border-color 0.15s",
        }}
      >
        {Icon && <Icon size={12} color="#9ca3af" />}
        <span>{value}</span>
        <ChevronDown
          size={12}
          color="#9ca3af"
          style={{
            transform: _open ? "rotate(180deg)" : "rotate(0deg)",
            transition: "transform 0.15s",
          }}
        />
      </Box>

      {_open && (
        <>
          <Box
            sx={{ position: "fixed", inset: 0, zIndex: 28 }}
            onClick={() => _setOpen(false)}
          />
          <Box
            sx={{
              position: "absolute",
              left: 0,
              top: "calc(100% + 4px)",
              bgcolor: "#fff",
              border: "1px solid #e5e7eb",
              borderRadius: 2,
              boxShadow: "0 8px 24px rgba(0,0,0,0.10)",
              zIndex: 29,
              py: 0.5,
              minWidth: 160,
            }}
          >
            {options.map((opt) => (
              <Box
                key={opt}
                onClick={() => {
                  onChange(opt);
                  _setOpen(false);
                }}
                sx={{
                  display: "flex",
                  alignItems: "center",
                  gap: 1,
                  px: 1.75,
                  py: 1,
                  fontSize: 12,
                  cursor: "pointer",
                  color: value === opt ? "#2563eb" : "#374151",
                  bgcolor: value === opt ? "#eff6ff" : "transparent",
                  "&:hover": { bgcolor: value === opt ? "#eff6ff" : "#f9fafb" },
                }}
              >
                {value === opt && (
                  <CheckCircle2
                    size={11}
                    color="#2563eb"
                    style={{ flexShrink: 0 }}
                  />
                )}
                <Typography sx={{ fontSize: 12, color: "inherit" }}>
                  {opt}
                </Typography>
              </Box>
            ))}
          </Box>
        </>
      )}
    </Box>
  );
}

export default FilterSelect;
