// Generated by Copilot
import { useState, RefObject } from "react";
import { Box, Collapse, Typography } from "@mui/material";
import {
  Filter,
  ChevronDown,
  ChevronRight,
  CheckCircle2,
  X,
  Search,
  Download,
  ArrowUpCircle,
  ArrowDownCircle,
  RefreshCcw,
  CheckCircle,
  Clock,
  XCircle,
} from "lucide-react";
import {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
  SearchBox,
  ActionButton,
  CDSectionHeader,
  CDSectionTitle,
  CDTypeBadge,
  CDStatusBadge,
  CDModeBadge,
  CDFilterBarWrapper,
  CDFilterButton,
  CDFilterDropdownMenu,
  CDFilterOption,
  CDResetBtn,
  CDExpandedPanel,
  CDExpandedLabel,
  CDExpandedValue,
  CDExpandChevron,
  CDPaginationBar,
  CDPageBtn,
  CDExportMenu,
  CDExportOption,
} from "./styles";
import {
  useLocalization,
  formatAmountWithCurrency,
  type LocalizationConfig,
} from "@ui/ui-lib";

// ─── Types ────────────────────────────────────────────────────────────────────
export type TxType = "Deposit" | "Deduction" | "Refund";
export type TxStatus = "Completed" | "Pending" | "Processing" | "Failed";
export type TxMode = "NEFT" | "RTGS" | "Cash";

export interface CDTransaction {
  id: string;
  date: string;
  policy: string;
  policyNo: string;
  employee: string;
  employeeId: string;
  amount: number;
  type: TxType;
  mode: TxMode;
  status: TxStatus;
  ref: string;
  claimRef?: string;
  hospital?: string;
  diagnosis?: string;
  utrNo?: string;
  bank?: string;
  ifsc?: string;
  createdBy: string;
  approvedBy: string;
  remarks: string;
}

interface CDTransactionsTableProps {
  transactions: CDTransaction[];
  filterRef?: RefObject<HTMLDivElement>;
  externalPolicy?: string;
  onExternalPolicyConsumed?: () => void;
}

const PER_PAGE = 8;

// ─── Filter Dropdown ──────────────────────────────────────────────────────────
function FilterDropdown({
  value,
  onChange,
  options,
  icon: Icon,
  placeholder,
}: {
  value: string;
  onChange: (v: string) => void;
  options: string[];
  icon?: React.ElementType;
  placeholder?: string;
}) {
  const [open, setOpen] = useState(false);

  return (
    <Box sx={{ position: "relative" }}>
      <CDFilterButton onClick={() => setOpen((o) => !o)}>
        {Icon && <Icon size={13} style={{ color: "#9ca3af", flexShrink: 0 }} />}
        <span>{value || placeholder}</span>
        <ChevronDown
          size={12}
          style={{
            color: "#9ca3af",
            transform: open ? "rotate(180deg)" : "none",
            transition: "transform 0.15s",
          }}
        />
      </CDFilterButton>
      {open && (
        <CDFilterDropdownMenu>
          {options.map((opt) => (
            <CDFilterOption
              key={opt}
              selected={value === opt}
              onClick={() => {
                onChange(opt);
                setOpen(false);
              }}
            >
              {value === opt && (
                <CheckCircle2 size={12} style={{ flexShrink: 0 }} />
              )}
              {opt}
            </CDFilterOption>
          ))}
        </CDFilterDropdownMenu>
      )}
    </Box>
  );
}

// ─── Type badge ───────────────────────────────────────────────────────────────
const TX_TYPE_ICONS: Record<TxType, React.ElementType> = {
  Deposit: ArrowUpCircle,
  Deduction: ArrowDownCircle,
  Refund: RefreshCcw,
};

function TypeBadge({ type }: { type: TxType }) {
  const Icon = TX_TYPE_ICONS[type];
  return (
    <CDTypeBadge txType={type}>
      <Icon size={11} />
      {type}
    </CDTypeBadge>
  );
}

// ─── Status badge ─────────────────────────────────────────────────────────────
const TX_STATUS_ICONS: Record<TxStatus, React.ElementType> = {
  Completed: CheckCircle,
  Pending: Clock,
  Processing: Clock,
  Failed: XCircle,
};

function StatusBadgeInner({ status }: { status: TxStatus }) {
  const Icon = TX_STATUS_ICONS[status];
  return (
    <CDStatusBadge txStatus={status}>
      <Icon size={11} />
      {status}
    </CDStatusBadge>
  );
}

// ─── Expanded row detail ──────────────────────────────────────────────────────
function ExpandedDetail({ tx }: { tx: CDTransaction }) {
  const isDeposit = tx.type === "Deposit";

  return (
    <CDExpandedPanel>
      {isDeposit ? (
        <>
          <Box>
            <CDExpandedLabel>UTR Number</CDExpandedLabel>
            <CDExpandedValue sx={{ fontFamily: "monospace" }}>
              {tx.utrNo ?? "—"}
            </CDExpandedValue>
          </Box>
          <Box>
            <CDExpandedLabel>Bank</CDExpandedLabel>
            <CDExpandedValue>{tx.bank ?? "—"}</CDExpandedValue>
          </Box>
          <Box>
            <CDExpandedLabel>IFSC Code</CDExpandedLabel>
            <CDExpandedValue sx={{ fontFamily: "monospace" }}>
              {tx.ifsc ?? "—"}
            </CDExpandedValue>
          </Box>
          <Box>
            <CDExpandedLabel>Created By</CDExpandedLabel>
            <CDExpandedValue>{tx.createdBy}</CDExpandedValue>
          </Box>
        </>
      ) : (
        <>
          <Box>
            <CDExpandedLabel>Claim Reference</CDExpandedLabel>
            <CDExpandedValue sx={{ fontFamily: "monospace" }}>
              {tx.claimRef ?? "—"}
            </CDExpandedValue>
          </Box>
          <Box>
            <CDExpandedLabel>Hospital</CDExpandedLabel>
            <CDExpandedValue>{tx.hospital ?? "—"}</CDExpandedValue>
          </Box>
          <Box>
            <CDExpandedLabel>Diagnosis</CDExpandedLabel>
            <CDExpandedValue>{tx.diagnosis ?? "—"}</CDExpandedValue>
          </Box>
          <Box>
            <CDExpandedLabel>Created By</CDExpandedLabel>
            <CDExpandedValue>{tx.createdBy}</CDExpandedValue>
          </Box>
        </>
      )}
      <Box>
        <CDExpandedLabel>Approved By</CDExpandedLabel>
        <CDExpandedValue>{tx.approvedBy}</CDExpandedValue>
      </Box>
      <Box sx={{ gridColumn: "span 3" }}>
        <CDExpandedLabel>Remarks</CDExpandedLabel>
        <CDExpandedValue sx={{ fontStyle: "italic" }}>
          {tx.remarks}
        </CDExpandedValue>
      </Box>
    </CDExpandedPanel>
  );
}

// ─── Formatter ────────────────────────────────────────────────────────────────
function fmtINR(n: number, localization?: LocalizationConfig) {
  return `${formatAmountWithCurrency(n, localization)}`;
}

// ─── Main Component ───────────────────────────────────────────────────────────
export function CDTransactionsTable({
  transactions,
  filterRef,
  externalPolicy,
  onExternalPolicyConsumed,
}: CDTransactionsTableProps) {
  const [txPolicy, setTxPolicy] = useState("All Policies");
  const [txDateRange, setTxDateRange] = useState("This Year");
  const [txType, setTxType] = useState("All Types");
  const [txStatus, setTxStatus] = useState("All Status");
  const [txSearch, setTxSearch] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [page, setPage] = useState(1);
  const [exportOpen, setExportOpen] = useState(false);
  const { localizationData } = useLocalization();

  // Apply external policy filter driven by "View Transactions" click
  if (externalPolicy && externalPolicy !== txPolicy) {
    setTxPolicy(externalPolicy);
    setPage(1);
    onExternalPolicyConsumed?.();
  }

  const activeFilterCount = [
    txPolicy !== "All Policies",
    txDateRange !== "This Year",
    txType !== "All Types",
    txStatus !== "All Status",
    txSearch !== "",
  ].filter(Boolean).length;

  const resetFilters = () => {
    setTxPolicy("All Policies");
    setTxDateRange("This Year");
    setTxType("All Types");
    setTxStatus("All Status");
    setTxSearch("");
    setPage(1);
  };

  const filtered = transactions.filter((tx) => {
    if (txPolicy !== "All Policies" && tx.policy !== txPolicy) return false;
    if (txType !== "All Types" && tx.type !== txType) return false;
    if (txStatus !== "All Status" && tx.status !== txStatus) return false;
    if (txSearch) {
      const q = txSearch.toLowerCase();
      if (
        !tx.employee.toLowerCase().includes(q) &&
        !tx.ref.toLowerCase().includes(q) &&
        !tx.policyNo.toLowerCase().includes(q)
      )
        return false;
    }
    return true;
  });

  const totalPages = Math.ceil(filtered.length / PER_PAGE);
  const paginated = filtered.slice((page - 1) * PER_PAGE, page * PER_PAGE);

  return (
    <SectionCard
      ref={filterRef}
      sx={{ p: 0, overflow: "hidden", scrollMarginTop: 16 }}
    >
      {/* Header */}
      <CDSectionHeader>
        <Box>
          <CDSectionTitle>Deposit Transactions</CDSectionTitle>
          <Typography sx={{ fontSize: "11px", color: "text.grey", mt: 0.25 }}>
            {filtered.length} transaction{filtered.length !== 1 ? "s" : ""}
          </Typography>
        </Box>
        <Box sx={{ position: "relative" }}>
          <ActionButton
            onClick={() => setExportOpen((o) => !o)}
            sx={{ display: "flex", alignItems: "center", gap: 0.75 }}
          >
            <Download size={13} />
            Export
            <ChevronDown
              size={12}
              style={{
                transform: exportOpen ? "rotate(180deg)" : "none",
                transition: "transform 0.15s",
              }}
            />
          </ActionButton>
          {exportOpen && (
            <CDExportMenu>
              {["Export as CSV", "Export as Excel", "Export as PDF"].map(
                (opt) => (
                  <CDExportOption
                    key={opt}
                    onClick={() => setExportOpen(false)}
                  >
                    <Download size={13} />
                    {opt}
                  </CDExportOption>
                ),
              )}
            </CDExportMenu>
          )}
        </Box>
      </CDSectionHeader>

      {/* Filter bar */}
      <CDFilterBarWrapper>
        <Filter size={14} style={{ color: "#9ca3af", flexShrink: 0 }} />
        <FilterDropdown
          value={txPolicy}
          onChange={(v) => { setTxPolicy(v); setPage(1); }}
          options={["All Policies", "GMC", "GPA", "GTL"]}
          placeholder="All Policies"
        />
        <FilterDropdown
          value={txDateRange}
          onChange={(v) => { setTxDateRange(v); setPage(1); }}
          options={["This Year", "This Month", "Last 3 Months", "Last 6 Months"]}
          placeholder="This Year"
        />
        <FilterDropdown
          value={txType}
          onChange={(v) => { setTxType(v); setPage(1); }}
          options={["All Types", "Deposit", "Deduction", "Refund"]}
          placeholder="All Types"
        />
        <FilterDropdown
          value={txStatus}
          onChange={(v) => { setTxStatus(v); setPage(1); }}
          options={["All Status", "Completed", "Pending", "Processing", "Failed"]}
          placeholder="All Status"
        />
        <SearchBox sx={{ flex: 1, minWidth: 160, maxWidth: 260 }}>
          <Search size={13} />
          <input
            placeholder="Search employee, ref, policy..."
            value={txSearch}
            onChange={(e) => { setTxSearch(e.target.value); setPage(1); }}
          />
          {txSearch && (
            <X
              size={12}
              style={{ cursor: "pointer", color: "#9ca3af", flexShrink: 0 }}
              onClick={() => setTxSearch("")}
            />
          )}
        </SearchBox>
        {activeFilterCount > 0 && (
          <CDResetBtn onClick={resetFilters}>
            <X size={12} />
            Reset
            <Box
              sx={{
                width: 16,
                height: 16,
                borderRadius: "50%",
                backgroundColor: "secondary.selected",
                color: "neutral.veryLight",
                fontSize: "10px",
                fontWeight: 700,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              {activeFilterCount}
            </Box>
          </CDResetBtn>
        )}
      </CDFilterBarWrapper>

      {/* Table */}
      <Box sx={{ overflowX: "auto" }}>
        <StyledTable>
          <thead>
            <tr>
              <StyledTh sx={{ width: 32 }} />
              <StyledTh>Date</StyledTh>
              <StyledTh>Policy</StyledTh>
              <StyledTh>Employee</StyledTh>
              <StyledTh>Amount</StyledTh>
              <StyledTh>Type</StyledTh>
              <StyledTh>Mode</StyledTh>
              <StyledTh>Status</StyledTh>
              <StyledTh>Reference</StyledTh>
            </tr>
          </thead>
          <tbody>
            {paginated.map((tx) => {
              const isExpanded = expandedId === tx.id;
              const amtColor =
                tx.type === "Deposit"
                  ? "#16a34a"
                  : tx.type === "Refund"
                    ? "#2563eb"
                    : "#dc2626";
              const amtSign =
                tx.type === "Deposit" ? "+" : tx.type === "Refund" ? "↩ " : "−";

              return (
                <>
                  <tr
                    key={tx.id}
                    onClick={() =>
                      setExpandedId((prev) => (prev === tx.id ? null : tx.id))
                    }
                    style={{
                      cursor: "pointer",
                      backgroundColor: isExpanded
                        ? "rgba(59,130,246,0.04)"
                        : undefined,
                    }}
                  >
                    <StyledTd>
                      <CDExpandChevron expanded={isExpanded}>
                        <ChevronRight size={14} style={{ color: "#9ca3af" }} />
                      </CDExpandChevron>
                    </StyledTd>
                    <StyledTd sx={{ whiteSpace: "nowrap", color: "text.grey" }}>
                      {tx.date}
                    </StyledTd>
                    <StyledTd>
                      <Box>
                        <Typography
                          sx={{ fontSize: "13px", fontWeight: 600, color: "neutral.mediumDark" }}
                        >
                          {tx.policy}
                        </Typography>
                        <Typography
                          sx={{ fontSize: "11px", color: "text.grey", fontFamily: "monospace" }}
                        >
                          {tx.policyNo}
                        </Typography>
                      </Box>
                    </StyledTd>
                    <StyledTd>
                      {tx.employee !== "—" ? (
                        <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                          <Box
                            sx={{
                              width: 28,
                              height: 28,
                              borderRadius: "50%",
                              backgroundColor: "background.tableHeader",
                              display: "flex",
                              alignItems: "center",
                              justifyContent: "center",
                              fontSize: "11px",
                              fontWeight: 600,
                              color: "secondary.selected",
                              flexShrink: 0,
                            }}
                          >
                            {tx.employee.charAt(0)}
                          </Box>
                          <Box>
                            <Typography sx={{ fontSize: "13px", fontWeight: 500 }}>
                              {tx.employee}
                            </Typography>
                            <Typography
                              sx={{ fontSize: "11px", color: "text.grey", fontFamily: "monospace" }}
                            >
                              {tx.employeeId}
                            </Typography>
                          </Box>
                        </Box>
                      ) : (
                        <Typography sx={{ fontSize: "13px", color: "text.grey" }}>
                          —
                        </Typography>
                      )}
                    </StyledTd>
                    <StyledTd>
                      <Typography
                        sx={{ fontSize: "14px", fontWeight: 600, color: amtColor, whiteSpace: "nowrap" }}
                      >
                        {amtSign}{fmtINR(tx.amount, localizationData?.data)}
                      </Typography>
                    </StyledTd>
                    <StyledTd>
                      <TypeBadge type={tx.type} />
                    </StyledTd>
                    <StyledTd>
                      <CDModeBadge>{tx.mode}</CDModeBadge>
                    </StyledTd>
                    <StyledTd>
                      <StatusBadgeInner status={tx.status} />
                    </StyledTd>
                    <StyledTd
                      sx={{ fontFamily: "monospace", fontSize: "11px", color: "text.grey", whiteSpace: "nowrap" }}
                    >
                      {tx.ref}
                    </StyledTd>
                  </tr>
                  <tr key={`${tx.id}-expand`}>
                    <td colSpan={9} style={{ padding: 0, border: "none" }}>
                      <Collapse in={isExpanded} timeout={220}>
                        <ExpandedDetail tx={tx} />
                      </Collapse>
                    </td>
                  </tr>
                </>
              );
            })}
            {paginated.length === 0 && (
              <tr>
                <td colSpan={9} style={{ textAlign: "center", padding: "32px 16px" }}>
                  <Typography sx={{ fontSize: "13px", color: "text.grey" }}>
                    No transactions match the selected filters.
                  </Typography>
                </td>
              </tr>
            )}
          </tbody>
        </StyledTable>
      </Box>

      {/* Pagination */}
      {totalPages > 1 && (
        <CDPaginationBar>
          <Typography sx={{ fontSize: "12px", color: "text.grey" }}>
            Showing {(page - 1) * PER_PAGE + 1}–
            {Math.min(page * PER_PAGE, filtered.length)} of {filtered.length}
          </Typography>
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
            <CDPageBtn
              disabled={page === 1}
              onClick={() => page > 1 && setPage((p) => p - 1)}
            >
              ‹
            </CDPageBtn>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map((n) => (
              <CDPageBtn key={n} active={n === page} onClick={() => setPage(n)}>
                {n}
              </CDPageBtn>
            ))}
            <CDPageBtn
              disabled={page === totalPages}
              onClick={() => page < totalPages && setPage((p) => p + 1)}
            >
              ›
            </CDPageBtn>
          </Box>
        </CDPaginationBar>
      )}
    </SectionCard>
  );
}
