// Generated by Copilot
// Re-exports base shared tokens used by CDTransactionsTable.
export {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
  SearchBox,
  ActionButton,
} from "../../pages/HRPortal/styles";

// Re-exports shared section header used across CD sections.
export {
  CDSectionHeader,
  CDSectionTitle,
} from "../../pages/HRPortalFinance/styles";

import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";

// ─── Transaction type badge ────────────────────────────────────────────────────
export const CDTypeBadge = styled(Box)<{ txType?: string }>(
  ({ theme, txType }) => {
    const map: Record<string, { bg: string; color: string }> = {
      Deposit: {
        bg: theme.palette.chips.primary,
        color: theme.palette.neutral.green,
      },
      Deduction: {
        bg: theme.palette.chips.secondary,
        color: theme.palette.text.error,
      },
      Refund: {
        bg: theme.palette.chips.quaternary,
        color: theme.palette.secondary.selected,
      },
    };
    const s = txType
      ? map[txType] ?? { bg: "#f1f5f9", color: "#475569" }
      : { bg: "#f1f5f9", color: "#475569" };
    return {
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      padding: "2px 8px",
      borderRadius: 20,
      fontSize: theme.typography.fontSizes.xxs,
      fontWeight: theme.typography.fontWeights.semiBold,
      backgroundColor: s.bg,
      color: s.color,
      whiteSpace: "nowrap" as const,
    };
  },
);

// ─── Transaction status badge ──────────────────────────────────────────────────
export const CDStatusBadge = styled(Box)<{ txStatus?: string }>(
  ({ theme, txStatus }) => {
    const map: Record<string, { bg: string; color: string; border: string }> = {
      Completed: { bg: "#dcfce7", color: "#16a34a", border: "#bbf7d0" },
      Pending:   { bg: "#fef9c3", color: "#ca8a04", border: "#fde68a" },
      Processing: { bg: "#dbeafe", color: "#2563eb", border: "#bfdbfe" },
      Failed:    { bg: "#fee2e2", color: "#dc2626", border: "#fecaca" },
    };
    const s = txStatus
      ? map[txStatus] ?? { bg: "#f1f5f9", color: "#475569", border: "#e2e8f0" }
      : { bg: "#f1f5f9", color: "#475569", border: "#e2e8f0" };
    return {
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      padding: "2px 10px",
      borderRadius: 20,
      fontSize: theme.typography.fontSizes.xxs,
      fontWeight: theme.typography.fontWeights.semiBold,
      backgroundColor: s.bg,
      color: s.color,
      border: `1px solid ${s.border}`,
      whiteSpace: "nowrap" as const,
    };
  },
);

// ─── Mode badge ─────────────────────────────────────────────────────────────────
export const CDModeBadge = styled(Box)(({ theme }) => ({
  display: "inline-flex",
  padding: "2px 8px",
  borderRadius: 4,
  fontSize: theme.typography.fontSizes.xxs,
  fontWeight: theme.typography.fontWeights.medium,
  backgroundColor: theme.palette.background.tableHeader,
  color: theme.palette.text.grey,
}));

// ─── Filter bar ─────────────────────────────────────────────────────────────────
export const CDFilterBarWrapper = styled(Box)(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(1),
  flexWrap: "wrap",
  padding: theme.spacing(1, 2.5),
  borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
  backgroundColor: theme.palette.background.tableHeader,
}));

export const CDFilterButton = styled(Box)(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(0.75),
  height: 32,
  padding: theme.spacing(0, 1.5),
  fontSize: theme.typography.fontSizes.xss,
  color: theme.palette.neutral.medium,
  backgroundColor: theme.palette.background.paper,
  border: `1px solid ${theme.palette.neutral.tableBorder}`,
  borderRadius: theme.shape.borderRadii.medium,
  cursor: "pointer",
  whiteSpace: "nowrap" as const,
  "&:hover": {
    borderColor: theme.palette.neutral.medium,
  },
  transition: "border-color 0.15s ease",
}));

export const CDFilterDropdownMenu = styled(Box)(({ theme }) => ({
  position: "absolute",
  left: 0,
  top: "calc(100% + 4px)",
  backgroundColor: theme.palette.background.paper,
  border: `1px solid ${theme.palette.neutral.tableBorder}`,
  borderRadius: theme.shape.borderRadii.medium,
  boxShadow: theme.shadows[3],
  zIndex: 200,
  minWidth: 176,
  padding: theme.spacing(0.5, 0),
}));

export const CDFilterOption = styled(Box, {
  shouldForwardProp: (p) => p !== "selected",
})<{ selected?: boolean }>(({ theme, selected }) => ({
  padding: theme.spacing(0.875, 1.75),
  fontSize: theme.typography.fontSizes.xss,
  color: selected
    ? theme.palette.secondary.selected
    : theme.palette.neutral.medium,
  backgroundColor: selected
    ? theme.palette.background.tabsSelected
    : "transparent",
  cursor: "pointer",
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(1),
  "&:hover": {
    backgroundColor: theme.palette.background.tableHeader,
  },
}));

export const CDResetBtn = styled(Box)(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(0.5),
  height: 32,
  padding: theme.spacing(0, 1.25),
  fontSize: theme.typography.fontSizes.xss,
  color: theme.palette.secondary.selected,
  cursor: "pointer",
  borderRadius: theme.shape.borderRadii.medium,
  "&:hover": {
    backgroundColor: theme.palette.background.tabsSelected,
  },
}));

// ─── Expanded detail panel ──────────────────────────────────────────────────────
export const CDExpandedPanel = styled(Box)(({ theme }) => ({
  margin: theme.spacing(0, 2, 1.5),
  backgroundColor: theme.palette.background.tableHeader,
  borderRadius: theme.shape.borderRadii.medium,
  border: `1px solid ${theme.palette.neutral.tableBorder}`,
  padding: theme.spacing(2),
  display: "grid",
  gridTemplateColumns: "repeat(4, 1fr)",
  gap: theme.spacing(2),
}));

export const CDExpandedLabel = styled(Typography)(({ theme }) => ({
  fontSize: theme.typography.fontSizes.xxs,
  fontWeight: theme.typography.fontWeights.semiBold,
  color: theme.palette.text.grey,
  textTransform: "uppercase" as const,
  letterSpacing: "0.06em",
  marginBottom: theme.spacing(0.5),
}));

export const CDExpandedValue = styled(Typography)(({ theme }) => ({
  fontSize: theme.typography.fontSizes.xs,
  color: theme.palette.neutral.medium,
}));

// ─── Pagination ─────────────────────────────────────────────────────────────────
export const CDPaginationBar = styled(Box)(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  padding: theme.spacing(1.25, 2.5),
  borderTop: `1px solid ${theme.palette.neutral.tableBorder}`,
}));

export const CDPageBtn = styled(Box, {
  shouldForwardProp: (p) => p !== "active" && p !== "disabled",
})<{ active?: boolean; disabled?: boolean }>(({ theme, active, disabled }) => ({
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  minWidth: 30,
  height: 30,
  padding: theme.spacing(0, 0.75),
  borderRadius: theme.shape.borderRadii.medium,
  fontSize: theme.typography.fontSizes.xss,
  fontWeight: active
    ? theme.typography.fontWeights.semiBold
    : theme.typography.fontWeights.regular,
  cursor: disabled ? "not-allowed" : "pointer",
  backgroundColor: active ? theme.palette.secondary.selected : "transparent",
  color: active
    ? theme.palette.neutral.veryLight
    : disabled
      ? theme.palette.neutral.light
      : theme.palette.neutral.medium,
  border: active
    ? "none"
    : `1px solid ${theme.palette.neutral.tableBorder}`,
  "&:hover": disabled || active ? {} : { backgroundColor: theme.palette.background.tableHeader },
  transition: "all 0.15s ease",
}));

// ─── Row expand chevron ─────────────────────────────────────────────────────────
export const CDExpandChevron = styled(Box)<{ expanded?: boolean }>(
  ({ expanded }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "transform 0.18s ease",
    transform: expanded ? "rotate(90deg)" : "rotate(0deg)",
  }),
);

// ─── Export dropdown ────────────────────────────────────────────────────────────
export const CDExportMenu = styled(Box)(({ theme }) => ({
  position: "absolute",
  right: 0,
  top: "calc(100% + 4px)",
  backgroundColor: theme.palette.background.paper,
  border: `1px solid ${theme.palette.neutral.tableBorder}`,
  borderRadius: theme.shape.borderRadii.medium,
  boxShadow: theme.shadows[3],
  zIndex: 200,
  minWidth: 160,
  padding: theme.spacing(0.5, 0),
}));

export const CDExportOption = styled(Box)(({ theme }) => ({
  padding: theme.spacing(0.875, 1.75),
  fontSize: theme.typography.fontSizes.xss,
  color: theme.palette.neutral.medium,
  cursor: "pointer",
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(1.25),
  "&:hover": {
    backgroundColor: theme.palette.background.tableHeader,
  },
}));
