import { Module } from "@nestjs/common";
import { JwtModule } from "@nestjs/jwt";
import { TypeOrmModule } from "@nestjs/typeorm";
import { EntityService } from "../../../../../../libs/service-lib/src/lib/utils/entity-service.utils";
import { ScopeService } from "../../../../../../libs/service-lib/src/lib/utils/scope.utils";
import {
  AuditHistoryLog,
  AuditHistoryLogDetail,
  BusinessTarget,
  CautionDeposit,
  MirReport,
  MirReportSection,
  MstrMirSection,
  CautionDepositPolicyMapping,
  CautionDepositTransaction,
  Company,
  CompanyContactMap,
  ConfigCompany,
  ContactCommunicationDetails,
  DocumentProcessingFile,
  Endorsement,
  EndorsementFieldMapping,
  FileUpload,
  Insurer,
  LookUp,
  MstrEntityFieldsUtilityRef,
  MstrPolicyConstraint,
  NotificationEventParameterMapping,
  OpportunityActivityMap,
  OpportunityPlacementSlipGeneration,
  PerformanceOutput,
  Policy,
  PolicyAssetEndorsement,
  PolicyAssetEndorsementMap,
  PolicyAuditLog,
  PolicyClaim,
  PolicyComponentsConfigurationDetail,
  PolicyEnrollmentParameter,
  PolicyConfiguration,
  PolicyConfigurationComponentRelationMap,
  PolicyConfigurationTemplateDocMap,
  PolicyCoverMap,
  PolicyDependentEndorsement,
  PolicyEmployeeEndorsement,
  PolicyEmployeeEnrollment,
  PolicyEmployeeEnrollmentChoice,
  PolicyEndorsementTemplateDocMap,
  PolicyEnrollmentDependent,
  PolicyEnrollmentEmployee,
  PolicyEnrollmentEmployeePolicyMap,
  PolicyEnrollmentStepMapping,
  PolicyEnrollmentSteps,
  PolicyEnrollmentTemplateDocMap,
  PolicyEnrollmentUploadSummary,
  PolicyExtensionAudit,
  PolicyExtensionDocument,
  PolicyFeatureDocument,
  PolicyInsurerMap,
  PolicySubAssetEndorsementMap,
  Task,
  TatBucket,
  Tpa,
  User,
  PolicyInstallments,
  PolicyBrokerageDetails,
  PolicyBrokeragePremiumReceipt,
  PolicyBrokerageCommissionStatement,
  PolicyBrokerageInvoice,
  PolicyBrokerageCollection,
  MstrCoverSection,
  OrgSbu,
} from "../../../../service-lib/src/lib/entities";
import { ENV } from "../../../../service-lib/src/lib/environment";
import { InsuranceWellnessHubServiceLibModule } from "../../../../service-lib/src/lib/service-lib.module";
import { TraceIdService } from "../../../../service-lib/src/lib/trace-id.service";
import { LookUpValidationService } from "../../../../service-lib/src/lib/utils/lookup-validation";
import { MasterValidationService } from "../../../../service-lib/src/lib/utils/masters-validation";
import { NotificationUtils } from "../../../../service-lib/src/lib/utils/notification.utils";
import { PolicyReportService } from "../../../../service-lib/src/lib/utils/policy-report";
import { typeOrmConfig } from ".././../../../service-lib/src/lib/database/typeorm.config";
import { EndorsementCreationScheduler } from "./endorsement-creation.scheduler";
import { PolicyController } from "./policy.controller";
import { PolicyExtensionService } from "./policy-extension.service";
import { PolicyRepository } from "./policy.repository";
import { PolicyService } from "./policy.service";
import { MirReportService } from "./mir-report.service";
import { ServiceTatModule } from "../service-tat/service-tat.module";
@Module({
  imports: [
    TypeOrmModule.forRoot(typeOrmConfig),
    TypeOrmModule.forFeature([
      AuditHistoryLog,
      AuditHistoryLogDetail,
      BusinessTarget,
      CautionDeposit,
      CautionDepositPolicyMapping,
      CautionDepositTransaction,
      Company,
      CompanyContactMap,
      ContactCommunicationDetails,
      DocumentProcessingFile,
      Endorsement,
      EndorsementFieldMapping,
      FileUpload,
      Insurer,
      LookUp,
      MstrPolicyConstraint,
      NotificationEventParameterMapping,
      OpportunityActivityMap,
      OpportunityPlacementSlipGeneration,
      PerformanceOutput,
      Policy,
      PolicyAssetEndorsement,
      PolicyAssetEndorsementMap,
      PolicyAuditLog,
      ContactCommunicationDetails,
      ConfigCompany,
      MstrEntityFieldsUtilityRef,
      PolicyFeatureDocument,
      PolicyClaim,
      PolicyComponentsConfigurationDetail,
      PolicyEnrollmentParameter,
      PolicyConfiguration,
      PolicyConfigurationComponentRelationMap,
      PolicyConfigurationTemplateDocMap,
      PolicyCoverMap,
      PolicyDependentEndorsement,
      PolicyEmployeeEndorsement,
      PolicyEmployeeEnrollment,
      PolicyEmployeeEnrollmentChoice,
      PolicyEndorsementTemplateDocMap,
      PolicyEnrollmentDependent,
      PolicyEnrollmentEmployee,
      PolicyEnrollmentEmployeePolicyMap,
      PolicyEnrollmentStepMapping,
      PolicyEnrollmentSteps,
      PolicyEnrollmentTemplateDocMap,
      PolicyEnrollmentUploadSummary,
      PolicyExtensionAudit,
      PolicyExtensionDocument,
      PolicyFeatureDocument,
      PolicyInsurerMap,
      PolicySubAssetEndorsementMap,
      Task,
      Tpa,
      User,
      MstrEntityFieldsUtilityRef,
      TatBucket,
      ConfigCompany,
      PolicyInstallments,
      PolicyBrokerageDetails,
      PolicyBrokeragePremiumReceipt,
      PolicyBrokerageCommissionStatement,
      PolicyBrokerageInvoice,
      PolicyBrokerageCollection,
      MstrCoverSection,
      OrgSbu,
      MirReport,
      MirReportSection,
      MstrMirSection,
    ]),
    InsuranceWellnessHubServiceLibModule,
    JwtModule.register({ secret: ENV.JWT_SECRET }),
    ServiceTatModule,
  ],
  controllers: [PolicyController],
  exports: [PolicyService, PolicyRepository],
  providers: [
    PolicyService,
    PolicyExtensionService,
    PolicyRepository,
    MirReportService,
    EndorsementCreationScheduler,
    EntityService,
    ScopeService,
    TraceIdService,
    PolicyReportService,
    LookUpValidationService,
    MasterValidationService,
    NotificationUtils,
  ],
})
export class PolicyModule {}
