// Generated by Copilot
import { BadgePill } from "./styles";

const BADGE_MAP: Record<
  string,
  { bg: string; textColor: string; borderColor: string }
> = {
  Settled: { bg: "#f0fdf4", textColor: "#15803d", borderColor: "#bbf7d0" },
  Approved: { bg: "#f0fdf4", textColor: "#15803d", borderColor: "#bbf7d0" },
  Enrolled: { bg: "#eff6ff", textColor: "#1d4ed8", borderColor: "#bfdbfe" },
  Processing: { bg: "#eff6ff", textColor: "#1d4ed8", borderColor: "#bfdbfe" },
  Sent: { bg: "#eff6ff", textColor: "#1d4ed8", borderColor: "#bfdbfe" },
  Added: { bg: "#f0fdf4", textColor: "#15803d", borderColor: "#bbf7d0" },
  Resubmit: { bg: "#fffbeb", textColor: "#92400e", borderColor: "#fde68a" },
  Pending: { bg: "#fffbeb", textColor: "#92400e", borderColor: "#fde68a" },
  Modified: { bg: "#fffbeb", textColor: "#92400e", borderColor: "#fde68a" },
  Cashless: { bg: "#e0f2fe", textColor: "#0369a1", borderColor: "#bae6fd" },
  Marriage: { bg: "#f5f3ff", textColor: "#5b21b6", borderColor: "#ddd6fe" },
  Newborn: { bg: "#fdf2f8", textColor: "#9d174d", borderColor: "#fbcfe8" },
  Rejected: { bg: "#fef2f2", textColor: "#b91c1c", borderColor: "#fecaca" },
  Removed: { bg: "#fef2f2", textColor: "#b91c1c", borderColor: "#fecaca" },
  "Not Enrolled": {
    bg: "#fef2f2",
    textColor: "#b91c1c",
    borderColor: "#fecaca",
  },
  Reimbursement: {
    bg: "#e0e7ff",
    textColor: "#4338ca",
    borderColor: "#c7d2fe",
  },
  GMC: { bg: "#eff6ff", textColor: "#1d4ed8", borderColor: "#bfdbfe" },
  GPA: { bg: "#f5f3ff", textColor: "#5b21b6", borderColor: "#ddd6fe" },
  GTL: { bg: "#f0fdf4", textColor: "#15803d", borderColor: "#bbf7d0" },
  Yes: { bg: "#f0fdf4", textColor: "#15803d", borderColor: "#bbf7d0" },
  No: { bg: "#f9fafb", textColor: "#6b7280", borderColor: "#e5e7eb" },
};

const _default = {
  bg: "#f9fafb",
  textColor: "#374151",
  borderColor: "#e5e7eb",
};

export function ReportBadge({ value }: { value: string }) {
  const _style = BADGE_MAP[String(value)] ?? _default;
  return (
    <BadgePill
      bg={_style.bg}
      textColor={_style.textColor}
      borderColor={_style.borderColor}
    >
      {value}
    </BadgePill>
  );
}

export default ReportBadge;
