// Generated by Copilot
import { useState, useMemo } from "react";
import { Box, Typography, Select, MenuItem } from "@mui/material";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import { Layers, Table2, Download } from "lucide-react";
import {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  StatusBadge,
  ActionButton,
} from "../../../pages/HRPortal/styles";
import {
  RICH,
  DATA_BY_GROUP,
  STACKS,
  fmtAmt,
  STATUS_COLOR,
  type ChartType,
  type ViewBy,
  type GroupBy,
  type InsightPoint,
} from "../data";

interface ClaimsAnalyticsTabProps {
  policyId: string;
}

const TIME_RANGES = [
  { label: "3 months", value: 3 },
  { label: "6 months", value: 6 },
  { label: "12 months", value: 12 },
];

function fmtTick(v: unknown, viewBy: ViewBy): string {
  const n = Number(v);
  if (viewBy === "amount" || viewBy === "avg") return fmtAmt(n);
  return String(n);
}

function getDataKey(
  point: InsightPoint,
  viewBy: ViewBy,
  stackKey: keyof InsightPoint,
): number {
  if (viewBy === "count") return 0;
  if (viewBy === "avg")
    return Number(point[stackKey]) / Math.max(1, point.count);
  return Number(point[stackKey]);
}

export function ClaimsAnalyticsTab({ policyId }: ClaimsAnalyticsTabProps) {
  const [chartType, setChartType] = useState<ChartType>("stacked");
  const [viewBy, setViewBy] = useState<ViewBy>("amount");
  const [groupBy, setGroupBy] = useState<GroupBy>("month");
  const [timeRange, setTimeRange] = useState(12);

  const _rich = RICH[policyId];

  const _chartData = useMemo(() => {
    const base = DATA_BY_GROUP[groupBy];
    if (groupBy !== "month") return base;
    return base.slice(-timeRange);
  }, [groupBy, timeRange]);

  const _yTickFmt = (v: unknown) => fmtTick(v, viewBy);

  const _tatColor = (tat: number) =>
    tat <= 3
      ? { bg: "#D1FAE5", color: "#059669" }
      : tat <= 7
      ? { bg: "#FEF9C3", color: "#CA8A04" }
      : { bg: "#FEE2E2", color: "#DC2626" };

  if (!_rich) return null;

  return (
    <Box sx={{ mt: 3 }}>
      {/* Stacked Chart / Table toggle */}
      <SectionCard sx={{ mb: 3 }}>
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: 2,
            flexWrap: "wrap",
            gap: 1.5,
          }}
        >
          <SectionTitle sx={{ mb: 0 }}>Claims Distribution</SectionTitle>
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              gap: 1.5,
              flexWrap: "wrap",
            }}
          >
            {/* Chart / Table toggle */}
            <Box
              sx={{
                display: "flex",
                border: "1px solid #e5e7eb",
                borderRadius: 1.5,
                overflow: "hidden",
              }}
            >
              {(["stacked", "table"] as ChartType[]).map((t) => (
                <Box
                  key={t}
                  onClick={() => setChartType(t)}
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: 0.5,
                    px: 1.5,
                    py: 0.75,
                    fontSize: 12,
                    cursor: "pointer",
                    backgroundColor: chartType === t ? "#eff6ff" : "#fff",
                    color: chartType === t ? "#2563eb" : "#6b7280",
                    fontWeight: chartType === t ? 600 : 400,
                    "&:hover": {
                      backgroundColor: chartType === t ? "#eff6ff" : "#f9fafb",
                    },
                  }}
                >
                  {t === "stacked" ? (
                    <Layers size={13} />
                  ) : (
                    <Table2 size={13} />
                  )}
                  {t === "stacked" ? "Stacked Bar" : "Table"}
                </Box>
              ))}
            </Box>

            {/* View By toggle */}
            <Box
              sx={{
                display: "flex",
                border: "1px solid #e5e7eb",
                borderRadius: 1.5,
                overflow: "hidden",
              }}
            >
              {(["amount", "count", "avg"] as ViewBy[]).map((v) => (
                <Box
                  key={v}
                  onClick={() => setViewBy(v)}
                  sx={{
                    px: 1.5,
                    py: 0.75,
                    fontSize: 12,
                    cursor: "pointer",
                    backgroundColor: viewBy === v ? "#eff6ff" : "#fff",
                    color: viewBy === v ? "#2563eb" : "#6b7280",
                    fontWeight: viewBy === v ? 600 : 400,
                    textTransform: "capitalize",
                    "&:hover": {
                      backgroundColor: viewBy === v ? "#eff6ff" : "#f9fafb",
                    },
                  }}
                >
                  {v}
                </Box>
              ))}
            </Box>

            <ActionButton
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 0.75,
                fontSize: 12,
                py: 0.75,
                px: 1.5,
              }}
            >
              <Download size={13} />
              Export
            </ActionButton>
          </Box>
        </Box>

        {/* Filters */}
        {chartType === "stacked" && (
          <Box sx={{ display: "flex", gap: 2, mb: 2, flexWrap: "wrap" }}>
            <Select
              size="small"
              value={groupBy}
              onChange={(e) => setGroupBy(e.target.value as GroupBy)}
              sx={{ fontSize: 12, minWidth: 140, height: 32 }}
            >
              <MenuItem value="month">By Month</MenuItem>
              <MenuItem value="city">By City</MenuItem>
              <MenuItem value="hospital">By Hospital</MenuItem>
              <MenuItem value="department">By Department</MenuItem>
            </Select>
            {groupBy === "month" && (
              <Select
                size="small"
                value={timeRange}
                onChange={(e) => setTimeRange(Number(e.target.value))}
                sx={{ fontSize: 12, minWidth: 120, height: 32 }}
              >
                {TIME_RANGES.map((r) => (
                  <MenuItem key={r.value} value={r.value}>
                    {r.label}
                  </MenuItem>
                ))}
              </Select>
            )}
          </Box>
        )}

        {/* Cashless / Reimbursement legend */}
        {chartType === "stacked" && (
          <Box sx={{ display: "flex", gap: 3, mb: 2 }}>
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
              <Box
                sx={{
                  width: 10,
                  height: 10,
                  borderRadius: "50%",
                  backgroundColor: "#3b82f6",
                }}
              />
              <Typography sx={{ fontSize: 11.5, color: "#6b7280" }}>
                Cashless 62%
              </Typography>
            </Box>
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
              <Box
                sx={{
                  width: 10,
                  height: 10,
                  borderRadius: "50%",
                  backgroundColor: "#10b981",
                }}
              />
              <Typography sx={{ fontSize: 11.5, color: "#6b7280" }}>
                Reimbursement 38%
              </Typography>
            </Box>
          </Box>
        )}

        {chartType === "stacked" ? (
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={_chartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis
                dataKey="name"
                tick={{ fontSize: 11, fill: "#9ca3af" }}
                axisLine={false}
                tickLine={false}
              />
              <YAxis
                tickFormatter={_yTickFmt}
                tick={{ fontSize: 11, fill: "#9ca3af" }}
                axisLine={false}
                tickLine={false}
              />
              <RechartTooltip
                contentStyle={{
                  borderRadius: 8,
                  border: "1px solid #e5e7eb",
                  fontSize: 12,
                }}
                formatter={(v: unknown, name: unknown) => [
                  fmtTick(v, viewBy),
                  String(name),
                ]}
              />
              <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} />
              {STACKS.map((s) => (
                <Bar
                  key={s.key}
                  dataKey={(d: InsightPoint) => getDataKey(d, viewBy, s.key)}
                  name={s.label}
                  stackId="a"
                  fill={s.color}
                />
              ))}
            </BarChart>
          </ResponsiveContainer>
        ) : (
          <StyledTable>
            <thead>
              <tr>
                <StyledTh>Name</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Amount</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Count</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Paid</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Outstanding</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Rejected</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Closed</StyledTh>
                <StyledTh sx={{ textAlign: "right" }}>Denied</StyledTh>
              </tr>
            </thead>
            <tbody>
              {_chartData.map((row, i) => (
                <tr key={i}>
                  <StyledTd sx={{ fontWeight: 500 }}>{row.name}</StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {fmtAmt(row.amount)}
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>{row.count}</StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {fmtAmt(row.paid)}
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {fmtAmt(row.outstanding)}
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {fmtAmt(row.rejected)}
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {fmtAmt(row.closed)}
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {fmtAmt(row.denied)}
                  </StyledTd>
                </tr>
              ))}
            </tbody>
          </StyledTable>
        )}
      </SectionCard>

      {/* Recent Claims Table */}
      <SectionCard>
        <SectionTitle>Recent Claims</SectionTitle>
        <StyledTable>
          <thead>
            <tr>
              <StyledTh>Claim No.</StyledTh>
              <StyledTh>Employee</StyledTh>
              <StyledTh>Hospital</StyledTh>
              <StyledTh>Type</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>Claim Amt</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>Settled Amt</StyledTh>
              <StyledTh>Status</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>TAT (days)</StyledTh>
            </tr>
          </thead>
          <tbody>
            {_rich.claimsTable.map((row, i) => {
              const _sc = STATUS_COLOR[row.status] ?? {
                bg: "#f3f4f6",
                color: "#6b7280",
              };
              const _tc = _tatColor(row.tat);
              return (
                <tr key={i}>
                  <StyledTd sx={{ fontFamily: "monospace", fontSize: 11.5 }}>
                    {row.claimNo}
                  </StyledTd>
                  <StyledTd sx={{ fontWeight: 500, color: "#111827" }}>
                    {row.employee}
                  </StyledTd>
                  <StyledTd sx={{ color: "#6b7280" }}>{row.hospital}</StyledTd>
                  <StyledTd>
                    <StatusBadge
                      sx={{ backgroundColor: "#eff6ff", color: "#2563eb" }}
                    >
                      {row.type}
                    </StatusBadge>
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right", fontWeight: 500 }}>
                    {fmtAmt(row.claimAmt)}
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    {row.settledAmt > 0 ? fmtAmt(row.settledAmt) : "—"}
                  </StyledTd>
                  <StyledTd>
                    <StatusBadge
                      sx={{ backgroundColor: _sc.bg, color: _sc.color }}
                    >
                      {row.status}
                    </StatusBadge>
                  </StyledTd>
                  <StyledTd sx={{ textAlign: "right" }}>
                    <StatusBadge
                      sx={{ backgroundColor: _tc.bg, color: _tc.color }}
                    >
                      {row.tat}d
                    </StatusBadge>
                  </StyledTd>
                </tr>
              );
            })}
          </tbody>
        </StyledTable>
      </SectionCard>
    </Box>
  );
}

export default ClaimsAnalyticsTab;
