// Generated by Copilot
import { Box, Typography } from "@mui/material";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import { Wallet, FileText, Activity, TrendingUp } from "lucide-react";
import {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTd,
} from "../../../pages/HRPortal/styles";
import { SmallKpiCard } from "../styles";
import { RICH, fmtAmt } from "../data";

interface FinancialTabProps {
  policyId: string;
}

const TT_STYLE = {
  contentStyle: {
    borderRadius: 8,
    border: "1px solid #e5e7eb",
    fontSize: 12,
    boxShadow: "0 4px 16px rgba(0,0,0,.08)",
    padding: "6px 10px",
  },
};

export function FinancialTab({ policyId }: FinancialTabProps) {
  const _rich = RICH[policyId];
  if (!_rich) return null;

  const _kpis = [
    {
      label: "Total Premium",
      value: _rich.totalPremiumPaid,
      Icon: Wallet,
      color: "#3b82f6",
    },
    {
      label: "Claim Paid (YTD)",
      value: _rich.totalClaimPaid,
      Icon: FileText,
      color: "#ef4444",
    },
    {
      label: "Outstanding",
      value: _rich.outstandingClaims,
      Icon: Activity,
      color: "#f59e0b",
    },
    {
      label: "Loss Ratio",
      value: `${_rich.lossRatio}%`,
      Icon: TrendingUp,
      color:
        _rich.lossRatio > 80
          ? "#ef4444"
          : _rich.lossRatio > 60
          ? "#f59e0b"
          : "#10b981",
    },
  ];

  return (
    <Box sx={{ mt: 3 }}>
      {/* KPI Cards */}
      <Box
        sx={{
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: 2,
          mb: 3,
        }}
      >
        {_kpis.map((kpi) => (
          <SmallKpiCard key={kpi.label}>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                mb: 1,
              }}
            >
              <Typography sx={{ fontSize: 11.5, color: "#6b7280" }}>
                {kpi.label}
              </Typography>
              <Box
                sx={{
                  width: 28,
                  height: 28,
                  borderRadius: "50%",
                  backgroundColor: `${kpi.color}18`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <kpi.Icon size={14} color={kpi.color} />
              </Box>
            </Box>
            <Typography
              sx={{ fontSize: 20, fontWeight: 600, color: "#111827" }}
            >
              {kpi.value}
            </Typography>
          </SmallKpiCard>
        ))}
      </Box>

      {/* Premium vs Claims chart + Financial Summary */}
      <Box
        sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 3, mb: 3 }}
      >
        <SectionCard>
          <SectionTitle>Premium vs Claim Trend</SectionTitle>
          <ResponsiveContainer width="100%" height={200}>
            <LineChart data={_rich.premiumVsClaim}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis
                dataKey="month"
                tick={{ fontSize: 11, fill: "#9ca3af" }}
                axisLine={false}
                tickLine={false}
              />
              <YAxis
                tickFormatter={(v: unknown) => fmtAmt(Number(v))}
                tick={{ fontSize: 11, fill: "#9ca3af" }}
                axisLine={false}
                tickLine={false}
              />
              <RechartTooltip
                {...TT_STYLE}
                formatter={(v: unknown, name: unknown) => [
                  fmtAmt(Number(v)),
                  String(name),
                ]}
              />
              <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} />
              <Line
                type="monotone"
                dataKey="premium"
                name="Premium"
                stroke="#8b5cf6"
                strokeWidth={2}
                strokeDasharray="5 5"
                dot={{ r: 3 }}
              />
              <Line
                type="monotone"
                dataKey="claim"
                name="Claim"
                stroke="#ef4444"
                strokeWidth={2}
                dot={{ r: 3 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </SectionCard>

        <SectionCard>
          <SectionTitle>Financial Summary</SectionTitle>
          <StyledTable>
            <tbody>
              {_rich.financialTable.map((row, i) => (
                <tr key={i}>
                  <StyledTd sx={{ color: "#6b7280" }}>{row.label}</StyledTd>
                  <StyledTd
                    sx={{
                      textAlign: "right",
                      fontWeight: 600,
                      color: "#111827",
                    }}
                  >
                    {row.value}
                  </StyledTd>
                </tr>
              ))}
            </tbody>
          </StyledTable>
        </SectionCard>
      </Box>

      {/* Utilization Donut */}
      <SectionCard>
        <SectionTitle>Claim Utilization</SectionTitle>
        <Box sx={{ display: "flex", alignItems: "center", gap: 4 }}>
          {/* SVG Donut */}
          <Box
            sx={{
              position: "relative",
              width: 120,
              height: 120,
              flexShrink: 0,
            }}
          >
            <svg
              viewBox="0 0 36 36"
              style={{
                width: "100%",
                height: "100%",
                transform: "rotate(-90deg)",
              }}
            >
              <circle
                cx="18"
                cy="18"
                r="15.9"
                fill="none"
                stroke="#f0f0f0"
                strokeWidth="3.5"
              />
              <circle
                cx="18"
                cy="18"
                r="15.9"
                fill="none"
                stroke={
                  _rich.utilizationPct > 80
                    ? "#ef4444"
                    : _rich.utilizationPct > 60
                    ? "#f59e0b"
                    : "#10b981"
                }
                strokeWidth="3.5"
                strokeDasharray={`${_rich.utilizationPct} ${
                  100 - _rich.utilizationPct
                }`}
                strokeLinecap="round"
              />
            </svg>
            <Box
              sx={{
                position: "absolute",
                inset: 0,
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Typography
                sx={{ fontSize: 20, fontWeight: 600, color: "#111827" }}
              >
                {_rich.utilizationPct}%
              </Typography>
              <Typography sx={{ fontSize: 10, color: "#9ca3af" }}>
                Utilised
              </Typography>
            </Box>
          </Box>
          <Box sx={{ flex: 1 }}>
            <Typography sx={{ fontSize: 13, color: "#374151", mb: 1 }}>
              <strong>{_rich.utilizationPct}%</strong> of total sum insured has
              been utilised this policy year.
            </Typography>
            <Box sx={{ display: "flex", gap: 3 }}>
              <Box>
                <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
                  Claimed
                </Typography>
                <Typography
                  sx={{ fontSize: 14, fontWeight: 600, color: "#ef4444" }}
                >
                  {_rich.totalClaimPaid}
                </Typography>
              </Box>
              <Box>
                <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
                  Remaining
                </Typography>
                <Typography
                  sx={{ fontSize: 14, fontWeight: 600, color: "#10b981" }}
                >
                  {100 - _rich.utilizationPct}%
                </Typography>
              </Box>
            </Box>
          </Box>
        </Box>
      </SectionCard>
    </Box>
  );
}

export default FinancialTab;
