// Generated by Copilot
import { Box, Typography, LinearProgress } from "@mui/material";
import {
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
} from "../../../pages/HRPortal/styles";
import { RICH, fmtAmt } from "../data";

interface MemberAnalyticsTabProps {
  policyId: string;
}

const TT_STYLE = {
  contentStyle: {
    borderRadius: 8,
    border: "1px solid #e5e7eb",
    fontSize: 12,
    boxShadow: "0 4px 16px rgba(0,0,0,.08)",
    padding: "6px 10px",
  },
};

export function MemberAnalyticsTab({ policyId }: MemberAnalyticsTabProps) {
  const _rich = RICH[policyId];
  if (!_rich) return null;

  return (
    <Box
      sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 3, mt: 3 }}
    >
      {/* Age Groups */}
      <SectionCard>
        <SectionTitle>Members by Age Group</SectionTitle>
        <ResponsiveContainer width="100%" height={200}>
          <BarChart data={_rich.ageGroups}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis
              dataKey="band"
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <YAxis
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <RechartTooltip {...TT_STYLE} />
            <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} />
            <Bar
              dataKey="employees"
              name="Employees"
              fill="#3b82f6"
              radius={[2, 2, 0, 0]}
            />
            <Bar
              dataKey="dependents"
              name="Dependents"
              fill="#8b5cf6"
              radius={[2, 2, 0, 0]}
            />
          </BarChart>
        </ResponsiveContainer>
      </SectionCard>

      {/* Gender Split */}
      <SectionCard>
        <SectionTitle>Gender Split</SectionTitle>
        <Box sx={{ display: "flex", alignItems: "center", gap: 3 }}>
          <ResponsiveContainer width="50%" height={180}>
            <PieChart>
              <Pie
                data={_rich.genderSplit}
                dataKey="value"
                nameKey="name"
                cx="50%"
                cy="50%"
                innerRadius={40}
                outerRadius={65}
              >
                {_rich.genderSplit.map((entry, i) => (
                  <Cell key={i} fill={entry.color} />
                ))}
              </Pie>
              <RechartTooltip {...TT_STYLE} />
            </PieChart>
          </ResponsiveContainer>
          <Box
            sx={{ flex: 1, display: "flex", flexDirection: "column", gap: 1.5 }}
          >
            {_rich.genderSplit.map((g) => {
              const _total = _rich.genderSplit.reduce((s, x) => s + x.value, 0);
              const _pct = Math.round((g.value / Math.max(1, _total)) * 100);
              return (
                <Box key={g.name}>
                  <Box
                    sx={{
                      display: "flex",
                      justifyContent: "space-between",
                      mb: 0.5,
                    }}
                  >
                    <Box
                      sx={{ display: "flex", alignItems: "center", gap: 0.75 }}
                    >
                      <Box
                        sx={{
                          width: 10,
                          height: 10,
                          borderRadius: "50%",
                          backgroundColor: g.color,
                        }}
                      />
                      <Typography sx={{ fontSize: 12, color: "#374151" }}>
                        {g.name}
                      </Typography>
                    </Box>
                    <Typography
                      sx={{ fontSize: 12, fontWeight: 600, color: "#111827" }}
                    >
                      {g.value} ({_pct}%)
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      height: 5,
                      borderRadius: 3,
                      backgroundColor: "#f0f0f0",
                      overflow: "hidden",
                    }}
                  >
                    <Box
                      sx={{
                        height: "100%",
                        width: `${_pct}%`,
                        backgroundColor: g.color,
                        borderRadius: 3,
                      }}
                    />
                  </Box>
                </Box>
              );
            })}
          </Box>
        </Box>
      </SectionCard>

      {/* Department Enrollment */}
      <SectionCard>
        <SectionTitle>Department Enrollment</SectionTitle>
        <Box sx={{ display: "flex", flexDirection: "column", gap: 2, mt: 1 }}>
          {_rich.deptEnrollment.map((d) => {
            const _pct = Math.round((d.enrolled / Math.max(1, d.total)) * 100);
            const _barColor =
              _pct >= 90 ? "#10b981" : _pct >= 70 ? "#f59e0b" : "#ef4444";
            return (
              <Box key={d.dept}>
                <Box
                  sx={{
                    display: "flex",
                    justifyContent: "space-between",
                    mb: 0.5,
                  }}
                >
                  <Typography sx={{ fontSize: 12, color: "#374151" }}>
                    {d.dept}
                  </Typography>
                  <Typography
                    sx={{ fontSize: 12, fontWeight: 600, color: _barColor }}
                  >
                    {d.enrolled}/{d.total} ({_pct}%)
                  </Typography>
                </Box>
                <LinearProgress
                  variant="determinate"
                  value={_pct}
                  sx={{
                    height: 6,
                    borderRadius: 3,
                    backgroundColor: "#f0f0f0",
                    "& .MuiLinearProgress-bar": {
                      backgroundColor: _barColor,
                      borderRadius: 3,
                    },
                  }}
                />
              </Box>
            );
          })}
        </Box>
      </SectionCard>

      {/* Member Table */}
      <SectionCard>
        <SectionTitle>Covered Members</SectionTitle>
        <StyledTable>
          <thead>
            <tr>
              <StyledTh>Emp ID</StyledTh>
              <StyledTh>Name</StyledTh>
              <StyledTh>Dept</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>SI</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>Dep.</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>Claims</StyledTh>
              <StyledTh sx={{ textAlign: "right" }}>Total Claim</StyledTh>
            </tr>
          </thead>
          <tbody>
            {_rich.memberTable.map((m, i) => (
              <tr key={i}>
                <StyledTd sx={{ fontFamily: "monospace", fontSize: 11.5 }}>
                  {m.empId}
                </StyledTd>
                <StyledTd sx={{ fontWeight: 500, color: "#111827" }}>
                  {m.name}
                </StyledTd>
                <StyledTd sx={{ color: "#6b7280" }}>{m.dept}</StyledTd>
                <StyledTd sx={{ textAlign: "right" }}>{m.si}</StyledTd>
                <StyledTd sx={{ textAlign: "right" }}>{m.dependents}</StyledTd>
                <StyledTd sx={{ textAlign: "right" }}>{m.claimsCount}</StyledTd>
                <StyledTd sx={{ textAlign: "right", fontWeight: 500 }}>
                  {fmtAmt(m.totalClaim)}
                </StyledTd>
              </tr>
            ))}
          </tbody>
        </StyledTable>
      </SectionCard>
    </Box>
  );
}

export default MemberAnalyticsTab;
