// Generated by Copilot
import { Box, Typography } from "@mui/material";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import { SectionCard, SectionTitle } from "../../../pages/HRPortal/styles";
import { RICH, fmtAmt } from "../data";

interface OverviewTabProps {
  policyId: string;
}

const TT_STYLE = {
  contentStyle: {
    borderRadius: 8,
    border: "1px solid #e5e7eb",
    fontSize: 12,
    boxShadow: "0 4px 16px rgba(0,0,0,.08)",
    padding: "6px 10px",
  },
};

export function OverviewTab({ policyId }: OverviewTabProps) {
  const _rich = RICH[policyId];
  if (!_rich) return null;

  return (
    <Box
      sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 3, mt: 3 }}
    >
      {/* Claims Trend */}
      <SectionCard>
        <SectionTitle>Claims Trend</SectionTitle>
        <ResponsiveContainer width="100%" height={200}>
          <LineChart data={_rich.monthlyTrend}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis
              dataKey="month"
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <YAxis
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <RechartTooltip {...TT_STYLE} />
            <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} />
            <Line
              type="monotone"
              dataKey="claims"
              name="Total Claims"
              stroke="#3b82f6"
              strokeWidth={2}
              dot={{ r: 3 }}
            />
            <Line
              type="monotone"
              dataKey="settled"
              name="Settled"
              stroke="#10b981"
              strokeWidth={2}
              dot={{ r: 3 }}
            />
          </LineChart>
        </ResponsiveContainer>
      </SectionCard>

      {/* Top Hospitals */}
      <SectionCard>
        <SectionTitle>Top Hospitals</SectionTitle>
        <ResponsiveContainer width="100%" height={200}>
          <BarChart
            data={_rich.topHospitals}
            layout="vertical"
            margin={{ left: 8, right: 16 }}
          >
            <CartesianGrid
              strokeDasharray="3 3"
              stroke="#f0f0f0"
              horizontal={false}
            />
            <XAxis
              type="number"
              tickFormatter={(v: unknown) => fmtAmt(Number(v))}
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <YAxis
              type="category"
              dataKey="name"
              tick={{ fontSize: 11, fill: "#374151" }}
              axisLine={false}
              tickLine={false}
              width={90}
            />
            <RechartTooltip
              {...TT_STYLE}
              formatter={(v: unknown) => [fmtAmt(Number(v)), "Amount"]}
            />
            <Bar dataKey="amount" fill="#3b82f6" radius={[0, 4, 4, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </SectionCard>

      {/* Disease Breakdown */}
      <SectionCard>
        <SectionTitle>Disease Breakdown</SectionTitle>
        <Box sx={{ display: "flex", alignItems: "center", gap: 3 }}>
          <ResponsiveContainer width="55%" height={180}>
            <PieChart>
              <Pie
                data={_rich.diseaseBreakdown}
                dataKey="count"
                nameKey="name"
                cx="50%"
                cy="50%"
                innerRadius={45}
                outerRadius={70}
              >
                {_rich.diseaseBreakdown.map((entry, i) => (
                  <Cell key={i} fill={entry.color} />
                ))}
              </Pie>
              <RechartTooltip {...TT_STYLE} />
            </PieChart>
          </ResponsiveContainer>
          <Box sx={{ display: "flex", flexDirection: "column", gap: 1 }}>
            {_rich.diseaseBreakdown.map((d) => (
              <Box
                key={d.name}
                sx={{ display: "flex", alignItems: "center", gap: 1 }}
              >
                <Box
                  sx={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    backgroundColor: d.color,
                    flexShrink: 0,
                  }}
                />
                <Typography sx={{ fontSize: 11.5, color: "#374151" }}>
                  {d.name}
                </Typography>
                <Typography
                  sx={{
                    fontSize: 11.5,
                    fontWeight: 600,
                    color: "#111827",
                    ml: "auto",
                    pl: 2,
                  }}
                >
                  {d.count}
                </Typography>
              </Box>
            ))}
          </Box>
        </Box>
      </SectionCard>

      {/* Claim Type Split */}
      <SectionCard>
        <SectionTitle>Claim Type Split</SectionTitle>
        <Box sx={{ display: "flex", alignItems: "center", gap: 3 }}>
          <ResponsiveContainer width="45%" height={180}>
            <PieChart>
              <Pie
                data={_rich.claimsByType}
                dataKey="value"
                nameKey="name"
                cx="50%"
                cy="50%"
                innerRadius={40}
                outerRadius={65}
              >
                {_rich.claimsByType.map((entry, i) => (
                  <Cell key={i} fill={entry.color} />
                ))}
              </Pie>
              <RechartTooltip {...TT_STYLE} />
            </PieChart>
          </ResponsiveContainer>
          <Box
            sx={{ flex: 1, display: "flex", flexDirection: "column", gap: 1.5 }}
          >
            {_rich.claimsByType.map((d) => (
              <Box key={d.name}>
                <Box
                  sx={{
                    display: "flex",
                    justifyContent: "space-between",
                    mb: 0.5,
                  }}
                >
                  <Box
                    sx={{ display: "flex", alignItems: "center", gap: 0.75 }}
                  >
                    <Box
                      sx={{
                        width: 10,
                        height: 10,
                        borderRadius: "50%",
                        backgroundColor: d.color,
                      }}
                    />
                    <Typography sx={{ fontSize: 11.5, color: "#374151" }}>
                      {d.name}
                    </Typography>
                  </Box>
                  <Typography
                    sx={{ fontSize: 11.5, fontWeight: 600, color: "#111827" }}
                  >
                    {d.value}%
                  </Typography>
                </Box>
                <Box
                  sx={{
                    height: 5,
                    borderRadius: 3,
                    backgroundColor: "#f0f0f0",
                    overflow: "hidden",
                  }}
                >
                  <Box
                    sx={{
                      height: "100%",
                      width: `${d.value}%`,
                      backgroundColor: d.color,
                      borderRadius: 3,
                    }}
                  />
                </Box>
              </Box>
            ))}
          </Box>
        </Box>
      </SectionCard>
    </Box>
  );
}

export default OverviewTab;
