// Generated by Copilot
export {
  KPIGrid,
  KPICard,
  KPILabel,
  KPIValue,
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  SearchBox,
  ActionButton,
  TwoColGrid,
} from "../HRPortal/styles";
