// Generated by Copilot
import { Box, Typography, LinearProgress } from "@mui/material";
import {
  CheckCircle2,
  Clock,
  AlertTriangle,
  Shield,
  XCircle,
} from "lucide-react";
import { HOSPITALS, fmtINR } from "../../pages/HRPortalHospitals/data";
import type { RiskLevel } from "../../pages/HRPortalHospitals/data";
import { HospitalKpiCard } from "../HospitalKpiCard";
import {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
} from "../../pages/HRPortal/styles";

// ─── Risk badge ───────────────────────────────────────────────────────────────
function _RiskBadge({ level }: { level: RiskLevel }) {
  const _cfg: Record<
    RiskLevel,
    { bg: string; color: string; Icon: typeof Shield }
  > = {
    Low: { bg: "#ecfdf5", color: "#059669", Icon: Shield },
    Medium: { bg: "#fffbeb", color: "#d97706", Icon: AlertTriangle },
    High: { bg: "#fef2f2", color: "#ef4444", Icon: XCircle },
  };
  const { bg, color, Icon } = _cfg[level];
  return (
    <Box
      sx={{
        display: "inline-flex",
        alignItems: "center",
        gap: 0.5,
        px: 1.25,
        py: "2px",
        borderRadius: 20,
        backgroundColor: bg,
        fontSize: 10.5,
        fontWeight: 600,
        color,
      }}
    >
      <Icon size={12} /> {level}
    </Box>
  );
}

// ─── Approval rate bar ────────────────────────────────────────────────────────
function _ApprovalBar({ pct }: { pct: number }) {
  const _color = pct >= 90 ? "#10b981" : pct >= 80 ? "#f59e0b" : "#ef4444";
  return (
    <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
      <LinearProgress
        variant="determinate"
        value={pct}
        sx={{
          width: 80,
          height: 6,
          borderRadius: 3,
          backgroundColor: "#f3f4f6",
          "& .MuiLinearProgress-bar": {
            backgroundColor: _color,
            borderRadius: 3,
          },
        }}
      />
      <Typography
        sx={{ fontSize: 12, fontWeight: 700, color: _color, minWidth: 36 }}
      >
        {pct}%
      </Typography>
    </Box>
  );
}

interface HospitalPerformanceTabProps {
  policyCode: string;
}

export function HospitalPerformanceTab({
  policyCode,
}: HospitalPerformanceTabProps) {
  const _avgApproval = Math.round(
    HOSPITALS.reduce((s, h) => s + h.approvalRate, 0) / HOSPITALS.length,
  );
  const _avgDays = (
    HOSPITALS.reduce((s, h) => s + h.avgSettlementDays, 0) / HOSPITALS.length
  ).toFixed(1);
  const _totalComplaints = HOSPITALS.reduce((s, h) => s + h.complaintsCount, 0);
  const _highRiskCount = HOSPITALS.filter((h) => h.riskLevel === "High").length;

  return (
    <Box>
      <Box sx={{ mb: 3 }}>
        <Typography sx={{ fontSize: 20, fontWeight: 700, color: "#111827" }}>
          Hospital Performance
        </Typography>
        <Typography sx={{ fontSize: 13, color: "#6b7280", mt: 0.25 }}>
          Approval rates, settlement times & risk levels · {policyCode}
        </Typography>
      </Box>

      {/* KPI grid */}
      <Box
        sx={{
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: 2.5,
          mb: 3,
        }}
      >
        <HospitalKpiCard
          icon={CheckCircle2}
          iconColor="#10b981"
          iconBg="#ecfdf5"
          accentColor="#10b981"
          label="Avg Approval Rate"
          value={`${_avgApproval}%`}
          sub="Across all network hospitals"
        />
        <HospitalKpiCard
          icon={Clock}
          iconColor="#3b82f6"
          iconBg="#eff6ff"
          accentColor="#3b82f6"
          label="Avg Settlement Time"
          value={`${_avgDays}d`}
          sub="End-to-end claim settlement"
        />
        <HospitalKpiCard
          icon={AlertTriangle}
          iconColor="#f59e0b"
          iconBg="#fffbeb"
          accentColor="#f59e0b"
          label="Total Complaints"
          value={String(_totalComplaints)}
          sub={`${_highRiskCount} high-risk hospital(s)`}
        />
        <HospitalKpiCard
          icon={Shield}
          iconColor="#ef4444"
          iconBg="#fef2f2"
          accentColor="#ef4444"
          label="High Risk Hospitals"
          value={String(_highRiskCount)}
          sub="Require immediate attention"
        />
      </Box>

      {/* Performance table */}
      <SectionCard sx={{ p: 0, overflow: "hidden" }}>
        <Box
          sx={{
            px: 3,
            py: 2,
            borderBottom: "1px solid #f3f4f6",
            display: "flex",
            alignItems: "center",
            gap: 1,
          }}
        >
          <CheckCircle2 size={16} color="#9ca3af" />
          <Typography sx={{ fontSize: 14, fontWeight: 700, color: "#111827" }}>
            Performance Overview
          </Typography>
          <Typography sx={{ fontSize: 12, color: "#9ca3af" }}>
            — All {HOSPITALS.length} network hospitals
          </Typography>
        </Box>
        <Box sx={{ overflowX: "auto" }}>
          <StyledTable>
            <thead>
              <tr>
                <StyledTh>Hospital Name</StyledTh>
                <StyledTh>City</StyledTh>
                <StyledTh>Approval Rate</StyledTh>
                <StyledTh>Rejection Rate</StyledTh>
                <StyledTh>Avg Settlement</StyledTh>
                <StyledTh>Avg Claim</StyledTh>
                <StyledTh>Complaints</StyledTh>
                <StyledTh>Risk Level</StyledTh>
              </tr>
            </thead>
            <tbody>
              {HOSPITALS.map((h) => (
                <tr key={h.id}>
                  <StyledTd>
                    <Typography
                      sx={{ fontSize: 13, fontWeight: 600, color: "#111827" }}
                    >
                      {h.name}
                    </Typography>
                    <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
                      {h.type}
                    </Typography>
                  </StyledTd>
                  <StyledTd sx={{ fontSize: 12.5, color: "#6b7280" }}>
                    {h.city}
                  </StyledTd>
                  <StyledTd sx={{ minWidth: 160 }}>
                    <_ApprovalBar pct={h.approvalRate} />
                  </StyledTd>
                  <StyledTd>
                    <Typography
                      sx={{
                        fontSize: 12.5,
                        fontWeight: 600,
                        color:
                          h.rejectionRate >= 15
                            ? "#ef4444"
                            : h.rejectionRate >= 10
                            ? "#f59e0b"
                            : "#6b7280",
                      }}
                    >
                      {h.rejectionRate}%
                    </Typography>
                  </StyledTd>
                  <StyledTd sx={{ fontWeight: 500 }}>
                    {h.avgSettlementDays}d
                  </StyledTd>
                  <StyledTd>{fmtINR(h.avgAmount)}</StyledTd>
                  <StyledTd>
                    <Typography
                      sx={{
                        fontSize: 12.5,
                        fontWeight: 600,
                        color:
                          h.complaintsCount >= 10
                            ? "#ef4444"
                            : h.complaintsCount >= 5
                            ? "#f59e0b"
                            : "#6b7280",
                      }}
                    >
                      {h.complaintsCount}
                    </Typography>
                  </StyledTd>
                  <StyledTd>
                    <_RiskBadge level={h.riskLevel} />
                  </StyledTd>
                </tr>
              ))}
            </tbody>
          </StyledTable>
        </Box>
      </SectionCard>
    </Box>
  );
}

export default HospitalPerformanceTab;
