export const localConfigPayload = {
  systemDefaultFilter: {
    SmartSearchValues: {
      COMPANY: {
        organisationId: {
          value: 1,
          label: "IIRM India",
        },
        sbuId: "",
        verticalId: "",
        branchId: "",
        ownerId: {
          value: 1469,
          label: "Jom",
        },
        viewBy: {
          value: "team",
          label: "Manager + Team",
        },
        financialYear: {
          value: "2025",
          label: "2025-2026",
        },
        period: "",
        month: "",
        from: "",
        to: "",
        type: "",
        industrySegment: "",
        priority: "",
        city: "",
        companyType: "",
        status: {
          value: "Active",
          label: "Active",
        },
      },
      CONTACT: {
        branch: { value: 5, label: "allagandla" },
        department: "",
        financialYear: { value: "2025", label: "2025-2026" },
        from: "2025-04-01",
        month: "",
        organisationId: { value: 1, label: "IIRM India" },
        organisationName: { value: 263642, label: "Test org" },
        ownedBy: "",
        owner: "",
        ownerId: { value: 1469, label: "Suryamohan" },
        period: "",
        sbuId: "",
        status: { value: "Active", label: "Active" },
        to: "2026-03-31",
        verticalId: "",
        viewBy: { value: "team", label: "Manager + Team" },
      },
      RENEWAL_OPPORTUNITY: {
        branchId: "",
        companyName: "",
        financialYear: "",
        from: "2025-09-18",
        month: "",
        opportunityContact: "",
        opportunityIndustrySegment: "",
        opportunityPriority: "",
        organisationId: { value: 1, label: "IIRM India" },
        ownerId: { value: 1469, label: "Suryamohan" },
        period: { value: "3 Months", label: "3 Months" },
        sbuId: "",
        state: { value: "Active", label: "Active" },
        to: "2025-12-18",
        verticalId: "",
        viewBy: { value: "team", label: "Manager + Team" },
        opportunityPolicyType: "",
        activityName: "",
      },
      SALES_OPPORTUNITY: {
        activityName: "",
        branchId: "",
        companyName: "",
        financialYear: "",
        from: "2025-09-18",
        month: "",
        opportunityContact: "",
        opportunityIndustrySegment: "",
        opportunityPriority: "",
        organisationId: { value: 1, label: "IIRM India" },
        ownerId: { value: 1469, label: "Suryamohan" },
        period: { value: "3 Months", label: "3 Months" },
        sbuId: "",
        state: { value: "Active", label: "Active" },
        opportunityPolicyType: "",
        to: "2025-12-18",
        verticalId: "",
        viewBy: { value: "team", label: "Manager + Team" },
      },
      POLICY: {
        organisationId: {
          value: 1,
          label: "IIRM India",
        },
        sbuId: "",
        verticalId: "",
        branchId: "",
        ownerId: {
          value: 1469,
          label: "Suryamohan",
        },
        viewBy: {
          value: "team",
          label: "Manager + Team",
        },
        financialYear: {
          value: "2025",
          label: "2025-2026",
        },
        period: "",
        month: "",
        from: "2025-04-01",
        to: "2026-03-31",
        companyName: "",
        policyExpiryFromDate: "",
        policyExpiryToDate: "",
        renewalPeriod: "",
        industry: "",
        policyType: "",
      },
      CLIENT_PORTFOLIO: {
        branchId: "",
        companyType: "",
        financialYear: { value: "2025", label: "2025-2026" },
        from: "2025-04-01",
        organisationId: { value: 1, label: "IIRM India" },
        sbuId: "",
        verticalId: "",
        ownerId: "",
        priority: "",
        serviceScore: "",
        status: { value: "Active", label: "Active" },
        to: "2026-03-31",
        viewBy: "",
        period: { value: "3 Months", label: "3 Months" },
        month: "",
      },
      CLAIMS: {
        branchId: "",
        sbuId: "",
        verticalId: "",
        companyType: "",
        financialYear: { value: "2025", label: "2025-2026" },
        from: "2025-04-01",
        industrySegment: "",
        organisationId: { value: 1, label: "IIRM India" },
        ownerId: "",
        priorityLid: "",
        to: "2026-03-31",
        period: "",
        month: "",
        opportunityPolicyType: "",
        tatRange: "",
        claimStatus: "",
        viewBy: { value: "team", label: "Manager + Team" },
      },
      BIZ_DONE_REPORT: {
        organisationId: {
          value: 1,
          label: "IIRM India",
        },
        sbuId: "",
        verticalId: "",
        departmentId: "",
        branchId: "",
        financialYear: {
          value: "2025",
          label: "2025-2026",
        },
        quarter: {
          value: "ALL",
          label: "All",
        },
        month: {
          value: "ALL",
          label: "All",
        },
        userId: {
          value: 1469,
          label: "Suryamohan Surampudi",
        },
        owner: {
          value: "team",
          label: "Manager + Team",
        },
      },
    },
    TableDefaultSettings: {
      COMPANY: [
        { index: 0, name: "displayName", hide: false },
        { index: 1, name: "priority", hide: false },
        { index: 2, name: "policyPremium", hide: false },
        { index: 3, name: "roPremium", hide: false },
        { index: 4, name: "soPremium", hide: false },
        { index: 5, name: "leadCRM", hide: false },
        { index: 6, name: "status", hide: false },
        { index: 7, name: "currency", hide: true },
        { index: 8, name: "sumInsured", hide: true },
        { index: 9, name: "city", hide: true },
        { index: 10, name: "companyType", hide: true },
        { index: 11, name: "sentiment", hide: true },
        { index: 12, name: "country", hide: true },
        { index: 13, name: "companyName", hide: true },
        { index: 14, name: "industrySegment", hide: true },
      ],
      CONTACT: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "contactName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "owner", hide: false },
        { index: 7, name: "status", hide: false },
      ],
      RENEWAL_OPPORTUNITY: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "priority", hide: false },
        { index: 2, name: "policyType", hide: false },
        { index: 3, name: "expectedCloseDate", hide: false },
        { index: 4, name: "premium", hide: false },
        { index: 5, name: "activityName", hide: false },
        { index: 6, name: "assignedTo", hide: false },
        { index: 7, name: "branch", hide: false },
        { index: 8, name: "policyId", hide: false },
        { index: 9, name: "estimatedBrokerage", hide: true },
        { index: 10, name: "stageName", hide: true },
        { index: 11, name: "opportunityCreationDate", hide: true },
        { index: 12, name: "state", hide: true },
        { index: 13, name: "industrySegment", hide: true },
        { index: 14, name: "sumInsured", hide: true },
      ],
      SALES_OPPORTUNITY: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "priority", hide: false },
        { index: 2, name: "policyType", hide: false },
        { index: 3, name: "expectedCloseDate", hide: false },
        { index: 4, name: "activityName", hide: false },
        { index: 5, name: "premium", hide: false },
        { index: 6, name: "estimatedBrokerage", hide: false },
        { index: 7, name: "assignedTo", hide: false },
        { index: 8, name: "branch", hide: false },
        { index: 9, name: "stageName", hide: true },
        { index: 10, name: "opportunityCreationDate", hide: true },
        { index: 11, name: "state", hide: true },
        { index: 12, name: "industrySegment", hide: true },
        { index: 13, name: "sumInsured", hide: true },
      ],
      POLICY: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "policyType", hide: false },
        { index: 2, name: "insurerPolicyNumber", hide: false },
        { index: 3, name: "priority", hide: false },
        { index: 4, name: "premium", hide: false },
        { index: 5, name: "insurer", hide: false },
        { index: 6, name: "policyFrom", hide: false },
        { index: 7, name: "policyTo", hide: false },
        { index: 8, name: "policyStatus", hide: false },
        { index: 9, name: "sumInsured", hide: true },
        { index: 10, name: "bdOwner", hide: true },
        { index: 11, name: "accountManager", hide: true },
        { index: 12, name: "policyStep", hide: true },
        { index: 13, name: "currency", hide: true },
        { index: 14, name: "brokerageAmount", hide: false },
        { index: 15, name: "action", hide: false },
        { index: 16, name: "contacts", hide: true },
      ],
      BIZ_DONE_REPORT: [
        { index: 0, name: "iirmPolNo", hide: false },
        { index: 1, name: "iirmRefNo", hide: true },
        { index: 2, name: "insPolNo", hide: true },
        { index: 3, name: "insEndNo", hide: true },
        { index: 4, name: "incomeType", hide: true },
        { index: 5, name: "entryInIwork", hide: true },
        { index: 6, name: "incomeMonth", hide: true },
        { index: 7, name: "dateOfIncome", hide: true },
        { index: 8, name: "policyFromDate", hide: false },
        { index: 9, name: "policyToDate", hide: false },
        { index: 10, name: "custId", hide: true },
        { index: 11, name: "customerName", hide: false },
        { index: 12, name: "customerCategory", hide: true },
        { index: 13, name: "policyName", hide: false },
        { index: 14, name: "policyCategory", hide: true },
        { index: 15, name: "insurer", hide: false },
        { index: 16, name: "insBranch", hide: true },
        { index: 17, name: "empName", hide: false },
        { index: 18, name: "iirmBranch", hide: false },
        { index: 19, name: "vertical", hide: true },
        { index: 20, name: "department", hide: true },
        { index: 21, name: "status", hide: true },
        { index: 22, name: "sharePercentage", hide: true },
        { index: 23, name: "netPremium", hide: false },
        { index: 24, name: "terrorism", hide: true },
        { index: 25, name: "other", hide: true },
        { index: 26, name: "serviceTax", hide: true },
        { index: 27, name: "premiumCollected", hide: false },
        { index: 28, name: "grossPremium", hide: false },
        { index: 29, name: "brokeragePercentage", hide: true },
        { index: 30, name: "brokerageAmount", hide: false },
        { index: 31, name: "brokerageCollected", hide: true },
        { index: 32, name: "brokerageAmountAsEnteredByIsg", hide: true },
        { index: 33, name: "brokerageAmountAsPerIwork", hide: true },
        { index: 34, name: "fees", hide: true },
        { index: 35, name: "dealConfirmed", hide: true },
        { index: 36, name: "policyGroup", hide: true },
        { index: 37, name: "terrorismCommissionAmount", hide: true },
        { index: 38, name: "terrorismCommissionPercentage", hide: true },
        { index: 39, name: "policyStatus", hide: false },
        { index: 40, name: "companyVertical", hide: true },
      ],
      INSURER: [
        { index: 0, name: "insurerName", hide: false },
        { index: 1, name: "insurerAddresses", hide: false },
        { index: 2, name: "cityId", hide: false },
        { index: 3, name: "stateId", hide: false },
        { index: 4, name: "phoneNumber", hide: false },
      ],
      TPA: [
        { index: 0, name: "tpaName", hide: false },
        { index: 1, name: "tpaAddresses", hide: false },
        { index: 2, name: "cityId", hide: false },
        { index: 3, name: "stateId", hide: false },
        { index: 4, name: "phoneNumber", hide: false },
      ],
      BROKER: [
        { index: 0, name: "brokerName", hide: false },
        { index: 1, name: "brokerAddresses", hide: false },
        { index: 2, name: "cityId", hide: false },
        { index: 3, name: "stateId", hide: false },
        { index: 4, name: "phoneNumber", hide: false },
      ],
      INSURER_CONTACT: [
        { index: 0, name: "contactName", hide: false },
        { index: 1, name: "companyName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "status", hide: false },
      ],
      BROKER_CONTACT: [
        { index: 0, name: "contactName", hide: false },
        { index: 1, name: "companyName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "status", hide: false },
      ],

      TPA_CONTACT: [
        { index: 0, name: "contactName", hide: false },
        { index: 1, name: "companyName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "status", hide: false },
      ],
      CLIENT_PORTFOLIO: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "policyCount", hide: false },
        { index: 2, name: "policyPremium", hide: false },
        { index: 3, name: "priority", hide: false },
        { index: 4, name: "claimAmount", hide: false },
        { index: 5, name: "ServiceScore", hide: false },
        { index: 6, name: "actions", hide: false },
      ],
      ENDORSEMENT: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "endorsementId", hide: false },
        { index: 2, name: "companyPriority", hide: false },
        { index: 3, name: "policyNumber", hide: false },
        { index: 4, name: "policyType", hide: false },
        { index: 5, name: "endorsementDate", hide: false },
        { index: 6, name: "TATDate", hide: false },
        { index: 7, name: "status", hide: false },
      ],
      CLAIMS: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "claimNumber", hide: false },
        { index: 2, name: "policyType", hide: false },
        { index: 3, name: "companyPriority", hide: false },
        { index: 4, name: "claimDate", hide: false },
        { index: 5, name: "status", hide: false },
        { index: 6, name: "tatDays", hide: false },
        { index: 7, name: "claimAmount", hide: false },
      ],
      CD_MANAGEMENT: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "cdAccount", hide: false },
        { index: 2, name: "policyNumber", hide: false },
        { index: 3, name: "amount", hide: false },
        { index: 4, name: "minimumBalance", hide: false },
        { index: 5, name: "status", hide: false },
        { index: 6, name: "alert", hide: false },
        { index: 7, name: "actions", hide: false },
      ],
      EMPLOYEE: [
        { index: 0, name: "iirmEmpId", hide: false },
        { index: 1, name: "firstName", hide: false },
        { index: 2, name: "lastName", hide: false },
        { index: 3, name: "emailId", hide: false },
        { index: 4, name: "mobile", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "organisation", hide: false },
        { index: 7, name: "sbu", hide: false },
        { index: 8, name: "vertical", hide: false },
        { index: 9, name: "department", hide: false },
        { index: 10, name: "branch", hide: false },
        { index: 11, name: "status", hide: false },
        { index: 12, name: "roles", hide: false },
      ],
    },
  },
  userFilter: {
    SmartSearchValues: {
      COMPANY: {
        organisationId: {
          value: 1,
          label: "IIRM India",
        },
        sbuId: "",
        verticalId: "",
        branchId: "",
        ownerId: {
          value: 1469,
          label: "Jom",
        },
        viewBy: {
          value: "team",
          label: "Manager + Team",
        },
        financialYear: {
          value: "2024",
          label: "2024-2025",
        },
        period: "",
        month: { value: "January", label: "January" },
        from: "",
        to: "",
        type: "",
        industrySegment: "",
        priority: "",
        city: "",
        companyType: "",
        status: {
          value: "Active",
          label: "Active",
        },
      },
      CONTACT: {
        branch: { value: 7, label: "allagandla" },
        department: "",
        financialYear: "",
        from: "",
        month: "",
        organisationId: { value: 3, label: "IIRM India" },
        organisationName: { value: 263642, label: "Test org" },
        ownedBy: "",
        owner: "",
        ownerId: { value: 2001, label: "Jom" },
        period: { value: "3 Months", label: "3 Months" },
        sbuId: "",
        status: { value: "Active", label: "Active" },
        to: "2026-03-31",
        verticalId: { value: 305, label: "Lenders Advisory" },
        viewBy: { value: "manager", label: "Manager" },
      },
      RENEWAL_OPPORTUNITY: {
        branchId: "",
        companyName: "",
        financialYear: "",
        from: "2025-09-18",
        month: "",
        opportunityContact: "",
        opportunityIndustrySegment: "",
        opportunityPriority: "",
        organisationId: { value: 1, label: "IIRM India" },
        ownerId: { value: 1469, label: "Suryamohan" },
        period: { value: "3 Months", label: "3 Months" },
        sbuId: "",
        state: { value: "Active", label: "Active" },
        to: "2025-12-18",
        verticalId: "",
        viewBy: { value: "team", label: "Manager + Team" },
        opportunityPolicyType: "",
        activityName: "",
      },
      SALES_OPPORTUNITY: {
        activityName: "",
        branchId: "",
        companyName: "",
        financialYear: "",
        from: "2025-09-18",
        month: "",
        opportunityContact: "",
        opportunityIndustrySegment: "",
        opportunityPriority: "",
        organisationId: { value: 1, label: "IIRM India" },
        ownerId: { value: 1469, label: "Suryamohan" },
        period: { value: "3 Months", label: "3 Months" },
        opportunityPolicyType: "",
        sbuId: "",
        state: { value: "Active", label: "Active" },
        to: "2025-12-18",
        verticalId: "",
        viewBy: { value: "team", label: "Manager + Team" },
      },
      POLICY: {
        organisationId: {
          value: 1,
          label: "IIRM India",
        },
        sbuId: "",
        verticalId: "",
        branchId: "",
        ownerId: {
          value: 1469,
          label: "Suryamohan",
        },
        viewBy: {
          value: "team",
          label: "Manager + Team",
        },
        financialYear: {
          value: "2025",
          label: "2025-2026",
        },
        period: "",
        month: "",
        from: "2025-04-01",
        to: "2026-03-31",
        companyName: "",
        policyExpiryFromDate: "",
        policyExpiryToDate: "",
        renewalPeriod: "",
        industry: "",
        policyType: "",
      },
      CLIENT_PORTFOLIO: {
        branchId: "",
        companyType: "",
        financialYear: { value: "2025", label: "2025-2026" },
        from: "2025-04-01",
        organisationId: { value: 1, label: "IIRM India" },
        sbuId: "",
        verticalId: "",
        ownerId: "",
        priority: "",
        serviceScore: "",
        status: { value: "Active", label: "Active" },
        to: "2026-03-31",
        viewBy: "",
        period: { value: "3 Months", label: "3 Months" },
        month: "",
      },
      CLAIMS: {
        branchId: "",
        sbuId: "",
        verticalId: "",
        companyType: "",
        financialYear: { value: "2025", label: "2025-2026" },
        from: "2025-04-01",
        industrySegment: "",
        organisationId: { value: 1, label: "IIRM India" },
        ownerId: "",
        priorityLid: "",
        to: "2026-03-31",
        period: "",
        month: "",
        opportunityPolicyType: "",
        tatRange: "",
        claimStatus: "",
        viewBy: { value: "team", label: "Manager + Team" },
      },
      BIZ_DONE_REPORT: {
        organisationId: {
          value: 1,
          label: "IIRM India",
        },
        sbuId: "",
        verticalId: "",
        departmentId: "",
        branchId: "",
        financialYear: {
          value: "2025",
          label: "2025-2026",
        },
        quarter: {
          value: "ALL",
          label: "All",
        },
        month: {
          value: "ALL",
          label: "All",
        },
        userId: {
          value: 1469,
          label: "Suryamohan Surampudi",
        },
        owner: {
          value: "team",
          label: "Manager + Team",
        },
      },
    },
    TableDefaultSettings: {
      COMPANY: [
        { index: 0, name: "displayName", hide: false },
        { index: 1, name: "priority", hide: false },
        { index: 2, name: "policyPremium", hide: false },
        { index: 3, name: "roPremium", hide: false },
        { index: 4, name: "soPremium", hide: false },
        { index: 5, name: "leadCRM", hide: false },
        { index: 6, name: "status", hide: false },
        { index: 7, name: "currency", hide: true },
        { index: 8, name: "sumInsured", hide: true },
        { index: 9, name: "city", hide: true },
        { index: 10, name: "companyType", hide: true },
        { index: 11, name: "sentiment", hide: true },
        { index: 12, name: "country", hide: true },
        { index: 13, name: "companyName", hide: true },
        { index: 14, name: "industrySegment", hide: true },
      ],
      CONTACT: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "contactName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "owner", hide: false },
        { index: 7, name: "status", hide: false },
      ],
      RENEWAL_OPPORTUNITY: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "priority", hide: false },
        { index: 2, name: "policyType", hide: false },
        { index: 3, name: "expectedCloseDate", hide: false },
        { index: 4, name: "premium", hide: false },
        { index: 5, name: "activityName", hide: false },
        { index: 6, name: "assignedTo", hide: false },
        { index: 7, name: "branch", hide: false },
        { index: 8, name: "policyId", hide: false },
        { index: 9, name: "estimatedBrokerage", hide: true },
        { index: 10, name: "stageName", hide: true },
        { index: 11, name: "opportunityCreationDate", hide: true },
        { index: 12, name: "state", hide: true },
        { index: 13, name: "industrySegment", hide: true },
        { index: 14, name: "sumInsured", hide: true },
      ],
      SALES_OPPORTUNITY: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "priority", hide: false },
        { index: 2, name: "policyType", hide: false },
        { index: 3, name: "expectedCloseDate", hide: false },
        { index: 4, name: "activityName", hide: false },
        { index: 5, name: "premium", hide: false },
        { index: 6, name: "estimatedBrokerage", hide: false },
        { index: 7, name: "assignedTo", hide: false },
        { index: 8, name: "branch", hide: false },
        { index: 9, name: "stageName", hide: true },
        { index: 10, name: "opportunityCreationDate", hide: true },
        { index: 11, name: "state", hide: true },
        { index: 12, name: "industrySegment", hide: true },
        { index: 13, name: "sumInsured", hide: true },
      ],
      POLICY: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "policyType", hide: false },
        { index: 2, name: "insurerPolicyNumber", hide: false },
        { index: 3, name: "priority", hide: false },
        { index: 4, name: "premium", hide: false },
        { index: 5, name: "insurer", hide: false },
        { index: 6, name: "policyFrom", hide: false },
        { index: 7, name: "policyTo", hide: false },
        { index: 8, name: "policyStatus", hide: false },
        { index: 9, name: "sumInsured", hide: true },
        { index: 10, name: "bdOwner", hide: true },
        { index: 11, name: "accountManager", hide: true },
        { index: 12, name: "policyStep", hide: true },
        { index: 13, name: "currency", hide: true },
        { index: 14, name: "brokerageAmount", hide: false },
        { index: 15, name: "action", hide: false },
        { index: 16, name: "contacts", hide: true },
      ],
      BIZ_DONE_REPORT: [
        { index: 0, name: "iirmPolNo", hide: false },
        { index: 1, name: "iirmRefNo", hide: true },
        { index: 2, name: "insPolNo", hide: true },
        { index: 3, name: "insEndNo", hide: true },
        { index: 4, name: "incomeType", hide: true },
        { index: 5, name: "entryInIwork", hide: true },
        { index: 6, name: "incomeMonth", hide: true },
        { index: 7, name: "dateOfIncome", hide: true },
        { index: 8, name: "policyFromDate", hide: false },
        { index: 9, name: "policyToDate", hide: false },
        { index: 10, name: "custId", hide: true },
        { index: 11, name: "customerName", hide: false },
        { index: 12, name: "customerCategory", hide: true },
        { index: 13, name: "policyName", hide: false },
        { index: 14, name: "policyCategory", hide: true },
        { index: 15, name: "insurer", hide: false },
        { index: 16, name: "insBranch", hide: true },
        { index: 17, name: "empName", hide: false },
        { index: 18, name: "iirmBranch", hide: false },
        { index: 19, name: "vertical", hide: true },
        { index: 20, name: "department", hide: true },
        { index: 21, name: "status", hide: true },
        { index: 22, name: "sharePercentage", hide: true },
        { index: 23, name: "netPremium", hide: false },
        { index: 24, name: "terrorism", hide: true },
        { index: 25, name: "other", hide: true },
        { index: 26, name: "serviceTax", hide: true },
        { index: 27, name: "premiumCollected", hide: false },
        { index: 28, name: "grossPremium", hide: false },
        { index: 29, name: "brokeragePercentage", hide: true },
        { index: 30, name: "brokerageAmount", hide: false },
        { index: 31, name: "brokerageCollected", hide: true },
        { index: 32, name: "brokerageAmountAsEnteredByIsg", hide: true },
        { index: 33, name: "brokerageAmountAsPerIwork", hide: true },
        { index: 34, name: "fees", hide: true },
        { index: 35, name: "dealConfirmed", hide: true },
        { index: 36, name: "policyGroup", hide: true },
        { index: 37, name: "terrorismCommissionAmount", hide: true },
        { index: 38, name: "terrorismCommissionPercentage", hide: true },
        { index: 39, name: "policyStatus", hide: false },
        { index: 40, name: "companyVertical", hide: true },
      ],
      INSURER: [
        { index: 0, name: "insurerName", hide: false },
        { index: 1, name: "insurerAddresses", hide: false },
        { index: 2, name: "cityId", hide: false },
        { index: 3, name: "stateId", hide: false },
        { index: 4, name: "phoneNumber", hide: false },
      ],
      TPA: [
        { index: 0, name: "tpaName", hide: false },
        { index: 1, name: "tpaAddresses", hide: false },
        { index: 2, name: "cityId", hide: false },
        { index: 3, name: "stateId", hide: false },
        { index: 4, name: "phoneNumber", hide: false },
      ],
      BROKER: [
        { index: 0, name: "brokerName", hide: false },
        { index: 1, name: "brokerAddresses", hide: false },
        { index: 2, name: "cityId", hide: false },
        { index: 3, name: "stateId", hide: false },
        { index: 4, name: "phoneNumber", hide: false },
      ],
      INSURER_CONTACT: [
        { index: 0, name: "contactName", hide: false },
        { index: 1, name: "companyName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "status", hide: false },
      ],
      BROKER_CONTACT: [
        { index: 0, name: "contactName", hide: false },
        { index: 1, name: "companyName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "status", hide: false },
      ],
      TPA_CONTACT: [
        { index: 0, name: "contactName", hide: false },
        { index: 1, name: "companyName", hide: false },
        { index: 2, name: "phone", hide: false },
        { index: 3, name: "email", hide: false },
        { index: 4, name: "department", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "status", hide: false },
      ],
      CLIENT_PORTFOLIO: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "policyCount", hide: false },
        { index: 2, name: "policyPremium", hide: false },
        { index: 3, name: "priority", hide: false },
        { index: 4, name: "claimAmount", hide: false },
        { index: 5, name: "ServiceScore", hide: false },
        { index: 6, name: "actions", hide: false },
      ],
      ENDORSEMENT: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "endorsementId", hide: false },
        { index: 2, name: "companyPriority", hide: false },
        { index: 3, name: "policyNumber", hide: false },
        { index: 4, name: "policyType", hide: false },
        { index: 5, name: "endorsementDate", hide: false },
        { index: 6, name: "TATDate", hide: false },
        { index: 7, name: "status", hide: false },
      ],
      CLAIMS: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "claimNumber", hide: false },
        { index: 2, name: "policyType", hide: false },
        { index: 3, name: "companyPriority", hide: false },
        { index: 4, name: "claimDate", hide: false },
        { index: 5, name: "status", hide: false },
        { index: 6, name: "tatDays", hide: false },
        { index: 7, name: "claimAmount", hide: false },
      ],
      CD_MANAGEMENT: [
        { index: 0, name: "companyName", hide: false },
        { index: 1, name: "cdAccount", hide: false },
        { index: 2, name: "policyNumber", hide: false },
        { index: 3, name: "amount", hide: false },
        { index: 4, name: "minimumBalance", hide: false },
        { index: 5, name: "status", hide: false },
        { index: 6, name: "alert", hide: false },
        { index: 7, name: "actions", hide: false },
      ],
      EMPLOYEE: [
        { index: 0, name: "iirmEmpId", hide: false },
        { index: 1, name: "firstName", hide: false },
        { index: 2, name: "lastName", hide: false },
        { index: 3, name: "emailId", hide: false },
        { index: 4, name: "mobile", hide: false },
        { index: 5, name: "designation", hide: false },
        { index: 6, name: "organisation", hide: false },
        { index: 7, name: "sbu", hide: false },
        { index: 8, name: "vertical", hide: false },
        { index: 9, name: "department", hide: false },
        { index: 10, name: "branch", hide: false },
        { index: 11, name: "status", hide: false },
        { index: 12, name: "roles", hide: false },
      ],
      CRON_JOBS: [
        { index: 0, name: "schedulerName", hide: false },
        { index: 1, name: "schedulerExpression", hide: false },
        { index: 2, name: "lastRunStatus", hide: false },
        { index: 3, name: "lastSuccessfulRunAt", hide: false },
        { index: 4, name: "lastFailedRunAt", hide: false },
        { index: 5, name: "isEnabled", hide: false },
        { index: 6, name: "description", hide: false },
        { index: 7, name: "actions", hide: false },
      ],
    },
  },
};
