DELETE FROM mstr_nudge_scope_role_mapping
DELETE FROM mstr_nudge_parameters
DELETE FROM mstr_nudge_scope
DELETE FROM mstr_nudge_action
DELETE FROM mstr_nudge

ALTER SEQUENCE mstr_nudge_id_seq RESTART WITH 1;
ALTER SEQUENCE mstr_nudge_action_id_seq RESTART WITH 1;
ALTER SEQUENCE mstr_nudge_parameters_id_seq RESTART WITH 1;
ALTER SEQUENCE mstr_nudge_scope_id_seq RESTART WITH 1;
ALTER SEQUENCE mstr_nudge_scope_role_mapping_id_seq RESTART WITH 1;

INSERT INTO mstr_nudge
(name, description, nudge_template, prompt, endpoint_url, method, is_enable, org_id, key, icon_key, background_color)
VALUES
(
 'Lead Qualification Alert',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '140 leads are unqualified. Schedule a review session to improve lead qualification rate?',
 'Identify all unqualified leads and suggest suitable actions. Recommend scheduling a lead qualification review meeting to improve conversion rates.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'LEAD_QUALIFICATION_ALERT',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Pending Proposals',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '85 qualified leads havenot received proposals yet. Generate proposal drafts for top prospects?',
 'Fetch qualified leads with no proposals. Recommend generating proposal drafts for high-value prospects and creating a prioritized proposal list.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'PENDING_PROPOSALS',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'Pending Client Response',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '53 proposals are pending client response. Send follow-up reminders to move them to negotiation?',
 'Locate proposals pending client response. Suggest sending personalized follow-up reminders and guide the user to move these leads toward negotiation.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'PENDING_CLIENT_RESPONSE',
 'clockIcon',
 '#FFF7ED'
),
(
 'Stalled Negotiations',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 '14 deals are in negotiation for over 2 weeks. Schedule review meetings with sales managers?',
 'Identify deals stuck in negotiation beyond expected TAT. Recommend scheduling internal review meetings with sales managers to re-strategize.',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'STALLED_NEGOTIATIONS',
 'flagIcon',
 '#FEF2F2'
),
(
 'Renewal Quotes Pending',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '15 policies due for renewal havenot been quoted yet. Generate renewal quotes?',
 'Fetch all due-renewal cases without quotes. Suggest generating renewal quotes immediately to avoid potential renewal leakage.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'RENEWAL_QUOTES_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Renewal Follow-ups Due',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '20 quoted renewals need follow-up. Schedule client calls for this week?',
 'Find all renewal cases where quotes are submitted but follow-up is not done. Recommend scheduling client calls within the week.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'RENEWAL_FOLLOW_UPS_DUE',
 'phoneCallIcon',
 '#EFF6FF'
),
(
 'At-Risk Renewals',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '5 renewals in negotiation are at risk of loss due to pricing. Review competitive pricing options?',
 'Identify renewal negotiations marked as high risk due to pricing. Recommend reviewing competitive pricing options or alternative benefit structures.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'AT_RISK_RENEWALS',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Win-Back Opportunity',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '15 policies were lost this month. Initiate win-back campaigns for competitive losses?',
 'Find all recently lost policies and classify competitive losses. Suggest launching targeted win-back campaigns with revised offerings.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'WIN_BACK_OPPORTUNITY',
 'targetIcon',
 '#F3E8FF'
),
(
 'Mined Business Below Target',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Mined business is at 72%, below the 75% target. Review cross-sell opportunities with existing clients?',
 'Analyze mined business performance vs target. Recommend exploring cross-sell or up-sell opportunities to bridge performance gap.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'MINED_BUSSINESS_BELOW_TARGET',
'chartLineIcon',
'#FFF7ED'
),
(
 'New Business Target Exceeded!',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'New business exceeded target by 11%! Recognize top performers and share best practices with the team?',
 'Identify contributors who exceeded new business targets. Suggest recognition actions and share best practices across the team.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'NEW_BUSSINESS_TARGET_EXCEEDED',
 'trendingUpIcon',
 '#F0FDF4'
),
(
 'Incomplete Company Profiles',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '5 companies have incomplete profiles. Add missing details to improve data quality.',
 'Identify companies with incomplete profiles. Highlight missing fields and prompt the user to update company information to improve data completeness.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'INCOMPLETE_COMPANY_PROFILES',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Outdated Contact Details',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '3 companies have outdated contact details. Refresh contact info for better communication.',
 'Fetch companies flagged with outdated or invalid contact details. Recommend updating phone numbers, emails, and primary contact information.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'OUTDATED_CONTACT_DETAILS',
 'phoneCallIcon',
 '#EFF6FF'
),
(
 'Red-Flag Companies',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '4 companies marked RED require attention. Schedule follow-up activities.',
 'Locate companies marked as RED status. Suggest scheduling follow-up actions or escalation tasks to resolve pending issues.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'RED_FLAG_COMPANIES',
 'flagIcon',
 '#FEF2F2'
),
(
 'Qualified Leads Ready for Conversion',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 '12 qualified leads are ready for conversion. Move them to prospect stage.',
 'Find all qualified leads linked to companies and not yet moved to the prospect stage. Recommend progressing them to prospect status.',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'QUALIFIED_LEADS_READY_FOR_CONVERSION',
 'targetIcon',
 '#F3E8FF'
),
(
 'Unassigned Relationship Managers',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '7 companies donot have assigned relationship managers. Allocate resources.',
 'Identify companies without assigned relationship managers. Suggest allocating BD/CRM resources to ensure ongoing engagement.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'UNASSIGNED_RELATIONSHIP_MANAGERS',
 'usersIcon',
 '#EFF6FF'
),
(
 'Quarterly Client Review Due',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '8 clients are due for quarterly client review. Book meetings now.',
 'Fetch clients whose quarterly review is due. Recommend scheduling review meetings and preparing agendas.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'QUARTERLY_CLIENT_REVIEW_DUE',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Industry Intelligence Update',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 'Update industry intelligence for 6 companies to enhance sales strategy.',
 'Locate companies whose industry intelligence is outdated. Recommend updating key market insights to strengthen sales planning.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'INDUSTRY_INTELLIGENCE_UPDATE',
 'chartLineIcon',
 '#FFF7ED'
),
(
 'Policies Expiring This Month',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '15 policies expiring this month. Initiate renewal opportunities.',
 'Identify companies with policies expiring this month. Suggest initiating renewal outreach, quote preparation, and follow-up actions.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'POLICIES_EXPIRING_THIS_MONTH',
 'clockIcon',
 '#FFF7ED'
),
(
 'No Recent Interaction',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Log activities for 10 companies with no recent interactions in 30+ days.',
 'Fetch companies without logged interactions in the last 30+ days. Prompt the user to log a follow-up call, meeting, or email.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'NO_RECENT_INTERACTION',
'chatIcon',
'#EFF6FF'
),
(
 'Incomplete Address Information',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '4 companies have incomplete address information. Update for accurate records.',
 'Identify companies with missing or incomplete address fields. Recommend updating full address details for accuracy and compliance.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'INCOMPLETE_ADDRESS_INFORMATION',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Incomplete Contact Profiles',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '18 contacts have incomplete profiles. Update missing fields for better engagement.',
 'Identify contacts with incomplete profiles. Highlight missing fields like email, phone, designation, or department and prompt the user to update the details.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'INCOMPLETE_CONTACT_PROFILES',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Invalid / Outdated Email IDs',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '6 contacts have bounced emails. Update valid email IDs to ensure successful communication.',
 'Fetch contacts tagged with invalid or bounced emails. Recommend updating and verifying email details.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'INVALID_OR_OUTDATED_EMAIL_IDS',
 'documentAlertIcon',
'#FFF7ED'
),
(
 'Unreachable Contacts',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '9 contacts marked unreachable. Try alternate contact details or verify availability.',
 'Locate contacts for whom calls have failed or marked as unreachable. Suggest verifying phone numbers, alternate contacts, or updating communication preferences.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'UNREACHABLE_CONTACTS',
 'phoneCallIcon',
 '#EFF6FF'
),
(
 'No Recent Interaction',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 '22 contacts have had no interaction for 45+ days. Engage to maintain relationship.',
 'Identify contacts with no logged interactions in the last 45+ days. Recommend scheduling calls or sending engagement emails.',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'NO_RECENT_INTERACTION',
 'chatIcon',
 '#EFF6FF'
),
(
 'Decision Maker Not Identified',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '7 companies have contacts but no decision-maker assigned. Identify and tag the right person.',
 'Fetch companies where no contact is tagged as the decision-maker. Suggest identifying and marking the primary decision authority.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'DECISION_MAKER_NOT_IDENTIFIED',
 'usersIcon',
 '#EFF6FF'
),
(
 'Contacts without Company Mapping',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '4 contacts are not linked to any company. Assign them to the appropriate organization.',
 'Locate contacts not linked to any company. Recommend mapping them to the correct organization for clean data structure.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'CONTACTS_WITHOUT_COMPANY_MAPPING',
 'briefcaseIcon',
 '#EFF6FF'
),
(
 'Duplicate Contacts Detected',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '5 possible duplicate contacts found. Review and merge records.',
 'Identify contacts flagged as potential duplicates based on name, email, or mobile. Suggest merging or cleaning them.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'DUPLICATE_CONTACTS_DETECTED',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'Birthday / Anniversary Due',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '12 contacts have birthdays/anniversaries this week. Schedule greetings.',
 'Fetch upcoming birthdays or anniversaries for contacts. Recommend sending personalized greetings or automating messages.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'BIRTHDAY_OR_ANNIVERSARY_DUE',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Contact Role Change Needed',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '8 contacts may have updated roles or designations. Refresh information.',
 'Locate contacts whose designations or roles changed in CRM updates or external sources. Suggest updating profiles to maintain accuracy.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'CONTACT_ROLE_CHANGE_NEEDED',
'usersIcon',
'#EFF6FF'
),
(
 'Inactive Decision Makers',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 decision makers have been inactive for 60+ days. Re-engage with updated proposals or check-ins.',
 'Identify decision-makers with no recent engagement. Recommend initiating contact with new updates or check-in messages.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'INACTIVE_DECISION_MAKERS',
 'clockIcon',
 '#FFF7ED'
),
(
 'Opportunities Stuck in Early Stages',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '18 opportunities are stuck in Data Validation / KDM Meeting for over the expected TAT. Take action to push them forward.',
 'Identify opportunities stuck in early stages (Data Validation, KDM Meeting) beyond defined TAT. Recommend actions to progress them to Mandate or RFP stages.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'OPPORTUNITIES_STUCK_IN_EARLY_STAGES',
 'flagIcon',
 '#FEF2F2'
),
(
 'RFP Data Pending',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '10 opportunities have missing RFP data. Complete the information to avoid delays in broking slip generation.',
 'Fetch opportunities where RFP Data Collection or RFP Details Entry is incomplete. Suggest updating missing fields for smooth ISG and broking slip process.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'RFP_DATA_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Quotes Not Entered',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '7 opportunities have broking slips generated but quotes are not yet entered. Update quotes to proceed with QCR.',
 'Identify opportunities where broking slip exists but quote entry is pending. Recommend entering quotes to enable QCR generation.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'QUOTES_NOT_ENTERED',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'QCR Pending',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 '5 opportunities have pending QCR generation. Complete QCR to move opportunities into negotiation.',
 'Find opportunities with quotes entered but QCR not generated. Suggest generating QCR to advance the opportunity toward negotiation.',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'QCR_PENDING',
 'documentLinesIcon',
'#FAF5FF'
),
(
 'Stalled Negotiations',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '9 opportunities are in Negotiation stage for more than 10 days. Take follow-up action.',
 'Locate negotiation-stage opportunities delayed beyond expected timeframe. Recommend scheduling negotiation review meetings and client follow-ups.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'STALLED_NEGOTIATIONS',
 'clockIcon',
 '#FFF7ED'
),
(
 'Placement Slip Pending',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '6 opportunities cleared negotiation but placement slip is not created. Create the placement slip to proceed.',
 'Identify opportunities where Final Negotiation is completed but placement slip generation is pending. Suggest generating placement slips immediately.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'PLACEMENT_SLIP_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Premium Calculation Pending',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '4 opportunities require premium calculations for closure. Complete premium calculations to finalize the opportunity.',
 'Fetch opportunities where placement slip exists but premium calculation is pending. Recommend completing the premium calculation step.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'PREMIUM_CALCULATION_PENDING',
 'chartLineIcon',
 '#FFF7ED'
),
(
 'Held Cover Note Pending',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 opportunities have premium calculated but held cover note not issued. Issue cover note to avoid delays.',
 'Identify opportunities where premium is calculated but Held Cover Note is not issued. Prompt user to generate the held cover note.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'HELD_COVER_NOTE_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Policy Documentation Delayed',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '6 opportunities awaiting policy doclet / docket generation. Complete documentation for successful closure.',
 'Locate opportunities at Policy Doclet / Docket stage with pending documents. Suggest completing documentation for final policy issuance.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'POLICY_DOCUMENTATION_DELAYED',
'documentAlertIcon',
'#FFF7ED'
),
(
 'Client Follow-Up Required',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '11 opportunities require client follow-up (last activity > 7 days). Re-engage to prevent drop-off.',
 'Fetch opportunities with no interaction in last 7+ days. Suggest scheduling follow-ups to maintain client engagement.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'CLIENT_FOLLOW_UP_REQUIRED',
 'phoneCallIcon',
 '#EFF6FF'
),
(
 'High-Value Opportunities Pending Action',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '5 high-value opportunities (> ₹50L) require immediate updates. Prioritize for faster closure.',
 'Identify high-value opportunities needing attention. Recommend prioritizing updates and engaging decision makers.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'HIGH_VALUE_OPPORTUNITIES_PENDING_ACTION',
 'targetIcon',
 '#F3E8FF'
),
(
 'Opportunities Near Expected Closure Date',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '8 opportunities are nearing their expected closure date. Confirm status and expedite final steps.',
 'Find opportunities with expected closure date within next 7 days. Suggest final check-ins and accelerating pending actions.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'OPPORTUNITY_NEAR_EXPECTED_CLOSURE_DATE',
'calendarDateIcon',
'#F0FDFA'
),
(
 'Loss Risks Identified',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 opportunities flagged at risk due to pricing or delay. Take corrective measures.',
 'Locate opportunities marked as ‘at risk.’ Recommend reviewing pricing options, benefits, or engagement strategy.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'LOSS_RISKS_IDENTIFIED',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'RSR Creation Pending',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '9 renewal opportunities are due for RSR creation. Complete RSR to initiate renewal workflow.',
 'Identify renewal opportunities where RSR Creation is pending. Recommend creating the RSR to formally start the renewal process.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'RSR_CREATION_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Renewal KDM Meeting Pending',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '6 renewal opportunities require KDM meetings. Schedule meetings to finalize mandate renewal.',
 'Fetch renewal opportunities without completed KDM meetings. Suggest scheduling Renewal KDM Meetings with clients.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'RENEWAL_KDM_MEETING_PENDING',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Mandate Entry Pending',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '7 renewals have not completed Mandate Details Entry. Update mandate info to proceed with RFP.',
 'Locate renewal cases missing Mandate Details Entry. Prompt users to enter mandate details to progress the renewal opportunity.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'MANDATE_ENTRY_PENDING',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'RFP Data Collection Pending',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 '10 renewals have incomplete RFP data. Complete data to move to ISG planning.',
 'Fetch renewals where RFP Data Collection or RFP Details Entry is incomplete. Suggest updating missing fields to enable ISG planning.',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'RFP_DATA_COLLECTION_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'ISG Planning Delays',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '4 renewals are pending ISG planning. Initiate ISG discussions for timely slip creation.',
 'Identify renewals awaiting ISG planning. Recommend initiating ISG processes to prepare for broking slip generation.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'ISG_PLANNING_DELAYS',
 'clockIcon',
 '#FFF7ED'
),
(
 'Broking Slip Not Generated',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '8 renewals are ready for broking slips but not generated. Complete the slip to progress quoting.',
 'Find renewals where prerequisites are complete but broking slip not generated. Suggest generating slips to proceed to quote entry.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'BROKING_SLIP_NOT_GENERATED',
 'documentLinesIcon',
 '#FAF5FF'

),
(
 'Quotes Not Entered',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '5 renewals have broking slips generated but quotes not entered. Update quotes to move ahead.',
 'Identify renewal opportunities with broking slips but no quote entry. Recommend entering quotes for QCR generation.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'QUOTES_NOT_ENTERED',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'QCR Pending',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 renewals need QCR generation. Complete QCR to proceed with negotiation.',
 'Locate renewals with quotes entered but QCR not generated. Suggest completing QCR to move into negotiation stage.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'QCR_PENDING',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'Negotiation Stalled',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '6 renewals have been in negotiation for over 10 days. Follow up to avoid renewal leakage.',
 'Fetch renewal opportunities stuck in negotiation beyond TAT. Recommend follow-up with clients or insurers to revive movement.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'NEGOTIATION_STALLED',
'flagIcon',
'#FEF2F2'
),
(
 'Placement Slip Pending',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '4 renewals have completed negotiation but placement slip is not created. Generate slip to proceed.',
 'Identify renewals where negotiation is done but placement slip is pending. Suggest generating placement slip immediately.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'PLACEMENT_SLIP_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Premium Calculation Pending',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 renewals require premium calculation for closure. Complete calculations to finalize renewal.',
 'Fetch renewal opportunities where placement slip exists but premium calculation is pending. Recommend completing premium calculation.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'PREMIUM_CALCULATION_PENDING',
 'chartLineIcon',
 '#FFF7ED'
),
(
 'Held Cover Note Pending',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '2 renewals have premium calculated but held cover note not issued. Issue cover note to avoid delays.',
 'Locate renewals needing Held Cover Note issuance. Prompt user to generate the cover note.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'HELD_COVER_NOTE_PENDING',
'documentAlertIcon',
'#FFF7ED'
),
(
 'Policy Documentation Pending',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '5 renewal opportunities have pending Policy Docket/Doclet. Complete documentation for closure.',
 'Fetch renewals awaiting policy documentation. Suggest completing policy docket/doclet to finalize renewal.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'POLICY_DOCUMENTATION_PENDING',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Upcoming Renewals This Month',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '12 renewals are due within the next 30 days. Prioritize engagement.',
 'Identify upcoming renewals within 30 days. Recommend initiating renewal discussions, data updates, and follow-ups.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'UPCOMING_RENEWALS_THIS_MONTH',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'At-Risk Renewals',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '4 renewals are marked high risk due to pricing or competitor pressure. Take corrective action.',
 'Locate renewals marked as high risk. Recommend reviewing pricing, benefits, or competitive strategy to reduce leakage.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'AT_RISK_RENEWALS',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Renewal Follow-Up Required',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '9 renewal opportunities have no follow-up in 7+ days. Engage clients to avoid drop-off.',
 'Fetch renewals with no recent engagement. Suggest follow-up actions to keep the renewal cycle active.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'RENEWAL_FOLLOW_UP_REQUIRED',
 'phoneCallIcon',
 '#EFF6FF'
),
(
 'High-Value Renewals Pending Action',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 high-value renewals (> ₹50L) require immediate attention. Prioritize engagement.',
 'Identify high-value renewal opportunities needing action. Recommend prioritizing communication and required updates.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'HIGH_VALUE_RENEWALS_PENDING_ACTION',
'clockIcon',
'#FFF7ED'
),
(
 'Renewal Lead Conversion Opportunity',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '7 renewal leads have become qualified for cross-sell. Move them into New Opportunity stage.',
 'Locate renewal leads eligible for cross-sell/new products. Suggest converting them into new opportunities.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'RENEWAL_LEAD_CONVERSION_OPPORTUNITY',
 'targetIcon',
 '#F3E8FF'
),
(
 'Policies Pending Issuance',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '14 policies are pending issuance from insurer. Follow-up to expedite.',
 'Identify policies where placement is completed but issuance is pending. Recommend following up with insurer teams for faster issuance.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'POLICIES_PENDING_ISSUANCE',
 'clockIcon',
 '#FFF7ED'
),
(
 'Policy Documents Not Uploaded',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '11 issued policies do not have policy document uploaded. Add documents for compliance.',
 'Fetch issued policies where policy documents are missing in the system. Prompt user to upload soft copies for compliance and servicing.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'POLICY_DOCUMENTS_NOT_UPLOADED',
'documentAlertIcon',
'#FFF7ED'
),
(
 'Held Cover Notes Expiring',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '6 held cover notes are expiring within the next 7 days. Convert to final policy.',
 'Locate policies with held cover notes nearing expiration. Suggest initiating final policy issuance with insurer.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'HELD_COVER_NOTES_EXPIRING',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Endorsements Pending',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 '9 policies have pending endorsement requests. Complete endorsements to avoid servicing delays.',
 'Fetch policies with open endorsement requests. Recommend completing pending endorsements or following up with insurers.',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'ENDORSEMENTS_PENDING',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'Unassigned Policy Owners',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '4 policies do not have assigned owners/CRM. Allocate responsible user.',
 'Identify policies without assigned ownership (CRM/Servicing). Suggest allocating responsible users to ensure ongoing servicing.',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'UNASSIGNED_POLICY_OWNERS',
 'usersIcon',
 '#EFF6FF'
),
(
 'Premium Payment Pending',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 '7 policies have pending premium payments. Follow up with client/finance team.',
 'Fetch policies awaiting premium payment confirmation. Prompt user to follow up for payment collection and update.',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'PREMIUM_PAYMENT_PENDING',
 'chartLineIcon',
 '#FFF7ED'
),
(
 'Policy Renewal Due Soon',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 '18 policies are due for renewal within next 30 days. Initiate renewal process.',
 'Identify policies with renewal dates in next 30 days. Recommend creating renewal opportunities and reaching out to clients.',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'POLICY_RENEWAL_DUE_SOON',
'calendarDateIcon',
'#F0FDFA'
),
(
 'Policy Lapsed / At Risk',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 policies are at risk of lapse due to non-payment or delay. Take urgent action.',
 'Locate policies flagged as ‘at risk’ or ‘lapsed’. Suggest initiating urgent communication to revive or reinstate policy.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'POLICY_LAPSED_OR_AT_RISK',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Missing Policy Schedule',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '5 policies do not have policy schedule uploaded. Update records.',
 'Identify policies missing schedule documents. Recommend uploading schedules for complete policy documentation.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'MISSING_POLICY_SCHEDULE',
'documentAlertIcon',
'#FFF7ED'
),
(
 'Claims Reported but No FNOL Logged',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '4 policies have reported claims but no FNOL recorded. Log FNOL immediately.',
 'Fetch policies with claims reported externally but missing FNOL in system. Suggest logging FNOL and starting claim workflow.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'CLAIMS_REPORTED_BUT_NO_FNOL_LOGGED',
 'notificationBellIcon',
 '#FEF2F2'
),
(
 'Policies Without Sum Insured Details',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '8 policies have incomplete sum insured details. Update SI values to maintain accuracy.',
 'Locate policies missing Sum Insured details. Suggest updating SI fields for premium accuracy and reporting.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'POLICIES_WITHOUT_SUM_INSURED_DETAILS',
 'chartLineIcon',
 '#FFF7ED'
),
(
 'Insurer Mapping Missing',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '3 policies are missing insurer mapping or incorrect insurer name. Correct mapping required.',
 'Identify policies with missing/incorrect insurer IDs. Recommend updating insurer mapping for correct reconciliation.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'INSURER_MAPPING_MISSING',
'warningTriangleIcon',
'#FEF2F2'
),
(
 'Commission Not Received',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '10 policies issued >30 days ago have no commission entries yet. Follow up with insurer.',
 'Fetch policies older than 30 days without commission received. Suggest following up with insurer for commission statement.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'COMMISION_NOT_RECEIVED',
 'chartLineIcon',
 '#FFF7ED'
),
(
 'Premium Register Mismatch',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '6 policies mismatch with insurer premium register. Review and reconcile.',
 'Locate policies not found/mismatched in insurer premium register. Recommend reconciliation through RCON process.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'PREMIUM_REGISTER_MISMATCH',
'documentAlertIcon',
'#FFF7ED'
),
(
 'Policy End Date Approaching',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '12 policies will end within 15 days. Alert client for next steps.',
 'Identify policies with end dates in next 15 days. Suggest sending alerts to client and initiating renewal discussion.',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'POLICY_END_DATE_APPROACHING',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Policy with Missing Risk Details',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 '7 policies have incomplete risk information (vehicle, member count, assets). Update details.',
 'Fetch policies missing risk details. Recommend completing risk attributes for better analytics and compliance.',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'POLICY_WITH_MISSING_RISK_DETAILS',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Meetings Scheduled Today',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'You have meetings lined up today. Ensure you are prepared.',
 '“You have {{count_today}} meetings scheduled for today. Review agenda and prepare material?”',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'MEETINGS_SCHEDULED_TODAY',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Meetings Overdue',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 'Past meetings have incomplete minutes or updates.',
 'You have {{overdue_meetings}} overdue meetings without outcomes recorded. Update minutes now?',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'MEETINGS_OVERDUE',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Upcoming Meetings (Next 7 Days)',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 'Meetings coming up soon but no prep material or agenda.',
 'You have {{upcoming_7}} meetings in the next 7 days. Add agenda points or attach documents?',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'UPCOMING_MEETINGS',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Client Review Meetings Pending',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 'Clients due for monthly/quarterly review do not have meetings scheduled.',
 '{{client_reviews}} clients are due for review. Would you like to schedule review meetings?',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'CLIENT_REVIEW_MEETINGS_PENDING',
 'clockIcon',
 '#FFF7ED'
),
(
 'KDM Meetings Not Conducted',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'KDM meetings missing for important accounts (SO/RO).',
 'KDM meetings for {{missing_kdm}} key opportunities are pending. Schedule them to progress the cycle?',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'KDM_MEETINGS_NOT_CONDUCTED',
 'documentAlertIcon',
 '#FFF7ED'
),
(
 'Negotiation Meetings Delayed',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 'Final negotiation meetings pending for high-value deals.',
 '{{negotiation_pending}} high-value deals require negotiation meetings. Fix dates with decision-makers?',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'NEGOTIATION_MEETINGS_DELAYED',
 'clockIcon',
 '#FFF7ED'
),
(
 'Meeting Notes Missing',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 'Meetings conducted but minutes/notes missing.',
 '{{meetings_without_notes}} meetings don’t have notes recorded. Add outcomes to maintain audit trail?',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'MEETING_NOTES_MISSING',
 'documentLinesIcon',
 '#FAF5FF'
),
(
 'Low Meeting Conversion Rate',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Many meetings are done, but opportunities are not moving.',
 'Meeting-to-opportunity movement is low this week. Review {{stuck_after_meeting}} cases needing escalation?',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'LOW_MEETING_CONVERSION_RATE',
 'trendingUpIcon',
 '#F0FDF4'
),
(
 'Client Not Attended Meetings',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Clients have missed scheduled meetings; follow-up required.',
 '{{client_no_show}} meetings had client no-shows. Send rescheduling request?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'CLIENT_NOT_ATTENDED_MEETINGS',
'notificationBellIcon',
'#FEF2F2'
),
(
 'Internal Meetings Pending Approval',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Internal review meetings scheduled but not approved by managers.',
 '{{internal_pending}} internal meetings need managerial approval. Send reminders?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'INTERNAL_MEETINGS_PENDING_APPROVAL',
 'checkmarkCircleIcon',
 '#F0FDF4'
),
(
 'Tasks Due Today',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks scheduled for today need user attention.',
 'You have {{tasks_due_today}} tasks due today. Would you like to prioritize or mark them as completed?',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'TASKS_DUE_TODAY',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Overdue Tasks',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 'Tasks that were due earlier remain incomplete.',
 '{{tasks_overdue}} tasks are overdue. Review pending items to avoid delays?',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'OVERDUE_TASKS',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'High Priority Tasks Pending',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 'Critical tasks with high priority are still open.',
 'You have {{high_priority_pending}} high-priority tasks pending. Complete them to keep business on track?',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'HIGH_PRIORITY_TASKS_PENDING',
 'flagIcon',
 '#FEF2F2'
),
(
 'Tasks Pending for More Than 7 Days',
 'Deals stalled beyond 2 weeks. Tooltip: Last negotiation event, client activity.',
 'Tasks older than 7 days with no update.',
 '{{tasks_7days}} tasks are pending for more than 7 days. Update status or reassign?',
 '/api/deals/stalled',
 'GET',
 TRUE,
 1,
 'TASKS_PENDING_FOR_MORE_THAN_SEVEN_DAYS',
 'clockIcon',
 '#FFF7ED'
),
(
 'Tasks Without Due Date',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks created without a due date (risk of neglect).',
 '{{tasks_no_due_date}} tasks don’t have a due date. Add deadlines to avoid slippage?',
 '/api/leads/unqualified-count',
 'GET',
 TRUE,
 1,
 'TASKS_WITHOUT_DUE_DATE',
 'warningTriangleIcon',
 '#FEF2F2'
),
(
 'Tasks Assigned but Not Started',
 'Shows number of qualified leads awaiting proposals. Tooltip: Proposal pending duration, last activity, etc.',
 'Tasks are assigned but users haven’t started them.',
 '{{tasks_not_started}} tasks assigned to you haven’t been started yet. Begin progress?',
 '/api/proposals/pending',
 'GET',
 TRUE,
 1,
 'TASKS_ASSIGNED_BUT_NOT_STARTED',
 'clockIcon',
 '#FFF7ED'
),
(
 'Tasks Waiting for Client Inputs',
 'Shows proposals that require client response. Tooltip: Last message date, follow-up suggestion.',
 'Tasks pending action from clients (documents/approvals).',
 '{{client_pending_tasks}} tasks are waiting for client inputs. Send reminders?',
 '/api/proposals/pending-client-response',
 'GET',
 TRUE,
 1,
 'TASKS_WAITING_FOR_CLIENT_INPUTS',
 'phoneCallIcon',
 '#EFF6FF'
),
(
 'Repetitive Tasks Due This Week',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Weekly/recurring tasks scheduled.',
 'Your {{recurring tasks}} are due this week. Review and take action?',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'REPETITIVE_TASKS_DUE_THIS_WEEK',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Tasks Pending Review/Approval',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks require manager review before closure.',
 '{{tasks_pending_review}} tasks require manager approval. Notify or send reminders?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'TASKS_PENDING_REVIEW_OR_APPROVAL',
'checkmarkCircleIcon',
'#F0FDF4'
),
(
 'Tasks Linked to High-Value Deals',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks tied to large opportunities are pending.',
 'You have {{critical_opportunity_tasks}} tasks linked to high-value opportunities. Complete them to avoid deal delay?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'TASKS_LINKED_TO_HIGH_VALUE_DEALS',
 'targetIcon',
 '#F3E8FF'
),
(
 'Cross-Department Tasks Pending',
 'Shows count of leads that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks assigned to other departments stuck without update.',
 '{{cross_dept_pending}} tasks need follow-up with Ops/Servicing/Finance. Coordinate with teams?',
 '/api/leads/policy-count',
 'GET',
 TRUE,
 1,
 'CROSS_DEPARTMENT_TASKS_PENDING',
 'usersIcon',
 '#EFF6FF'
),
(
 'Tasks With Missing Documentation',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks pending due to missing invoice/quote/attachment.',
 '{{tasks_missing_docs}} tasks are missing documents. Upload or request required files?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'TASKS_WITH_MISSING_DOCUMENTATION',
'documentAlertIcon',
'#FFF7ED'
),
(
 'Tasks Related to Renewals Due Soon',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Renewal-linked tasks require action before expiry.',
 '{{renewal_tasks_due}} renewal-related tasks need attention. Complete to avoid renewal slippage?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'TASKS_RELATED_TO_RENEWAL_DUE_SOON',
 'calendarDateIcon',
 '#F0FDFA'
),
(
 'Tasks Auto-Created by Workflow',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Workflow-generated tasks pending confirmation.',
 '{{auto_tasks_pending}} auto-created tasks require your confirmation. Review and close?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
'TASKS_AUTO_CREATED_BY_WORKFLOW',
'notificationBellIcon',
'#FEF2F2'
),
(
 'Tasks Stuck in Progress',
 'Shows count of quoted renewals that are unqualified. Tooltip: Detailed reasoning why a lead is marked unqualified.',
 'Tasks in-progress but with no update for long.',
 '{{stuck_tasks}} tasks haven’t been updated in over X days. Add update or escalate?',
 '/api/leads/quoted-renewals-count',
 'GET',
 TRUE,
 1,
 'TASKS_STUCK_IN_PROGRESS',
 'flagIcon',
 '#FEF2F2'
);


INSERT INTO mstr_nudge_action (nudge_id, action_url, name, additional_details)
VALUES
    (1, '/review/leads', 'Review Now', 'Takes user to unqualified leads list'),
    (1, '', 'Not Now', 'Dismiss reminder temporarily'),

    (2, '/proposals/generate', 'Generate Proposals', 'Auto-generate proposal drafts'),
    (2, '', 'Later', 'Skip for now'),

    (3, '/proposals/send-reminders', 'Send Reminders', 'Trigger follow-up email'),
    (3, '', 'Skip', 'Ignore reminder now'),

    (4, '/meetings/schedule', 'Schedule Meetings', 'Set up negotiation review'),
    (4, '', 'Not Now', 'Skip reminder');


INSERT INTO mstr_nudge_parameters (nudge_id, parameter, data_type, type)
VALUES
	(1, 'unqualified_no', 'number', 'value'),

	(2, 'pending_proposals', 'number', 'value'),

	(3, 'pending_client_response', 'number', 'value'),

	(4, 'stalled_negotiations', 'number', 'value');


INSERT INTO mstr_nudge_scope (name, description, key)
VALUES
('Dashboard', 'Sales related nudge', 'DASHBOARD_SCOPE'),
('Company', 'Lead management nudge', 'COMPANY_SCOPE'),
('Contacts', 'Contact nudge', 'CONTACTS_SCOPE'),
('SO', 'Sales related nudge', 'SO_SCOPE'),
('RO', 'Proposal tracking nudge', 'RO_SCOPE'),
('Policy', 'Policy', 'POLICY_SCOPE'),
('Meetings', 'Meetings', 'MEETINGD_SCOPE'),
('Task', 'Task', 'TASK_SCOPE');


INSERT INTO mstr_nudge_scope_role_mapping (nudge_id, scope_id, role_id, is_enable)
SELECT
    n.nudge_id,
    n.scope_id,
    r.role_id,
    TRUE
FROM (
    
    SELECT generate_series(1, 10)  AS nudge_id, 1 AS scope_id UNION ALL
    SELECT generate_series(11, 20), 2 UNION ALL
    SELECT generate_series(21, 30), 3 UNION ALL
    SELECT generate_series(31, 43), 4 UNION ALL
    SELECT generate_series(44, 61), 5 UNION ALL
    SELECT generate_series(62, 77), 6 UNION ALL
    SELECT generate_series(78, 87), 7 UNION ALL
    SELECT generate_series(88, 102), 8
) n
CROSS JOIN (
    -- Roles list
    SELECT unnest(ARRAY[
        1,3,5,7,8,9,10,11,15,17,18,20,21,22,23,24,25,28,29
    ]) AS role_id
) r;

