// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const CategoryCard = styled(Box, {
  shouldForwardProp: (p) => p !== "active" && p !== "accentColor",
})<{ active?: boolean; accentColor?: string }>(({ active, accentColor }) => ({
  backgroundColor: active && accentColor ? `${accentColor}0f` : "#fff",
  borderRadius: 16,
  border:
    active && accentColor ? `2px solid ${accentColor}` : "1px solid #e5e7eb",
  padding: "20px 24px",
  cursor: "pointer",
  boxShadow:
    active && accentColor
      ? `0 4px 16px ${accentColor}20`
      : "0 1px 3px rgba(0,0,0,0.06)",
  transition: "all 0.2s ease",
  "&:hover": {
    boxShadow: accentColor
      ? `0 4px 16px ${accentColor}20`
      : "0 4px 12px rgba(0,0,0,0.08)",
    borderColor: accentColor ?? "#d1d5db",
  },
}));

export const CategoryIconWrap = styled(Box, {
  shouldForwardProp: (p) => p !== "accentColor" && p !== "active",
})<{ accentColor?: string; active?: boolean }>(({ accentColor, active }) => ({
  width: 40,
  height: 40,
  borderRadius: 12,
  backgroundColor: active
    ? "rgba(255,255,255,0.6)"
    : accentColor
    ? `${accentColor}18`
    : "#f3f4f6",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexShrink: 0,
}));

export const CountPill = styled(Box, {
  shouldForwardProp: (p) => p !== "accentColor",
})<{ accentColor?: string }>(({ accentColor }) => ({
  display: "inline-flex",
  alignItems: "center",
  padding: "3px 10px",
  borderRadius: 20,
  fontSize: 11,
  fontWeight: 600,
  backgroundColor: accentColor ? `${accentColor}12` : "#f3f4f6",
  color: accentColor ?? "#6b7280",
  marginTop: 12,
}));

export const ExpandedPanel = styled(Box, {
  shouldForwardProp: (p) => p !== "accentColor",
})<{ accentColor?: string }>(({ accentColor }) => ({
  marginTop: 12,
  backgroundColor: "#f8fafc",
  border: `1px solid ${accentColor ? `${accentColor}30` : "#e5e7eb"}`,
  borderRadius: "0 0 16px 16px",
  borderTop: "none",
  overflow: "hidden",
}));

export const PanelHeader = styled(Box, {
  shouldForwardProp: (p) => p !== "accentColor",
})<{ accentColor?: string }>(({ accentColor }) => ({
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  padding: "14px 20px",
  borderBottom: "1px solid #f1f5f9",
  backgroundColor: accentColor ? `${accentColor}0a` : "#f8fafc",
}));

export const ReportCardItem = styled(Box)({
  display: "flex",
  alignItems: "flex-start",
  justifyContent: "space-between",
  gap: 16,
  backgroundColor: "rgba(249,250,251,0.7)",
  border: "1px solid transparent",
  borderRadius: 12,
  padding: "14px 18px",
  transition: "all 0.15s ease",
  "&:hover": {
    backgroundColor: "#fff",
    borderColor: "#e5e7eb",
    boxShadow: "0 1px 6px rgba(0,0,0,0.06)",
  },
});

export const ReportIconWrap = styled(Box, {
  shouldForwardProp: (p) => p !== "accentBg",
})<{ accentBg?: string }>(({ accentBg }) => ({
  width: 36,
  height: 36,
  borderRadius: 10,
  backgroundColor: accentBg ?? "#f3f4f6",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexShrink: 0,
  marginTop: 2,
}));

export const OpenReportBtn = styled(Box, {
  shouldForwardProp: (p) => p !== "accentBg" && p !== "accentColor",
})<{ accentBg?: string; accentColor?: string }>(
  ({ accentBg, accentColor }) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    height: 32,
    padding: "0 14px",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
    marginTop: 2,
    cursor: "pointer",
    whiteSpace: "nowrap",
    backgroundColor: accentBg ?? "#eff6ff",
    color: accentColor ?? "#2563eb",
    border: "none",
    transition: "filter 0.1s",
    "&:hover": { filter: "brightness(0.95)" },
  }),
);
