// Generated by Copilot
import { useState } from "react";
import { Globe, Sun, Moon, Monitor } from "lucide-react";
import { useThemeMode, ThemeMode } from "../../context/ThemeModeContext";
import {
    SectionCard,
    SectionTitle,
    PrimaryButton,
    ActionButton,
} from "../../pages/HRPortal/styles";
import {
    PreferenceGroup,
    PreferenceGroupLabel,
    OptionGrid,
    OptionChip,
    PreferencesActionRow,
} from "./styles";

type Language = "en" | "fr";

const LANGUAGES: { id: Language; label: string }[] = [
    { id: "en", label: "English" },
    { id: "fr", label: "Français" },
];

const THEMES: { id: ThemeMode; label: string; Icon: React.ElementType }[] = [
    { id: "light", label: "Light", Icon: Sun },
    { id: "dark", label: "Dark", Icon: Moon },
    { id: "system", label: "System", Icon: Monitor },
];

export function SettingsPreferencesTab() {
    const { themeMode, setThemeMode } = useThemeMode();
    const [language, setLanguage] = useState<Language>("en");
    const [savedLanguage, setSavedLanguage] = useState<Language>("en");
    const [savedTheme, setSavedTheme] = useState<ThemeMode>(themeMode);

    const hasChanged = language !== savedLanguage || themeMode !== savedTheme;

    function handleSave() {
        setSavedLanguage(language);
        setSavedTheme(themeMode);
    }

    function handleCancel() {
        setLanguage(savedLanguage);
        setThemeMode(savedTheme);
    }

    return (
        <SectionCard sx={{ maxWidth: 680 }}>
            <SectionTitle>Preferences</SectionTitle>

            {/* Language */}
            <PreferenceGroup>
                <PreferenceGroupLabel>
                    <Globe size={12} style={{ display: "inline", marginRight: 6, verticalAlign: "middle" }} />
                    Language
                </PreferenceGroupLabel>
                <OptionGrid>
                    {LANGUAGES.map((lang) => (
                        <OptionChip
                            key={lang.id}
                            selected={language === lang.id}
                            onClick={() => setLanguage(lang.id)}
                        >
                            {lang.label}
                        </OptionChip>
                    ))}
                </OptionGrid>
            </PreferenceGroup>

            {/* Theme */}
            <PreferenceGroup>
                <PreferenceGroupLabel>
                    <Sun size={12} style={{ display: "inline", marginRight: 6, verticalAlign: "middle" }} />
                    Theme
                </PreferenceGroupLabel>
                <OptionGrid>
                    {THEMES.map(({ id, label, Icon }) => (
                        <OptionChip
                            key={id}
                            selected={themeMode === id}
                            onClick={() => setThemeMode(id)}
                        >
                            <Icon size={13} />
                            {label}
                        </OptionChip>
                    ))}
                </OptionGrid>
            </PreferenceGroup>

            <PreferencesActionRow>
                <PrimaryButton
                    sx={{
                        cursor: hasChanged ? "pointer" : "not-allowed",
                        opacity: hasChanged ? 1 : 0.5,
                    }}
                    onClick={hasChanged ? handleSave : undefined}
                >
                    Save Preferences
                </PrimaryButton>
                <ActionButton sx={{ cursor: "pointer" }} onClick={handleCancel}>
                    Cancel
                </ActionButton>
            </PreferencesActionRow>
        </SectionCard>
    );
}

export default SettingsPreferencesTab;
