// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";

export const PreferenceGroup = styled(Box)(({ theme }) => ({
    marginBottom: theme.spacing(3),
}));

export const PreferenceGroupLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.text.grey,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: theme.spacing(1.25),
}));

export const OptionGrid = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(1.25),
    flexWrap: "wrap" as const,
}));

export const OptionChip = styled(Box, {
    shouldForwardProp: (p) => p !== "selected",
})<{ selected?: boolean }>(({ theme, selected }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(0.75),
    padding: theme.spacing(0.875, 2),
    borderRadius: theme.shape.borderRadii.medium,
    border: `1.5px solid ${selected ? theme.palette.secondary.selected : theme.palette.neutral.tableBorder}`,
    backgroundColor: selected ? theme.palette.background.tabsSelected : theme.palette.background.paper,
    color: selected ? theme.palette.secondary.selected : theme.palette.neutral.medium,
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: selected ? theme.typography.fontWeights.semiBold : theme.typography.fontWeights.regular,
    cursor: "pointer",
    userSelect: "none" as const,
    transition: "all 0.15s ease",
    "&:hover": {
        borderColor: theme.palette.secondary.selected,
        backgroundColor: theme.palette.background.tabsSelected,
        color: theme.palette.secondary.selected,
    },
}));

export const PreferencesActionRow = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(3),
    paddingTop: theme.spacing(2.5),
    borderTop: `1px solid ${theme.palette.neutral.tableBorder}`,
}));
