import { renderHook, act } from '@testing-library/react';
import { useDebounce } from './useDebounce';

// Generated by Copilot

describe('useDebounce', () => {
  it('should return the initial value immediately', () => {
    const { result } = renderHook(({ value }) => useDebounce(value), {
      initialProps: { value: 'test' },
    });
    expect(result.current).toBe('test');
  });

  it('should debounce value changes', async () => {
    jest.useFakeTimers();
    const { result, rerender } = renderHook(({ value }) => useDebounce(value, 300), {
      initialProps: { value: 'first' },
    });
    expect(result.current).toBe('first');

    rerender({ value: 'second' });
    expect(result.current).toBe('first');

    act(() => {
      jest.advanceTimersByTime(299);
    });
    expect(result.current).toBe('first');

    act(() => {
      jest.advanceTimersByTime(1);
    });
    expect(result.current).toBe('second');
    jest.useRealTimers();
  });

  it('should reset timer if value changes before delay', () => {
    jest.useFakeTimers();
    const { result, rerender } = renderHook(({ value }) => useDebounce(value, 200), {
      initialProps: { value: 'a' },
    });
    rerender({ value: 'b' });
    act(() => {
      jest.advanceTimersByTime(100);
    });
    rerender({ value: 'c' });
    act(() => {
      jest.advanceTimersByTime(200);
    });
    expect(result.current).toBe('c');
    jest.useRealTimers();
  });
});
