// Generated by Copilot
import { Box, Typography } from "@mui/material";
import { ChevronDown } from "lucide-react";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
} from "recharts";
import { TwoColGrid, ChartBox, ActionButton } from "./styles";
import type { TrendPoint } from "../../pages/HRPortalDashboard/types";

const CLAIMS_TREND: TrendPoint[] = [
  { m: "Oct", v: 28 },
  { m: "Nov", v: 35 },
  { m: "Dec", v: 42 },
  { m: "Jan", v: 38 },
  { m: "Feb", v: 51 },
  { m: "Mar", v: 44 },
];

const ENROLMENT_TREND: TrendPoint[] = [
  { m: "Oct", v: 820 },
  { m: "Nov", v: 855 },
  { m: "Dec", v: 880 },
  { m: "Jan", v: 910 },
  { m: "Feb", v: 950 },
  { m: "Mar", v: 980 },
];

const TT_STYLE = {
  contentStyle: {
    borderRadius: 8,
    border: "1px solid #e5e7eb",
    fontSize: 12,
    boxShadow: "0 4px 16px rgba(0,0,0,.08)",
    padding: "6px 10px",
  },
};

export function ChartsRow() {
  return (
    <TwoColGrid sx={{ mb: 2.5 }}>
      {/* Claims Trend */}
      <ChartBox>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            mb: 2,
          }}
        >
          <Typography sx={{ fontSize: 14, fontWeight: 600, color: "#111827" }}>
            Claims Trend
          </Typography>
          <ActionButton
            sx={{
              display: "flex",
              alignItems: "center",
              gap: 0.5,
              fontSize: 12,
              py: 0.5,
              px: 1.25,
            }}
          >
            <span>Last 6 months</span>
            <ChevronDown size={12} />
          </ActionButton>
        </Box>
        <ResponsiveContainer width="100%" height={180}>
          <LineChart data={CLAIMS_TREND}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis
              dataKey="m"
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <YAxis
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <RechartTooltip {...TT_STYLE} />
            <Line
              type="monotone"
              dataKey="v"
              stroke="#3b82f6"
              strokeWidth={2.5}
              dot={{ r: 3, fill: "#3b82f6" }}
            />
          </LineChart>
        </ResponsiveContainer>
      </ChartBox>

      {/* Enrolled Lives */}
      <ChartBox>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            mb: 2,
          }}
        >
          <Typography sx={{ fontSize: 14, fontWeight: 600, color: "#111827" }}>
            Enrolled Lives
          </Typography>
          <ActionButton
            sx={{
              display: "flex",
              alignItems: "center",
              gap: 0.5,
              fontSize: 12,
              py: 0.5,
              px: 1.25,
            }}
          >
            <span>Last 6 months</span>
            <ChevronDown size={12} />
          </ActionButton>
        </Box>
        <ResponsiveContainer width="100%" height={180}>
          <BarChart data={ENROLMENT_TREND}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis
              dataKey="m"
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <YAxis
              tick={{ fontSize: 11, fill: "#9ca3af" }}
              axisLine={false}
              tickLine={false}
            />
            <RechartTooltip {...TT_STYLE} />
            <Bar dataKey="v" fill="#10b981" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </ChartBox>
    </TwoColGrid>
  );
}

export default ChartsRow;
