// Generated by Copilot
import { Box } from "@mui/material";
import { TrendingUp, TrendingDown } from "lucide-react";
import type { KPIItem } from "../../pages/HRPortalDashboard/types";
import { KPIGrid, KPICard, KPILabel, KPIValue, KPIChange } from "./styles";

interface KPIRowProps {
  items: KPIItem[];
}

export function KPIRow({ items }: KPIRowProps) {
  return (
    <KPIGrid>
      {items.map((kpi) => (
        <KPICard key={kpi.label}>
          <Box
            sx={{
              display: "flex",
              alignItems: "flex-start",
              justifyContent: "space-between",
              mb: 1.5,
            }}
          >
            <Box>
              <KPILabel>{kpi.label}</KPILabel>
              <KPIValue sx={{ mt: 0.5 }}>{kpi.value}</KPIValue>
            </Box>
            <Box
              sx={{
                width: 36,
                height: 36,
                borderRadius: "50%",
                backgroundColor: `${kpi.accent}18`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <kpi.Icon size={17} color={kpi.accent} />
            </Box>
          </Box>
          <KPIChange positive={kpi.positive}>
            {kpi.positive ? (
              <TrendingUp size={12} />
            ) : (
              <TrendingDown size={12} />
            )}
            {kpi.change} this month
          </KPIChange>
        </KPICard>
      ))}
    </KPIGrid>
  );
}

export default KPIRow;
