// Generated by Copilot
// Re-exports shared KPI styled components from the central HRPortal design tokens.
export {
  KPIGrid,
  KPICard,
  KPILabel,
  KPIValue,
  KPIChange,
} from "../../pages/HRPortal/styles";
