// Generated by Copilot
import { useState } from "react";
import { Box, Typography } from "@mui/material";
import { Eye, EyeOff, Check, X } from "lucide-react";
import {
    SectionCard,
    SectionTitle,
    PrimaryButton,
    ActionButton,
} from "../../pages/HRPortal/styles";
import {
    PasswordFieldWrap,
    PasswordInput,
    EyeToggle,
    FieldLabel,
    StrengthBarWrap,
    StrengthSegment,
    StrengthLabel,
    MatchHint,
    SecurityActionRow,
} from "./styles";

// ─── Strength logic ───────────────────────────────────────────────────────────
type StrengthLevel = 0 | 1 | 2 | 3 | 4 | 5;

const STRENGTH_META: Record<
    StrengthLevel,
    { label: string; color: string; filled: number }
> = {
    0: { label: "", color: "", filled: 0 },
    1: { label: "Very weak", color: "#E15857", filled: 1 },
    2: { label: "Weak", color: "#E15857", filled: 2 },
    3: { label: "Fair", color: "#825905", filled: 3 },
    4: { label: "Good", color: "#338CE5", filled: 4 },
    5: { label: "Strong", color: "#079F92", filled: 5 },
};

function getStrength(password: string): StrengthLevel {
    if (!password) return 0;
    let score = 0;
    if (password.length >= 8) score++;
    if (password.length >= 12) score++;
    if (/[A-Z]/.test(password)) score++;
    if (/[0-9]/.test(password)) score++;
    if (/[^A-Za-z0-9]/.test(password)) score++;
    return Math.min(score, 5) as StrengthLevel;
}

// ─── Component ────────────────────────────────────────────────────────────────
export function SettingsSecurityTab() {
    const [currentPass, setCurrentPass] = useState("");
    const [newPass, setNewPass] = useState("");
    const [confirmPass, setConfirmPass] = useState("");
    const [showCurrent, setShowCurrent] = useState(false);
    const [showNew, setShowNew] = useState(false);
    const [showConfirm, setShowConfirm] = useState(false);

    const strength = getStrength(newPass) as StrengthLevel;
    const meta = STRENGTH_META[strength];
    const passwordsMatch = newPass.length > 0 && confirmPass.length > 0 && newPass === confirmPass;
    const passwordsMismatch = confirmPass.length > 0 && newPass !== confirmPass;

    function handleReset() {
        setCurrentPass("");
        setNewPass("");
        setConfirmPass("");
    }

    return (
        <SectionCard sx={{ maxWidth: 680 }}>
            <SectionTitle>Change Password</SectionTitle>
            <Box sx={{ display: "flex", flexDirection: "column", gap: 2.5, maxWidth: 400 }}>

                {/* Current Password */}
                <Box>
                    <FieldLabel>Current Password</FieldLabel>
                    <PasswordFieldWrap>
                        <PasswordInput
                            type={showCurrent ? "text" : "password"}
                            value={currentPass}
                            onChange={(e) => setCurrentPass(e.target.value)}
                            placeholder="••••••••"
                        />
                        <EyeToggle onClick={() => setShowCurrent((s) => !s)}>
                            {showCurrent ? <EyeOff size={15} /> : <Eye size={15} />}
                        </EyeToggle>
                    </PasswordFieldWrap>
                </Box>

                {/* New Password */}
                <Box>
                    <FieldLabel>New Password</FieldLabel>
                    <PasswordFieldWrap>
                        <PasswordInput
                            type={showNew ? "text" : "password"}
                            value={newPass}
                            onChange={(e) => setNewPass(e.target.value)}
                            placeholder="••••••••"
                        />
                        <EyeToggle onClick={() => setShowNew((s) => !s)}>
                            {showNew ? <EyeOff size={15} /> : <Eye size={15} />}
                        </EyeToggle>
                    </PasswordFieldWrap>

                    {/* Strength bar */}
                    {newPass.length > 0 && (
                        <Box>
                            <StrengthBarWrap>
                                {([1, 2, 3, 4, 5] as const).map((seg) => (
                                    <StrengthSegment
                                        key={seg}
                                        filled={seg <= meta.filled}
                                        segmentColor={meta.color}
                                    />
                                ))}
                            </StrengthBarWrap>
                            <StrengthLabel labelColor={meta.color}>
                                {meta.label}
                            </StrengthLabel>
                        </Box>
                    )}
                </Box>

                {/* Confirm Password */}
                <Box>
                    <FieldLabel>Confirm New Password</FieldLabel>
                    <PasswordFieldWrap>
                        <PasswordInput
                            type={showConfirm ? "text" : "password"}
                            value={confirmPass}
                            onChange={(e) => setConfirmPass(e.target.value)}
                            placeholder="••••••••"
                        />
                        <EyeToggle onClick={() => setShowConfirm((s) => !s)}>
                            {showConfirm ? <EyeOff size={15} /> : <Eye size={15} />}
                        </EyeToggle>
                    </PasswordFieldWrap>

                    {/* Match indicator */}
                    {passwordsMatch && (
                        <MatchHint matched>
                            <Check size={13} />
                            <Typography sx={{ fontSize: "inherit", color: "inherit" }}>
                                Passwords match
                            </Typography>
                        </MatchHint>
                    )}
                    {passwordsMismatch && (
                        <MatchHint matched={false}>
                            <X size={13} />
                            <Typography sx={{ fontSize: "inherit", color: "inherit" }}>
                                Passwords do not match
                            </Typography>
                        </MatchHint>
                    )}
                </Box>
            </Box>

            <SecurityActionRow>
                <PrimaryButton
                    sx={{
                        cursor: passwordsMatch ? "pointer" : "not-allowed",
                        opacity: passwordsMatch ? 1 : 0.5,
                    }}
                >
                    Update Password
                </PrimaryButton>
                <ActionButton sx={{ cursor: "pointer" }} onClick={handleReset}>
                    Cancel
                </ActionButton>
            </SecurityActionRow>
        </SectionCard>
    );
}

export default SettingsSecurityTab;
