// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";

export const PasswordFieldWrap = styled(Box)(() => ({
    position: "relative",
}));

export const PasswordInput = styled("input")(({ theme }) => ({
    width: "100%",
    padding: "10px 40px 10px 14px",
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xss,
    outline: "none",
    boxSizing: "border-box",
    color: theme.palette.neutral.mediumDark,
    backgroundColor: theme.palette.background.paper,
    fontFamily: "inherit",
    "&:focus": {
        borderColor: theme.palette.secondary.selected,
    },
}));

export const EyeToggle = styled(Box)(({ theme }) => ({
    position: "absolute",
    right: 12,
    top: "50%",
    transform: "translateY(-50%)",
    cursor: "pointer",
    color: theme.palette.text.grey,
    display: "flex",
    alignItems: "center",
    "&:hover": {
        color: theme.palette.neutral.medium,
    },
}));

export const FieldLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.medium,
    marginBottom: theme.spacing(0.75),
}));

export const StrengthBarWrap = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(0.5),
    marginTop: theme.spacing(1),
}));

export const StrengthSegment = styled(Box, {
    shouldForwardProp: (p) => p !== "filled" && p !== "segmentColor",
})<{ filled?: boolean; segmentColor?: string }>(({ theme, filled, segmentColor }) => ({
    flex: 1,
    height: 4,
    borderRadius: 4,
    backgroundColor: filled && segmentColor
        ? segmentColor
        : theme.palette.neutral.tableBorder,
    transition: "background-color 0.2s",
}));

export const StrengthLabel = styled(Typography, {
    shouldForwardProp: (p) => p !== "labelColor",
})<{ labelColor?: string }>(({ theme, labelColor }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.medium,
    color: labelColor ?? theme.palette.text.grey,
    marginTop: theme.spacing(0.5),
}));

export const MatchHint = styled(Box, {
    shouldForwardProp: (p) => p !== "matched",
})<{ matched?: boolean }>(({ theme, matched }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(0.5),
    marginTop: theme.spacing(0.75),
    fontSize: theme.typography.fontSizes.xs,
    color: matched ? theme.palette.neutral.green : theme.palette.text.error,
}));

export const SecurityActionRow = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(3),
}));
