import {
  Controller,
  Post,
  Body,
  Res,
  ForbiddenException,
  NotFoundException,
  Get,
  Req,
  UnauthorizedException,
  UseGuards,
} from "@nestjs/common";
import { HttpStatus } from "@nestjs/common";
import { SimpleAuthService } from "./simple-auth.service";
import {
  loginSwaggerMetadata,
  getUserDetailsSwaggerMetadata,
  refreshTokenSwaggerMetadata,
  crmRedirectTokenSwaggerMetadata,
} from "./simple-auth.swagger";
import { ApiTags } from "@nestjs/swagger";
import { CreateSimpleAuthDto } from "../../../../service-lib/src/lib/dto/create-simple-auth.dto";
import {
  errorMessages,
  successMessage,
} from "../../../../../../libs/service-lib/src/lib/messages";
import type { Request, Response } from "express"; // Generated by Copilot
import { TraceIdService } from "../../../../service-lib/src/lib/trace-id.service";
import { createLogger } from "../../../../service-lib/src/lib/logger";
import { serviceNames } from "../../../../service-lib/src/lib/constants";
import { buildLogMessage } from "../../../../service-lib/src/lib/utils/logger.util";
import { handleErrorResponse } from "../../../../../../libs/service-lib/src/lib/utils/response.utils";
import { RefreshTokenDto } from "../simple-auth/dto/refresh-token.dto";
import { UserTrace } from "../../../../service-lib/src/lib/audit-history/decorators/user-trace.decorator";
import { AuthProtected } from "../../../../service-lib/src/lib/auth-protection";
import { CaptchaGuard } from "@divami-labs/nestjs-captcha";
import { JwtService } from "@nestjs/jwt";
import { ENV } from "../../../../service-lib/src/lib/environment";
@ApiTags("SimpleAuth") // Grouping the endpoints under "SimpleAuth"
@Controller("")
export class SimpleAuthController {
  private readonly logger: ReturnType<typeof createLogger>;

  constructor(
    private readonly simpleAuthService: SimpleAuthService,
    private readonly traceIdService: TraceIdService,
    private readonly jwtService: JwtService
  ) {
    this.logger = createLogger(this.traceIdService, serviceNames.AUTH_SERVICE);
  }
  // Login endpoint
  @Post("login")
  @AuthProtected()
  @UserTrace("LOGIN")
  @UseGuards(CaptchaGuard)
  @loginSwaggerMetadata()
  async login(
    @Body() loginDto: CreateSimpleAuthDto,
    @Req() req: Request,
    @Res() res: Response
  ): Promise<any> {
    const userId = 1; // default user context for login
    this.logger.log({
      level: "info",
      message: buildLogMessage({
        traceId: this.traceIdService.traceId,
        userId,
        status: "success",
        location: "SimpleAuthController",
        method: "login",
        payload: loginDto,
        messageData: "method invoked",
      }),
    });
    try {
      // Use forceLogin directly from the validated DTO
      const forceLogin = loginDto.forceLogin === true;
      
      const user = await this.simpleAuthService.validateUser(
        loginDto.userName,
        loginDto.password,
        (loginDto.clientScopeId ||
          (req.headers["x-client-scope"] as string | undefined)) ??
          undefined,
        forceLogin,
        loginDto.domain,
      );
      this.logger.log({
        level: "info",
        message: buildLogMessage({
          traceId: this.traceIdService.traceId,
          userId,
          status: "success",
          location: "SimpleAuthController",
          method: "login",
          payload: loginDto,
          messageData: successMessage.userLoggedIn,
        }),
      });
      return res.status(HttpStatus.OK).json({
        statusCode: HttpStatus.OK,
        message: successMessage.userLoggedIn,
        data: user,
      });
    } catch (error) {
      this.logger.error({
        level: "error",
        message: buildLogMessage({
          traceId: this.traceIdService.traceId,
          userId,
          status: "failure",
          location: "SimpleAuthController",
          method: "login",
          messageData: error,
        }),
      });
      if (error instanceof ForbiddenException) {
        return res.status(HttpStatus.FORBIDDEN).json({
          statusCode: HttpStatus.FORBIDDEN,
          message: error.message,
        });
      } else if (error instanceof NotFoundException) {
        return res.status(HttpStatus.NOT_FOUND).json({
          statusCode: HttpStatus.NOT_FOUND,
          message: error.message,
        });
      }
      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
        statusCode: HttpStatus.INTERNAL_SERVER_ERROR,
        message:
          error instanceof Error
            ? error.message
            : errorMessages.internalServerError,
      });
      // Handle the error appropriately, e.g., throw a specific exception
    }
  }

  // User details endpoint
  @Get("user-details")
  @getUserDetailsSwaggerMetadata()
  async getUserDetails(
    @Req() req: Request,
    @Res() res: Response
  ): Promise<any> {
    // Fall back to JWT when userid header is missing (backward compatible).
    let userId = parseInt(String(req?.headers?.userid ?? "0"), 10);
    if (!userId || Number.isNaN(userId)) {
      const authHeader = req.headers.authorization;
      if (authHeader) {
        try {
          const token = authHeader.split(" ")[1];
          const decoded = this.jwtService.verify(token, {
            secret: ENV.JWT_SECRET,
          }) as any;
          userId =
            decoded?.userDetails?.userId ?? decoded?.userId ?? decoded?.sub;
        } catch {
          // leave userId as is; handled below
        }
      }
    }
    this.logger.log({
      level: "info",
      message: buildLogMessage({
        traceId: this.traceIdService.traceId,
        userId,
        status: "success",
        location: "SimpleAuthController",
        method: "getUserDetails",
        payload: { userId },
        messageData: "method invoked",
      }),
    });
    try {
      const userDetails = await this.simpleAuthService.getUserDetails(userId);
      this.logger.log({
        level: "info",
        message: buildLogMessage({
          traceId: this.traceIdService.traceId,
          userId,
          status: "success",
          location: "SimpleAuthController",
          method: "getUserDetails",
          payload: { userId },
          messageData: successMessage.userDetailsRetrieved,
        }),
      });
      return res.status(HttpStatus.OK).json({
        statusCode: HttpStatus.OK,
        message: successMessage.userDetailsRetrieved,
        data: userDetails,
      });
    } catch (error) {
      this.logger.error({
        level: "error",
        message: buildLogMessage({
          traceId: this.traceIdService.traceId,
          userId,
          status: "failure",
          location: "SimpleAuthController",
          method: "getUserDetails",
          payload: { userId },
          messageData: error,
        }),
      });
      return handleErrorResponse(
        error as Error,
        res,
        errorMessages.userNotFound,
        error?.message,
        errorMessages.failedToFindUser
      );
    }
  }

  @Post("refresh-token")
  @refreshTokenSwaggerMetadata()
  async refreshToken(
    @Body() refreshTokenDto: RefreshTokenDto,
    @Res() res: Response
  ): Promise<any> {
    const userId = 1;
    this.logger.log({
      level: "info",
      message: buildLogMessage({
        traceId: this.traceIdService.traceId,
        userId,
        status: "success",
        location: "SimpleAuthController",
        method: "refreshToken",
        payload: refreshTokenDto,
        messageData: "method invoked",
      }),
    });
    try {
      const { accessToken } =
        await this.simpleAuthService.validateRefreshTokenAndGenerateAccessToken(
          refreshTokenDto.refreshToken
        );
      this.logger.log({
        level: "info",
        message: buildLogMessage({
          traceId: this.traceIdService.traceId,
          userId,
          status: "success",
          location: "SimpleAuthController",
          method: "refreshToken",
          payload: refreshTokenDto,
          messageData: successMessage.tokenRefreshed,
        }),
      });
      return res.status(HttpStatus.OK).json({
        statusCode: HttpStatus.OK,
        message: successMessage.tokenRefreshed,
        data: { accessToken },
      });
    } catch (error) {
      this.logger.error({
        level: "error",
        message: buildLogMessage({
          traceId: this.traceIdService.traceId,
          userId,
          status: "failure",
          location: "SimpleAuthController",
          method: "refreshToken",
          payload: refreshTokenDto,
          messageData: error,
        }),
      });
      if (error instanceof ForbiddenException) {
        return res.status(HttpStatus.FORBIDDEN).json({
          statusCode: HttpStatus.FORBIDDEN,
          message: error.message,
        });
      }
      if (error instanceof NotFoundException) {
        return res.status(HttpStatus.NOT_FOUND).json({
          statusCode: HttpStatus.NOT_FOUND,
          message: error.message,
        });
      }
      if (error instanceof UnauthorizedException) {
        const response = error.getResponse();
        if (typeof response === "object" && response !== null) {
          return res.status(HttpStatus.UNAUTHORIZED).json(response);
        }
        return res.status(HttpStatus.UNAUTHORIZED).json({
          statusCode: HttpStatus.UNAUTHORIZED,
          message: error.message,
        });
      }
      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
        statusCode: HttpStatus.INTERNAL_SERVER_ERROR,
        message:
          error instanceof Error
            ? error.message
            : errorMessages.internalServerError,
      });
    }
  }

  @Post("logout")
  @UserTrace("LOGOUT")
  async logout(@Req() req: Request, @Res() res: Response): Promise<any> {
    try {
      const authHeader = req.headers.authorization;
      // Decode token if present to revoke the correct session id.
      let sessionId: string | undefined;
      let userId = parseInt(String(req?.headers?.userid ?? "0"), 10);
      if (authHeader) {
        try {
          const token = authHeader.split(" ")[1];
          const decoded = this.jwtService.verify(token, {
            secret: ENV.JWT_SECRET,
          }) as any;
          userId = decoded?.userDetails?.userId ?? decoded?.userId ?? userId;
          sessionId = decoded?.sid;
        } catch {
          // Ignore token decode errors for logout to remain idempotent
        }
      }
      await this.simpleAuthService.logoutSession(userId, sessionId);
      return res.status(HttpStatus.OK).json({
        statusCode: HttpStatus.OK,
        message: successMessage.userLoggedOut,
      });
    } catch (error) {
      return handleErrorResponse(
        error as Error,
        res,
        errorMessages.userNotFound,
        error?.message,
        errorMessages.failedToFindUser
      );
    }
  }

  @Post("crm-redirect-token")
  @crmRedirectTokenSwaggerMetadata()
  async crmRedirectToken(
    @Body() body: { userId: number; companyId: number },
    @Res() res: Response
  ): Promise<any> {
    try {
      const data = await this.simpleAuthService.generateCrmRedirectToken(
        body.userId,
        body.companyId,
      );
      return res.status(HttpStatus.OK).json({ statusCode: HttpStatus.OK, data });
    } catch (error) {
      return handleErrorResponse(
        error as Error,
        res,
        errorMessages.internalServerError,
        error?.message,
        "Failed to generate CRM redirect token"
      );
    }
  }

  @Post("dev/force-logout")
  async forceLogout(@Body("loginName") loginName: string, @Res() res: Response) {
    if (ENV.NODE_ENV !== "dev") {
      return res.status(HttpStatus.NOT_FOUND).json({
        statusCode: HttpStatus.NOT_FOUND,
        message: "Not found",
      });
    }
    if (!loginName) {
      return res.status(HttpStatus.BAD_REQUEST).json({
        statusCode: HttpStatus.BAD_REQUEST,
        message: "loginName is required",
      });
    }
    try {
      await this.simpleAuthService.forceLogoutByLoginName(loginName);
      return res.status(HttpStatus.OK).json({
        statusCode: HttpStatus.OK,
        message: "Session cleared",
      });
    } catch (error) {
      return handleErrorResponse(
        error as Error,
        res,
        errorMessages.userNotFound,
        error?.message,
        errorMessages.failedToFindUser
      );
    }
  }
}
