// Generated by Copilot
import { ElementType } from "react";
import { Box } from "@mui/material";
import { TrendingUp, TrendingDown } from "lucide-react";
import { Line, LineChart, ResponsiveContainer } from "recharts";
import {
  CDKpiCardRoot,
  CDKpiIconWrap,
  CDKpiValue,
  CDKpiSparkRow,
  CDKpiSparkWrap,
  CDKpiDivider,
  CDKpiTrendWrap,
  CDKpiTrendText,
  CDKpiSubText,
  CDKpiLabel,
} from "./styles";

export interface CDKpiCardProps {
  icon: ElementType;
  iconColor: string;
  iconBg: string;
  label: string;
  value: string;
  sub?: string;
  trend?: string;
  trendSub?: string;
  trendUp?: boolean;
  sparkData?: number[];
  sparkColor?: string;
}

export function CDKpiCard({
  icon: Icon,
  iconColor,
  iconBg,
  label,
  value,
  sub,
  trend,
  trendSub,
  trendUp,
  sparkData,
  sparkColor = "#3b82f6",
}: CDKpiCardProps) {
  const chartData = sparkData?.map((v, i) => ({ i, v })) ?? [];
  const trendDir =
    trendUp === true ? "up" : trendUp === false ? "down" : "neutral";

  return (
    <CDKpiCardRoot>
      {/* Row 1: icon + value */}
      <Box sx={{ display: "flex", alignItems: "center", gap: 1.25 }}>
        <CDKpiIconWrap bgColor={iconBg}>
          <Icon size={17} color={iconColor} />
        </CDKpiIconWrap>
        <CDKpiValue>{value}</CDKpiValue>
      </Box>

      {/* Row 2: sparkline + divider + trend */}
      {sparkData && sparkData.length > 0 && (
        <CDKpiSparkRow>
          <CDKpiSparkWrap>
            <ResponsiveContainer width="100%" height={36}>
              <LineChart data={chartData}>
                <Line
                  type="monotone"
                  dataKey="v"
                  stroke={sparkColor}
                  strokeWidth={1.8}
                  dot={false}
                />
              </LineChart>
            </ResponsiveContainer>
          </CDKpiSparkWrap>

          <CDKpiDivider />

          <CDKpiTrendWrap>
            {trend && (
              <CDKpiTrendText trendDir={trendDir}>
                {trendUp === true && <TrendingUp size={12} />}
                {trendUp === false && <TrendingDown size={12} />}
                {trend}
              </CDKpiTrendText>
            )}
            {trendSub && <CDKpiSubText>{trendSub}</CDKpiSubText>}
          </CDKpiTrendWrap>
        </CDKpiSparkRow>
      )}

      {/* Row 3: label + sub */}
      <Box sx={{ display: "flex", flexDirection: "column", gap: 0.25 }}>
        <CDKpiLabel>{label}</CDKpiLabel>
        {sub && <CDKpiSubText>{sub}</CDKpiSubText>}
      </Box>
    </CDKpiCardRoot>
  );
}
