import { Module } from "@nestjs/common";
import { CompanyEmployeeService } from "./company-employee.service";
import { CompanyEmployeeController } from "./company-employee.controller";
import { CompanyEmployeeRepository } from "./company-employee.repository";
import { TpaSsoExecutorService } from "./tpa-sso-executor.service";
import { PolicyConfiguration } from ".././../../../service-lib/src/lib/entities/policy-configuration.entity";
import { TypeOrmModule } from "@nestjs/typeorm";
import { typeOrmConfig } from ".././../../../service-lib/src/lib/database/typeorm.config";
import {
  Policy,
  Company,
  OpportunityActivityMap,
  Tpa,
  Insurer,
  LookUp,
  OpportunityPlacementSlipGeneration,
  DocumentProcessingFile,
  PolicyEnrollmentEmployee,
  PolicyEnrollmentDependent,
  PolicyEnrollmentEmployeePolicyMap,
  PolicyEmployeeEnrollmentChoice,
  PolicyEmployeeEnrollmentChoiceDependent,
  PolicyEmployeeEnrollment,
  PolicyEmployeeEndorsement,
  PolicyDependentEndorsement,
  User,
  UserRole,
  Role,
  PolicyEndorsementTemplateDocMap,
  Endorsement,
  EndorsementFieldMapping,
  FileUpload,
  MstrHospital,
  MstrHospitalAddress,
  MstrPolicyHospitalMap,
  PolicyFeatureDocument,
  PolicyEnrollmentUploadSummary,
  PolicyClaim,
  PolicyClaimStatus,
  PolicyClaimAudit,
  ClaimTpaSubmissionJob,
  PolicyClaimSettlement,
  PolicyContactMetric,
  PolicyTpaMap,
  PolicyInsurerMap,
  TpaExternalFeatureConfig,
  MstrTpaFeatureType,
  CompanyPortalConfigurationDetail,
  ConfigCompany,
  CompanyAuthenticationMapping,
  CompanyAuthenticationConfig,
  AuthenticationMethod,
  EmployeeEnrollmentSubmission,
  NotificationInfo,
  UserActivityLog,
  RaiseTicket,
  GroupCompanyMap,
  Opportunity,
  Country,
  State,
  City,
  TpaSsoConfig,
  TpaSsoFieldMapping,
  ClaimFormExtraction,
  LocalizationRegulatoryFieldsCountryMap,
  CompanyPolicyConfigurationLocation,
} from "../../../../service-lib/src/lib/entities";
import { CompanyPortalConfigScope } from "../../../../service-lib/src/lib/entities/company-portal-config-scope.entity";
import { HrUserManagement } from "../../../../service-lib/src/lib/entities/hr-user-management.entity";
import { TraceIdService } from "../../../../service-lib/src/lib/trace-id.service";
import { UserActivityLogService } from "../../../../service-lib/src/lib/company-employee-activity-log.service";
import { JwtModule } from "@nestjs/jwt";
import { OnboardingModule } from "../onboarding/onboarding.module";
import { HrModule } from "../hr-module/hr.module";

@Module({
  imports: [
    TypeOrmModule.forRoot(typeOrmConfig),
    TypeOrmModule.forFeature([
      Policy,
      Company,
      PolicyConfiguration,
      LookUp,
      OpportunityActivityMap,
      OpportunityPlacementSlipGeneration,
      Tpa,
      Insurer,
      PolicyEnrollmentEmployee,
      PolicyEnrollmentDependent,
      PolicyEnrollmentEmployeePolicyMap,
      PolicyEmployeeEnrollmentChoice,
      PolicyEmployeeEnrollmentChoiceDependent,
      PolicyEmployeeEnrollment,
      EmployeeEnrollmentSubmission,
      PolicyEmployeeEndorsement,
      PolicyDependentEndorsement,
      PolicyEndorsementTemplateDocMap,
      Endorsement,
      EndorsementFieldMapping,
      FileUpload,
      DocumentProcessingFile,
      PolicyEnrollmentUploadSummary,
      PolicyContactMetric,
      PolicyClaim,
      PolicyClaimStatus,
      PolicyClaimAudit,
      ClaimTpaSubmissionJob,
      PolicyClaimSettlement,
      PolicyTpaMap,
      PolicyInsurerMap,
      TpaExternalFeatureConfig,
      MstrTpaFeatureType,
      CompanyPortalConfigurationDetail,
      MstrHospital,
      MstrHospitalAddress,
      MstrPolicyHospitalMap,
      PolicyFeatureDocument,
      ConfigCompany,
      CompanyAuthenticationMapping,
      CompanyAuthenticationConfig,
      AuthenticationMethod,
      NotificationInfo,
      User,
      UserRole,
      Role,
      UserActivityLog,
      RaiseTicket,
      HrUserManagement,
      GroupCompanyMap,
      Opportunity,
      Country,
      State,
      City,
      ClaimFormExtraction,
      CompanyPortalConfigScope,
      TpaSsoConfig,
      TpaSsoFieldMapping,
      LocalizationRegulatoryFieldsCountryMap,
      CompanyPolicyConfigurationLocation,
    ]),
    JwtModule.register({
      secret: process.env.JWT_SECRET || "default_jwt_secret",
      signOptions: { expiresIn: "1d" },
    }),
    OnboardingModule,
    HrModule,
  ],
  providers: [
    CompanyEmployeeService,
    CompanyEmployeeRepository,
    TpaSsoExecutorService,
    TraceIdService,
    UserActivityLogService
  ],
  exports: [CompanyEmployeeService, CompanyEmployeeRepository],
  controllers: [CompanyEmployeeController],
})
export class CompanyEmployeeModule {}
