// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const KpiStrip = styled(Box)({
  display: "grid",
  gridTemplateColumns: "repeat(5, 1fr)",
  gap: 12,
  marginBottom: 20,
});

export const KpiTile = styled(Box, {
  shouldForwardProp: (p) => p !== "tileBg" && p !== "tileBorder",
})<{ tileBg: string; tileBorder: string }>(({ tileBg, tileBorder }) => ({
  background: tileBg,
  border: `1px solid ${tileBorder}`,
  borderRadius: 10,
  padding: "12px 16px",
}));

export const MiniStepBar = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 2,
  marginTop: 6,
});

export const StepSegment = styled(Box, {
  shouldForwardProp: (p) => p !== "state",
})<{ state: "past" | "current" | "future" }>(({ state }) => ({
  flex: 1,
  height: 5,
  borderRadius: 3,
  backgroundColor:
    state === "past" ? "#3b82f6" : state === "current" ? "#93c5fd" : "#e5e7eb",
  transition: "background 0.2s",
}));

export const ActionMenuWrap = styled(Box)({
  position: "absolute",
  right: 0,
  top: "calc(100% + 4px)",
  width: 168,
  background: "#fff",
  border: "1px solid #e5e7eb",
  borderRadius: 10,
  boxShadow: "0 8px 24px rgba(0,0,0,0.10)",
  zIndex: 50,
  overflow: "hidden",
  padding: "3px 0",
});

export const ActionMenuItem = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "8px 12px",
  fontSize: 12,
  fontWeight: 500,
  cursor: "pointer",
  transition: "background 0.1s",
  "&:hover": { background: "#f9fafb" },
});

export const SortBtn = styled(Box)({
  display: "inline-flex",
  alignItems: "center",
  gap: 3,
  cursor: "pointer",
  userSelect: "none",
  "&:hover .label": { color: "#111827" },
});
