// Generated by Copilot
import { ElementType } from "react";
import { Box, Typography } from "@mui/material";

interface HospitalKpiCardProps {
  icon: ElementType;
  iconColor: string;
  iconBg: string;
  accentColor: string;
  label: string;
  value: string;
  sub: string;
}

export function HospitalKpiCard({
  icon: Icon,
  iconColor,
  iconBg,
  accentColor,
  label,
  value,
  sub,
}: HospitalKpiCardProps) {
  return (
    <Box
      sx={{
        backgroundColor: "#fff",
        borderRadius: "14px",
        border: "1px solid #e5e7eb",
        overflow: "hidden",
        boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
        transition: "box-shadow 0.2s",
        "&:hover": { boxShadow: "0 4px 12px rgba(0,0,0,0.10)" },
      }}
    >
      <Box sx={{ height: 4, backgroundColor: accentColor }} />
      <Box sx={{ p: 2.5, display: "flex", alignItems: "flex-start", gap: 2 }}>
        <Box
          sx={{
            width: 44,
            height: 44,
            borderRadius: "12px",
            backgroundColor: iconBg,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexShrink: 0,
            mt: 0.25,
          }}
        >
          <Icon size={20} color={iconColor} />
        </Box>
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Typography sx={{ fontSize: 11, color: "#9ca3af", lineHeight: 1.3 }}>
            {label}
          </Typography>
          <Typography
            sx={{
              fontSize: 24,
              fontWeight: 700,
              color: "#111827",
              lineHeight: 1.2,
              mt: 0.5,
            }}
          >
            {value}
          </Typography>
          <Box sx={{ height: "1px", backgroundColor: "#f3f4f6", my: 1 }} />
          <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>{sub}</Typography>
        </Box>
      </Box>
    </Box>
  );
}

export default HospitalKpiCard;
