// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const SpecTag = styled(Box, {
  shouldForwardProp: (p) => p !== "bg" && p !== "textColor",
})<{ bg?: string; textColor?: string }>(
  ({ bg = "#f3f4f6", textColor = "#6b7280" }) => ({
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 8px",
    borderRadius: 12,
    fontSize: 11,
    fontWeight: 500,
    backgroundColor: bg,
    color: textColor,
    whiteSpace: "nowrap" as const,
  }),
);

export const CashlessChip = styled(Box, {
  shouldForwardProp: (p) => p !== "active",
})<{ active?: boolean }>(({ active }) => ({
  display: "inline-flex",
  alignItems: "center",
  gap: 4,
  padding: "2px 10px",
  borderRadius: 20,
  fontSize: 11,
  fontWeight: 600,
  backgroundColor: active ? "#ecfdf5" : "#fef2f2",
  color: active ? "#059669" : "#ef4444",
}));

export const HStatusChip = styled(Box, {
  shouldForwardProp: (p) => p !== "status",
})<{ status?: string }>(({ status }) => {
  const map: Record<string, { bg: string; color: string }> = {
    Active: { bg: "#ecfdf5", color: "#059669" },
    Inactive: { bg: "#f3f4f6", color: "#6b7280" },
    "Under Review": { bg: "#fffbeb", color: "#d97706" },
  };
  const s = status
    ? map[status] ?? { bg: "#f3f4f6", color: "#6b7280" }
    : { bg: "#f3f4f6", color: "#6b7280" };
  return {
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 10px",
    borderRadius: 20,
    fontSize: 10,
    fontWeight: 600,
    backgroundColor: s.bg,
    color: s.color,
    border: `1px solid ${s.color}30`,
    whiteSpace: "nowrap" as const,
  };
});

export const ViewBtn = styled(Box)(() => ({
  display: "inline-flex",
  alignItems: "center",
  gap: 4,
  fontSize: 12.5,
  fontWeight: 600,
  color: "#2563eb",
  cursor: "pointer",
  "&:hover": { textDecoration: "underline" },
}));

export const FilterSelect = styled("select")(() => ({
  height: 32,
  fontSize: 12.5,
  color: "#374151",
  border: "1px solid #e5e7eb",
  borderRadius: 8,
  padding: "0 10px",
  backgroundColor: "#fff",
  cursor: "pointer",
  outline: "none",
  "&:hover": { borderColor: "#2563eb" },
  "&:focus": {
    borderColor: "#2563eb",
    boxShadow: "0 0 0 2px rgba(37,99,235,0.15)",
  },
}));

export const PageBtn = styled(Box, {
  shouldForwardProp: (p) => p !== "active" && p !== "disabled",
})<{ active?: boolean; disabled?: boolean }>(({ active, disabled }) => ({
  height: 28,
  minWidth: 28,
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  borderRadius: 8,
  fontSize: 12,
  fontWeight: active ? 700 : 500,
  cursor: disabled ? "default" : "pointer",
  backgroundColor: active ? "#2563eb" : "transparent",
  color: active ? "#fff" : disabled ? "#d1d5db" : "#6b7280",
  border: active ? "none" : "1px solid #e5e7eb",
  padding: "0 8px",
  "&:hover": {
    backgroundColor: active ? "#1d4ed8" : disabled ? "transparent" : "#f9fafb",
  },
  transition: "all 0.15s",
}));
