// Generated by Copilot
import { useState } from "react";
import { Box, LinearProgress, Typography } from "@mui/material";
import { Eye, Download, ChevronDown, Search } from "lucide-react";
import {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
  SearchBox,
  ActionButton,
  CDSectionHeader,
  CDSectionTitle,
  CDPolicyTag,
} from "./styles";
import {
  useLocalization,
  formatAmountWithCurrency,
  getCurrencySymbolPrefix,
  type LocalizationConfig,
} from "@ui/ui-lib";

export interface CDAccount {
  id: string;
  policyName: string;
  policyNumber: string;
  type: string;
  tagColor: string;
  depositBalance: number;
  pendingClaims: number;
  utilised: number;
  available: number;
  lastUpdated: string;
  status: string;
  utilPct: number;
}

interface CDAccountsTableProps {
  accounts: CDAccount[];
  onViewTransactions: (policyId: string) => void;
}

function fmtL(n: number, localization?: LocalizationConfig) {
  return `${getCurrencySymbolPrefix(localization)}${(n / 100000).toFixed(2)}L`;
}

function fmtINR(n: number, localization?: LocalizationConfig) {
  return `${formatAmountWithCurrency(n, localization)}`;
}

const POLICY_TAG_COLORS: Record<string, string> = {
  GMC: "#2563eb",
  GPA: "#f59e0b",
  GTL: "#10b981",
};

export function CDAccountsTable({
  accounts,
  onViewTransactions,
}: CDAccountsTableProps) {
  const [search, setSearch] = useState("");
  const [exportOpen, setExportOpen] = useState(false);
  const { localizationData } = useLocalization();

  const filtered = accounts.filter(
    (a) =>
      a.policyName.toLowerCase().includes(search.toLowerCase()) ||
      a.policyNumber.toLowerCase().includes(search.toLowerCase()),
  );

  const totalDeposit = accounts.reduce((s, a) => s + a.depositBalance, 0);
  const totalPending = accounts.reduce((s, a) => s + a.pendingClaims, 0);
  const totalUtilised = accounts.reduce((s, a) => s + a.utilised, 0);

  return (
    <SectionCard sx={{ p: 0, overflow: "hidden" }}>
      <CDSectionHeader>
        <CDSectionTitle>Account Details</CDSectionTitle>
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <SearchBox sx={{ minWidth: 220 }}>
            <Search size={13} />
            <input
              placeholder="Search policy, number..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </SearchBox>
          <Box sx={{ position: "relative" }}>
            <ActionButton
              onClick={() => setExportOpen((o) => !o)}
              sx={{ display: "flex", alignItems: "center", gap: 0.75 }}
            >
              <Download size={13} />
              Export
              <ChevronDown
                size={12}
                style={{
                  transform: exportOpen ? "rotate(180deg)" : "none",
                  transition: "transform 0.15s",
                }}
              />
            </ActionButton>
            {exportOpen && (
              <Box
                sx={{
                  position: "absolute",
                  right: 0,
                  top: "calc(100% + 4px)",
                  bgcolor: "background.paper",
                  border: "1px solid",
                  borderColor: "neutral.tableBorder",
                  borderRadius: 1,
                  boxShadow: 3,
                  zIndex: 200,
                  minWidth: 150,
                  py: 0.5,
                }}
              >
                {["Export as CSV", "Export as Excel", "Export as PDF"].map(
                  (opt) => (
                    <Box
                      key={opt}
                      onClick={() => setExportOpen(false)}
                      sx={{
                        px: 2,
                        py: 0.875,
                        fontSize: "13px",
                        color: "neutral.medium",
                        cursor: "pointer",
                        "&:hover": { bgcolor: "background.tableHeader" },
                      }}
                    >
                      {opt}
                    </Box>
                  ),
                )}
              </Box>
            )}
          </Box>
        </Box>
      </CDSectionHeader>

      <Box sx={{ overflowX: "auto" }}>
        <StyledTable>
          <thead>
            <tr>
              <StyledTh>Policy Name</StyledTh>
              <StyledTh>Policy Number</StyledTh>
              <StyledTh>Deposit Balance</StyledTh>
              <StyledTh>Pending Claims</StyledTh>
              <StyledTh>Utilised Amount</StyledTh>
              <StyledTh>Utilisation</StyledTh>
              <StyledTh>Last Updated</StyledTh>
              <StyledTh>Status</StyledTh>
              <StyledTh>Action</StyledTh>
            </tr>
          </thead>
          <tbody>
            {filtered.map((acc) => {
              const tagColor = POLICY_TAG_COLORS[acc.type] ?? "#2563eb";
              return (
                <tr key={acc.id}>
                  <StyledTd>
                    <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                      <CDPolicyTag tagColor={tagColor}>{acc.type}</CDPolicyTag>
                      <Typography
                        sx={{
                          fontSize: "13px",
                          fontWeight: 600,
                          color: "neutral.mediumDark",
                        }}
                      >
                        {acc.policyName}
                      </Typography>
                    </Box>
                  </StyledTd>
                  <StyledTd sx={{ fontFamily: "monospace", color: "text.grey" }}>
                    {acc.policyNumber}
                  </StyledTd>
                  <StyledTd sx={{ fontWeight: 600 }}>
                    {fmtL(acc.depositBalance, localizationData?.data)}
                  </StyledTd>
                  <StyledTd sx={{ fontWeight: 600, color: "text.error" }}>
                    {fmtINR(acc.pendingClaims, localizationData?.data)}
                  </StyledTd>
                  <StyledTd sx={{ fontWeight: 600, color: "text.error" }}>
                    {fmtL(acc.utilised, localizationData?.data)}
                  </StyledTd>
                  <StyledTd sx={{ minWidth: 140 }}>
                    <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                      <LinearProgress
                        variant="determinate"
                        value={acc.utilPct}
                        sx={{
                          flex: 1,
                          height: 6,
                          borderRadius: 3,
                          backgroundColor: "#f3f4f6",
                          "& .MuiLinearProgress-bar": {
                            backgroundColor:
                              acc.utilPct >= 70 ? "#f59e0b" : "#10b981",
                          },
                        }}
                      />
                      <Typography
                        sx={{
                          fontSize: "12px",
                          fontWeight: 700,
                          minWidth: 32,
                          color: acc.utilPct >= 70 ? "#f59e0b" : "#10b981",
                        }}
                      >
                        {acc.utilPct}%
                      </Typography>
                    </Box>
                  </StyledTd>
                  <StyledTd sx={{ color: "text.grey" }}>
                    {acc.lastUpdated}
                  </StyledTd>
                  <StyledTd>
                    <Box
                      sx={{
                        display: "inline-flex",
                        alignItems: "center",
                        padding: "2px 10px",
                        borderRadius: 20,
                        fontSize: "12px",
                        fontWeight: 600,
                        backgroundColor:
                          acc.status === "Active" ? "#dcfce7" : "#fee2e2",
                        color: acc.status === "Active" ? "#16a34a" : "#dc2626",
                      }}
                    >
                      {acc.status}
                    </Box>
                  </StyledTd>
                  <StyledTd>
                    <Box
                      onClick={() => onViewTransactions(acc.id)}
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: 0.5,
                        color: "secondary.selected",
                        fontSize: "13px",
                        fontWeight: 600,
                        cursor: "pointer",
                        "&:hover": { textDecoration: "underline" },
                      }}
                    >
                      <Eye size={13} />
                      View Transactions
                    </Box>
                  </StyledTd>
                </tr>
              );
            })}
            {/* Total row */}
            <tr>
              <StyledTd
                colSpan={2}
                sx={{ fontWeight: 700, color: "neutral.mediumDark" }}
              >
                Total
              </StyledTd>
              <StyledTd sx={{ fontWeight: 700, color: "neutral.mediumDark" }}>
                {fmtL(totalDeposit, localizationData?.data)}
              </StyledTd>
              <StyledTd sx={{ fontWeight: 700, color: "text.error" }}>
                {fmtINR(totalPending, localizationData?.data)}
              </StyledTd>
              <StyledTd sx={{ fontWeight: 700, color: "text.error" }}>
                {fmtL(totalUtilised, localizationData?.data)}
              </StyledTd>
              <StyledTd />
              <StyledTd />
              <StyledTd />
              <StyledTd />
            </tr>
          </tbody>
        </StyledTable>
      </Box>
    </SectionCard>
  );
}
