// Generated by Copilot
// Re-exports base shared tokens used by CDAccountsTable.
export {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
  SearchBox,
  ActionButton,
} from "../../pages/HRPortal/styles";

// Re-exports shared section header used across CD sections.
export {
  CDSectionHeader,
  CDSectionTitle,
} from "../../pages/HRPortalFinance/styles";

import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

// ─── Policy type tag ───────────────────────────────────────────────────────────
export const CDPolicyTag = styled(Box)<{ tagColor?: string }>(
  ({ tagColor }) => ({
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 700,
    backgroundColor: tagColor ? `${tagColor}1A` : "#dbeafe",
    color: tagColor ?? "#2563eb",
    flexShrink: 0,
    lineHeight: 1.6,
  }),
);
