// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export {
  KPIGrid,
  KPICard,
  KPILabel,
  KPIValue,
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  StatusBadge,
  SearchBox,
  ActionButton,
  PrimaryButton,
  TabBar,
  TabItem,
  TwoColGrid,
} from "../HRPortal/styles";

type ClaimStatusType =
  | "Paid"
  | "Outstanding"
  | "Rejected"
  | "Closed"
  | "Denied"
  | "Processing";

export const ClaimStatusBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "status",
})<{ status: ClaimStatusType }>(({ theme, status }) => {
  const map: Record<
    ClaimStatusType,
    { bg: string; color: string; border: string }
  > = {
    Paid: {
      bg: theme.palette.background.tabsSelected,
      color: theme.palette.neutral.green,
      border: theme.palette.neutral.tableBorder,
    },
    Outstanding: {
      bg: theme.palette.background.tableHeader,
      color: theme.palette.text.yellow,
      border: theme.palette.neutral.tableBorder,
    },
    Rejected: {
      bg: theme.palette.background.tableHeader,
      color: theme.palette.text.error,
      border: theme.palette.neutral.tableBorder,
    },
    Closed: {
      bg: theme.palette.background.tableHeader,
      color: theme.palette.text.grey,
      border: theme.palette.neutral.tableBorder,
    },
    Denied: {
      bg: theme.palette.background.tableHeader,
      color: theme.palette.text.error,
      border: theme.palette.neutral.tableBorder,
    },
    Processing: {
      bg: theme.palette.background.tabsSelected,
      color: theme.palette.secondary.selected,
      border: theme.palette.neutral.tableBorder,
    },
  };
  const c = map[status] ?? {
    bg: theme.palette.background.tableHeader,
    color: theme.palette.text.grey,
    border: theme.palette.neutral.tableBorder,
  };
  return {
    display: "inline-flex",
    alignItems: "center",
    padding: `${theme.spacing(0.375)} ${theme.spacing(1.5)}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    backgroundColor: c.bg,
    color: c.color,
    border: `1px solid ${c.border}`,
    whiteSpace: "nowrap",
  };
});

export const ClaimTypeBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "claimType",
})<{ claimType: "Cashless" | "Reimbursement" }>(({ theme, claimType }) => ({
  display: "inline-flex",
  alignItems: "center",
  padding: `${theme.spacing(0.375)} ${theme.spacing(1.5)}`,
  borderRadius: theme.shape.borderRadii.medium,
  fontSize: theme.typography.fontSizes.xs,
  fontWeight: theme.typography.fontWeights.semiBold,
  backgroundColor:
    claimType === "Cashless"
      ? theme.palette.background.tabsSelected
      : theme.palette.background.tableHeader,
  color:
    claimType === "Cashless"
      ? theme.palette.secondary.selected
      : theme.palette.text.grey,
  border: `1px solid ${theme.palette.neutral.tableBorder}`,
  whiteSpace: "nowrap",
}));

export const TATBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "tat",
})<{ tat: number }>(({ theme, tat }) => ({
  display: "inline-flex",
  alignItems: "center",
  padding: `${theme.spacing(0.375)} ${theme.spacing(1.5)}`,
  borderRadius: theme.shape.borderRadii.medium,
  fontSize: theme.typography.fontSizes.xs,
  fontWeight: theme.typography.fontWeights.semiBold,
  backgroundColor:
    tat <= 14
      ? theme.palette.background.tabsSelected
      : theme.palette.background.tableHeader,
  color:
    tat <= 14
      ? theme.palette.neutral.green
      : tat <= 30
      ? theme.palette.text.yellow
      : theme.palette.text.error,
  whiteSpace: "nowrap",
}));

export const ProcedureTimeBadge = styled(Box)(({ theme }) => ({
  padding: `${theme.spacing(0.375)} ${theme.spacing(1.25)}`,
  borderRadius: theme.shape.borderRadii.medium,
  backgroundColor: theme.palette.background.tabsSelected,
  fontSize: theme.typography.fontSizes.xs,
  fontWeight: theme.typography.fontWeights.semiBold,
  color: theme.palette.secondary.selected,
  whiteSpace: "nowrap",
  marginLeft: theme.spacing(2),
}));

export const PolicyTypeChip = styled(Box, {
  shouldForwardProp: (p) => p !== "chipColor",
})<{ chipColor: string }>(({ chipColor }) => ({
  display: "inline-flex",
  alignItems: "center",
  gap: 4,
  padding: "7px 16px",
  backgroundColor: chipColor,
  color: "#FFFFFF",
  borderRadius: "8px",
  cursor: "pointer",
  fontSize: 13,
  fontWeight: 600,
  userSelect: "none",
  "&:hover": { opacity: 0.9 },
}));
