// Generated by Copilot
import { useState, useMemo } from "react";
import { Box, Typography } from "@mui/material";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Cell,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
} from "recharts";
import { SectionCard, SectionTitle } from "../../pages/HRPortal/styles";
import { ToggleChip } from "./styles";
import { TOP10_SNAPSHOT, formatDiseaseAmt, type SnapshotRow } from "./data";
import { useLocalization } from "@ui/ui-lib";

type SnapshotFilter = "all" | "Employee" | "Hospital";

const FILTER_TABS: { label: string; value: SnapshotFilter }[] = [
  { label: "All", value: "all" },
  { label: "Employees", value: "Employee" },
  { label: "Hospitals", value: "Hospital" },
];

export function ClaimSnapshot() {
  const { localizationData } = useLocalization();
  const [filter, setFilter] = useState<SnapshotFilter>("all");

  const _filteredData = useMemo<SnapshotRow[]>(() => {
    if (filter === "all") return TOP10_SNAPSHOT;
    return TOP10_SNAPSHOT.filter((r) => r.type === filter);
  }, [filter]);

  const _barColor = (type: "Employee" | "Hospital") =>
    type === "Employee" ? "#3B82F6" : "#8B5CF6";

  return (
    <SectionCard>
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: 2,
        }}
      >
        <SectionTitle sx={{ mb: 0 }}>Claim Snapshot – Top 10</SectionTitle>
        <Box sx={{ display: "flex", gap: 0.75 }}>
          {FILTER_TABS.map((tab) => (
            <ToggleChip
              key={tab.value}
              active={filter === tab.value}
              activeBg={"#3B82F6"}
              onClick={() => setFilter(tab.value)}
            >
              {tab.label}
            </ToggleChip>
          ))}
        </Box>
      </Box>

      <ResponsiveContainer width="100%" height={220}>
        <BarChart
          data={_filteredData}
          layout="vertical"
          margin={{ left: 8, right: 24 }}
        >
          <XAxis
            type="number"
            tickFormatter={(v: unknown) => formatDiseaseAmt(Number(v), localizationData?.data)}
            tick={{ fontSize: 11, fill: "#9ca3af" }}
            axisLine={false}
            tickLine={false}
          />
          <YAxis
            type="category"
            dataKey="name"
            tick={{ fontSize: 11, fill: "#374151" }}
            axisLine={false}
            tickLine={false}
            width={110}
          />
          <RechartTooltip
            contentStyle={{
              borderRadius: 8,
              border: "1px solid #e5e7eb",
              fontSize: 12,
            }}
            formatter={(
              v: unknown,
              _name: unknown,
              props: { payload?: SnapshotRow },
            ) => [formatDiseaseAmt(Number(v), localizationData?.data), props.payload?.type ?? "Amount"]}
          />
          <Bar dataKey="amount" radius={[0, 4, 4, 0]}>
            {_filteredData.map((row, i) => (
              <Cell key={i} fill={_barColor(row.type)} />
            ))}
          </Bar>
        </BarChart>
      </ResponsiveContainer>

      {/* Legend */}
      <Box sx={{ display: "flex", gap: 3, mt: 1.5 }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
          <Box
            sx={{
              width: 10,
              height: 10,
              borderRadius: "50%",
              backgroundColor: "#3B82F6",
            }}
          />
          <Typography sx={{ fontSize: 11, color: "#6b7280" }}>
            Employee
          </Typography>
        </Box>
        <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
          <Box
            sx={{
              width: 10,
              height: 10,
              borderRadius: "50%",
              backgroundColor: "#8B5CF6",
            }}
          />
          <Typography sx={{ fontSize: 11, color: "#6b7280" }}>
            Hospital
          </Typography>
        </Box>
      </Box>
    </SectionCard>
  );
}

export default ClaimSnapshot;
