// Generated by Copilot
import { getCurrencySymbolPrefix, type LocalizationConfig } from "@ui/ui-lib";

export type DiseaseOption =
  | "All Diseases"
  | "Orthopedic"
  | "Cardiology"
  | "General"
  | "Dental"
  | "Others";

export interface DiseaseEntry {
  name: string;
  amount: number;
  color: string;
}

export interface SnapshotRow {
  name: string;
  type: "Employee" | "Hospital";
  amount: number;
  hospital: string;
}

export const ALL_DISEASES_BY_PERIOD: Record<
  string,
  Record<string, DiseaseEntry[]>
> = {
  month: {
    "Feb 2026": [
      { name: "Orthopedic", amount: 180000, color: "#3B82F6" },
      { name: "Cardiology", amount: 140000, color: "#8B5CF6" },
      { name: "General", amount: 98000, color: "#10B981" },
      { name: "Dental", amount: 65000, color: "#F59E0B" },
      { name: "Others", amount: 117000, color: "#6B7280" },
    ],
    "Jan 2026": [
      { name: "Orthopedic", amount: 165000, color: "#3B82F6" },
      { name: "Cardiology", amount: 120000, color: "#8B5CF6" },
      { name: "General", amount: 87000, color: "#10B981" },
      { name: "Dental", amount: 52000, color: "#F59E0B" },
      { name: "Others", amount: 96000, color: "#6B7280" },
    ],
    "Dec 2025": [
      { name: "Orthopedic", amount: 195000, color: "#3B82F6" },
      { name: "Cardiology", amount: 158000, color: "#8B5CF6" },
      { name: "General", amount: 108000, color: "#10B981" },
      { name: "Dental", amount: 72000, color: "#F59E0B" },
      { name: "Others", amount: 132000, color: "#6B7280" },
    ],
  },
  year: {
    "2025": [
      { name: "Orthopedic", amount: 2100000, color: "#3B82F6" },
      { name: "Cardiology", amount: 1650000, color: "#8B5CF6" },
      { name: "General", amount: 1180000, color: "#10B981" },
      { name: "Dental", amount: 720000, color: "#F59E0B" },
      { name: "Others", amount: 1320000, color: "#6B7280" },
    ],
    "2024": [
      { name: "Orthopedic", amount: 1900000, color: "#3B82F6" },
      { name: "Cardiology", amount: 1480000, color: "#8B5CF6" },
      { name: "General", amount: 1050000, color: "#10B981" },
      { name: "Dental", amount: 640000, color: "#F59E0B" },
      { name: "Others", amount: 1180000, color: "#6B7280" },
    ],
  },
};

export const PERIOD_OPTIONS: Record<string, string[]> = {
  month: ["Feb 2026", "Jan 2026", "Dec 2025"],
  year: ["2025", "2024"],
};

export const TOP10_SNAPSHOT: SnapshotRow[] = [
  {
    name: "Rajesh Kumar",
    type: "Employee",
    amount: 485000,
    hospital: "Apollo Hospital",
  },
  {
    name: "Apollo Hospital",
    type: "Hospital",
    amount: 420000,
    hospital: "Apollo Hospital",
  },
  {
    name: "Priya Sharma",
    type: "Employee",
    amount: 390000,
    hospital: "Fortis Healthcare",
  },
  {
    name: "Fortis Healthcare",
    type: "Hospital",
    amount: 350000,
    hospital: "Fortis Healthcare",
  },
  {
    name: "Amit Patel",
    type: "Employee",
    amount: 315000,
    hospital: "Max Hospital",
  },
  {
    name: "Max Hospital",
    type: "Hospital",
    amount: 290000,
    hospital: "Max Hospital",
  },
  {
    name: "Sunita Rao",
    type: "Employee",
    amount: 270000,
    hospital: "Manipal Hospital",
  },
  {
    name: "Manipal Hospital",
    type: "Hospital",
    amount: 245000,
    hospital: "Manipal Hospital",
  },
  {
    name: "Vikram Singh",
    type: "Employee",
    amount: 220000,
    hospital: "Narayana Health",
  },
  {
    name: "Narayana Health",
    type: "Hospital",
    amount: 198000,
    hospital: "Narayana Health",
  },
];

export function formatDiseaseAmt(v: number, localization?: LocalizationConfig): string {
  const sym = getCurrencySymbolPrefix(localization);
  if (v >= 1_000_000) return `${sym}${(v / 1_000_000).toFixed(1)}M`;
  if (v >= 100_000) return `${sym}${(v / 100_000).toFixed(1)}L`;
  if (v >= 1_000) return `${sym}${(v / 1_000).toFixed(0)}k`;
  return `${sym}${v}`;
}
