// Generated by Copilot
import { Box } from "@mui/material";
import { DiseaseCategory } from "./DiseaseCategory";
import { ClaimSnapshot } from "./ClaimSnapshot";

export function DiseaseAndSnapshot() {
  return (
    <Box
      sx={{
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 3,
        mt: 2.5,
        mb: 2.5,
      }}
    >
      <DiseaseCategory />
      <ClaimSnapshot />
    </Box>
  );
}

export default DiseaseAndSnapshot;
