// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const FilterSelectWrapper = styled(Box)({
  border: "1px solid #E5E7EB",
  borderRadius: 6,
  padding: "4px 12px",
});

export const ToggleChip = styled(Box, {
  shouldForwardProp: (prop) => prop !== "active" && prop !== "activeBg",
})<{ active: boolean; activeBg: string }>(({ active, activeBg }) => ({
  padding: "6px 12px",
  borderRadius: 20,
  fontSize: 12,
  fontWeight: 500,
  cursor: "pointer",
  border: `1px solid ${active ? activeBg : "#E5E7EB"}`,
  background: active ? activeBg : "transparent",
  color: active ? "#fff" : "#6B7280",
  transition: "all 0.15s",
}));
