// Generated by Copilot

export type TabId = "overview" | "claims" | "members" | "financial";
export type ChartType = "stacked" | "table";
export type ViewBy = "amount" | "count" | "avg";
export type GroupBy = "month" | "city" | "hospital" | "department";

// ─── Insight point used for ClaimsAnalytics stacked chart ────────────────────

export interface InsightPoint {
  name: string;
  amount: number;
  count: number;
  avg: number;
  paid: number;
  outstanding: number;
  rejected: number;
  closed: number;
  denied: number;
}

export const STACKS: {
  key: keyof InsightPoint;
  color: string;
  label: string;
}[] = [
  { key: "paid", color: "#10B981", label: "Paid" },
  { key: "outstanding", color: "#F59E0B", label: "Outstanding" },
  { key: "rejected", color: "#EF4444", label: "Rejected" },
  { key: "closed", color: "#3B82F6", label: "Closed" },
  { key: "denied", color: "#9CA3AF", label: "Denied" },
];

const MONTHLY_INSIGHT: InsightPoint[] = [
  {
    name: "Mar '25",
    amount: 198000,
    count: 28,
    avg: 7071,
    paid: 119000,
    outstanding: 42000,
    rejected: 25000,
    closed: 9000,
    denied: 3000,
  },
  {
    name: "Apr '25",
    amount: 247000,
    count: 34,
    avg: 7265,
    paid: 148000,
    outstanding: 53000,
    rejected: 31000,
    closed: 12000,
    denied: 3000,
  },
  {
    name: "May '25",
    amount: 289000,
    count: 39,
    avg: 7410,
    paid: 174000,
    outstanding: 61000,
    rejected: 37000,
    closed: 14000,
    denied: 3000,
  },
  {
    name: "Jun '25",
    amount: 315000,
    count: 43,
    avg: 7326,
    paid: 189000,
    outstanding: 67000,
    rejected: 39000,
    closed: 16000,
    denied: 4000,
  },
  {
    name: "Jul '25",
    amount: 358000,
    count: 48,
    avg: 7458,
    paid: 215000,
    outstanding: 76000,
    rejected: 44000,
    closed: 18000,
    denied: 5000,
  },
  {
    name: "Aug '25",
    amount: 301000,
    count: 41,
    avg: 7341,
    paid: 181000,
    outstanding: 64000,
    rejected: 37000,
    closed: 15000,
    denied: 4000,
  },
  {
    name: "Sep '25",
    amount: 324000,
    count: 44,
    avg: 7364,
    paid: 195000,
    outstanding: 69000,
    rejected: 40000,
    closed: 16000,
    denied: 4000,
  },
  {
    name: "Oct '25",
    amount: 389000,
    count: 52,
    avg: 7481,
    paid: 233000,
    outstanding: 83000,
    rejected: 48000,
    closed: 20000,
    denied: 5000,
  },
  {
    name: "Nov '25",
    amount: 423000,
    count: 57,
    avg: 7421,
    paid: 254000,
    outstanding: 90000,
    rejected: 52000,
    closed: 21000,
    denied: 6000,
  },
  {
    name: "Dec '25",
    amount: 401000,
    count: 54,
    avg: 7426,
    paid: 241000,
    outstanding: 85000,
    rejected: 49000,
    closed: 20000,
    denied: 6000,
  },
  {
    name: "Jan '26",
    amount: 447000,
    count: 60,
    avg: 7450,
    paid: 268000,
    outstanding: 95000,
    rejected: 55000,
    closed: 23000,
    denied: 6000,
  },
  {
    name: "Feb '26",
    amount: 479000,
    count: 64,
    avg: 7484,
    paid: 288000,
    outstanding: 102000,
    rejected: 59000,
    closed: 24000,
    denied: 6000,
  },
];

const CITY_INSIGHT: InsightPoint[] = [
  {
    name: "Mumbai",
    amount: 1820000,
    count: 245,
    avg: 7429,
    paid: 1092000,
    outstanding: 385000,
    rejected: 228000,
    closed: 91000,
    denied: 24000,
  },
  {
    name: "Delhi",
    amount: 1540000,
    count: 210,
    avg: 7333,
    paid: 924000,
    outstanding: 325000,
    rejected: 192000,
    closed: 77000,
    denied: 22000,
  },
  {
    name: "Bangalore",
    amount: 1240000,
    count: 168,
    avg: 7381,
    paid: 744000,
    outstanding: 262000,
    rejected: 155000,
    closed: 62000,
    denied: 17000,
  },
  {
    name: "Pune",
    amount: 890000,
    count: 121,
    avg: 7355,
    paid: 534000,
    outstanding: 188000,
    rejected: 111000,
    closed: 45000,
    denied: 12000,
  },
  {
    name: "Chennai",
    amount: 760000,
    count: 103,
    avg: 7379,
    paid: 456000,
    outstanding: 161000,
    rejected: 95000,
    closed: 38000,
    denied: 10000,
  },
];

const HOSPITAL_INSIGHT: InsightPoint[] = [
  {
    name: "Apollo",
    amount: 1250000,
    count: 142,
    avg: 8803,
    paid: 750000,
    outstanding: 265000,
    rejected: 156000,
    closed: 63000,
    denied: 16000,
  },
  {
    name: "Fortis",
    amount: 980000,
    count: 115,
    avg: 8522,
    paid: 588000,
    outstanding: 207000,
    rejected: 122000,
    closed: 49000,
    denied: 14000,
  },
  {
    name: "Max",
    amount: 720000,
    count: 87,
    avg: 8276,
    paid: 432000,
    outstanding: 152000,
    rejected: 90000,
    closed: 36000,
    denied: 10000,
  },
  {
    name: "Medanta",
    amount: 650000,
    count: 78,
    avg: 8333,
    paid: 390000,
    outstanding: 137000,
    rejected: 81000,
    closed: 33000,
    denied: 9000,
  },
  {
    name: "AIIMS",
    amount: 540000,
    count: 67,
    avg: 8060,
    paid: 324000,
    outstanding: 114000,
    rejected: 67000,
    closed: 27000,
    denied: 8000,
  },
];

const DEPT_INSIGHT: InsightPoint[] = [
  {
    name: "Engineering",
    amount: 1480000,
    count: 198,
    avg: 7475,
    paid: 888000,
    outstanding: 313000,
    rejected: 185000,
    closed: 74000,
    denied: 20000,
  },
  {
    name: "Sales",
    amount: 1120000,
    count: 152,
    avg: 7368,
    paid: 672000,
    outstanding: 236000,
    rejected: 140000,
    closed: 56000,
    denied: 16000,
  },
  {
    name: "Operations",
    amount: 890000,
    count: 121,
    avg: 7355,
    paid: 534000,
    outstanding: 188000,
    rejected: 111000,
    closed: 45000,
    denied: 12000,
  },
  {
    name: "Finance",
    amount: 680000,
    count: 93,
    avg: 7312,
    paid: 408000,
    outstanding: 143000,
    rejected: 85000,
    closed: 34000,
    denied: 10000,
  },
  {
    name: "HR",
    amount: 540000,
    count: 74,
    avg: 7297,
    paid: 324000,
    outstanding: 114000,
    rejected: 67000,
    closed: 27000,
    denied: 8000,
  },
];

export const DATA_BY_GROUP: Record<GroupBy, InsightPoint[]> = {
  month: MONTHLY_INSIGHT,
  city: CITY_INSIGHT,
  hospital: HOSPITAL_INSIGHT,
  department: DEPT_INSIGHT,
};

// ─── Rich per-policy data ─────────────────────────────────────────────────────

export interface ClaimRow {
  claimNo: string;
  employee: string;
  hospital: string;
  type: string;
  claimAmt: number;
  settledAmt: number;
  status: string;
  tat: number;
}

export interface AgeGroup {
  band: string;
  employees: number;
  dependents: number;
}
export interface GenderEntry {
  name: string;
  value: number;
  color: string;
}
export interface DeptEnroll {
  dept: string;
  enrolled: number;
  total: number;
}
export interface MemberRow {
  empId: string;
  name: string;
  dept: string;
  si: string;
  dependents: number;
  claimsCount: number;
  totalClaim: number;
}
export interface PremiumPoint {
  month: string;
  premium: number;
  claim: number;
}
export interface FinRow {
  label: string;
  value: string;
}

export interface RichEntry {
  employeesCovered: number;
  dependentsCovered: number;
  totalClaimAmt: string;
  avgClaimSize: string;
  trendUp: boolean;
  monthlyTrend: {
    month: string;
    claims: number;
    settled: number;
    amount: number;
  }[];
  topHospitals: { name: string; claims: number; amount: number }[];
  diseaseBreakdown: { name: string; count: number; color: string }[];
  claimsByType: { name: string; value: number; color: string }[];
  claimsTable: ClaimRow[];
  ageGroups: AgeGroup[];
  genderSplit: GenderEntry[];
  deptEnrollment: DeptEnroll[];
  memberTable: MemberRow[];
  premiumVsClaim: PremiumPoint[];
  financialTable: FinRow[];
  lossRatio: number;
  totalPremiumPaid: string;
  totalClaimPaid: string;
  outstandingClaims: string;
  utilizationPct: number;
}

export const RICH: Record<string, RichEntry> = {
  ghi: {
    employeesCovered: 186,
    dependentsCovered: 224,
    totalClaimAmt: "₹38.5 L",
    avgClaimSize: "₹1.6 L",
    trendUp: true,
    monthlyTrend: [
      { month: "Aug", claims: 18, settled: 14, amount: 280000 },
      { month: "Sep", claims: 22, settled: 19, amount: 340000 },
      { month: "Oct", claims: 19, settled: 15, amount: 295000 },
      { month: "Nov", claims: 25, settled: 21, amount: 410000 },
      { month: "Dec", claims: 28, settled: 24, amount: 460000 },
      { month: "Jan", claims: 21, settled: 18, amount: 330000 },
      { month: "Feb", claims: 24, settled: 20, amount: 385000 },
    ],
    topHospitals: [
      { name: "Apollo Hospital", claims: 48, amount: 920000 },
      { name: "Fortis Healthcare", claims: 36, amount: 680000 },
      { name: "Max Hospital", claims: 29, amount: 540000 },
      { name: "Medanta", claims: 22, amount: 410000 },
      { name: "AIIMS", claims: 18, amount: 320000 },
    ],
    diseaseBreakdown: [
      { name: "Orthopedic", count: 42, color: "#3B82F6" },
      { name: "Cardiology", count: 35, color: "#8B5CF6" },
      { name: "General", count: 28, color: "#10B981" },
      { name: "Dental", count: 18, color: "#F59E0B" },
      { name: "Maternity", count: 14, color: "#EC4899" },
      { name: "Others", count: 20, color: "#6B7280" },
    ],
    claimsByType: [
      { name: "Cashless", value: 62, color: "#3B82F6" },
      { name: "Reimbursement", value: 38, color: "#10B981" },
    ],
    claimsTable: [
      {
        claimNo: "CLM-001",
        employee: "Rajesh Kumar",
        hospital: "Apollo Hospital",
        type: "Cashless",
        claimAmt: 485000,
        settledAmt: 472000,
        status: "Settled",
        tat: 3,
      },
      {
        claimNo: "CLM-002",
        employee: "Priya Sharma",
        hospital: "Fortis Healthcare",
        type: "Cashless",
        claimAmt: 390000,
        settledAmt: 380000,
        status: "Settled",
        tat: 4,
      },
      {
        claimNo: "CLM-003",
        employee: "Amit Patel",
        hospital: "Max Hospital",
        type: "Reimbursement",
        claimAmt: 315000,
        settledAmt: 0,
        status: "Pending",
        tat: 8,
      },
      {
        claimNo: "CLM-004",
        employee: "Sunita Verma",
        hospital: "Medanta",
        type: "Cashless",
        claimAmt: 278000,
        settledAmt: 265000,
        status: "Settled",
        tat: 2,
      },
      {
        claimNo: "CLM-005",
        employee: "Vikram Nair",
        hospital: "AIIMS",
        type: "Reimbursement",
        claimAmt: 220000,
        settledAmt: 0,
        status: "Rejected",
        tat: 12,
      },
      {
        claimNo: "CLM-006",
        employee: "Deepa Menon",
        hospital: "Apollo Hospital",
        type: "Reimbursement",
        claimAmt: 192000,
        settledAmt: 0,
        status: "Pending",
        tat: 6,
      },
      {
        claimNo: "CLM-007",
        employee: "Arun Sharma",
        hospital: "Narayana Health",
        type: "Cashless",
        claimAmt: 165000,
        settledAmt: 160000,
        status: "Settled",
        tat: 3,
      },
      {
        claimNo: "CLM-008",
        employee: "Kavita Singh",
        hospital: "Manipal Hospital",
        type: "Cashless",
        claimAmt: 148000,
        settledAmt: 145000,
        status: "Settled",
        tat: 2,
      },
    ],
    ageGroups: [
      { band: "18–25", employees: 28, dependents: 12 },
      { band: "26–35", employees: 64, dependents: 58 },
      { band: "36–45", employees: 52, dependents: 84 },
      { band: "46–55", employees: 30, dependents: 52 },
      { band: "56–65", employees: 10, dependents: 18 },
      { band: "65+", employees: 2, dependents: 0 },
    ],
    genderSplit: [
      { name: "Male", value: 112, color: "#3B82F6" },
      { name: "Female", value: 74, color: "#EC4899" },
    ],
    deptEnrollment: [
      { dept: "Engineering", enrolled: 58, total: 62 },
      { dept: "Sales", enrolled: 44, total: 50 },
      { dept: "HR", enrolled: 22, total: 24 },
      { dept: "Finance", enrolled: 30, total: 34 },
      { dept: "Operations", enrolled: 38, total: 44 },
      { dept: "Marketing", enrolled: 20, total: 22 },
    ],
    memberTable: [
      {
        empId: "EMP-001",
        name: "Rajesh Kumar",
        dept: "Engineering",
        si: "₹5 L",
        dependents: 3,
        claimsCount: 2,
        totalClaim: 485000,
      },
      {
        empId: "EMP-002",
        name: "Priya Sharma",
        dept: "Sales",
        si: "₹5 L",
        dependents: 2,
        claimsCount: 1,
        totalClaim: 390000,
      },
      {
        empId: "EMP-003",
        name: "Amit Patel",
        dept: "Finance",
        si: "₹5 L",
        dependents: 4,
        claimsCount: 1,
        totalClaim: 315000,
      },
      {
        empId: "EMP-004",
        name: "Sunita Verma",
        dept: "HR",
        si: "₹5 L",
        dependents: 2,
        claimsCount: 1,
        totalClaim: 278000,
      },
      {
        empId: "EMP-005",
        name: "Vikram Nair",
        dept: "Operations",
        si: "₹5 L",
        dependents: 3,
        claimsCount: 1,
        totalClaim: 220000,
      },
      {
        empId: "EMP-006",
        name: "Deepa Menon",
        dept: "Marketing",
        si: "₹5 L",
        dependents: 1,
        claimsCount: 1,
        totalClaim: 192000,
      },
    ],
    premiumVsClaim: [
      { month: "Aug", premium: 68333, claim: 280000 },
      { month: "Sep", premium: 68333, claim: 340000 },
      { month: "Oct", premium: 68333, claim: 295000 },
      { month: "Nov", premium: 68333, claim: 410000 },
      { month: "Dec", premium: 68333, claim: 460000 },
      { month: "Jan", premium: 68333, claim: 330000 },
      { month: "Feb", premium: 68333, claim: 385000 },
    ],
    financialTable: [
      { label: "Policy Premium", value: "₹82.0 L" },
      { label: "Claim Paid (YTD)", value: "₹38.5 L" },
      { label: "Outstanding Claims", value: "₹5.07 L" },
      { label: "Loss Ratio %", value: "46.9%" },
      { label: "Admin Charges", value: "₹4.1 L" },
      { label: "Net Liability", value: "₹47.7 L" },
    ],
    lossRatio: 47,
    totalPremiumPaid: "₹82.0 L",
    totalClaimPaid: "₹38.5 L",
    outstandingClaims: "₹5.07 L",
    utilizationPct: 45,
  },
  gpa: {
    employeesCovered: 342,
    dependentsCovered: 38,
    totalClaimAmt: "₹9.0 L",
    avgClaimSize: "₹1.1 L",
    trendUp: false,
    monthlyTrend: [
      { month: "Aug", claims: 3, settled: 3, amount: 120000 },
      { month: "Sep", claims: 4, settled: 3, amount: 180000 },
      { month: "Oct", claims: 2, settled: 2, amount: 80000 },
      { month: "Nov", claims: 5, settled: 4, amount: 220000 },
      { month: "Dec", claims: 4, settled: 3, amount: 160000 },
      { month: "Jan", claims: 3, settled: 3, amount: 120000 },
      { month: "Feb", claims: 5, settled: 4, amount: 200000 },
    ],
    topHospitals: [
      { name: "Apollo Hospital", claims: 8, amount: 280000 },
      { name: "Max Hospital", claims: 6, amount: 210000 },
      { name: "Fortis Healthcare", claims: 5, amount: 175000 },
      { name: "Lilavati Hospital", claims: 4, amount: 140000 },
      { name: "Kokilaben Hospital", claims: 3, amount: 95000 },
    ],
    diseaseBreakdown: [
      { name: "Accidental Injury", count: 18, color: "#F59E0B" },
      { name: "Fracture", count: 12, color: "#EF4444" },
      { name: "Burn Injury", count: 6, color: "#8B5CF6" },
      { name: "Dislocation", count: 4, color: "#3B82F6" },
      { name: "Others", count: 8, color: "#6B7280" },
    ],
    claimsByType: [
      { name: "Cashless", value: 48, color: "#F59E0B" },
      { name: "Reimbursement", value: 52, color: "#10B981" },
    ],
    claimsTable: [
      {
        claimNo: "PA-001",
        employee: "Ravi Menon",
        hospital: "Apollo Hospital",
        type: "Cashless",
        claimAmt: 250000,
        settledAmt: 245000,
        status: "Settled",
        tat: 4,
      },
      {
        claimNo: "PA-002",
        employee: "Sita Devi",
        hospital: "Max Hospital",
        type: "Reimbursement",
        claimAmt: 180000,
        settledAmt: 0,
        status: "Pending",
        tat: 7,
      },
      {
        claimNo: "PA-003",
        employee: "Anand Kumar",
        hospital: "Fortis Healthcare",
        type: "Cashless",
        claimAmt: 140000,
        settledAmt: 136000,
        status: "Settled",
        tat: 3,
      },
      {
        claimNo: "PA-004",
        employee: "Pooja Singh",
        hospital: "Lilavati Hospital",
        type: "Reimbursement",
        claimAmt: 120000,
        settledAmt: 0,
        status: "Rejected",
        tat: 10,
      },
      {
        claimNo: "PA-005",
        employee: "Kiran Patel",
        hospital: "Kokilaben Hosp.",
        type: "Cashless",
        claimAmt: 95000,
        settledAmt: 93000,
        status: "Settled",
        tat: 2,
      },
    ],
    ageGroups: [
      { band: "18–25", employees: 52, dependents: 4 },
      { band: "26–35", employees: 138, dependents: 18 },
      { band: "36–45", employees: 86, dependents: 12 },
      { band: "46–55", employees: 54, dependents: 4 },
      { band: "56–65", employees: 12, dependents: 0 },
      { band: "65+", employees: 0, dependents: 0 },
    ],
    genderSplit: [
      { name: "Male", value: 228, color: "#3B82F6" },
      { name: "Female", value: 114, color: "#EC4899" },
    ],
    deptEnrollment: [
      { dept: "Engineering", enrolled: 90, total: 96 },
      { dept: "Sales", enrolled: 76, total: 80 },
      { dept: "HR", enrolled: 34, total: 36 },
      { dept: "Finance", enrolled: 52, total: 56 },
      { dept: "Operations", enrolled: 68, total: 72 },
      { dept: "Marketing", enrolled: 22, total: 24 },
    ],
    memberTable: [
      {
        empId: "EMP-101",
        name: "Ravi Menon",
        dept: "Engineering",
        si: "₹10 L",
        dependents: 0,
        claimsCount: 1,
        totalClaim: 250000,
      },
      {
        empId: "EMP-102",
        name: "Sita Devi",
        dept: "Operations",
        si: "₹10 L",
        dependents: 1,
        claimsCount: 1,
        totalClaim: 180000,
      },
      {
        empId: "EMP-103",
        name: "Anand Kumar",
        dept: "Sales",
        si: "₹10 L",
        dependents: 0,
        claimsCount: 1,
        totalClaim: 140000,
      },
      {
        empId: "EMP-104",
        name: "Pooja Singh",
        dept: "Finance",
        si: "₹10 L",
        dependents: 0,
        claimsCount: 1,
        totalClaim: 120000,
      },
      {
        empId: "EMP-105",
        name: "Kiran Patel",
        dept: "Marketing",
        si: "₹10 L",
        dependents: 0,
        claimsCount: 1,
        totalClaim: 95000,
      },
    ],
    premiumVsClaim: [
      { month: "Aug", premium: 15416, claim: 120000 },
      { month: "Sep", premium: 15416, claim: 180000 },
      { month: "Oct", premium: 15416, claim: 80000 },
      { month: "Nov", premium: 15416, claim: 220000 },
      { month: "Dec", premium: 15416, claim: 160000 },
      { month: "Jan", premium: 15416, claim: 120000 },
      { month: "Feb", premium: 15416, claim: 200000 },
    ],
    financialTable: [
      { label: "Policy Premium", value: "₹18.5 L" },
      { label: "Claim Paid (YTD)", value: "₹9.0 L" },
      { label: "Outstanding Claims", value: "₹1.8 L" },
      { label: "Loss Ratio %", value: "48.6%" },
      { label: "Admin Charges", value: "₹0.9 L" },
      { label: "Net Liability", value: "₹11.7 L" },
    ],
    lossRatio: 49,
    totalPremiumPaid: "₹18.5 L",
    totalClaimPaid: "₹9.0 L",
    outstandingClaims: "₹1.8 L",
    utilizationPct: 28,
  },
  gtl: {
    employeesCovered: 316,
    dependentsCovered: 316,
    totalClaimAmt: "₹30.0 L",
    avgClaimSize: "₹7.5 L",
    trendUp: false,
    monthlyTrend: [
      { month: "Aug", claims: 1, settled: 1, amount: 1000000 },
      { month: "Sep", claims: 2, settled: 2, amount: 2000000 },
      { month: "Oct", claims: 1, settled: 0, amount: 1000000 },
      { month: "Nov", claims: 2, settled: 2, amount: 2000000 },
      { month: "Dec", claims: 1, settled: 1, amount: 1000000 },
      { month: "Jan", claims: 2, settled: 2, amount: 2000000 },
      { month: "Feb", claims: 1, settled: 0, amount: 1000000 },
    ],
    topHospitals: [{ name: "N/A – Life Claims", claims: 10, amount: 30000000 }],
    diseaseBreakdown: [
      { name: "Natural Death", count: 6, color: "#8B5CF6" },
      { name: "Accidental Death", count: 3, color: "#EF4444" },
      { name: "Critical Illness", count: 1, color: "#F59E0B" },
    ],
    claimsByType: [
      { name: "Death Benefit", value: 80, color: "#8B5CF6" },
      { name: "CI Benefit", value: 20, color: "#F59E0B" },
    ],
    claimsTable: [
      {
        claimNo: "GTL-001",
        employee: "Mohan Das",
        hospital: "—",
        type: "Death Benefit",
        claimAmt: 1000000,
        settledAmt: 1000000,
        status: "Settled",
        tat: 14,
      },
      {
        claimNo: "GTL-002",
        employee: "Lakshmi Iyer",
        hospital: "—",
        type: "Death Benefit",
        claimAmt: 1000000,
        settledAmt: 0,
        status: "Pending",
        tat: 20,
      },
      {
        claimNo: "GTL-003",
        employee: "Farhan Ali",
        hospital: "—",
        type: "CI Benefit",
        claimAmt: 500000,
        settledAmt: 500000,
        status: "Settled",
        tat: 10,
      },
      {
        claimNo: "GTL-004",
        employee: "Seema Rao",
        hospital: "—",
        type: "Death Benefit",
        claimAmt: 500000,
        settledAmt: 500000,
        status: "Settled",
        tat: 12,
      },
    ],
    ageGroups: [
      { band: "18–25", employees: 42, dependents: 0 },
      { band: "26–35", employees: 118, dependents: 0 },
      { band: "36–45", employees: 92, dependents: 0 },
      { band: "46–55", employees: 48, dependents: 0 },
      { band: "56–65", employees: 16, dependents: 0 },
      { band: "65+", employees: 0, dependents: 0 },
    ],
    genderSplit: [
      { name: "Male", value: 198, color: "#3B82F6" },
      { name: "Female", value: 118, color: "#EC4899" },
    ],
    deptEnrollment: [
      { dept: "Engineering", enrolled: 82, total: 96 },
      { dept: "Sales", enrolled: 66, total: 80 },
      { dept: "HR", enrolled: 30, total: 36 },
      { dept: "Finance", enrolled: 44, total: 56 },
      { dept: "Operations", enrolled: 60, total: 72 },
      { dept: "Marketing", enrolled: 18, total: 24 },
    ],
    memberTable: [
      {
        empId: "EMP-201",
        name: "Mohan Das",
        dept: "Engineering",
        si: "₹30 L",
        dependents: 2,
        claimsCount: 1,
        totalClaim: 1000000,
      },
      {
        empId: "EMP-202",
        name: "Lakshmi Iyer",
        dept: "Sales",
        si: "₹30 L",
        dependents: 1,
        claimsCount: 1,
        totalClaim: 1000000,
      },
      {
        empId: "EMP-203",
        name: "Farhan Ali",
        dept: "Finance",
        si: "₹15 L",
        dependents: 3,
        claimsCount: 1,
        totalClaim: 500000,
      },
      {
        empId: "EMP-204",
        name: "Seema Rao",
        dept: "HR",
        si: "₹15 L",
        dependents: 1,
        claimsCount: 1,
        totalClaim: 500000,
      },
    ],
    premiumVsClaim: [
      { month: "Aug", premium: 28500, claim: 1000000 },
      { month: "Sep", premium: 28500, claim: 2000000 },
      { month: "Oct", premium: 28500, claim: 1000000 },
      { month: "Nov", premium: 28500, claim: 2000000 },
      { month: "Dec", premium: 28500, claim: 1000000 },
      { month: "Jan", premium: 28500, claim: 2000000 },
      { month: "Feb", premium: 28500, claim: 1000000 },
    ],
    financialTable: [
      { label: "Policy Premium", value: "₹34.2 L" },
      { label: "Claim Paid (YTD)", value: "₹30.0 L" },
      { label: "Outstanding Claims", value: "₹10.0 L" },
      { label: "Loss Ratio %", value: "87.7%" },
      { label: "Admin Charges", value: "₹1.7 L" },
      { label: "Net Liability", value: "₹41.7 L" },
    ],
    lossRatio: 88,
    totalPremiumPaid: "₹34.2 L",
    totalClaimPaid: "₹30.0 L",
    outstandingClaims: "₹10.0 L",
    utilizationPct: 12,
  },
};

export function fmtAmt(v: number): string {
  if (v >= 10_000_000) return `₹${(v / 10_000_000).toFixed(1)}Cr`;
  if (v >= 100_000) return `₹${(v / 100_000).toFixed(1)}L`;
  if (v >= 1_000) return `₹${(v / 1_000).toFixed(0)}k`;
  return `₹${v}`;
}

export const STATUS_COLOR: Record<string, { bg: string; color: string }> = {
  Settled: { bg: "#D1FAE5", color: "#059669" },
  Pending: { bg: "#FEF9C3", color: "#CA8A04" },
  Rejected: { bg: "#FEE2E2", color: "#DC2626" },
};
