// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const TabButton = styled(Box, {
  shouldForwardProp: (prop) => prop !== "active",
})<{ active: boolean }>(({ active }) => ({
  display: "flex",
  alignItems: "center",
  gap: 7,
  padding: "12px 20px",
  border: "none",
  backgroundColor: "transparent",
  cursor: "pointer",
  fontSize: 13,
  fontWeight: active ? 600 : 400,
  color: active ? "#2563EB" : "#6B7280",
  borderBottom: active ? "2px solid #2563EB" : "2px solid transparent",
  marginBottom: -2,
  transition: "all 0.12s",
  "&:hover": {
    color: active ? "#2563EB" : "#374151",
  },
}));

export const TabStrip = styled(Box)({
  display: "flex",
  borderBottom: "2px solid #F3F4F6",
  marginBottom: 24,
});

export const SmallKpiCard = styled(Box)({
  background: "#fff",
  border: "1px solid #F3F4F6",
  borderRadius: 10,
  padding: "12px 16px",
  boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
});

export const BackButton = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 6,
  padding: "7px 12px",
  border: "1px solid #E5E7EB",
  borderRadius: 6,
  backgroundColor: "#fff",
  cursor: "pointer",
  fontSize: 13,
  color: "#374151",
  fontWeight: 500,
  flexShrink: 0,
  transition: "all 0.12s",
  "&:hover": {
    backgroundColor: "#F9FAFB",
    borderColor: "#D1D5DB",
  },
});
