// Generated by Copilot
import { getCurrencySymbolPrefix, type LocalizationConfig } from "@ui/ui-lib";

export interface ClaimPoint {
  name: string;
  amount: number;
  count: number;
  paid: number;
  outstanding: number;
  rejected: number;
  closed: number;
  denied: number;
}

export const CI_STACKS = [
  { key: "paid", color: "#10B981", label: "Paid" },
  { key: "outstanding", color: "#F59E0B", label: "Outstanding" },
  { key: "rejected", color: "#EF4444", label: "Rejected" },
  { key: "closed", color: "#3B82F6", label: "Closed" },
  { key: "denied", color: "#9CA3AF", label: "Denied" },
] as const;

export const CI_MONTHLY: ClaimPoint[] = [
  {
    name: "Mar '25",
    amount: 198000,
    count: 28,
    paid: 119000,
    outstanding: 42000,
    rejected: 25000,
    closed: 9000,
    denied: 3000,
  },
  {
    name: "Apr '25",
    amount: 247000,
    count: 34,
    paid: 148000,
    outstanding: 53000,
    rejected: 31000,
    closed: 12000,
    denied: 3000,
  },
  {
    name: "May '25",
    amount: 289000,
    count: 39,
    paid: 174000,
    outstanding: 61000,
    rejected: 37000,
    closed: 14000,
    denied: 3000,
  },
  {
    name: "Jun '25",
    amount: 315000,
    count: 43,
    paid: 189000,
    outstanding: 67000,
    rejected: 39000,
    closed: 16000,
    denied: 4000,
  },
  {
    name: "Jul '25",
    amount: 358000,
    count: 48,
    paid: 215000,
    outstanding: 76000,
    rejected: 44000,
    closed: 18000,
    denied: 5000,
  },
  {
    name: "Aug '25",
    amount: 301000,
    count: 41,
    paid: 181000,
    outstanding: 64000,
    rejected: 37000,
    closed: 15000,
    denied: 4000,
  },
  {
    name: "Sep '25",
    amount: 324000,
    count: 44,
    paid: 195000,
    outstanding: 69000,
    rejected: 40000,
    closed: 16000,
    denied: 4000,
  },
  {
    name: "Oct '25",
    amount: 389000,
    count: 52,
    paid: 233000,
    outstanding: 83000,
    rejected: 48000,
    closed: 20000,
    denied: 5000,
  },
  {
    name: "Nov '25",
    amount: 423000,
    count: 57,
    paid: 254000,
    outstanding: 90000,
    rejected: 52000,
    closed: 21000,
    denied: 6000,
  },
  {
    name: "Dec '25",
    amount: 401000,
    count: 54,
    paid: 241000,
    outstanding: 85000,
    rejected: 49000,
    closed: 20000,
    denied: 6000,
  },
  {
    name: "Jan '26",
    amount: 447000,
    count: 60,
    paid: 268000,
    outstanding: 95000,
    rejected: 55000,
    closed: 23000,
    denied: 6000,
  },
  {
    name: "Feb '26",
    amount: 479000,
    count: 64,
    paid: 288000,
    outstanding: 102000,
    rejected: 59000,
    closed: 24000,
    denied: 6000,
  },
];

export const CI_CITY: ClaimPoint[] = [
  {
    name: "Mumbai",
    amount: 1820000,
    count: 245,
    paid: 1092000,
    outstanding: 385000,
    rejected: 228000,
    closed: 91000,
    denied: 24000,
  },
  {
    name: "Delhi",
    amount: 1540000,
    count: 210,
    paid: 924000,
    outstanding: 325000,
    rejected: 192000,
    closed: 77000,
    denied: 22000,
  },
  {
    name: "Bangalore",
    amount: 1240000,
    count: 168,
    paid: 744000,
    outstanding: 262000,
    rejected: 155000,
    closed: 62000,
    denied: 17000,
  },
  {
    name: "Pune",
    amount: 890000,
    count: 121,
    paid: 534000,
    outstanding: 188000,
    rejected: 111000,
    closed: 45000,
    denied: 12000,
  },
  {
    name: "Chennai",
    amount: 760000,
    count: 103,
    paid: 456000,
    outstanding: 161000,
    rejected: 95000,
    closed: 38000,
    denied: 10000,
  },
];

export const CI_HOSPITAL: ClaimPoint[] = [
  {
    name: "Apollo",
    amount: 1250000,
    count: 142,
    paid: 750000,
    outstanding: 265000,
    rejected: 156000,
    closed: 63000,
    denied: 16000,
  },
  {
    name: "Fortis",
    amount: 980000,
    count: 115,
    paid: 588000,
    outstanding: 207000,
    rejected: 122000,
    closed: 49000,
    denied: 14000,
  },
  {
    name: "Max",
    amount: 720000,
    count: 87,
    paid: 432000,
    outstanding: 152000,
    rejected: 90000,
    closed: 36000,
    denied: 10000,
  },
  {
    name: "Medanta",
    amount: 650000,
    count: 78,
    paid: 390000,
    outstanding: 137000,
    rejected: 81000,
    closed: 33000,
    denied: 9000,
  },
  {
    name: "AIIMS",
    amount: 540000,
    count: 67,
    paid: 324000,
    outstanding: 114000,
    rejected: 67000,
    closed: 27000,
    denied: 8000,
  },
];

export const CI_DEPT: ClaimPoint[] = [
  {
    name: "Engineering",
    amount: 1480000,
    count: 198,
    paid: 888000,
    outstanding: 313000,
    rejected: 185000,
    closed: 74000,
    denied: 20000,
  },
  {
    name: "Sales",
    amount: 1120000,
    count: 152,
    paid: 672000,
    outstanding: 236000,
    rejected: 140000,
    closed: 56000,
    denied: 16000,
  },
  {
    name: "Operations",
    amount: 890000,
    count: 121,
    paid: 534000,
    outstanding: 188000,
    rejected: 111000,
    closed: 45000,
    denied: 12000,
  },
  {
    name: "Finance",
    amount: 680000,
    count: 93,
    paid: 408000,
    outstanding: 143000,
    rejected: 85000,
    closed: 34000,
    denied: 10000,
  },
  {
    name: "HR",
    amount: 540000,
    count: 74,
    paid: 324000,
    outstanding: 114000,
    rejected: 67000,
    closed: 27000,
    denied: 8000,
  },
];

export const CI_BY_GROUP: Record<string, ClaimPoint[]> = {
  month: CI_MONTHLY,
  city: CI_CITY,
  hospital: CI_HOSPITAL,
  department: CI_DEPT,
};

export function fmtCI(v: number, localization?: LocalizationConfig): string {
  const sym = getCurrencySymbolPrefix(localization);
  if (v >= 100_000) return `${sym}${(v / 100_000).toFixed(1)}L`;
  if (v >= 1_000) return `${sym}${(v / 1_000).toFixed(0)}k`;
  return `${sym}${v}`;
}
