// Generated by Copilot
import { useState, useMemo } from "react";
import { Box, Typography, Select, MenuItem } from "@mui/material";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import { Layers, Table2, Download } from "lucide-react";
import {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  ActionButton,
} from "../../pages/HRPortal/styles";
import { ToggleBtn } from "./styles";
import { CI_BY_GROUP, CI_STACKS, fmtCI, type ClaimPoint } from "./data";
import { useLocalization } from "@ui/ui-lib";

type ChartMode = "stacked" | "table";
type ViewMode = "amount" | "count";
type GroupMode = "month" | "city" | "hospital" | "department";
type ClaimTypeFilter = "All Claim Types" | "Cashless" | "Reimbursement";
type StatusFilter =
  | "All Status"
  | "Paid"
  | "Outstanding"
  | "Rejected"
  | "Closed"
  | "Denied";
type MemberFilter = "Member Type" | "Employee" | "Dependent";

const TIME_RANGE_OPTIONS = [
  { label: "3 months", value: 3 },
  { label: "6 months", value: 6 },
  { label: "12 months", value: 12 },
];

const GROUP_OPTIONS: { label: string; value: GroupMode }[] = [
  { label: "By Month", value: "month" },
  { label: "By City", value: "city" },
  { label: "By Hospital", value: "hospital" },
  { label: "By Department", value: "department" },
];

export function ClaimsInsights() {
  const { localizationData } = useLocalization();
  const [chartMode, setChartMode] = useState<ChartMode>("stacked");
  const [viewMode, setViewMode] = useState<ViewMode>("amount");
  const [groupBy, setGroupBy] = useState<GroupMode>("month");
  const [timeRange, setTimeRange] = useState(6);
  const [claimTypeFilter, setClaimTypeFilter] =
    useState<ClaimTypeFilter>("All Claim Types");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("All Status");
  const [memberFilter, setMemberFilter] = useState<MemberFilter>("Member Type");

  const chartData = useMemo<ClaimPoint[]>(() => {
    const base = CI_BY_GROUP[groupBy];
    const sliced = groupBy === "month" ? base.slice(-timeRange) : base;

    return sliced.map((point) => {
      let next = { ...point };

      if (claimTypeFilter === "Cashless") {
        next = {
          ...next,
          amount: Math.round(next.amount * 0.65),
          count: Math.round(next.count * 0.62),
        };
      }

      if (claimTypeFilter === "Reimbursement") {
        next = {
          ...next,
          amount: Math.round(next.amount * 0.35),
          count: Math.max(1, Math.round(next.count * 0.38)),
        };
      }

      if (statusFilter !== "All Status") {
        const selectedValue =
          next[statusFilter.toLowerCase() as keyof ClaimPoint];
        const numericValue =
          typeof selectedValue === "number" ? selectedValue : next.amount;

        next = {
          ...next,
          amount: numericValue,
          count: Math.max(
            1,
            Math.round((numericValue / Math.max(point.amount, 1)) * next.count)
          ),
          paid: statusFilter === "Paid" ? next.paid : 0,
          outstanding: statusFilter === "Outstanding" ? next.outstanding : 0,
          rejected: statusFilter === "Rejected" ? next.rejected : 0,
          closed: statusFilter === "Closed" ? next.closed : 0,
          denied: statusFilter === "Denied" ? next.denied : 0,
        };
      }

      if (memberFilter === "Employee") {
        next = {
          ...next,
          amount: Math.round(next.amount * 0.72),
          count: Math.max(1, Math.round(next.count * 0.74)),
          paid: Math.round(next.paid * 0.72),
          outstanding: Math.round(next.outstanding * 0.72),
          rejected: Math.round(next.rejected * 0.72),
          closed: Math.round(next.closed * 0.72),
          denied: Math.round(next.denied * 0.72),
        };
      }

      if (memberFilter === "Dependent") {
        next = {
          ...next,
          amount: Math.round(next.amount * 0.28),
          count: Math.max(1, Math.round(next.count * 0.26)),
          paid: Math.round(next.paid * 0.28),
          outstanding: Math.round(next.outstanding * 0.28),
          rejected: Math.round(next.rejected * 0.28),
          closed: Math.round(next.closed * 0.28),
          denied: Math.round(next.denied * 0.28),
        };
      }

      return next;
    });
  }, [claimTypeFilter, groupBy, memberFilter, statusFilter, timeRange]);

  const yTickFmt = (v: unknown) => {
    if (viewMode === "amount") return fmtCI(Number(v), localizationData?.data);
    return String(v);
  };

  const totalAmount = useMemo(
    () =>
      chartData.reduce(
        (acc, row) => ({
          cashless: acc.cashless + row.paid + row.closed,
          reimbursement:
            acc.reimbursement + row.outstanding + row.rejected + row.denied,
        }),
        { cashless: 0, reimbursement: 0 }
      ),
    [chartData]
  );

  const totalBase = Math.max(
    1,
    totalAmount.cashless + totalAmount.reimbursement
  );
  const cashlessPct = Math.round((totalAmount.cashless / totalBase) * 100);
  const reimbursementPct = 100 - cashlessPct;

  const getCountValue = (
    row: ClaimPoint,
    key: "amount" | "paid" | "outstanding" | "rejected" | "closed" | "denied"
  ) => {
    if (key === "amount") return row.count;
    return Math.max(
      0,
      Math.round((row[key] / Math.max(row.amount, 1)) * row.count)
    );
  };

  return (
    <SectionCard sx={{ mb: 2.5 }}>
      {/* ── Header ── */}
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: 2,
          flexWrap: "wrap",
          gap: 1.5,
        }}
      >
        <SectionTitle sx={{ mb: 0 }}>Claims Insights</SectionTitle>
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            gap: 1.5,
            flexWrap: "wrap",
          }}
        >
          {/* Stacked / Table toggle */}
          <Box
            sx={{
              display: "flex",
              border: "1px solid #e5e7eb",
              borderRadius: 1.5,
              overflow: "hidden",
            }}
          >
            <ToggleBtn
              active={chartMode === "stacked"}
              onClick={() => setChartMode("stacked")}
            >
              <Layers size={13} />
              Stacked Bar
            </ToggleBtn>
            <ToggleBtn
              active={chartMode === "table"}
              onClick={() => setChartMode("table")}
            >
              <Table2 size={13} />
              Table
            </ToggleBtn>
          </Box>

          {/* Amount / Count toggle */}
          <Box
            sx={{
              display: "flex",
              border: "1px solid #e5e7eb",
              borderRadius: 1.5,
              overflow: "hidden",
            }}
          >
            <ToggleBtn
              active={viewMode === "amount"}
              onClick={() => setViewMode("amount")}
            >
              Amount
            </ToggleBtn>
            <ToggleBtn
              active={viewMode === "count"}
              onClick={() => setViewMode("count")}
            >
              Count
            </ToggleBtn>
          </Box>

          <ActionButton
            sx={{
              display: "flex",
              alignItems: "center",
              gap: 0.75,
              fontSize: 13,
              py: 0.75,
              px: 1.5,
            }}
          >
            <Download size={13} />
            Export
          </ActionButton>
        </Box>
      </Box>

      {/* ── Filters ── */}
      <Box sx={{ display: "flex", gap: 2, mb: 2.25, flexWrap: "wrap" }}>
        <Select
          size="small"
          value={timeRange}
          onChange={(e) => setTimeRange(Number(e.target.value))}
          sx={{ fontSize: 14, minWidth: 160, height: 40 }}
        >
          {TIME_RANGE_OPTIONS.map((r) => (
            <MenuItem key={r.value} value={r.value}>
              Last {r.value} Months
            </MenuItem>
          ))}
        </Select>
        <Select
          size="small"
          value={claimTypeFilter}
          onChange={(e) =>
            setClaimTypeFilter(e.target.value as ClaimTypeFilter)
          }
          sx={{ fontSize: 14, minWidth: 180, height: 40 }}
        >
          {["All Claim Types", "Cashless", "Reimbursement"].map((option) => (
            <MenuItem key={option} value={option}>
              {option}
            </MenuItem>
          ))}
        </Select>
        <Select
          size="small"
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value as StatusFilter)}
          sx={{ fontSize: 14, minWidth: 160, height: 40 }}
        >
          {[
            "All Status",
            "Paid",
            "Outstanding",
            "Rejected",
            "Closed",
            "Denied",
          ].map((option) => (
            <MenuItem key={option} value={option}>
              {option}
            </MenuItem>
          ))}
        </Select>
        <Select
          size="small"
          value={memberFilter}
          onChange={(e) => setMemberFilter(e.target.value as MemberFilter)}
          sx={{ fontSize: 14, minWidth: 160, height: 40 }}
        >
          {["Member Type", "Employee", "Dependent"].map((option) => (
            <MenuItem key={option} value={option}>
              {option}
            </MenuItem>
          ))}
        </Select>
        {chartMode === "stacked" ? (
          <Select
            size="small"
            value={groupBy}
            onChange={(e) => setGroupBy(e.target.value as GroupMode)}
            sx={{ fontSize: 14, minWidth: 160, height: 40 }}
          >
            {GROUP_OPTIONS.map((g) => (
              <MenuItem key={g.value} value={g.value}>
                {g.label}
              </MenuItem>
            ))}
          </Select>
        ) : null}
      </Box>

      {/* ── Cashless / Reimbursement legend ── */}
      {chartMode === "stacked" && (
        <Box sx={{ display: "flex", gap: 3, mb: 1.5 }}>
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
            <Box
              sx={{
                width: 10,
                height: 10,
                borderRadius: "50%",
                backgroundColor: "#3b82f6",
              }}
            />
            <Typography sx={{ fontSize: 13, color: "#6b7280" }}>
              Cashless {cashlessPct}%
            </Typography>
          </Box>
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
            <Box
              sx={{
                width: 10,
                height: 10,
                borderRadius: "50%",
                backgroundColor: "#10b981",
              }}
            />
            <Typography sx={{ fontSize: 13, color: "#6b7280" }}>
              Reimbursement {reimbursementPct}%
            </Typography>
          </Box>
        </Box>
      )}

      {/* ── Chart or Table ── */}
      {chartMode === "stacked" ? (
        <ResponsiveContainer width="100%" height={260}>
          <BarChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis
              dataKey="name"
              tick={{ fontSize: 12.5, fill: "#7b8794" }}
              axisLine={false}
              tickLine={false}
            />
            <YAxis
              tickFormatter={yTickFmt}
              tick={{ fontSize: 12.5, fill: "#7b8794" }}
              axisLine={false}
              tickLine={false}
            />
            <RechartTooltip
              contentStyle={{
                borderRadius: 8,
                border: "1px solid #e5e7eb",
                fontSize: 12,
              }}
              formatter={(v: unknown, name: unknown) => [
                viewMode === "amount" ? fmtCI(Number(v), localizationData?.data) : String(v),
                String(name),
              ]}
            />
            <Legend iconSize={10} wrapperStyle={{ fontSize: 12.5 }} />
            {CI_STACKS.map((s) => (
              <Bar
                key={s.key}
                dataKey={(d: ClaimPoint) =>
                  viewMode === "amount" ? d[s.key] : getCountValue(d, s.key)
                }
                name={s.label}
                stackId="a"
                fill={s.color}
              />
            ))}
          </BarChart>
        </ResponsiveContainer>
      ) : (
        <StyledTable>
          <thead>
            <tr>
              <StyledTh sx={{ fontSize: 13 }}>Name</StyledTh>
              <StyledTh sx={{ textAlign: "right", fontSize: 13 }}>
                {viewMode === "amount" ? "Amount" : "Count"}
              </StyledTh>
              <StyledTh sx={{ textAlign: "right", fontSize: 13 }}>
                Paid
              </StyledTh>
              <StyledTh sx={{ textAlign: "right", fontSize: 13 }}>
                Outstanding
              </StyledTh>
              <StyledTh sx={{ textAlign: "right", fontSize: 13 }}>
                Rejected
              </StyledTh>
              <StyledTh sx={{ textAlign: "right", fontSize: 13 }}>
                Closed
              </StyledTh>
              <StyledTh sx={{ textAlign: "right", fontSize: 13 }}>
                Denied
              </StyledTh>
            </tr>
          </thead>
          <tbody>
            {chartData.map((row, i) => (
              <tr key={i}>
                <StyledTd sx={{ fontWeight: 500, fontSize: 13 }}>
                  {row.name}
                </StyledTd>
                <StyledTd sx={{ textAlign: "right", fontSize: 13 }}>
                  {viewMode === "amount" ? fmtCI(row.amount, localizationData?.data) : row.count}
                </StyledTd>
                <StyledTd sx={{ textAlign: "right", fontSize: 13 }}>
                  {viewMode === "amount"
                    ? fmtCI(row.paid, localizationData?.data)
                    : getCountValue(row, "paid")}
                </StyledTd>
                <StyledTd sx={{ textAlign: "right", fontSize: 13 }}>
                  {viewMode === "amount"
                    ? fmtCI(row.outstanding, localizationData?.data)
                    : getCountValue(row, "outstanding")}
                </StyledTd>
                <StyledTd sx={{ textAlign: "right", fontSize: 13 }}>
                  {viewMode === "amount"
                    ? fmtCI(row.rejected, localizationData?.data)
                    : getCountValue(row, "rejected")}
                </StyledTd>
                <StyledTd sx={{ textAlign: "right", fontSize: 13 }}>
                  {viewMode === "amount"
                    ? fmtCI(row.closed, localizationData?.data)
                    : getCountValue(row, "closed")}
                </StyledTd>
                <StyledTd sx={{ textAlign: "right", fontSize: 13 }}>
                  {viewMode === "amount"
                    ? fmtCI(row.denied, localizationData?.data)
                    : getCountValue(row, "denied")}
                </StyledTd>
              </tr>
            ))}
          </tbody>
        </StyledTable>
      )}
    </SectionCard>
  );
}

export default ClaimsInsights;
