// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const ToggleBtn = styled(Box, {
  shouldForwardProp: (prop) => prop !== "active",
})<{ active: boolean }>(({ active }) => ({
  padding: "6px 16px",
  borderRadius: 6,
  fontSize: 12,
  fontWeight: 500,
  cursor: "pointer",
  border: "none",
  background: active ? "#fff" : "transparent",
  color: active ? "#111827" : "#9CA3AF",
  boxShadow: active ? "0 1px 4px rgba(0,0,0,0.08)" : "none",
  transition: "all 0.12s",
}));

export const FilterSelectWrapper = styled(Box)({
  border: "1px solid #E5E7EB",
  borderRadius: 6,
  padding: "5px 12px",
  backgroundColor: "#F9FAFB",
});
