// Generated by Copilot
import type { ElementType } from "react";

// ─── HR Analytics API Response Types ─────────────────────────────────────────
// Field names match the SQL column aliases in hr-module-analytics-scripts.sql.
// All reports are called via POST /hr-module/generate/:reportKey.
// Response envelope: { data: { data: T[], count?: number } }

/** One row from dashboard_policy_cards */
export interface PolicyCardRow {
  policyId: number;
  policyName: string;
  policyTypeKey: string;
  iiRmTypeKey: string;
  policyNumber?: string | null;
  insurer: string;
  tpaName?: string | null;
  periodStart: string;
  periodEnd: string;
  totalLives: number;
  employeeCount: number;
  dependentCount: number;
  netPremium: number;
  earnedPremium?: number;
  cdBalance: number;
  cdUsedAmount: number;
  cdRunningBalance?: number | null;
  cdAccountNumber?: string | null;
  safeLimit?: number | null;
  totalClaims: number;
  claimAmount: number;
  enrolledCount: number;
  enrolledPercent: number | null;
  inProgressCount: number;
  inProgressPercent: number | null;
  notEnrolledCount: number;
  notEnrolledPercent: number | null;
  notLoggedInCount: number;
  loggedInCount: number;
  icrPercent: number | null;
  icrClaimCount: number;
  icrSamePeriodLYPercent: number | null;
  icrSamePeriodLYAmount: number;
  icrFullYearAvgLY: number | null;
  icrFullYearAvgLYAmount: number;
  icrYoYChangePercent: number | null;
  icrForecastPercent: number | null;
  memberAdditions: number;
  memberDeletions: number;
  totalAssets?: number | null;
  totalSubAssets?: number | null;
  totalSumInsured?: number | null;
  assetTotalPremium?: number | null;
}

/** One row from dashboard_premium_summary (single-row report) */
export interface PremiumSummaryRow {
  inceptionPremium: number;
  additionPremium: number;
  deletionPremium: number;
  topUpPremium: number;
  totalPremium: number;
  inceptionPremiumPrevYear: number;
  additionPremiumPrevYear: number;
  deletionPremiumPrevYear: number;
  topUpPremiumPrevYear: number;
  totalPremiumPrevYear: number;
  totalPremiumYoYChangePercent: number | null;
}

/** One row from dashboard_claims_analysis_kpi (single-row report) */
export interface ClaimsKpiRow {
  totalClaimsCount: number;
  totalClaimsAmount: number;
  paidClaimsAmount: number;
  paidClaimsCount: number;
  pendingClaimsAmount: number;
  pendingClaimsCount: number;
  claimRatioPercent: number | null;
  totalClaimsCountPrevYear: number;
  totalClaimsAmountPrevYear: number;
  paidClaimsAmountPrevYear: number;
  paidClaimsCountPrevYear: number;
  pendingClaimsAmountPrevYear: number;
  pendingClaimsCountPrevYear: number;
  claimRatioPercentPrevYear: number | null;
  totalClaimsAmountYoYChangePercent: number | null;
  paidClaimsAmountYoYChangePercent: number | null;
  pendingClaimsAmountYoYChangePercent: number | null;
}

/** One row from dashboard_claims_monthly_trend */
export interface ClaimsMonthRow {
  month: string;
  monthStart: string;
  cashlessAmount: number;
  reimbursementAmount: number;
  cashlessCount: number;
  reimbursementCount: number;
  cashlessAmountPrevYear: number;
  reimbursementAmountPrevYear: number;
  cashlessCountPrevYear: number;
  reimbursementCountPrevYear: number;
}

/** One row from dashboard_enrollment_status (single-row report) */
export interface EnrollmentStatusRow {
  totalEligible: number;
  loggedIn: number;
  notLoggedIn: number;
  enrollmentConfirmed: number;
  loggedInPercent: number | null;
  notLoggedInPercent: number | null;
  enrollmentConfirmedPercent: number | null;
}

/** One row from dashboard_demographics (single-row report) */
export interface DemographicsRow {
  inceptionMembersTotal: number;
  inceptionEmployees: number;
  inceptionDependents: number;
  newAdditionsTotal: number;
  newAdditionsEmployees: number;
  newAdditionsDependents: number;
  deletionsTotal: number;
  deletionsEmployees: number;
  deletionsDependents: number;
  totalActiveMembers: number;
  totalActiveEmployees: number;
  totalActiveDependents: number;
}

/** One row from dashboard_top10_employees */
export interface Top10EmployeeRow {
  employeeId: number;
  employeeCode: string;
  employeeName: string;
  department: string;
  totalClaims: number;
  totalAmount: number;
  totalAmountPrevYear: number;
  rankPrevYear: number | null;
  rankChange: number | null;
  yoYChangePercent: number | null;
}

/** One row from dashboard_top10_hospitals */
export interface Top10HospitalRow {
  hospitalId: string;
  hospitalName: string;
  city: string;
  totalClaims: number;
  totalAmount: number;
  totalAmountPrevYear: number;
  rankPrevYear: number | null;
  rankChange: number | null;
  yoYChangePercent: number | null;
}

/** One row from dashboard_top10_diseases */
export interface Top10DiseaseRow {
  diseaseCategory: string;
  totalClaims: number;
  totalAmount: number;
  totalAmountPrevYear: number;
  rankPrevYear: number | null;
  rankChange: number | null;
  yoYChangePercent: number | null;
}

/** One row from emp_support_kpi_summary (single-row report) */
export interface EmpSupportKpiRow {
  [key: string]: unknown;
}

/** Full policy row shown in the Policy Overview cards. */
export interface Policy {
  id: string;
  name: string;
  policyNo: string;
  policyPeriod: string;
  enrollmentPeriod: string;
  dotColor: string;
  totalLives: number;
  sumInsured: string;
  netPremium: string;
  activeClaims: number;
  enrolledCount: number;
  totalCount: number;
  enrollmentPct: number;
  claimUtilPct: number;
  additions: number;
  deletions: number;
  accentColor: string;
  enrollBarColor: string;
  claimBarColor: string;
}

/** Subset of Policy passed to the PolicyDetail component when a card is opened. */
export interface PolicyDetailMeta {
  id: string;
  name: string;
  policyNo: string;
  policyPeriod: string;
  dotColor: string;
  totalLives: number;
  sumInsured: string;
  netPremium: string;
  activeClaims: number;
  enrolledCount: number;
  totalCount: number;
  enrollmentPct: number;
  claimUtilPct: number;
}

export type AlertSeverity = "warning" | "error" | "info";

export interface AlertItem {
  id: number;
  type: AlertSeverity;
  message: string;
  action: string;
  Icon: ElementType;
}

export interface KPIItem {
  label: string;
  value: string;
  change: string;
  positive: boolean;
  Icon: ElementType;
  accent: string;
}

export interface TrendPoint {
  m: string;
  v: number;
}

export interface TopClaimRow {
  name: string;
  type: "Employee" | "Hospital";
  amount: string;
  hospital: string;
}
