// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const FormCard = styled(Box)({
  background: "#fff",
  border: "1px solid #f0f0f0",
  borderRadius: 16,
  boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  overflow: "hidden",
});

export const SectionLabel = styled(Box)({
  fontSize: 10,
  fontWeight: 700,
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  color: "#2563eb",
  marginBottom: 12,
});

export const InputWrap = styled(Box)({
  position: "relative",
  "& input, & select": {
    width: "100%",
    height: 36,
    padding: "0 12px",
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    background: "#fff",
    fontSize: 13,
    color: "#374151",
    outline: "none",
    transition: "border-color 0.15s, box-shadow 0.15s",
    "&:focus": {
      borderColor: "#60a5fa",
      boxShadow: "0 0 0 3px rgba(147,197,253,0.35)",
    },
    "&:disabled": {
      background: "#f9fafb",
      color: "#9ca3af",
      cursor: "not-allowed",
    },
  },
  "& select": {
    appearance: "none",
    paddingRight: 28,
    cursor: "pointer",
  },
});

export const IconLeft = styled(Box)({
  position: "absolute",
  left: 10,
  top: "50%",
  transform: "translateY(-50%)",
  pointerEvents: "none",
  display: "flex",
  alignItems: "center",
  color: "#9ca3af",
});

export const ChevronRight = styled(Box)({
  position: "absolute",
  right: 10,
  top: "50%",
  transform: "translateY(-50%)",
  pointerEvents: "none",
  display: "flex",
  alignItems: "center",
  color: "#9ca3af",
});

export const EmployeePill = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "6px 12px",
  background: "#eff6ff",
  border: "1px solid #bfdbfe",
  borderRadius: 10,
  marginTop: 4,
});

export const DropdownList = styled(Box)({
  position: "absolute",
  top: "calc(100% + 4px)",
  left: 0,
  right: 0,
  background: "#fff",
  border: "1px solid #e5e7eb",
  borderRadius: 10,
  boxShadow: "0 8px 24px rgba(0,0,0,0.10)",
  zIndex: 20,
  overflow: "hidden",
});

export const DropdownItem = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 12,
  padding: "10px 16px",
  cursor: "pointer",
  transition: "background 0.1s",
  "&:hover": { background: "#eff6ff" },
});

export const ToggleRow = styled(Box)({
  display: "flex",
  gap: 8,
});

export const TypeToggle = styled(Box, {
  shouldForwardProp: (p) => p !== "active",
})<{ active: boolean }>(({ active }) => ({
  flex: 1,
  height: 36,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  borderRadius: 10,
  border: active ? "1px solid #2563eb" : "1px solid #e5e7eb",
  background: active ? "#2563eb" : "#fff",
  color: active ? "#fff" : "#6b7280",
  fontSize: 13,
  fontWeight: 500,
  cursor: "pointer",
  transition: "all 0.15s",
  "&:hover": {
    borderColor: active ? "#2563eb" : "#93c5fd",
    color: active ? "#fff" : "#2563eb",
  },
}));

export const DropZone = styled(Box)({
  border: "2px dashed #e5e7eb",
  borderRadius: 14,
  padding: "28px 16px",
  textAlign: "center",
  cursor: "pointer",
  transition: "all 0.15s",
  "&:hover": {
    borderColor: "#93c5fd",
    background: "rgba(239,246,255,0.4)",
  },
});

export const FileRow = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 10,
  padding: "8px 12px",
  background: "#f9fafb",
  border: "1px solid #f0f0f0",
  borderRadius: 10,
});
