// Generated by Copilot
import { Box, Typography, IconButton } from "@mui/material";
import type { AlertItem } from "../../pages/HRPortalDashboard/types";
import { AlertChip } from "./styles";

const ALERT_PALETTE: Record<
  string,
  { bg: string; border: string; icon: string }
> = {
  warning: { bg: "#fffbeb", border: "#fde68a", icon: "#d97706" },
  error: { bg: "#fef2f2", border: "#fecaca", icon: "#dc2626" },
  info: { bg: "#eff6ff", border: "#bfdbfe", icon: "#2563eb" },
};

interface AlertsBarProps {
  alerts: AlertItem[];
  dismissedIds: number[];
  onDismiss: (id: number) => void;
}

export function AlertsBar({ alerts, dismissedIds, onDismiss }: AlertsBarProps) {
  const _visible = alerts.filter((a) => !dismissedIds.includes(a.id));

  if (_visible.length === 0) return null;

  return (
    <Box sx={{ display: "flex", flexWrap: "wrap", gap: 1.5, mb: 3 }}>
      {_visible.map((alert) => {
        const c = ALERT_PALETTE[alert.type] ?? ALERT_PALETTE.info;
        return (
          <AlertChip key={alert.id} chipBg={c.bg} chipBorder={c.border}>
            <alert.Icon size={14} color={c.icon} />
            <Typography sx={{ fontSize: 12, color: "#374151" }}>
              {alert.message}
            </Typography>
            <Typography
              sx={{
                fontSize: 12,
                fontWeight: 600,
                color: c.icon,
                cursor: "pointer",
              }}
            >
              {alert.action}
            </Typography>
            <IconButton
              size="small"
              onClick={() => onDismiss(alert.id)}
              sx={{ p: 0.25 }}
            >
              <Typography
                sx={{ fontSize: 14, color: "#9ca3af", lineHeight: 1 }}
              >
                ×
              </Typography>
            </IconButton>
          </AlertChip>
        );
      })}
    </Box>
  );
}

export default AlertsBar;
