// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const AlertChip = styled(Box, {
  shouldForwardProp: (prop) => prop !== "chipBg" && prop !== "chipBorder",
})<{ chipBg: string; chipBorder: string }>(({ chipBg, chipBorder }) => ({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "6px 12px",
  backgroundColor: chipBg,
  border: `1px solid ${chipBorder}`,
  borderRadius: 8,
}));
