-- Scripts as of 04/06/2025
-- Data Validation
-- KDM MEETING
update
    opportunity_activity_map
set
    activity_meta = '[ { "key": "kdmMeetingFormFields",
"title": "Enter new KDM meeting details or select from existing one",
"config": [ { "key": "kdmMeetingTypeLid",
"name": "kdmMeetingTypeLid",
"label": "Select KDM Meeting as",
"type": "segmentedcontrol",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"SELECT_MEETING\")",
"clearFieldsOnChange": [ "selectMeeting" ] },
"rules": { "required": { "value": true,
"message": "Please select KDM Meeting type." } },
"componentProps": { "fullWidth": true } },
{ "key": "selectMeeting",
"name": "selectMeeting",
"label": "Select Meeting",
"type": "select",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.meetingList(opportunityActivityId)",
"utilityFunction": "#meetingUtilityFunction",
"showCondition": "#(watch) =>!!watch(\"kdmMeetingTypeLid\") && watch(\"kdmMeetingTypeLid\") !== 359" },
"componentProps": { "fullWidth": true,
"onChange": "handleSelectMeeting" },
"invokeFunction": "fetchMeetingDetails",
"rules": { "validate": "#(value, formValues) => { if (formValues.kdmMeetingTypeLid !== 359 && formValues.kdmMeetingTypeLid !== \"undefined\") {return \"Please select a meeting.\";} return true; }" } },
{ "key": "meetingDate",
"name": "meetingDate",
"label": "Meeting Date",
"type": "date",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Please select the meeting date." } } },
{ "key": "meetingTime",
"name": "meetingTime",
"label": "Meeting time",
"type": "timerange",
"fromName": "availableFrom",
"toName": "availableTo",
"fromLabel": "Available from",
"toLabel": "Available to",
"componentProps": { "fullWidth": true },
"gridColumn": 5,
"rules": { "required": { "value": true,
"message": "Please select the available meeting time." } } },
{ "key": "meetingTypeLid",
"name": "meetingTypeLid",
"label": "Type of meeting",
"type": "select",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_TYPE\")" },
"componentProps": { "fullWidth": true,
"placeholder": "Select..." },
"rules": { "required": "Please select the meeting type." } },
{ "key": "locationTypeLid",
"name": "locationTypeLid",
"label": "Location (Held At)",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_LOCATION\")" } } ],
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"defaultValues": { "kdmMeetingTypeLid": 359,
"selectMeeting": null,
"meetingDate": null,
"availableFrom": null,
"availableTo": null,
"meetingTypeLid": null,
"locationTypeLid": null } },
{ "key": "companyParticipants",
"title": "Company Participants",
"config": [ { "key": "companyId",
"name": "companyId",
"label": "Company Participants",
"type": "select",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.companiesList",
"utilityFunction": "#companyUtilityFunction" },
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Please select a company Participants." } } },
{ "key": "companyContactPerson",
"name": "companyContactPerson",
"label": "Company Contact Person",
"type": "multiselect",
"gridColumn": 5,
"apiDependencies": { "dependentField": "companyId",
"endPoint": "#endPoints.companyContacts",
"utilityFunction": "#companyContactsUtilityFunction" },
"rules": { "required": { "value": true,
"message": "Please select at least one contact person." } } } ],
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"defaultValues": [ { "companyId": null,
"companyContactPerson": [ ] } ] },
{ "key": "employeeParticipants",
"title": "Employee Participants",
"config": [ { "key": "employees",
"name": "employees",
"label": "Employee Participants",
"type": "multiselect",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" },
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Please select at least one employee participant." } } } ],
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"defaultValues": { "employees": [ ] } },
{ "key": "remarksMomSection",
"config": [ { "key": "mom",
"name": "mom",
"label": "MOM",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Should not exceed 1000 characters.\")}" } },
{ "key": "remarks",
"name": "remarks",
"label": "Remarks",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" } } ],
"defaultValues": { "mom": null,
"remarks": null } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"label": "Document type",
"type": "select",
"gridColumn": 3,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"label": "RFP data Collection Document",
"type": "file",
"gridColumn": 6,
"componentProps": { "customVariant": "primary" } } ],
"isMultiple": true,
"defaultValues": [ { "documentTypeLid": null,
"documentId": null } ] } ]'
where
    ref_activity_id = 2;

update
    mstr_activity
set
    activity_detail_meta = '[ { "key": "kdmMeetingFormFields",
"title": "Enter new KDM meeting details or select from existing one",
"config": [ { "key": "kdmMeetingTypeLid",
"name": "kdmMeetingTypeLid",
"type": "segmentedcontrol",
"label": "Select KDM Meeting as",
"rules": { "required": { "value": true,
"message": "Please select KDM Meeting type." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"SELECT_MEETING\")",
"clearFieldsOnChange": [ "selectMeeting" ] } },
{ "key": "selectMeeting",
"name": "selectMeeting",
"type": "select",
"label": "Select Meeting",
"rules": { "validate": "#(value, formValues) => { if (formValues.kdmMeetingTypeLid !== 359 && formValues.kdmMeetingTypeLid !== \"undefined\") {return \"Please select a meeting.\";} return true; }" },
"gridColumn": 5,
"componentProps": { "onChange": "handleSelectMeeting",
"fullWidth": true },
"invokeFunction": "fetchMeetingDetails",
"apiDependencies": { "endPoint": "#endPoints.meetingList(opportunityActivityId)",
"showCondition": "#(watch) =>!!watch(\"kdmMeetingTypeLid\") && watch(\"kdmMeetingTypeLid\") !== 359",
"utilityFunction": "#meetingUtilityFunction" } },
{ "key": "meetingDate",
"name": "meetingDate",
"type": "date",
"label": "Meeting Date",
"rules": { "required": { "value": true,
"message": "Please select the meeting date." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTime",
"name": "meetingTime",
"type": "timerange",
"label": "Meeting time",
"rules": { "required": { "value": true,
"message": "Please select the available meeting time." } },
"toName": "availableTo",
"toLabel": "Available to",
"fromName": "availableFrom",
"fromLabel": "Available from",
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTypeLid",
"name": "meetingTypeLid",
"type": "select",
"label": "Type of meeting",
"rules": { "required": "Pleaseselect the meeting type." },
"gridColumn": 5,
"componentProps": { "fullWidth": true,
"placeholder": "Select..." },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_TYPE\")" } },
{ "key": "locationTypeLid",
"name": "locationTypeLid",
"type": "select",
"label": "Location (Held At)",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_LOCATION\")" } } ],
"defaultValues": { "availableTo": null,
"meetingDate": null,
"availableFrom": null,
"selectMeeting": null,
"meetingTypeLid": null,
"locationTypeLid": null,
"kdmMeetingTypeLid": 359 },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "companyParticipants",
"title": "Company Participants",
"config": [ { "key": "companyId",
"name": "companyId",
"type": "select",
"label": "Company Participants",
"rules": { "required": { "value": true,
"message": "Please select a company Participants." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.companiesList",
"utilityFunction": "#companyUtilityFunction" } },
{ "key": "companyContactPerson",
"name": "companyContactPerson",
"type": "multiselect",
"label": "Company Contact Person",
"rules": { "required": { "value": true,
"message": "Please select at least one contact person." } },
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.companyContacts",
"dependentField": "companyId",
"utilityFunction": "#companyContactsUtilityFunction" } } ],
"defaultValues": [ { "companyId": null,
"companyContactPerson": [ ] } ],
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "employeeParticipants",
"title": "Employee Participants",
"config": [ { "key": "employees",
"name": "employees",
"type": "multiselect",
"label": "Employee Participants",
"rules": { "required": { "value": true,
"message": "Please select at least one employee participant." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" } } ],
"defaultValues": { "employees": [ ] },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "remarksMomSection",
"config": [ { "key": "mom",
"name": "mom",
"type": "textarea",
"label": "MOM",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } },
{ "key": "remarks",
"name": "remarks",
"type": "textarea",
"label": "Remarks",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } } ],
"defaultValues": { "mom": null,
"remarks": null } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"type": "select",
"label": "Document type",
"gridColumn": 3,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"type": "file",
"label": "RFP data Collection Document",
"gridColumn": 6,
"componentProps": { "customVariant": "primary" } } ],
"isMultiple": true,
"defaultValues": [ { "documentId": null,
"documentTypeLid": null } ] } ]'
where
    id = 2 -- RFP DETAILS ENTRY
update
    opportunity_activity_map
set
    activity_meta = '[ { "key": "descriptionRequirements",
"config": [ { "key": "description",
"name": "description",
"label": "Description",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"rows": 3,
"multiline": true },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Requirements should not exceed 1000 characters.\")}" } },
{ "key": "requirements",
"name": "requirements",
"label": "Requirements",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"rows": 3,
"multiline": true },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Requirements should not exceed 1000 characters.\")}" } } ],
"defaultValues": { "description": "",
"requirements": "" } },
{ "key": "preferredInsurers",
"title": "Preferred Insurers",
"config": [ { "key": "insurerId",
"name": "insurerId",
"label": "Insurer name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Insurer name is required." },
"apiDependencies": { "endPoint": "#endPoints.allInsurers",
"utilityFunction": "#insurerUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Location is required." } },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationListUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Branch is required." } },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationAddressUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerContactList",
"dependentField": "insurerId",
"utilityFunction": "#insurerContactPersonUtilityFunction" } } ],
"isMultiple": true,
"defaultValues": [ { "insurerId": null,
"locationId": "",
"branchId": "",
"contactId": "" } ] },
{ "key": "preferredTPA",
"title": "Preferred TPAs",
"config": [ { "key": "tpaId",
"name": "tpaId",
"label": "TPA name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "TPA name is required." },
"apiDependencies": { "endPoint": "#endPoints.AllTpas",
"utilityFunction": "#tpaUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Location is required." },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationListUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Branch is required." },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationAddressUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaContactList",
"dependentField": "tpaId",
"utilityFunction": "#tpaContactPersonUtilityFunction" } } ],
"isMultiple": true,
"defaultValues": [ { "tpaId": null,
"locationId": "",
"branchId": "",
"contactId": "" } ] },
{ "key": "dynamicQuote",
"title": "Deal Dynamics for quote procurment",
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"config": [ { "key": "multipleBrokerInvolved",
"name": "multipleBrokerInvolved",
"label": "Multiple broker involved",
"type": "segmentedcontrol",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"TOGGLE_TYPE\")" },
"rules": { "required": "This field is required." } },
{ "key": "isMarketAllocationDone",
"name": "isMarketAllocationDone",
"label": "Is marker allocation done",
"type": "segmentedcontrol",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"TOGGLE_TYPE\")",
"showCondition": "#(watch) =>!!watch(\"multipleBrokerInvolved\") && watch(\"multipleBrokerInvolved\") !== 399" },
"rules": { "validate": "#(value, formValues) => {\n if (\n formValues.multipleBrokerInvolved !== 399 &&\n formValues.multipleBrokerInvolved !== \"undefined\"\n ) {\n return \"Please toggle market allocation.\";\n }\n return true;\n}" } } ],
"defaultValues": { "multipleBrokerInvolved": 398,
"isMarketAllocationDone": null } },
{ "key": "clientContactDetails",
"title": "Client Contact Details",
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"config": [ { "key": "contactId",
"name": "contactId",
"label": "Select Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Select Contact is required." },
"apiDependencies": { "endPoint": "#endPoints.allContacts",
"utilityFunction": "#contactsUtilityFunction" } },
{ "key": "decisionInfluencers",
"name": "decisionInfluencers",
"label": "Who influences the ultimate decision",
"type": "multiselect",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"CONTACT_TAG\")" } },
{ "key": "expectedPremium",
"name": "expectedPremium",
"label": "Expected premium of client",
"type": "number",
"gridColumn": 5,
"componentProps": { "placeholder": "Enter premium amount",
"fullWidth": true },
"rules": { "required": "Expected premium is required." } } ],
"defaultValues": { "contactId": null,
"decisionInfluencers": [ ],
"expectedPremium": null } },
{ "key": "excludedTPA",
"config": [ { "key": "tpaId",
"name": "tpaId",
"label": "TPA name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.AllTpas",
"utilityFunction": "#tpaUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationListUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationAddressUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaContactList",
"dependentField": "tpaId",
"utilityFunction": "#tpaContactPersonUtilityFunction" } } ],
"title": "Excluded TPA`s",
"isMultiple": true,
"defaultValues": [ { "tpaId": null,
"locationId": null,
"branchId": null,
"contactId": null } ] },
{ "key": "excludedInsurers",
"config": [ { "key": "insurerId",
"name": "insurerId",
"label": "Insurer name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.allInsurers",
"utilityFunction": "#insurerUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationListUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationAddressUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerContactList",
"dependentField": "insurerId",
"utilityFunction": "#insurerContactPersonUtilityFunction" } } ],
"title": "Excluded Insurers",
"isMultiple": true,
"defaultValues": [ { "insurerId": null,
"contactId": null,
"locationId": null,
"branchId": null } ] },
{ "key": "clientConsiderations",
"isCoversRequired": true,
"config": [ { "key": "clientConsiderations",
"name": "clientConsiderations",
"label": "Clients other expectations on coverage/service deliverables",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Client considerations are required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Client considerations should not exceed 1000 characters.\")}" } },
{ "key": "threatsFromExistingInsurer",
"name": "threatsFromExistingInsurer",
"label": "Threats from existing insurer",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Threats from existing insurer is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Threats from existing insurer should not exceed 1000 characters.\")}" } },
{ "key": "threatsFromExistingBroker",
"name": "threatsFromExistingBroker",
"label": "Threats from existing broker/ other brokers in the deal",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Threats from existing broker is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Threats from existing broker should not exceed 1000 characters.\")}" } },
{ "key": "extraneousFactors",
"name": "extraneousFactors",
"label": "Any extraneous factors influencing/affecting/likely to affect decision by client*",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Threats from existing broker is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Threats from existing broker should not exceed 1000 characters.\")}" } },
{ "key": "planForClosingDetail",
"name": "planForClosingDetail",
"label": "Our strategy/Plan for closing the deal*",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Plan for closing detail is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Plan for closing detail should not exceed 1000 characters.\")}" } } ] },
{ "key": "targetQcrDate",
"config": [ { "key": "targetQcrDate",
"name": "targetQcrDate",
"label": "Target QCR date",
"type": "date",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Target QCR date is required." } } } ],
"defaultValues": { "targetQcrDate": null } },
{ "key": "creditSharing",
"title": "Credit Sharing",
"config": [ { "key": "executiveId",
"name": "executiveId",
"label": "Add Executives",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" } },
{ "key": "percentage",
"name": "percentage",
"label": "Credit sharing percentage",
"type": "number",
"gridColumn": 5,
"componentProps": { "type": "number",
"fullWidth": true,
"inputProps": { "min": 0,
"max": 100 } } } ],
"isMultiple": true,
"defaultValues": [ { "executiveId": "",
"percentage": "" } ] },
{ "key": "remarks",
"config": [ { "key": "remarks",
"name": "remarks",
"label": "Remarks",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "multiline": true,
"minRows": 3,
"placeholder": "",
"fullWidth": true },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" } } ] },
{ "key": "documents",
"title": "Document Upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"label": "Document type",
"type": "select",
"gridColumn": 3,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"label": "RFP data Collection Document",
"type": "file",
"gridColumn": 7,
"componentProps": { "customVariant": "primary" } } ],
"isMultiple": true,
"defaultValues": [ { "documentTypeLid": null,
"documentId": null } ] } ]'
where
    ref_activity_id = 5;

update
    mstr_activity
set
    activity_detail_meta = '[ { "key": "descriptionRequirements",
"config": [ { "key": "description",
"name": "description",
"label": "Description",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"rows": 3,
"multiline": true },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Requirements should not exceed 1000 characters.\")}" } },
{ "key": "requirements",
"name": "requirements",
"label": "Requirements",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"rows": 3,
"multiline": true },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Requirements should not exceed 1000 characters.\")}" } } ],
"defaultValues": { "description": "",
"requirements": "" } },
{ "key": "preferredInsurers",
"title": "Preferred Insurers",
"config": [ { "key": "insurerId",
"name": "insurerId",
"label": "Insurer name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Insurer name is required." },
"apiDependencies": { "endPoint": "#endPoints.allInsurers",
"utilityFunction": "#insurerUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Location is required." } },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationListUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Branch is required." } },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationAddressUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerContactList",
"dependentField": "insurerId",
"utilityFunction": "#insurerContactPersonUtilityFunction" } } ],
"isMultiple": true,
"defaultValues": [ { "insurerId": null,
"locationId": "",
"branchId": "",
"contactId": "" } ] },
{ "key": "preferredTPA",
"title": "Preferred TPAs",
"config": [ { "key": "tpaId",
"name": "tpaId",
"label": "TPA name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "TPA name is required." },
"apiDependencies": { "endPoint": "#endPoints.AllTpas",
"utilityFunction": "#tpaUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Location is required." },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationListUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Branch is required." },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationAddressUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaContactList",
"dependentField": "tpaId",
"utilityFunction": "#tpaContactPersonUtilityFunction" } } ],
"isMultiple": true,
"defaultValues": [ { "tpaId": null,
"locationId": "",
"branchId": "",
"contactId": "" } ] },
{ "key": "dynamicQuote",
"title": "Deal Dynamics for quote procurment",
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"config": [ { "key": "multipleBrokerInvolved",
"name": "multipleBrokerInvolved",
"label": "Multiple broker involved",
"type": "segmentedcontrol",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"TOGGLE_TYPE\")" },
"rules": { "required": "This field is required." } },
{ "key": "isMarketAllocationDone",
"name": "isMarketAllocationDone",
"label": "Is marker allocation done",
"type": "segmentedcontrol",
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"TOGGLE_TYPE\")",
"showCondition": "#(watch) =>!!watch(\"multipleBrokerInvolved\") && watch(\"multipleBrokerInvolved\") !== 399" },
"rules": { "validate": "#(value, formValues) => {\n if (\n formValues.multipleBrokerInvolved !== 399 &&\n formValues.multipleBrokerInvolved !== \"undefined\"\n ) {\n return \"Please toggle market allocation.\";\n }\n return true;\n}" } } ],
"defaultValues": { "multipleBrokerInvolved": 398,
"isMarketAllocationDone": null } },
{ "key": "clientContactDetails",
"title": "Client Contact Details",
"containerStyles": { "display": "flex",
"flexDirection": "column",
"gap": "16px" },
"config": [ { "key": "contactId",
"name": "contactId",
"label": "Select Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": "Select Contact is required." },
"apiDependencies": { "endPoint": "#endPoints.allContacts",
"utilityFunction": "#contactsUtilityFunction" } },
{ "key": "decisionInfluencers",
"name": "decisionInfluencers",
"label": "Who influences the ultimate decision",
"type": "multiselect",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"CONTACT_TAG\")" } },
{ "key": "expectedPremium",
"name": "expectedPremium",
"label": "Expected premium of client",
"type": "number",
"gridColumn": 5,
"componentProps": { "placeholder": "Enter premium amount",
"fullWidth": true },
"rules": { "required": "Expected premium is required." } } ],
"defaultValues": { "contactId": null,
"decisionInfluencers": [ ],
"expectedPremium": null } },
{ "key": "excludedTPA",
"config": [ { "key": "tpaId",
"name": "tpaId",
"label": "TPA name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.AllTpas",
"utilityFunction": "#tpaUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationListUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaByID",
"utilityFunction": "#tpaLocationAddressUtilityFunction",
"dependentField": "tpaId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.tpaContactList",
"dependentField": "tpaId",
"utilityFunction": "#tpaContactPersonUtilityFunction" } } ],
"title": "Excluded TPA`s",
"isMultiple": true,
"defaultValues": [ { "tpaId": null,
"locationId": null,
"branchId": null,
"contactId": null } ] },
{ "key": "excludedInsurers",
"config": [ { "key": "insurerId",
"name": "insurerId",
"label": "Insurer name",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.allInsurers",
"utilityFunction": "#insurerUtilityFunction",
"clearFieldsOnChange": [ "locationId",
"branchId",
"contactId" ] } },
{ "key": "locationId",
"name": "locationId",
"label": "Location",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationListUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "branchId",
"contactId" ] } },
{ "key": "branchId",
"name": "branchId",
"label": "Branch",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerById",
"utilityFunction": "#insurerLocationAddressUtilityFunction",
"dependentField": "insurerId",
"clearFieldsOnChange": [ "contactId" ] } },
{ "key": "contactId",
"name": "contactId",
"label": "Contact",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.insurerContactList",
"dependentField": "insurerId",
"utilityFunction": "#insurerContactPersonUtilityFunction" } } ],
"title": "Excluded Insurers",
"isMultiple": true,
"defaultValues": [ { "insurerId": null,
"contactId": null,
"locationId": null,
"branchId": null } ] },
{ "key": "clientConsiderations",
"isCoversRequired": true,
"config": [ { "key": "clientConsiderations",
"name": "clientConsiderations",
"label": "Clients other expectations on coverage/service deliverables",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Client considerations are required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Client considerations should not exceed 1000 characters.\")}" } },
{ "key": "threatsFromExistingInsurer",
"name": "threatsFromExistingInsurer",
"label": "Threats from existing insurer",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Threats from existing insurer is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Threats from existing insurer should not exceed 1000 characters.\")}" } },
{ "key": "threatsFromExistingBroker",
"name": "threatsFromExistingBroker",
"label": "Threats from existing broker/ other brokers in the deal",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Threats from existing broker is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Threats from existing broker should not exceed 1000 characters.\")}" } },
{ "key": "extraneousFactors",
"name": "extraneousFactors",
"label": "Any extraneous factors influencing/affecting/likely to affect decision by client*",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Threats from existing broker is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Threats from existing broker should not exceed 1000 characters.\")}" } },
{ "key": "planForClosingDetail",
"name": "planForClosingDetail",
"label": "Our strategy/Plan for closing the deal*",
"type": "richtext",
"gridColumn": 9,
"componentProps": { "fullWidth": true,
"multiline": true,
"rows": 3 },
"rules": { "required": "Plan for closing detail is required.",
"validate": "#(value) => { return (value.length <= 1000 || \"Plan for closing detail should not exceed 1000 characters.\")}" } } ] },
{ "key": "targetQcrDate",
"config": [ { "key": "targetQcrDate",
"name": "targetQcrDate",
"label": "Target QCR date",
"type": "date",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"rules": { "required": { "value": true,
"message": "Target QCR date is required." } } } ],
"defaultValues": { "targetQcrDate": null } },
{ "key": "creditSharing",
"title": "Credit Sharing",
"config": [ { "key": "executiveId",
"name": "executiveId",
"label": "Add Executives",
"type": "select",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" } },
{ "key": "percentage",
"name": "percentage",
"label": "Credit sharing percentage",
"type": "number",
"gridColumn": 5,
"componentProps": { "type": "number",
"fullWidth": true,
"inputProps": { "min": 0,
"max": 100 } } } ],
"isMultiple": true,
"defaultValues": [ { "executiveId": "",
"percentage": "" } ] },
{ "key": "remarks",
"config": [ { "key": "remarks",
"name": "remarks",
"label": "Remarks",
"type": "textarea",
"gridColumn": 9,
"componentProps": { "multiline": true,
"minRows": 3,
"placeholder": "",
"fullWidth": true },
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" } } ] },
{ "key": "documents",
"title": "Document Upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"label": "Document type",
"type": "select",
"gridColumn": 3,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"label": "RFP data Collection Document",
"type": "file",
"gridColumn": 7,
"componentProps": { "customVariant": "primary" } } ],
"isMultiple": true,
"defaultValues": [ { "documentTypeLid": null,
"documentId": null } ] } ]'
where
    id = 5;

-- PREMIUM cALCULATION
update
    opportunity_activity_map
set
    activity_meta = '[ { "key": "premiumCalculationDetails",
"title": "Premium Calculation",
"config": [ ],
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" },
"isCoversRequired": true },
{ "key": "remarksSection",
"config": [ { "key": "remarks",
"name": "remarks",
"type": "textarea",
"label": "Remarks",
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } } ],
"defaultValues": { "remarks": "" } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"type": "select",
"label": "Document type",
"gridColumn": 3,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"type": "file",
"label": "File upload",
"gridColumn": 7,
"componentProps": { "fullWidth": true,
"placeholder": "Enter your email",
"customVariant": "primary" } } ],
"isMultiple": true,
"defaultValues": [ { "documentId": null,
"documentTypeLid": null } ] } ]'
where
    ref_activity_id = 11;

update
    mstr_activity
set
    activity_meta = '[ { "key": "premiumCalculationDetails",
"title": "Premium Calculation",
"config": [ ],
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" },
"isCoversRequired": true },
{ "key": "remarksSection",
"config": [ { "key": "remarks",
"name": "remarks",
"type": "textarea",
"label": "Remarks",
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } } ],
"defaultValues": { "remarks": "" } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"type": "select",
"label": "Document type",
"gridColumn": 3,
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"type": "file",
"label": "File upload",
"gridColumn": 7,
"componentProps": { "fullWidth": true,
"placeholder": "Enter your email",
"customVariant": "primary" } } ],
"isMultiple": true,
"defaultValues": [ { "documentId": null,
"documentTypeLid": null } ] } ]'
where
    id = 11;

-- Handover meet
update
    opportunity_activity_map
set
    activity_meta = '
    [ { "key": "handOverMeetFields",
"title": "Select the hand over meet details or select form existing meetings from the following list",
"config": [ { "key": "handOverMeetingTypeLid",
"name": "handOverMeetingTypeLid",
"type": "segmentedcontrol",
"label": "Select hand over Meet from existing meetings",
"rules": { "required": { "value": true,
"message": "Please select hand over meeting type." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"SELECT_MEETING\")",
"clearFieldsOnChange": [ "selectMeeting" ] } },
{ "key": "selectMeeting",
"name": "selectMeeting",
"type": "select",
"label": "Select Meeting",
"rules": { "validate": "#(value, formValues) => {\n  if (\n    formValues.handOverMeetingTypeLid !== 359 &&\n    formValues.handOverMeetingTypeLid !== \"undefined\"\n  ) {\n    return \"Please select a meeting.\";\n  }\n  return true;\n}" },
"gridColumn": 5,
"componentProps": { "onChange": "handleSelectMeeting",
"fullWidth": true },
"invokeFunction": "fetchMeetingDetails",
"apiDependencies": { "endPoint": "#endPoints.meetingList(opportunityActivityId)",
"showCondition": "#(watch) =>!!watch(\"handOverMeetingTypeLid\") && watch(\"handOverMeetingTypeLid\") !== 359",
"utilityFunction": "#meetingUtilityFunction" } },
{ "key": "meetingDate",
"name": "meetingDate",
"type": "date",
"label": "Meeting Date",
"rules": { "required": { "value": true,
"message": "Please select the meeting date." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTime",
"name": "meetingTime",
"type": "timerange",
"label": "Meeting time",
"rules": { "required": { "value": true,
"message": "Please select the available meeting time." } },
"toName": "availableTo",
"toLabel": "Available to",
"fromName": "availableFrom",
"fromLabel": "Available from",
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTypeLid",
"name": "meetingTypeLid",
"type": "select",
"label": "Type of meeting",
"rules": { "required": "Please select the meeting type." },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_TYPE\")" } },
{ "key": "locationTypeLid",
"name": "locationTypeLid",
"type": "select",
"label": "Location (Held At)",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_LOCATION\")" } } ],
"defaultValues": { "availableTo": null,
"meetingDate": null,
"availableFrom": null,
"selectMeeting": null,
"meetingTypeLid": null,
"locationTypeLid": null,
"handOverMeetingTypeLid": 359 },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "companyParticipants",
"title": "Company Participants",
"config": [ { "key": "companyId",
"name": "companyId",
"type": "select",
"label": "Company Participants",
"rules": { "required": { "value": true,
"message": "Please select a company Participants." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.companiesList",
"utilityFunction": "#companyUtilityFunction" } },
{ "key": "companyContactPerson",
"name": "companyContactPerson",
"type": "multiselect",
"label": "Company Contact Person",
"rules": { "required": { "value": true,
"message": "Please select at least one contact person." } },
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.companyContacts",
"dependentField": "companyId",
"utilityFunction": "#companyContactsUtilityFunction" } } ],
"defaultValues": [ { "companyId": null,
"companyContactPerson": [ ] } ],
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "employeeParticipants",
"title": "Employee Participants",
"config": [ { "key": "employees",
"name": "employees",
"type": "multiselect",
"label": "Employee Participants",
"rules": { "required": { "value": true,
"message": "Please select at least one employee participant." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" } } ],
"defaultValues": { "employees": [ ] },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "remarksMomSection",
"config": [ { "key": "mom",
"name": "mom",
"type": "textarea",
"label": "MOM",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } },
{ "key": "remarks",
"name": "remarks",
"type": "textarea",
"label": "Remarks",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } } ],
"defaultValues": { "mom": null,
"remarks": null } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"type": "select",
"label": "Document type",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"type": "file",
"label": "File upload",
"gridColumn": 5,
"componentProps": { "fullWidth": true,
"customVariant": "primary" },
"apiDependencies": { "endPoint": "#endPoints.fileUploadByCompanyId(companyId)" } } ],
"isMultiple": true,
"defaultValues": [ { "documentId": null,
"documentTypeLid": null } ] } ]'
where
    ref_activity_id = 15;

update
    mstr_activity
set
    activity_meta = '
    [ { "key": "handOverMeetFields",
"title": "Select the hand over meet details or select form existing meetings from the following list",
"config": [ { "key": "handOverMeetingTypeLid",
"name": "handOverMeetingTypeLid",
"type": "segmentedcontrol",
"label": "Select hand over Meet from existing meetings",
"rules": { "required": { "value": true,
"message": "Please select hand over meeting type." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"SELECT_MEETING\")",
"clearFieldsOnChange": [ "selectMeeting" ] } },
{ "key": "selectMeeting",
"name": "selectMeeting",
"type": "select",
"label": "Select Meeting",
"rules": { "validate": "#(value, formValues) => {\n  if (\n    formValues.handOverMeetingTypeLid !== 359 &&\n    formValues.handOverMeetingTypeLid !== \"undefined\"\n  ) {\n    return \"Please select a meeting.\";\n  }\n  return true;\n}" },
"gridColumn": 5,
"componentProps": { "onChange": "handleSelectMeeting",
"fullWidth": true },
"invokeFunction": "fetchMeetingDetails",
"apiDependencies": { "endPoint": "#endPoints.meetingList(opportunityActivityId)",
"showCondition": "#(watch) =>!!watch(\"handOverMeetingTypeLid\") && watch(\"handOverMeetingTypeLid\") !== 359",
"utilityFunction": "#meetingUtilityFunction" } },
{ "key": "meetingDate",
"name": "meetingDate",
"type": "date",
"label": "Meeting Date",
"rules": { "required": { "value": true,
"message": "Please select the meeting date." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTime",
"name": "meetingTime",
"type": "timerange",
"label": "Meeting time",
"rules": { "required": { "value": true,
"message": "Please select the available meeting time." } },
"toName": "availableTo",
"toLabel": "Available to",
"fromName": "availableFrom",
"fromLabel": "Available from",
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTypeLid",
"name": "meetingTypeLid",
"type": "select",
"label": "Type of meeting",
"rules": { "required": "Please select the meeting type." },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_TYPE\")" } },
{ "key": "locationTypeLid",
"name": "locationTypeLid",
"type": "select",
"label": "Location (Held At)",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_LOCATION\")" } } ],
"defaultValues": { "availableTo": null,
"meetingDate": null,
"availableFrom": null,
"selectMeeting": null,
"meetingTypeLid": null,
"locationTypeLid": null,
"handOverMeetingTypeLid": 359 },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "companyParticipants",
"title": "Company Participants",
"config": [ { "key": "companyId",
"name": "companyId",
"type": "select",
"label": "Company Participants",
"rules": { "required": { "value": true,
"message": "Please select a company Participants." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.companiesList",
"utilityFunction": "#companyUtilityFunction" } },
{ "key": "companyContactPerson",
"name": "companyContactPerson",
"type": "multiselect",
"label": "Company Contact Person",
"rules": { "required": { "value": true,
"message": "Please select at least one contact person." } },
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.companyContacts",
"dependentField": "companyId",
"utilityFunction": "#companyContactsUtilityFunction" } } ],
"defaultValues": [ { "companyId": null,
"companyContactPerson": [ ] } ],
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "employeeParticipants",
"title": "Employee Participants",
"config": [ { "key": "employees",
"name": "employees",
"type": "multiselect",
"label": "Employee Participants",
"rules": { "required": { "value": true,
"message": "Please select at least one employee participant." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" } } ],
"defaultValues": { "employees": [ ] },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "remarksMomSection",
"config": [ { "key": "mom",
"name": "mom",
"type": "textarea",
"label": "MOM",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } },
{ "key": "remarks",
"name": "remarks",
"type": "textarea",
"label": "Remarks",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } } ],
"defaultValues": { "mom": null,
"remarks": null } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"type": "select",
"label": "Document type",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"type": "file",
"label": "File upload",
"gridColumn": 5,
"componentProps": { "fullWidth": true,
"customVariant": "primary" },
"apiDependencies": { "endPoint": "#endPoints.fileUploadByCompanyId(companyId)" } } ],
"isMultiple": true,
"defaultValues": [ { "documentId": null,
"documentTypeLid": null } ] } ]'
where
    id = 15;

-- sample extra
update
    opportunity_activity_map
set
    activity_meta = '
    [ { "key": "handOverMeetFields",
"title": "Select the hand over meet details or select form existing meetings from the following list",
"config": [ { "key": "handOverMeetingTypeLid",
"name": "handOverMeetingTypeLid",
"type": "segmentedcontrol",
"label": "Select hand over Meet from existing meetings",
"rules": { "required": { "value": true,
"message": "Please select hand over meeting type." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"SELECT_MEETING\")",
"clearFieldsOnChange": [ "selectMeeting" ] } },
{ "key": "selectMeeting",
"name": "selectMeeting",
"type": "select",
"label": "Select Meeting",
"rules": { "validate": "#(value, formValues) => {\n  if (\n    formValues.handOverMeetingTypeLid !== 359 &&\n    formValues.handOverMeetingTypeLid !== \"undefined\"\n  ) {\n    return \"Please select a meeting.\";\n  }\n  return true;\n}" },
"gridColumn": 5,
"componentProps": { "onChange": "handleSelectMeeting",
"fullWidth": true },
"invokeFunction": "fetchMeetingDetails",
"apiDependencies": { "endPoint": "#endPoints.meetingList(opportunityActivityId)",
"showCondition": "#(watch) =>!!watch(\"handOverMeetingTypeLid\") && watch(\"handOverMeetingTypeLid\") !== 359",
"utilityFunction": "#meetingUtilityFunction" } },
{ "key": "meetingDate",
"name": "meetingDate",
"type": "date",
"label": "Meeting Date",
"rules": { "required": { "value": true,
"message": "Please select the meeting date." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTime",
"name": "meetingTime",
"type": "timerange",
"label": "Meeting time",
"rules": { "required": { "value": true,
"message": "Please select the available meeting time." } },
"toName": "availableTo",
"toLabel": "Available to",
"fromName": "availableFrom",
"fromLabel": "Available from",
"gridColumn": 5,
"componentProps": { "fullWidth": true } },
{ "key": "meetingTypeLid",
"name": "meetingTypeLid",
"type": "select",
"label": "Type of meeting",
"rules": { "required": "Please select the meeting type." },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_TYPE\")" } },
{ "key": "locationTypeLid",
"name": "locationTypeLid",
"type": "select",
"label": "Location (Held At)",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"MEETING_LOCATION\")" } } ],
"defaultValues": { "availableTo": null,
"meetingDate": null,
"availableFrom": null,
"selectMeeting": null,
"meetingTypeLid": null,
"locationTypeLid": null,
"handOverMeetingTypeLid": 359 },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "companyParticipants",
"title": "Company Participants",
"config": [ { "key": "companyId",
"name": "companyId",
"type": "select",
"label": "Company Participants",
"rules": { "required": { "value": true,
"message": "Please select a company Participants." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.companiesList",
"utilityFunction": "#companyUtilityFunction" } },
{ "key": "companyContactPerson",
"name": "companyContactPerson",
"type": "multiselect",
"label": "Company Contact Person",
"rules": { "required": { "value": true,
"message": "Please select at least one contact person." } },
"gridColumn": 5,
"apiDependencies": { "endPoint": "#endPoints.companyContacts",
"dependentField": "companyId",
"utilityFunction": "#companyContactsUtilityFunction" } } ],
"defaultValues": [ { "companyId": null,
"companyContactPerson": [ ] } ],
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "employeeParticipants",
"title": "Employee Participants",
"config": [ { "key": "employees",
"name": "employees",
"type": "multiselect",
"label": "Employee Participants",
"rules": { "required": { "value": true,
"message": "Please select at least one employee participant." } },
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.employeeListOfValues",
"utilityFunction": "#employeeReportingManagerUtilityFunction" } } ],
"defaultValues": { "employees": [ ] },
"containerStyles": { "gap": "16px",
"display": "flex",
"flexDirection": "column" } },
{ "key": "remarksMomSection",
"config": [ { "key": "mom",
"name": "mom",
"type": "textarea",
"label": "MOM",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } },
{ "key": "remarks",
"name": "remarks",
"type": "textarea",
"label": "Remarks",
"rules": { "validate": "#(value) => { return (value.length <= 1000 || \"Remarks should not exceed 1000 characters.\")}" },
"gridColumn": 9,
"componentProps": { "rows": 3,
"fullWidth": true,
"multiline": true } } ],
"defaultValues": { "mom": null,
"remarks": null } },
{ "key": "documents",
"title": "Document upload",
"config": [ { "key": "documentTypeLid",
"name": "documentTypeLid",
"type": "select",
"label": "Document type",
"gridColumn": 5,
"componentProps": { "fullWidth": true },
"apiDependencies": { "endPoint": "#endPoints.lookUpByName(\"DOCUMENT_TYPE\")" } },
{ "key": "documentId",
"name": "documentId",
"type": "file",
"label": "File upload",
"gridColumn": 5,
"componentProps": { "fullWidth": true,
"customVariant": "primary" },
"apiDependencies": { "endPoint": "#endPoints.fileUploadByCompanyId(companyId)" } } ],
"isMultiple": true,
"defaultValues": [ { "documentId": null,
"documentTypeLid": null } ] } ]'
where
    ref_activity_id = 15;