import { Module } from "@nestjs/common";
import { JwtModule } from "@nestjs/jwt";
import { TypeOrmModule } from "@nestjs/typeorm";
import { EntityService } from "../../../../../../libs/service-lib/src/lib/utils/entity-service.utils";
import { NotificationUtils } from "../../../../service-lib/src/lib/utils/notification.utils";
import { AuthGuard } from "../../../../auth-service/src/guards/auth.guard"; // Import AuthGuard here
import { RolesGuard } from "../../../../auth-service/src/guards/role.guard"; // Import RolesGuard here
import { AddressModule } from "../../../../org-service/src/app/address/address.module";
import { LookUpModule } from "../../../../org-service/src/app/look-up/look-up.module";
import { EmployeeModule } from "../../../../org-service/src/app/employee/employee.module";
import { CompanyModule } from "../../../../org-service/src/app/company/comapny.module";
import { InsuranceWellnessHubServiceLibModule } from "../../../../service-lib/src/lib/service-lib.module";
import {
  Company,
  CompanyContactMap,
  CompanyAddress,
  ContactCommunicationDetails,
  OpportunityDataValidation,
  OpportunityKdmMeeting,
  LookUp,
  Meeting,
  MstrActivity,
  MstrCoverSection,
  Opportunity,
  OpportunityActivityMap,
  OpportunityActivityParticipants,
  OpportunityBrokingSlipActivityDocumentMap,
  OpportunityChallenges,
  OpportunityClaimExperiences,
  OpportunityCompetitors,
  OpportunityContactMap,
  OpportunityCoverMap,
  OpportunityDocuments,
  OpportunityFinalNegotiation,
  OpportunityFinalNegotiationQcrVariation,
  OpportunityFinalNegotiationQuoteCoverDetail,
  OpportunityFinalNegotiationQuoteDocuments,
  OpportunityFinalNegotiationServiceLevelAgreement,
  OpportunityFinalNegotiationSharingDetail,
  OpportunityHandOverMeet,
  OpportunityMandateDetailsContactMap,
  OpportunityMandateDetailsDocumentMap,
  OpportunityMandateDetailsEntry,
  OpportunityPlacementSlipCDDetail,
  OpportunityPlacementSlipCoverDetail,
  OpportunityPlacementSlipGeneration,
  OpportunityPlacementSlipInstallementDetail,
  OpportunityPlacementSlipInsurerMap,
  OpportunityPlacementSlipSharingDetail,
  OpportunityPlacementSlipTpaMap,
  OpportunityQuote,
  OpportunityQuoteCoverDetail,
  OpportunityQuoteDocumentMap,
  OpportunityQuoteEntry,
  OpportunityQuoteEntryDocumentMap,
  OpportunityQuoteTaxMap,
  OpportunityRfpActivityDocumentMap,
  OpportunityRfpClientContactDetail,
  OpportunityRfpClientContactInfluencers,
  OpportunityRfpCoverDetail,
  OpportunityRfpCreditSharing,
  OpportunityRfpDetail,
  OpportunityRfpDetailsEntry,
  OpportunityRfpDetailsEntryDocumentMap,
  OpportunityRfpInsurerDetail,
  OpportunityRfpTpaDetail,
  OpportunityRiskLocations,
  OpportunityHeldCoverNoteInstallments,
  OpportunityPolicyConfirmationInstallments,
  OpportunityPolicyHardCopyInstallments,
  Task,
  User,
  City,
  Address,
  Contact,
  Tpa,
  Insurer,
  MstrStage,
  Policy,
  PolicyCoverMap,
  PolicyRiskLocationMap,
  BusinessTarget,
  PerformanceOutput,
  CautionDeposit,
  PolicyTypeSegregation,
  PolicyAssetEndorsement,
  Endorsement,
} from "../../../../service-lib/src/lib/entities";
import { OpportunityPlacementSlipInstallments } from "../../../../service-lib/src/lib/entities/opportunity-placement-slip-installments.entity";
import { LookUpValidationService } from "../../../../service-lib/src/lib/utils/lookup-validation";
import { MeetingModule } from "../meeting/meeting.module";
import { PolicyInstallments } from ".././../../../service-lib/src/lib/entities/policy-installments.entity";
import { ScopeService } from "../../../../../../libs/service-lib/src/lib/utils/scope.utils";
import { TaskModule } from "../task/task.module";
import { OpportunityController } from "./opportunity.controller";
import { OpportunityRepository } from "./opportunity.repository";
import { OpportunityService } from "./opportunity.service";
import { PolicyModule } from "../../../../policy-service/src/app/policy/policy.module";
import { ENV } from "../../../../service-lib/src/lib/environment";
import { CrmRecipientResolverService } from "../../../../service-lib/src/lib/crm-recipient-resolver.service";
@Module({
  imports: [
    TypeOrmModule.forFeature([
      Opportunity,
      OpportunityRiskLocations,
      OpportunityDocuments,
      OpportunityCompetitors,
      OpportunityClaimExperiences,
      OpportunityChallenges,
      OpportunityActivityMap,
      OpportunityActivityParticipants,
      LookUp,
      User,
      Policy,
      PolicyCoverMap,
      PolicyInstallments,
      PolicyRiskLocationMap,
      OpportunityDataValidation,
      Meeting,
      OpportunityKdmMeeting,
      OpportunityHandOverMeet,
      MstrActivity,
      MstrCoverSection,
      MstrStage,
      OpportunityMandateDetailsDocumentMap,
      OpportunityMandateDetailsEntry,
      OpportunityMandateDetailsContactMap,
      OpportunityRfpCoverDetail,
      OpportunityCoverMap,
      OpportunityRfpDetail,
      OpportunityRfpActivityDocumentMap,
      Task,
      OpportunityQuoteEntry,
      OpportunityQuoteEntryDocumentMap,
      OpportunityRfpDetailsEntry,
      OpportunityRfpTpaDetail,
      OpportunityRfpInsurerDetail,
      OpportunityRfpCreditSharing,
      OpportunityRfpClientContactDetail,
      OpportunityRfpClientContactInfluencers,
      OpportunityRfpDetailsEntryDocumentMap,
      OpportunityFinalNegotiation,
      OpportunityFinalNegotiationSharingDetail,
      OpportunityFinalNegotiationQcrVariation,
      OpportunityFinalNegotiationServiceLevelAgreement,
      OpportunityFinalNegotiationQuoteDocuments,
      OpportunityFinalNegotiationQuoteCoverDetail,
      OpportunityPlacementSlipGeneration,
      OpportunityPlacementSlipTpaMap,
      OpportunityPlacementSlipInsurerMap,
      OpportunityPlacementSlipSharingDetail,
      OpportunityPlacementSlipCDDetail,
      OpportunityPlacementSlipCoverDetail,
      OpportunityPlacementSlipInstallments,
      OpportunityHeldCoverNoteInstallments,
      OpportunityPolicyConfirmationInstallments,
      OpportunityPolicyHardCopyInstallments,
      OpportunityQuoteCoverDetail,
      OpportunityQuoteTaxMap,
      OpportunityQuoteDocumentMap,
      OpportunityQuote,
      OpportunityBrokingSlipActivityDocumentMap,
      OpportunityContactMap,
      OpportunityPlacementSlipInstallementDetail,
      OpportunityPlacementSlipInstallments,
      Company,
      CompanyContactMap,
      CompanyAddress,
      City,
      Address,
      Contact,
      ContactCommunicationDetails,
      Tpa,
      Insurer,
      BusinessTarget,
      PerformanceOutput,
      CautionDeposit,
      PolicyTypeSegregation,
      Endorsement,
      PolicyAssetEndorsement,
    ]),
    PolicyModule,
    AddressModule,
    JwtModule,
    LookUpModule,
    EmployeeModule,
    CompanyModule,
    TaskModule,
    MeetingModule,
    InsuranceWellnessHubServiceLibModule,
    JwtModule.register({ secret: ENV.JWT_SECRET }),
  ],
  providers: [
    OpportunityService,
    OpportunityRepository,
    AuthGuard,
    RolesGuard,
    EntityService,
    NotificationUtils,
    LookUpValidationService,
    ScopeService,
    CrmRecipientResolverService
  ],
  controllers: [OpportunityController],
  exports: [OpportunityService, OpportunityRepository],
})
export class OpportunityModule {}
