// Generated by Copilot
import { Box, Typography } from "@mui/material";
import { PolicyCard } from "./PolicyCard";
import type { Policy } from "../../pages/HRPortalDashboard/types";

const POLICIES: Policy[] = [
  {
    id: "ghi",
    name: "Group Health Insurance",
    policyNo: "GHI-2024-001",
    policyPeriod: "Apr 2024 – Mar 2025",
    enrollmentPeriod: "Mar 2024 – Apr 2024",
    dotColor: "#3b82f6",
    totalLives: 980,
    sumInsured: "₹5L",
    netPremium: "₹42.8L",
    activeClaims: 18,
    enrolledCount: 874,
    totalCount: 980,
    enrollmentPct: 89,
    claimUtilPct: 42,
    additions: 32,
    deletions: 14,
    accentColor: "#3b82f6",
    enrollBarColor: "#10b981",
    claimBarColor: "#f59e0b",
  },
  {
    id: "gpa",
    name: "Group Personal Accident",
    policyNo: "GPA-2024-002",
    policyPeriod: "Apr 2024 – Mar 2025",
    enrollmentPeriod: "Mar 2024 – Apr 2024",
    dotColor: "#10b981",
    totalLives: 960,
    sumInsured: "₹10L",
    netPremium: "₹12.4L",
    activeClaims: 4,
    enrolledCount: 960,
    totalCount: 980,
    enrollmentPct: 98,
    claimUtilPct: 18,
    additions: 20,
    deletions: 8,
    accentColor: "#10b981",
    enrollBarColor: "#10b981",
    claimBarColor: "#10b981",
  },
  {
    id: "gtl",
    name: "Group Term Life",
    policyNo: "GTL-2024-003",
    policyPeriod: "Apr 2024 – Mar 2025",
    enrollmentPeriod: "Mar 2024 – Apr 2024",
    dotColor: "#8b5cf6",
    totalLives: 945,
    sumInsured: "₹50L",
    netPremium: "₹18.9L",
    activeClaims: 1,
    enrolledCount: 945,
    totalCount: 980,
    enrollmentPct: 96,
    claimUtilPct: 5,
    additions: 15,
    deletions: 5,
    accentColor: "#8b5cf6",
    enrollBarColor: "#8b5cf6",
    claimBarColor: "#10b981",
  },
];

interface PolicyOverviewProps {
  onViewPolicy: (policy: Policy) => void;
}

export function PolicyOverview({ onViewPolicy }: PolicyOverviewProps) {
  return (
    <Box sx={{ mb: 3 }}>
      <Typography
        sx={{
          fontSize: 15,
          fontWeight: 700,
          color: "#111827",
          mb: 2,
          display: "inline-block",
          borderBottom: "2px solid #2563eb",
          pb: 0.5,
        }}
      >
        Policy Overview
      </Typography>
      {POLICIES.map((p) => (
        <PolicyCard key={p.id} policy={p} onViewPolicy={onViewPolicy} />
      ))}
    </Box>
  );
}

export default PolicyOverview;
