// Generated by Copilot
import { Box, Typography, LinearProgress, Tooltip } from "@mui/material";
import {
  ChevronDown,
  Activity,
  ExternalLink,
  Users,
  Shield,
  Wallet,
  FileText,
  UserPlus,
  UserMinus,
} from "lucide-react";
import type { Policy } from "../../pages/HRPortalDashboard/types";
import {
  PolicyCardWrapper,
  PolicyNoBadge,
  MemberActivityBtn,
  ViewPolicyLink,
  CardDivider,
} from "./styles";

interface PolicyCardProps {
  policy: Policy;
  onViewPolicy: (policy: Policy) => void;
}

interface MemberChangesTooltipProps {
  policy: Policy;
  netChange: number;
}

function MemberChangesTooltip({
  policy: p,
  netChange,
}: MemberChangesTooltipProps) {
  return (
    <Box sx={{ p: 0.5 }}>
      <Typography
        sx={{
          fontSize: 10,
          fontWeight: 700,
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          color: "#9ca3af",
          mb: 1,
        }}
      >
        Member Changes
      </Typography>
      <Box sx={{ display: "flex", flexDirection: "column", gap: 1 }}>
        <Box sx={{ display: "flex", justifyContent: "space-between", gap: 3 }}>
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
            <UserPlus size={13} color="#10b981" />
            <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
              Additions
            </Typography>
          </Box>
          <Typography sx={{ fontSize: 11, fontWeight: 700, color: "#10b981" }}>
            +{p.additions}
          </Typography>
        </Box>
        <Box sx={{ display: "flex", justifyContent: "space-between", gap: 3 }}>
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
            <UserMinus size={13} color="#ef4444" />
            <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
              Deletions
            </Typography>
          </Box>
          <Typography sx={{ fontSize: 11, fontWeight: 700, color: "#ef4444" }}>
            −{p.deletions}
          </Typography>
        </Box>
        <Box
          sx={{
            borderTop: "1px solid #374151",
            pt: 0.75,
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
            Net Change
          </Typography>
          <Typography
            sx={{
              fontSize: 11,
              fontWeight: 700,
              color: netChange >= 0 ? "#10b981" : "#ef4444",
            }}
          >
            {netChange >= 0 ? "+" : ""}
            {netChange}
          </Typography>
        </Box>
      </Box>
    </Box>
  );
}

const KPI_DEFS = (p: Policy) => [
  { label: "Total Lives", value: String(p.totalLives), Icon: Users },
  { label: "Sum Insured", value: p.sumInsured, Icon: Shield },
  { label: "Net Premium", value: p.netPremium, Icon: Wallet },
  { label: "Active Claims", value: String(p.activeClaims), Icon: FileText },
];

export function PolicyCard({ policy: p, onViewPolicy }: PolicyCardProps) {
  const _netChange = p.additions - p.deletions;

  return (
    <PolicyCardWrapper>
      {/* ── Header Row ── */}
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          gap: 1.5,
          px: 4,
          pt: 3,
          pb: 2.5,
        }}
      >
        <Box
          sx={{
            width: 10,
            height: 10,
            borderRadius: "50%",
            backgroundColor: p.dotColor,
            flexShrink: 0,
          }}
        />
        <Typography sx={{ fontSize: 13.5, fontWeight: 600, color: "#111827" }}>
          {p.name}
        </Typography>
        <PolicyNoBadge>
          {p.policyNo}
          <ChevronDown size={11} />
        </PolicyNoBadge>

        <Box
          sx={{
            ml: "auto",
            display: "flex",
            alignItems: "center",
            gap: 2,
            flexShrink: 0,
          }}
        >
          <Tooltip
            title={<MemberChangesTooltip policy={p} netChange={_netChange} />}
            arrow
            componentsProps={{
              tooltip: {
                sx: {
                  bgcolor: "#1f2937",
                  "& .MuiTooltip-arrow": { color: "#1f2937" },
                },
              },
            }}
          >
            <MemberActivityBtn>
              <Activity size={13} />
              <Typography sx={{ fontSize: 12, color: "inherit" }}>
                Member Activity
              </Typography>
            </MemberActivityBtn>
          </Tooltip>
          <ViewPolicyLink onClick={() => onViewPolicy(p)}>
            <ExternalLink size={13} />
            <Typography sx={{ fontSize: 12, color: "inherit" }}>
              View policy
            </Typography>
          </ViewPolicyLink>
        </Box>
      </Box>

      <CardDivider />

      {/* ── Body ── */}
      <Box sx={{ display: "flex", alignItems: "stretch", px: 4, py: 3 }}>
        {/* Left: KPI strip + dates */}
        <Box
          sx={{
            flex: 1,
            display: "flex",
            flexDirection: "column",
            gap: 3,
            pr: 4,
          }}
        >
          {/* KPI strip */}
          <Box
            sx={{
              display: "flex",
              alignItems: "stretch",
              "& > *:not(:first-of-type)": { borderLeft: "1px solid #f0f0f0" },
            }}
          >
            {KPI_DEFS(p).map(({ label, value, Icon }, i) => (
              <Box
                key={label}
                sx={{
                  flex: 1,
                  display: "flex",
                  flexDirection: "column",
                  gap: 1,
                  ...(i === 0 ? { pr: 4 } : i === 3 ? { pl: 4 } : { px: 4 }),
                }}
              >
                <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
                  <Icon size={13} color="#9ca3af" />
                  <Typography sx={{ fontSize: 11.5, color: "#9ca3af" }}>
                    {label}
                  </Typography>
                </Box>
                <Typography
                  sx={{ fontSize: 19, fontWeight: 700, color: "#111827" }}
                >
                  {value}
                </Typography>
              </Box>
            ))}
          </Box>

          {/* Dates row */}
          <Box sx={{ display: "flex", gap: 3 }}>
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
              <FileText size={12} color="#9ca3af" />
              <Typography sx={{ fontSize: 11.5, color: "#9ca3af" }}>
                Policy period
              </Typography>
              <Typography
                sx={{ fontSize: 11.5, fontWeight: 600, color: "#374151" }}
              >
                {p.policyPeriod}
              </Typography>
            </Box>
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
              <Users size={12} color="#9ca3af" />
              <Typography sx={{ fontSize: 11.5, color: "#9ca3af" }}>
                Enrolment
              </Typography>
              <Typography
                sx={{ fontSize: 11.5, fontWeight: 600, color: "#374151" }}
              >
                {p.enrollmentPeriod}
              </Typography>
            </Box>
          </Box>
        </Box>

        {/* Right: progress bars */}
        <Box
          sx={{
            width: 240,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            gap: 2,
            borderLeft: "1px solid #f0f0f0",
            pl: 4,
          }}
        >
          {/* Enrollment */}
          <Box>
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-between",
                mb: 0.75,
              }}
            >
              <Typography sx={{ fontSize: 11.5, color: "#6b7280" }}>
                Enrollment
              </Typography>
              <Box sx={{ display: "flex", alignItems: "center", gap: 0.75 }}>
                <Typography sx={{ fontSize: 11.5, color: "#6b7280" }}>
                  {p.enrolledCount} / {p.totalCount}
                </Typography>
                <Typography
                  sx={{ fontSize: 11.5, fontWeight: 700, color: "#10b981" }}
                >
                  {p.enrollmentPct}%
                </Typography>
              </Box>
            </Box>
            <LinearProgress
              variant="determinate"
              value={p.enrollmentPct}
              sx={{
                height: 6,
                borderRadius: 3,
                backgroundColor: "#f0f0f0",
                "& .MuiLinearProgress-bar": {
                  backgroundColor: p.enrollBarColor,
                  borderRadius: 3,
                },
              }}
            />
          </Box>

          {/* Claim Utilisation */}
          <Box>
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-between",
                mb: 0.75,
              }}
            >
              <Typography sx={{ fontSize: 11.5, color: "#6b7280" }}>
                Claim Utilisation
              </Typography>
              <Typography
                sx={{
                  fontSize: 11.5,
                  fontWeight: 700,
                  color: p.claimBarColor,
                }}
              >
                {p.claimUtilPct}%
              </Typography>
            </Box>
            <LinearProgress
              variant="determinate"
              value={p.claimUtilPct}
              sx={{
                height: 6,
                borderRadius: 3,
                backgroundColor: "#f0f0f0",
                "& .MuiLinearProgress-bar": {
                  backgroundColor: p.claimBarColor,
                  borderRadius: 3,
                },
              }}
            />
          </Box>
        </Box>
      </Box>
    </PolicyCardWrapper>
  );
}

export default PolicyCard;
