// Generated by Copilot

import { formatAmountWithCurrency, getCurrencySymbolPrefix, type LocalizationConfig } from "@ui/ui-lib";

// ─── Types ────────────────────────────────────────────────────────────────────
export type HospitalTab = "network" | "claims" | "performance" | "agreements";
export type HStatus = "Active" | "Inactive" | "Under Review";
export type RiskLevel = "Low" | "Medium" | "High";
export type PolicyTypeId = "gmc" | "pa" | "gtl";

export interface ClaimBreak {
  condition: string;
  count: number;
  amount: number;
  avgDays: number;
}

export interface Hospital {
  id: string;
  initials: string;
  name: string;
  city: string;
  state: string;
  type: string;
  specialities: string[];
  cashless: boolean;
  totalClaims: number;
  totalAmount: number;
  avgAmount: number;
  status: HStatus;
  topDisease: string;
  topDepartment: string;
  claimBreakdown: ClaimBreak[];
  approvalRate: number;
  rejectionRate: number;
  avgSettlementDays: number;
  complaintsCount: number;
  riskLevel: RiskLevel;
  agreementStart: string;
  agreementEnd: string;
  contactPerson: string;
  phone: string;
  email: string;
}

// ─── Mock Data ────────────────────────────────────────────────────────────────
export const HOSPITALS: Hospital[] = [
  {
    id: "h1",
    initials: "AH",
    name: "Apollo Hospitals",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Multi-Specialty",
    specialities: ["Cardiology", "Oncology", "Neurology", "Orthopedics"],
    cashless: true,
    totalClaims: 142,
    totalAmount: 2184000,
    avgAmount: 15380,
    status: "Active",
    topDisease: "Cardiac Conditions",
    topDepartment: "Cardiology",
    claimBreakdown: [
      {
        condition: "Cardiac Conditions",
        count: 38,
        amount: 680400,
        avgDays: 4.1,
      },
      {
        condition: "Oncology Treatments",
        count: 29,
        amount: 725000,
        avgDays: 5.2,
      },
      {
        condition: "Orthopedic Surgery",
        count: 24,
        amount: 432000,
        avgDays: 3.8,
      },
      { condition: "Neurological", count: 18, amount: 288000, avgDays: 4.4 },
      { condition: "Others", count: 33, amount: 358600, avgDays: 3.9 },
    ],
    approvalRate: 94,
    rejectionRate: 6,
    avgSettlementDays: 4.2,
    complaintsCount: 3,
    riskLevel: "Low",
    agreementStart: "01 Apr 2024",
    agreementEnd: "31 Mar 2027",
    contactPerson: "Dr. Sundar Raj",
    phone: "+91 98400 12345",
    email: "network@apollohospitals.com",
  },
  {
    id: "h2",
    initials: "FH",
    name: "Fortis Hospital",
    city: "Delhi",
    state: "Delhi",
    type: "Multi-Specialty",
    specialities: ["Orthopedics", "Cardiology", "Nephrology", "Transplants"],
    cashless: true,
    totalClaims: 98,
    totalAmount: 1456000,
    avgAmount: 14857,
    status: "Active",
    topDisease: "Orthopedic Conditions",
    topDepartment: "Orthopedics",
    claimBreakdown: [
      {
        condition: "Orthopedic Surgery",
        count: 42,
        amount: 672000,
        avgDays: 4.8,
      },
      { condition: "Cardiac", count: 28, amount: 476000, avgDays: 5.4 },
      { condition: "Nephrology", count: 14, amount: 224000, avgDays: 5.8 },
      { condition: "Maternity", count: 8, amount: 96000, avgDays: 4.2 },
      { condition: "Others", count: 6, amount: 88000, avgDays: 5.1 },
    ],
    approvalRate: 91,
    rejectionRate: 9,
    avgSettlementDays: 5.1,
    complaintsCount: 5,
    riskLevel: "Low",
    agreementStart: "01 Apr 2023",
    agreementEnd: "31 Mar 2026",
    contactPerson: "Ms. Priya Nair",
    phone: "+91 98110 22334",
    email: "tpa@fortishealthcare.com",
  },
  {
    id: "h3",
    initials: "KH",
    name: "KIMS Hospitals",
    city: "Hyderabad",
    state: "Telangana",
    type: "Multi-Specialty",
    specialities: ["Neurology", "Gastroenterology", "Oncology", "Nephrology"],
    cashless: true,
    totalClaims: 87,
    totalAmount: 1324000,
    avgAmount: 15218,
    status: "Active",
    topDisease: "Neurological Disorders",
    topDepartment: "Neurology",
    claimBreakdown: [
      { condition: "Neurological", count: 32, amount: 512000, avgDays: 5.8 },
      {
        condition: "Gastroenterology",
        count: 22,
        amount: 352000,
        avgDays: 4.4,
      },
      { condition: "Oncology", count: 18, amount: 324000, avgDays: 6.2 },
      { condition: "Nephrology", count: 10, amount: 100000, avgDays: 5.6 },
      { condition: "Others", count: 5, amount: 36000, avgDays: 4.8 },
    ],
    approvalRate: 89,
    rejectionRate: 11,
    avgSettlementDays: 5.8,
    complaintsCount: 7,
    riskLevel: "Low",
    agreementStart: "01 Jul 2024",
    agreementEnd: "30 Jun 2027",
    contactPerson: "Dr. Ravi Kumar",
    phone: "+91 93900 33445",
    email: "claims@kimshospital.com",
  },
  {
    id: "h4",
    initials: "MH",
    name: "Manipal Hospital",
    city: "Bangalore",
    state: "Karnataka",
    type: "Multi-Specialty",
    specialities: ["Orthopedics", "Cardiology", "Transplants", "Oncology"],
    cashless: true,
    totalClaims: 76,
    totalAmount: 1180000,
    avgAmount: 15526,
    status: "Active",
    topDisease: "Cardiac Conditions",
    topDepartment: "Cardiology",
    claimBreakdown: [
      { condition: "Cardiac", count: 28, amount: 448000, avgDays: 4.6 },
      { condition: "Orthopedics", count: 22, amount: 396000, avgDays: 3.8 },
      { condition: "Transplants", count: 8, amount: 240000, avgDays: 8.4 },
      { condition: "Oncology", count: 10, amount: 60000, avgDays: 5.2 },
      { condition: "Others", count: 8, amount: 36000, avgDays: 4.2 },
    ],
    approvalRate: 92,
    rejectionRate: 8,
    avgSettlementDays: 4.6,
    complaintsCount: 4,
    riskLevel: "Low",
    agreementStart: "01 Apr 2024",
    agreementEnd: "31 Mar 2027",
    contactPerson: "Ms. Kavitha Rao",
    phone: "+91 97420 44556",
    email: "tpa@manipalhospitals.com",
  },
  {
    id: "h5",
    initials: "MX",
    name: "Max Healthcare",
    city: "Gurugram",
    state: "Haryana",
    type: "Multi-Specialty",
    specialities: ["Orthopedics", "Cardiology", "Oncology", "Neurology"],
    cashless: true,
    totalClaims: 71,
    totalAmount: 1092000,
    avgAmount: 15380,
    status: "Active",
    topDisease: "Orthopedic Conditions",
    topDepartment: "Orthopedics",
    claimBreakdown: [
      { condition: "Orthopedics", count: 30, amount: 480000, avgDays: 6.2 },
      { condition: "Cardiac", count: 20, amount: 360000, avgDays: 6.8 },
      { condition: "Oncology", count: 12, amount: 192000, avgDays: 7.1 },
      { condition: "Others", count: 9, amount: 60000, avgDays: 5.4 },
    ],
    approvalRate: 88,
    rejectionRate: 12,
    avgSettlementDays: 6.2,
    complaintsCount: 8,
    riskLevel: "Medium",
    agreementStart: "01 Oct 2023",
    agreementEnd: "30 Sep 2026",
    contactPerson: "Mr. Anand Mehta",
    phone: "+91 96540 55667",
    email: "hr.claims@maxhealthcare.in",
  },
  {
    id: "h6",
    initials: "NH",
    name: "Narayana Health",
    city: "Bangalore",
    state: "Karnataka",
    type: "Specialty",
    specialities: ["Cardiology", "Nephrology", "Neurology"],
    cashless: true,
    totalClaims: 64,
    totalAmount: 944000,
    avgAmount: 14750,
    status: "Active",
    topDisease: "Cardiac Conditions",
    topDepartment: "Cardiology",
    claimBreakdown: [
      { condition: "Cardiac", count: 36, amount: 576000, avgDays: 5.4 },
      { condition: "Nephrology", count: 16, amount: 256000, avgDays: 5.8 },
      { condition: "Neurology", count: 8, amount: 80000, avgDays: 5.6 },
      { condition: "Others", count: 4, amount: 32000, avgDays: 4.4 },
    ],
    approvalRate: 90,
    rejectionRate: 10,
    avgSettlementDays: 5.4,
    complaintsCount: 6,
    riskLevel: "Low",
    agreementStart: "01 Apr 2024",
    agreementEnd: "31 Mar 2027",
    contactPerson: "Dr. Meera Krishnan",
    phone: "+91 98441 66778",
    email: "network@narayanahealth.org",
  },
  {
    id: "h7",
    initials: "AS",
    name: "Aster Medcity",
    city: "Kochi",
    state: "Kerala",
    type: "Multi-Specialty",
    specialities: [
      "Cardiology",
      "Orthopedics",
      "Gastroenterology",
      "Maternity",
    ],
    cashless: true,
    totalClaims: 58,
    totalAmount: 876000,
    avgAmount: 15103,
    status: "Active",
    topDisease: "Maternity",
    topDepartment: "Obstetrics",
    claimBreakdown: [
      { condition: "Maternity", count: 22, amount: 264000, avgDays: 3.2 },
      { condition: "Cardiac", count: 16, amount: 288000, avgDays: 5.1 },
      { condition: "Orthopedics", count: 12, amount: 192000, avgDays: 4.8 },
      { condition: "Gastroenterology", count: 8, amount: 132000, avgDays: 4.4 },
    ],
    approvalRate: 93,
    rejectionRate: 7,
    avgSettlementDays: 4.8,
    complaintsCount: 2,
    riskLevel: "Low",
    agreementStart: "01 Jul 2024",
    agreementEnd: "30 Jun 2027",
    contactPerson: "Mr. Thomas Varghese",
    phone: "+91 94470 77889",
    email: "claims@astermedcity.in",
  },
  {
    id: "h8",
    initials: "MD",
    name: "Medanta Hospital",
    city: "Gurugram",
    state: "Haryana",
    type: "Multi-Specialty",
    specialities: ["Cardiology", "Neurology", "Orthopedics", "Oncology"],
    cashless: true,
    totalClaims: 52,
    totalAmount: 812000,
    avgAmount: 15615,
    status: "Active",
    topDisease: "Cardiac Conditions",
    topDepartment: "Cardiology",
    claimBreakdown: [
      { condition: "Cardiac", count: 22, amount: 396000, avgDays: 6.8 },
      { condition: "Neurology", count: 14, amount: 252000, avgDays: 7.2 },
      { condition: "Orthopedics", count: 10, amount: 120000, avgDays: 6.4 },
      { condition: "Others", count: 6, amount: 44000, avgDays: 5.8 },
    ],
    approvalRate: 87,
    rejectionRate: 13,
    avgSettlementDays: 6.8,
    complaintsCount: 9,
    riskLevel: "Medium",
    agreementStart: "01 Apr 2023",
    agreementEnd: "31 Mar 2026",
    contactPerson: "Ms. Shalini Grover",
    phone: "+91 90120 88990",
    email: "tpa@medanta.org",
  },
  {
    id: "h9",
    initials: "LH",
    name: "Lilavati Hospital",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Multi-Specialty",
    specialities: ["Cardiology", "Nephrology", "Oncology", "Maternity"],
    cashless: true,
    totalClaims: 44,
    totalAmount: 728000,
    avgAmount: 16545,
    status: "Active",
    topDisease: "Cardiac Conditions",
    topDepartment: "Cardiology",
    claimBreakdown: [
      { condition: "Cardiac", count: 18, amount: 324000, avgDays: 5.2 },
      { condition: "Nephrology", count: 12, amount: 216000, avgDays: 5.6 },
      { condition: "Oncology", count: 8, amount: 144000, avgDays: 6.4 },
      { condition: "Others", count: 6, amount: 44000, avgDays: 4.4 },
    ],
    approvalRate: 90,
    rejectionRate: 10,
    avgSettlementDays: 5.2,
    complaintsCount: 5,
    riskLevel: "Low",
    agreementStart: "01 Apr 2024",
    agreementEnd: "31 Mar 2027",
    contactPerson: "Mr. Ramesh Patel",
    phone: "+91 98200 99001",
    email: "insurance@lilavati.org",
  },
  {
    id: "h10",
    initials: "KK",
    name: "Kokilaben Hospital",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Specialty",
    specialities: ["Oncology", "Neurology", "Orthopedics", "Robotic Surgery"],
    cashless: true,
    totalClaims: 41,
    totalAmount: 684000,
    avgAmount: 16683,
    status: "Active",
    topDisease: "Oncology",
    topDepartment: "Oncology",
    claimBreakdown: [
      { condition: "Oncology", count: 18, amount: 360000, avgDays: 6.2 },
      { condition: "Neurology", count: 12, amount: 204000, avgDays: 5.8 },
      { condition: "Orthopedics", count: 8, amount: 96000, avgDays: 4.8 },
      { condition: "Others", count: 3, amount: 24000, avgDays: 4.4 },
    ],
    approvalRate: 92,
    rejectionRate: 8,
    avgSettlementDays: 4.9,
    complaintsCount: 3,
    riskLevel: "Low",
    agreementStart: "01 Jan 2024",
    agreementEnd: "31 Dec 2026",
    contactPerson: "Dr. Nisha Chopra",
    phone: "+91 98220 00112",
    email: "network@kokilabenhospital.com",
  },
  {
    id: "h11",
    initials: "SP",
    name: "Sparsh Hospital",
    city: "Bangalore",
    state: "Karnataka",
    type: "Specialty",
    specialities: ["Orthopedics", "Spine Surgery", "Rehabilitation"],
    cashless: true,
    totalClaims: 28,
    totalAmount: 392000,
    avgAmount: 14000,
    status: "Active",
    topDisease: "Spine & Orthopedic",
    topDepartment: "Orthopedics",
    claimBreakdown: [
      { condition: "Spine Surgery", count: 12, amount: 192000, avgDays: 7.4 },
      { condition: "Orthopedics", count: 10, amount: 140000, avgDays: 6.8 },
      { condition: "Rehabilitation", count: 6, amount: 60000, avgDays: 8.2 },
    ],
    approvalRate: 86,
    rejectionRate: 14,
    avgSettlementDays: 7.2,
    complaintsCount: 11,
    riskLevel: "Medium",
    agreementStart: "01 Apr 2023",
    agreementEnd: "31 Mar 2026",
    contactPerson: "Mr. Vivek Shetty",
    phone: "+91 97422 11223",
    email: "claims@sparshhospital.com",
  },
  {
    id: "h12",
    initials: "YH",
    name: "Yashoda Hospital",
    city: "Hyderabad",
    state: "Telangana",
    type: "Multi-Specialty",
    specialities: ["Gastroenterology", "Nephrology", "Cardiology", "Oncology"],
    cashless: true,
    totalClaims: 22,
    totalAmount: 344000,
    avgAmount: 15636,
    status: "Under Review",
    topDisease: "Gastroenterological",
    topDepartment: "Gastroenterology",
    claimBreakdown: [
      {
        condition: "Gastroenterology",
        count: 10,
        amount: 160000,
        avgDays: 9.4,
      },
      { condition: "Nephrology", count: 6, amount: 108000, avgDays: 10.2 },
      { condition: "Cardiac", count: 4, amount: 64000, avgDays: 8.8 },
      { condition: "Others", count: 2, amount: 12000, avgDays: 7.6 },
    ],
    approvalRate: 78,
    rejectionRate: 22,
    avgSettlementDays: 9.4,
    complaintsCount: 18,
    riskLevel: "High",
    agreementStart: "01 Apr 2023",
    agreementEnd: "31 Mar 2026",
    contactPerson: "Mr. Suresh Babu",
    phone: "+91 90000 22334",
    email: "tpa@yashodahospitals.com",
  },
];

// ─── Policy Options ───────────────────────────────────────────────────────────
export const POLICY_TYPE_LABELS: Record<
  PolicyTypeId,
  { short: string; label: string; color: string; codes: string[] }
> = {
  gmc: {
    short: "GMC",
    label: "Group Medical Cover",
    color: "#2563eb",
    codes: ["GHI-2025-001", "GHI-2025-002"],
  },
  pa: {
    short: "PA",
    label: "Personal Accident",
    color: "#f59e0b",
    codes: ["PA-2025-001"],
  },
  gtl: {
    short: "GTL",
    label: "Group Term Life",
    color: "#10b981",
    codes: ["GTL-2025-001"],
  },
};

// ─── Speciality colours (for tags) ───────────────────────────────────────────
export const SPEC_COLORS: Record<string, string> = {
  Cardiology: "#3b82f6",
  Oncology: "#8b5cf6",
  Neurology: "#10b981",
  Orthopedics: "#f59e0b",
  Transplants: "#ef4444",
  Gastroenterology: "#06b6d4",
  Nephrology: "#6366f1",
  Maternity: "#f472b6",
  Pediatrics: "#84cc16",
  Rehabilitation: "#fb923c",
  "Robotic Surgery": "#a78bfa",
  "Spine Surgery": "#fb923c",
  "Cardiac Surgery": "#ec4899",
};

// ─── Initials colour map ──────────────────────────────────────────────────────
export const INIT_BG: Record<string, string> = {
  AH: "#dbeafe",
  FH: "#fce7f3",
  KH: "#d1fae5",
  MH: "#fef9c3",
  MX: "#fef9c3",
  NH: "#ede9fe",
  AS: "#d1fae5",
  MD: "#fee2e2",
  LH: "#ffedd5",
  KK: "#ede9fe",
  SP: "#fef3c7",
  YH: "#fee2e2",
};

export const INIT_TEXT: Record<string, string> = {
  AH: "#2563eb",
  FH: "#be185d",
  KH: "#059669",
  MH: "#92400e",
  MX: "#92400e",
  NH: "#6d28d9",
  AS: "#047857",
  MD: "#b91c1c",
  LH: "#c2410c",
  KK: "#6d28d9",
  SP: "#b45309",
  YH: "#b91c1c",
};

// ─── Rank card styles (for top-6 claims cards) ───────────────────────────────
export const RANK_STYLES = [
  { border: "#f59e0b", bg: "#fffbeb", rankBg: "#f59e0b", numColor: "#92400e" },
  { border: "#94a3b8", bg: "#f8fafc", rankBg: "#94a3b8", numColor: "#334155" },
  { border: "#f97316", bg: "#fff7ed", rankBg: "#f97316", numColor: "#9a3412" },
  { border: "#3b82f6", bg: "#eff6ff", rankBg: "#3b82f6", numColor: "#1e40af" },
  { border: "#3b82f6", bg: "#eff6ff", rankBg: "#3b82f6", numColor: "#1e40af" },
  { border: "#3b82f6", bg: "#eff6ff", rankBg: "#3b82f6", numColor: "#1e40af" },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function fmtINR(n: number, localization?: LocalizationConfig): string {
  return `${formatAmountWithCurrency(n, localization)}`;
}

export function fmtL(n: number, localization?: LocalizationConfig): string {
  return `${getCurrencySymbolPrefix(localization)}${(n / 100000).toFixed(2)}L`;
}

export function isExpiringSoon(dateStr: string): boolean {
  const [d, m, y] = dateStr.split(" ");
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const dt = new Date(parseInt(y), months.indexOf(m), parseInt(d));
  const diff = (dt.getTime() - Date.now()) / (1000 * 60 * 60 * 24);
  return diff >= 0 && diff <= 60;
}

export const CITIES = [
  "All Cities",
  ...Array.from(new Set(HOSPITALS.map((h) => h.city))),
];
export const SPECIALTIES = [
  "All Specialties",
  ...Array.from(new Set(HOSPITALS.flatMap((h) => h.specialities))),
];
export const STATUSES = ["All Status", "Active", "Inactive", "Under Review"];
