export const industrySegmentMap: Record<string, string> = {
  PRINTING_AND_PUBLICATION: "Printing and Publication",
  MID_MARKET: "Mid Market",
  FOOD_PRODUCTS_AND_PROCESSING: "Food Products and Processing",
  IT_CONSULTING_AND_SERVICES: "IT Consulting and Services",
  ADVERTISING: "Advertising",
  AGRICULTURE: "Agriculture",
  AUTOMOBILES_AND_AUTO_COMPONENTS: "Automobiles and Auto Components",
  AVIATION: "Aviation",
  BANKING: "Banking",
  BFSI: "BFSI",
  BPO: "BPO",
  CEMENT: "Cement",
  CHEMICALS: "Chemicals",
  CLINICAL: "Clinical",
  COMMUNICATIONS_EQUIPMENT: "Communications Equipment",
  CONSTRUCTION: "Construction",
  EDUCATION: "Education",
  ELECTRONICS: "Electronics",
  ENTERTAINMENT: "Entertainment",
  EXPORTS: "Exports",
  FERTILIZER: "Fertilizer",
  FMCG: "F M C G",
  HEALTH_CARE: "Health Care",
  HEAVY_ENGINEERING: "Heavy Engineering",
  HOSPITALITY: "Hospitality",
  HOTEL: "Hotel",
  HYDRO_POWER: "Hydro Power",
  INSURANCE: "Insurance",
  INSURANCE_COMPANY: "Insurance Company",
  ITES: "ITES",
  IT_HARDWARE: "IT Hardware",
  LEGAL: "Legal",
  LIABILITY: "Liability",
  LIFE: "Life",
  LIGHT_ENGINEERING: "Light Engineering",
  LOGISTICS: "Logistics",
  MARINE: "Marine",
  MINING: "Mining",
  MISCELLANEOUS: "Miscellaneous",
  NONE: "None",
  OTHER_MANUFACTURING: "Other Manufacturing",
  PERSONAL_LINES: "Personal Lines",
  PETROCHEMICAL: "Petrochemical",
  PHARMA: "Pharma",
  PSU: "PSU",
  SERVICE: "Service",
  SHIPPING: "Shipping",
  SOFTWARE: "Software",
  STEEL: "Steel",
  TELECOM: "Telecom",
  TEXTILES: "Textiles",
  TRAVEL: "Travel",
  THERMAL_GAS_POWER: "Thermal or Gas Power",
  OIL_AND_GAS_OFF_SHORE: "Oil and Gas Off shore",
  OIL_AND_GAS_ON_SHORE: "Oil and Gas On shore",
};

export const companyTypeMap: Record<string, string> = {
  "PUBLIC": "Public Limited Company (Ltd / PLC)",
  "PRIVATE": "Private Limited Company (Pvt Ltd)",
  "ONE PERSON COMPANY (OPC)": "One Person Company (OPC)",
  "SOLE PROPRIETORSHIP": "Sole Proprietorship",
  "PARTNERSHIP FIRM": "Partnership Firm",
  "LIMITED LIABILITY PARTNERSHIP (LLP)": "Limited Liability Partnership (LLP)",
  "JOINT VENTURE (JV)": "Joint Venture (JV)",
  "COOPERATIVE SOCIETY": "Cooperative Society",
  "TRUST / FOUNDATION / NGO": "Trust / Foundation / NGO"
};