// Activity Keys
export const ACTIVITY_KEYS = {
  PLACEMENT_SLIP_GENERATION: "placement_slip_generation_activity",
  FINAL_NEGOTIATION: "final_negotiation_activity",
  QUOTE_ENTRY: "quote_entry_activity",
  OPPORTUNITY_LOST: "opportunity_lost_activity",
  HELD_COVER_NOTE: "held_cover_note_activity",
  POLICY_CONFIRMATION: "policy_confirmation_activity",
  POLICY_HARD_COPY: "policy_hard_copy_activity",
} as const;

// Section Keys
export const SECTION_KEYS = {
  FEE_DETAILS: "feeDetails",
  POLICY_DETAILS: "policyDetails",
  SELECT_FINALISED_QUOTE: "selectFinalisedQuote",
  NET_PREMIUM_DETAILS: "netPremiumDetails",
  INSURER_DETAILS: "insurerDetails",
  PREMIUM_RECEIPT_DETAILS: "premiumReceiptDetailsSection",
  PREMIUM_RECEIPT_LEAD_SECTION: "premiumReceiptLeadSection",
  QUOTE_TAX_DETAILS: "quoteTaxDetails",
  COVERS: "covers",
  DEVIATIONS_ADDRESSED_SECTION: "deviationsAddressedSection",
  DEVIATION_SECTION: "deviationSection",
  POLICY_DATA_RECTIFIED_SECTION: "policyDataRectifiedSection",
  POLICY_DATA_WRONG_SECTION: "policyDataWrongSection",
  DOCUMENTS: "documents",
  QUOTE_DOCUMENTS: "quoteDocuments",
  INSURER_PARTICIPANTS: "insurerParticipants",
  TPA_PARTICIPANTS: "tpaParticipants",
} as const;

// Field Names
export const FIELD_NAMES = {
  // Lead/Policy Placement Fields
  POLICY_PLACED_TYPE_LID: "policyPlacedTypeLid",
  LEAD_INSURER_ID: "leadInsurerId",
  IS_LEAD_INSURER_PAY_COMMISSION: "isLeadInsurerPayCommission",
  IS_LEAD_INSURER_PAY_COMMISSION_LID: "isLeadInsurerPayCommissionLid",

  // Premium Fields
  BASIC_PREMIUM: "basicPremium",
  BASIC_BROKERAGE_PERCENTAGE: "basicBrokeragePercentage",
  BASIC_BROKERAGE_AMOUNT: "basicBrokerageAmount",
  TC_BROKERAGE_AMOUNT: "tcBrokerageAmount",
  TOTAL_BROKERAGE_AMOUNT: "totalBrokerageAmount",
  SRCC_AMOUNT: "srccAmount",
  SRCC_PERCENTAGE: "srccPercentage",
  SRCC_BROKERAGE_AMOUNT: "srccBrokerageAmount",
  TERRORISM: "terrorism",
  TERRORISM_BROKERAGE_PERCENTAGE: "terrorismBrokeragePercentage",
  GST_AMOUNT: "gstAmount",
  GST_PERCENTAGE: "gstPercentage",
  TOTAL_GROSS_PREMIUM_INC_TAX: "totalGrossPremiumIncTax",
  GROSS_PREMIUM: "grossPremium",
  FEE: "fee",
  FEE_PERCENTAGE: "feePercentage",
  OTHER: "other",
  OTHER_PERCENTAGE: "otherPercentage",
  ADMIN_CHARGES: "adminCharges",
  ADMIN_CHARGES_PERCENTAGE: "adminChargesPercentage",
  CESS_AMOUNT: "cessAmount",
  CESS_PERCENTAGE: "cessPercentage",
  NET_PREMIUM: "netPremium",
  SUM_INSURED: "sumInsured",
  BROKERAGE_AMOUNT: "brokerageAmount",
  TOTAL_PREMIUM: "totalPremium",
  TOTAL_NET_PREMIUM: "totalNetPremium",
  BROKERAGE_PERCENTAGE: "brokeragePercentage",

  // Insurer Fields
  INSURER_ID: "insurerId",
  INSURER_BRANCH_ID: "insurerBranchId",
  INSURER_CONTACT_ID: "insurerContactId",
  INSURER_LOCATION_ID: "insurerLocationId",
  SHARE_PERCENTAGE: "sharePercentage",
  SHARE_AMOUNT: "shareAmount",
  IS_LEAD_INSURER: "isLeadInsurer",

  // Quote Fields
  FINALIZED_QUOTE_ID: "finalizedQuoteId",
  FINALIZED_VERSION_ID: "finalizedVersionId",

  // Deviation Fields
  PREMIUM: "premium",
  EXCLUSIONS: "exclusions",
  DEVIATIONS_LID: "deviationsLid",
  DEDUCTIBLES: "deductibles",
  COVERAGES: "coverages",

  // Other Fields
  OPPORTUNITY_ACTIVITY_ID: "opportunityActivityId",
  STATUS_LID: "statusLid",
  RET_ARRAY: "retArray",
  DATA: "data",
} as const;

// Opportunity Activity Status Keys
export const OPPORTUNITY_ACTIVITY_STATUS = {
  WORK_IN_PROGRESS: "OPPORTUNITY_ACTIVITY_STATUS_WORK_IN_PROGRESS",
  SUBMITTED: "OPPORTUNITY_ACTIVITY_STATUS_SUBMITTED",
  APPROVED: "OPPORTUNITY_ACTIVITY_STATUS_APPROVED",
  CLOSED: "OPPORTUNITY_ACTIVITY_STATUS_CLOSED",
  OPEN: "OPPORTUNITY_ACTIVITY_STATUS_OPEN",
  REJECTED: "OPPORTUNITY_ACTIVITY_STATUS_REJECTED",
} as const;

// Action Types
export const ACTION_TYPES = {
  APPROVE_ACTIVITY: "APPROVE_ACTIVITY",
  REJECT_ACTIVITY: "REJECT_ACTIVITY",
} as const;

// Role Keys
export const ROLE_KEYS = {
  BD: "BD",
  ISG: "ISG",
} as const;

// Approval Values
export const APPROVAL_VALUES = {
  YES: "Yes",
  yes: "yes",
} as const;

// Lead Section Config Mapping
export const LEAD_SECTION_CONFIG = {
  [ACTIVITY_KEYS.PLACEMENT_SLIP_GENERATION]: {
    sectionKey: SECTION_KEYS.FEE_DETAILS,
    policyPlacedField: FIELD_NAMES.POLICY_PLACED_TYPE_LID,
    leadInsurerField: FIELD_NAMES.LEAD_INSURER_ID,
    leadPaysField: FIELD_NAMES.IS_LEAD_INSURER_PAY_COMMISSION,
  },
  [ACTIVITY_KEYS.FINAL_NEGOTIATION]: {
    sectionKey: SECTION_KEYS.POLICY_DETAILS,
    policyPlacedField: FIELD_NAMES.POLICY_PLACED_TYPE_LID,
    leadInsurerField: FIELD_NAMES.LEAD_INSURER_ID,
    leadPaysField: FIELD_NAMES.IS_LEAD_INSURER_PAY_COMMISSION_LID,
  },
  [ACTIVITY_KEYS.HELD_COVER_NOTE]: {
    sectionKey: SECTION_KEYS.PREMIUM_RECEIPT_LEAD_SECTION,
    policyPlacedField: FIELD_NAMES.POLICY_PLACED_TYPE_LID,
    leadInsurerField: FIELD_NAMES.LEAD_INSURER_ID,
    leadPaysField: FIELD_NAMES.IS_LEAD_INSURER_PAY_COMMISSION,
  },
  [ACTIVITY_KEYS.POLICY_CONFIRMATION]: {
    sectionKey: SECTION_KEYS.POLICY_DATA_RECTIFIED_SECTION,
    policyPlacedField: FIELD_NAMES.POLICY_PLACED_TYPE_LID,
    leadInsurerField: FIELD_NAMES.LEAD_INSURER_ID,
    leadPaysField: FIELD_NAMES.IS_LEAD_INSURER_PAY_COMMISSION,
  },
  [ACTIVITY_KEYS.POLICY_HARD_COPY]: {
    sectionKey: SECTION_KEYS.DEVIATION_SECTION,
    policyPlacedField: FIELD_NAMES.POLICY_PLACED_TYPE_LID,
    leadInsurerField: FIELD_NAMES.LEAD_INSURER_ID,
    leadPaysField: FIELD_NAMES.IS_LEAD_INSURER_PAY_COMMISSION,
  },
} as const;

// Premium Section Prefill Config
export const PREMIUM_SECTION_PREFILL_ALLOWED_FIELDS = {
  [ACTIVITY_KEYS.FINAL_NEGOTIATION]: [
    {
      section: SECTION_KEYS.SELECT_FINALISED_QUOTE,
      allowed: [
        FIELD_NAMES.BASIC_PREMIUM,
        FIELD_NAMES.BASIC_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.BASIC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TOTAL_BROKERAGE_AMOUNT,
        FIELD_NAMES.SRCC_AMOUNT,
        FIELD_NAMES.SRCC_PERCENTAGE,
        FIELD_NAMES.SRCC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TERRORISM,
        FIELD_NAMES.TERRORISM_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.GST_AMOUNT,
        FIELD_NAMES.GST_PERCENTAGE,
        FIELD_NAMES.TOTAL_GROSS_PREMIUM_INC_TAX,
        FIELD_NAMES.GROSS_PREMIUM,
        FIELD_NAMES.FEE,
        FIELD_NAMES.FEE_PERCENTAGE,
        FIELD_NAMES.OTHER,
        FIELD_NAMES.OTHER_PERCENTAGE,
        FIELD_NAMES.ADMIN_CHARGES,
        FIELD_NAMES.ADMIN_CHARGES_PERCENTAGE,
        FIELD_NAMES.CESS_AMOUNT,
        FIELD_NAMES.CESS_PERCENTAGE,
        FIELD_NAMES.NET_PREMIUM,
      ] as const,
    },
  ],
  [ACTIVITY_KEYS.PLACEMENT_SLIP_GENERATION]: [
    {
      section: SECTION_KEYS.POLICY_DETAILS,
      allowed: [
        FIELD_NAMES.SUM_INSURED,
        FIELD_NAMES.BASIC_PREMIUM,
        FIELD_NAMES.BASIC_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.BASIC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TC_BROKERAGE_AMOUNT,
        FIELD_NAMES.SRCC_AMOUNT,
        FIELD_NAMES.SRCC_PERCENTAGE,
        FIELD_NAMES.SRCC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TERRORISM,
        FIELD_NAMES.TERRORISM_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.GST_AMOUNT,
        FIELD_NAMES.GST_PERCENTAGE,
        FIELD_NAMES.TOTAL_GROSS_PREMIUM_INC_TAX,
        FIELD_NAMES.GROSS_PREMIUM,
        FIELD_NAMES.NET_PREMIUM,
        FIELD_NAMES.FEE,
        FIELD_NAMES.FEE_PERCENTAGE,
        FIELD_NAMES.OTHER,
        FIELD_NAMES.OTHER_PERCENTAGE,
        FIELD_NAMES.ADMIN_CHARGES,
        FIELD_NAMES.ADMIN_CHARGES_PERCENTAGE,
        FIELD_NAMES.CESS_AMOUNT,
        FIELD_NAMES.CESS_PERCENTAGE,
        FIELD_NAMES.BROKERAGE_AMOUNT,
      ] as const,
    },
  ],
  [ACTIVITY_KEYS.HELD_COVER_NOTE]: [
    {
      section: SECTION_KEYS.PREMIUM_RECEIPT_DETAILS,
      allowed: [
        FIELD_NAMES.SUM_INSURED,
        FIELD_NAMES.BASIC_PREMIUM,
        FIELD_NAMES.TC_BROKERAGE_AMOUNT,
        FIELD_NAMES.SRCC_AMOUNT,
        FIELD_NAMES.SRCC_PERCENTAGE,
        FIELD_NAMES.SRCC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TERRORISM,
        FIELD_NAMES.TERRORISM_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.GST_AMOUNT,
        FIELD_NAMES.GST_PERCENTAGE,
        FIELD_NAMES.FEE,
        FIELD_NAMES.FEE_PERCENTAGE,
        FIELD_NAMES.OTHER,
        FIELD_NAMES.OTHER_PERCENTAGE,
        FIELD_NAMES.ADMIN_CHARGES,
        FIELD_NAMES.ADMIN_CHARGES_PERCENTAGE,
        FIELD_NAMES.CESS_AMOUNT,
        FIELD_NAMES.CESS_PERCENTAGE,
        FIELD_NAMES.BASIC_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.BASIC_BROKERAGE_AMOUNT,
        FIELD_NAMES.NET_PREMIUM,
        FIELD_NAMES.TOTAL_BROKERAGE_AMOUNT,
        FIELD_NAMES.TOTAL_GROSS_PREMIUM_INC_TAX,
        FIELD_NAMES.GROSS_PREMIUM,
      ] as const,
    },
  ],
  [ACTIVITY_KEYS.POLICY_CONFIRMATION]: [
    {
      section: SECTION_KEYS.POLICY_DATA_RECTIFIED_SECTION,
      allowed: [
        FIELD_NAMES.BASIC_PREMIUM,
        FIELD_NAMES.SUM_INSURED,
        FIELD_NAMES.TC_BROKERAGE_AMOUNT,
        FIELD_NAMES.BASIC_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.BASIC_BROKERAGE_AMOUNT,
        FIELD_NAMES.GST_PERCENTAGE,
        FIELD_NAMES.GST_AMOUNT,
        FIELD_NAMES.FEE,
        FIELD_NAMES.FEE_PERCENTAGE,
        FIELD_NAMES.OTHER,
        FIELD_NAMES.OTHER_PERCENTAGE,
        FIELD_NAMES.NET_PREMIUM,
        FIELD_NAMES.TERRORISM,
        FIELD_NAMES.TERRORISM_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.SRCC_AMOUNT,
        FIELD_NAMES.SRCC_PERCENTAGE,
        FIELD_NAMES.SRCC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TOTAL_GROSS_PREMIUM_INC_TAX,
        FIELD_NAMES.GROSS_PREMIUM,
        FIELD_NAMES.ADMIN_CHARGES,
        FIELD_NAMES.ADMIN_CHARGES_PERCENTAGE,
        FIELD_NAMES.CESS_AMOUNT,
        FIELD_NAMES.CESS_PERCENTAGE,
        FIELD_NAMES.TOTAL_BROKERAGE_AMOUNT,
      ] as const,
    },
  ],
  [ACTIVITY_KEYS.POLICY_HARD_COPY]: [
    {
      section: SECTION_KEYS.DEVIATION_SECTION,
      allowed: [
        FIELD_NAMES.SUM_INSURED,
        FIELD_NAMES.BASIC_PREMIUM,
        FIELD_NAMES.BROKERAGE_PERCENTAGE,
        FIELD_NAMES.BROKERAGE_AMOUNT,
        FIELD_NAMES.GST_PERCENTAGE,
        FIELD_NAMES.GST_AMOUNT,
        FIELD_NAMES.NET_PREMIUM,
        FIELD_NAMES.TOTAL_GROSS_PREMIUM_INC_TAX,
        FIELD_NAMES.TOTAL_BROKERAGE_AMOUNT,
        FIELD_NAMES.FEE,
        FIELD_NAMES.FEE_PERCENTAGE,
        FIELD_NAMES.OTHER,
        FIELD_NAMES.OTHER_PERCENTAGE,
        FIELD_NAMES.ADMIN_CHARGES,
        FIELD_NAMES.ADMIN_CHARGES_PERCENTAGE,
        FIELD_NAMES.CESS_AMOUNT,
        FIELD_NAMES.CESS_PERCENTAGE,
        FIELD_NAMES.TC_BROKERAGE_AMOUNT,
        FIELD_NAMES.TERRORISM,
        FIELD_NAMES.TERRORISM_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.BASIC_BROKERAGE_AMOUNT,
        FIELD_NAMES.BASIC_BROKERAGE_PERCENTAGE,
        FIELD_NAMES.SRCC_AMOUNT,
        FIELD_NAMES.SRCC_PERCENTAGE,
        FIELD_NAMES.SRCC_BROKERAGE_AMOUNT,
        FIELD_NAMES.GROSS_PREMIUM,
      ] as const,
    },
  ],
} as const;

// Deviation Fields to Remove
export const DEVIATION_FIELDS_TO_REMOVE = [
  FIELD_NAMES.PREMIUM,
  FIELD_NAMES.EXCLUSIONS,
  FIELD_NAMES.DEVIATIONS_LID,
  FIELD_NAMES.DEDUCTIBLES,
  FIELD_NAMES.COVERAGES,
  FIELD_NAMES.BROKERAGE_PERCENTAGE,
  FIELD_NAMES.BROKERAGE_AMOUNT,
  FIELD_NAMES.BASIC_PREMIUM,
] as const;

// Final Negotiation Disallowed Fields
export const FINAL_NEGOTIATION_DISALLOWED_FIELDS = {
  [SECTION_KEYS.SELECT_FINALISED_QUOTE]: [
    FIELD_NAMES.TOTAL_PREMIUM,
    FIELD_NAMES.TOTAL_NET_PREMIUM,
  ],
  [SECTION_KEYS.NET_PREMIUM_DETAILS]: [
    FIELD_NAMES.NET_PREMIUM,
    FIELD_NAMES.BASIC_BROKERAGE_PERCENTAGE,
    FIELD_NAMES.BROKERAGE_PERCENTAGE,
  ],
} as const;

// Insurer Details Clear Fields
export const INSURER_DETAILS_CLEAR_FIELDS = [
  FIELD_NAMES.SHARE_PERCENTAGE,
  FIELD_NAMES.SHARE_AMOUNT,
  FIELD_NAMES.BROKERAGE_PERCENTAGE,
  FIELD_NAMES.BROKERAGE_AMOUNT,
  FIELD_NAMES.TERRORISM_BROKERAGE_PERCENTAGE,
  FIELD_NAMES.TC_BROKERAGE_AMOUNT,
  FIELD_NAMES.TOTAL_BROKERAGE_AMOUNT,
] as const;

// Shared Insurer Activities
export const SHARED_INSURER_ACTIVITIES = new Set([
  ACTIVITY_KEYS.PLACEMENT_SLIP_GENERATION,
  ACTIVITY_KEYS.FINAL_NEGOTIATION,
]);

// Brokerage Field Sets
export type BrokerageFieldSet = {
  basicBase: string;
  srccBase: string;
  tcBase: string;
  taxBase?: string | null;
};

export interface IsgHandoverAssignmentProps {
  isgAssignee?: { name?: string } | null;
  isgOwner?: { name?: string } | null;
}