// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";

export const CurrentPlanCard = styled(Box)(({ theme }) => ({
    padding: theme.spacing(2.5),
    backgroundColor: theme.palette.background.tableHeader,
    borderRadius: theme.shape.borderRadii.normal,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    marginBottom: theme.spacing(2.5),
}));

export const PlanGrid = styled(Box)(({ theme }) => ({
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: theme.spacing(1.5),
    marginBottom: theme.spacing(2.5),
}));

export const PlanCard = styled(Box, {
    shouldForwardProp: (p) => p !== "isCurrent" && p !== "isPopular",
})<{ isCurrent?: boolean; isPopular?: boolean }>(({ theme, isCurrent }) => ({
    position: "relative",
    padding: theme.spacing(2.5),
    borderRadius: theme.shape.borderRadii.normal,
    border: `1.5px solid ${isCurrent ? theme.palette.secondary.selected : theme.palette.neutral.tableBorder}`,
    backgroundColor: isCurrent ? theme.palette.background.tabsSelected : theme.palette.background.paper,
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
        borderColor: theme.palette.secondary.selected,
        backgroundColor: theme.palette.background.tabsSelected,
    },
}));

export const PlanBadge = styled(Box, {
    shouldForwardProp: (p) => p !== "variant",
})<{ variant?: "current" | "popular" }>(({ theme, variant }) => ({
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 10px",
    borderRadius: 20,
    fontSize: theme.typography.fontSizes.xxs,
    fontWeight: theme.typography.fontWeights.semiBold,
    backgroundColor: variant === "current"
        ? theme.palette.chips.primary
        : theme.palette.chips.quaternary,
    color: variant === "current"
        ? theme.palette.neutral.green
        : theme.palette.secondary.selected,
    marginBottom: theme.spacing(1),
}));

export const PlanPrice = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xll,
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.palette.neutral.mediumDark,
    lineHeight: 1.2,
}));

export const PlanPriceSub = styled("span")(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.regular,
    color: theme.palette.text.grey,
}));

export const PlanFeatureList = styled(Box)(({ theme }) => ({
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(0.75),
    marginTop: theme.spacing(1.5),
}));

export const PlanFeatureItem = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(0.75),
    fontSize: theme.typography.fontSizes.xs,
    color: theme.palette.text.grey,
}));

export const PaymentCard = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing(2),
    borderRadius: theme.shape.borderRadii.normal,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    backgroundColor: theme.palette.background.paper,
    marginBottom: theme.spacing(2.5),
}));

export const SubSectionLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
    marginBottom: theme.spacing(1.25),
}));

export const BillingBadge = styled(Box)(({ theme }) => ({
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 10px",
    borderRadius: 20,
    fontSize: theme.typography.fontSizes.xxs,
    fontWeight: theme.typography.fontWeights.semiBold,
    backgroundColor: theme.palette.chips.primary,
    color: theme.palette.neutral.green,
}));

export const CancelLink = styled(Box)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    color: theme.palette.text.error,
    cursor: "pointer",
    fontWeight: theme.typography.fontWeights.medium,
    "&:hover": {
        textDecoration: "underline",
    },
}));

export const DrawerInner = styled(Box)(({ theme }) => ({
    width: 520,
    padding: theme.spacing(3),
    display: "flex",
    flexDirection: "column",
    height: "100%",
}));

export const CancelSelect = styled("select")(({ theme }) => ({
    width: "100%",
    padding: "10px 14px",
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xss,
    outline: "none",
    color: theme.palette.neutral.mediumDark,
    backgroundColor: theme.palette.background.paper,
    fontFamily: "inherit",
    cursor: "pointer",
    "&:focus": {
        borderColor: theme.palette.secondary.selected,
    },
}));
