// Generated by Copilot
import { Box, Typography } from "@mui/material";
import { Download } from "lucide-react";
import {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  StatusBadge,
  ActionButton,
} from "./styles";
import type { TopClaimRow } from "../../pages/HRPortalDashboard/types";

const TOP_CLAIMS: TopClaimRow[] = [
  {
    name: "Rajesh Kumar",
    type: "Employee",
    amount: "₹2,84,500",
    hospital: "Apollo Hospital, Mumbai",
  },
  {
    name: "Apollo Hospital, Bangalore",
    type: "Hospital",
    amount: "₹18,40,000",
    hospital: "Bangalore",
  },
  {
    name: "Priya Sharma",
    type: "Employee",
    amount: "₹1,62,000",
    hospital: "Fortis Hospital, Delhi",
  },
  {
    name: "Fortis Hospital, Delhi",
    type: "Hospital",
    amount: "₹14,20,000",
    hospital: "Delhi",
  },
  {
    name: "Amit Patel",
    type: "Employee",
    amount: "₹1,38,500",
    hospital: "Max Hospital, Pune",
  },
];

export function TopClaimsTable() {
  return (
    <SectionCard sx={{ mb: 2.5 }}>
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          mb: 2,
        }}
      >
        <SectionTitle>Top Claims</SectionTitle>
        <ActionButton
          sx={{
            display: "flex",
            alignItems: "center",
            gap: 0.75,
            fontSize: 12,
          }}
        >
          <Download size={13} />
          Export
        </ActionButton>
      </Box>

      <StyledTable>
        <thead>
          <tr>
            <StyledTh>Name</StyledTh>
            <StyledTh>Type</StyledTh>
            <StyledTh>Hospital</StyledTh>
            <StyledTh sx={{ textAlign: "right" }}>Amount</StyledTh>
          </tr>
        </thead>
        <tbody>
          {TOP_CLAIMS.map((row, i) => (
            <tr key={i}>
              <StyledTd sx={{ fontWeight: 500, color: "#111827" }}>
                {row.name}
              </StyledTd>
              <StyledTd>
                <StatusBadge
                  sx={{
                    backgroundColor:
                      row.type === "Employee" ? "#eff6ff" : "#f5f3ff",
                    color: row.type === "Employee" ? "#2563eb" : "#7c3aed",
                  }}
                >
                  {row.type === "Employee" ? "Active" : "Processing"}
                </StatusBadge>
              </StyledTd>
              <StyledTd sx={{ color: "#6b7280" }}>{row.hospital}</StyledTd>
              <StyledTd
                sx={{ textAlign: "right", fontWeight: 600, color: "#111827" }}
              >
                {row.amount}
              </StyledTd>
            </tr>
          ))}
        </tbody>
      </StyledTable>

      <Typography
        sx={{
          fontSize: 12,
          color: "#2563eb",
          cursor: "pointer",
          mt: 1.5,
          textAlign: "center",
          "&:hover": { textDecoration: "underline" },
        }}
      >
        View all claims →
      </Typography>
    </SectionCard>
  );
}

export default TopClaimsTable;
