// Generated by Copilot
// Re-exports table styled components from the central design tokens.
export {
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  StatusBadge,
  ActionButton,
} from "../../pages/HRPortal/styles";
