import hospitalIconSvg from "../assets/svgs/hospital-icon.svg";
import registerClaimIconSvg from "../assets/svgs/claim-track-icon.svg";
import tpaCardsSvg from "../assets/svgs/tpa-cards-icon.svg";
import ImportantDocumnets from "../assets/svgs/important-documents-icon.svg";
import policyFeatureSvg from "../assets/svgs/policy-features-icon.svg";
import enrollmentStatusSvg from "../assets/svgs/enrollment-status-icon.svg";
import scheduleCallBackSvg from "../assets/svgs/schedule-callback-icon.svg";
import supportrequestSvg from "../assets/svgs/support-request-icon.svg";
import YogaTree from "../../assets/svgs/cards-image.svg";
import EmailIcon from "../../assets/svgs/email-support-icon.svg";
import CallIcon from "../../assets/svgs/call-support-icon.svg";
import { HOSPITAL_EXPORT_TOAST_MESSAGES } from "@ui/ui-lib";
import { backgroundClip } from "html2canvas/dist/types/css/property-descriptors/background-clip";

export const CARDS_DATA = {
  heading: "Explore wellness Benefits",
  cards: [
    {
      TITLE: "Boost Your Wellness",
      SUBTITLE:
        "Unlock premium wellness features and personalised health insights ",
      DESCRIPTION: [
        "Personalised plans",
        "Expert consultations",
        "24/7 support",
      ],
      BUTTON_LABEL: "Enroll now",
      DATE: "24 Apr 2025",
      COLOR: "#8944CF",
      IMAGE: YogaTree,
      TYPE: "expanded",
    },
    {
      TITLE: "Secure Personal Insurance",
      SUBTITLE:
        "Comprehensive protection with competitive rates and instant coverage.",
      DESCRIPTION: [
        "Personalised plans",
        "Expert consultations",
        "24/7 support",
      ],
      BUTTON_LABEL: "Enroll now",
      DATE: "24 Apr 2025",
      COLOR: "#DA3434",
      IMAGE: YogaTree,
      TYPE: "expanded",
    },
    {
      TITLE: "Discounted Benefits",
      SUBTITLE: "Annual health check-up Apollo Hospital",
      DESCRIPTION: [
        "Personalised plans",
        "Expert consultations",
        "24/7 support",
      ],
      BUTTON_LABEL: "Enroll now",
      DATE: "24 Apr 2025",
      COLOR: "#43A0E7",
      IMAGE: YogaTree,
      TYPE: "expanded",
    },
  ],
};
export const CONFIRMATION_ENROLLMENT_MODAL_MESSAGE = {
  TITLE: "Congratulations!  Your Enrolment Has Been Successfully Submitted",
  DESCRIPTION:
    "A confirmation email with all your submitted details will be sent shortly to your registered email ID.",
  BUTTON_TEXT: "Go back to Dashboard",
};

export const DASHBOARD_ACTIONS = [
  { label: "Hospital Network", icon: hospitalIconSvg, path: "/hospital" },
  {
    label: "Claim Intimation & Tracking",
    icon: registerClaimIconSvg,
    path: "/work-in-progress",
  },
  { label: "View TPA cards", icon: tpaCardsSvg, path: "/work-in-progress" },
  {
    label: "My Documents",
    icon: ImportantDocumnets,
    path: "/my-documents",
  },
  {
    label: "Policy Features",
    icon: policyFeatureSvg,
    path: "/policy-features",
  },
  {
    label: "View Enrolment",
    icon: enrollmentStatusSvg,
    path: "/work-in-progress",
  },
  {
    label: "Schedule Callback",
    icon: scheduleCallBackSvg,
    path: "/work-in-progress",
  },
  {
    label: "Support Requests",
    icon: supportrequestSvg,
    path: "/work-in-progress  ",
  },
];

// Function to filter dashboard actions based on Group Mediclaim Policy availability
export const getFilteredDashboardActions = (
  hasGroupMediclaimPolicy: boolean,
  flattenedPolicies?: any[]
) => {
  // Determine the enrollment status path based on flattened policies
  let enrollmentStatusPath = "/work-in-progress";

  if (flattenedPolicies && flattenedPolicies.length > 0) {
    // Check if there's at least one policy that can be viewed (has EDIT_ENROLL or LOCKED status)
    const hasViewablePolicies = flattenedPolicies.some(
      (policy) => policy.status === "editEnroll" || policy.status === "locked"
    );

    if (hasViewablePolicies) {
      enrollmentStatusPath = "/unified-summary";
    } else {
      // If there are policies but none are viewable, navigate to enrollment
      enrollmentStatusPath = "/unified-enrollment";
    }
  }

  // Create a copy of DASHBOARD_ACTIONS with updated enrollment status path
  const updatedActions = DASHBOARD_ACTIONS.map((action) => {
    if (action.label === "View Enrolment") {
      return {
        ...action,
        path: enrollmentStatusPath,
      };
    }
    return action;
  });

  if (hasGroupMediclaimPolicy) {
    return updatedActions;
  }

  // Filter out Hospital Network when no Group Mediclaim Policy
  return updatedActions.filter((action) => action.label !== "Hospital Network");
};
export const ECARD_SUPPORT_TEXT = "Your  E-Card will be available here soon.";
export const ECARD_SUPPORT_LABEL_TEXT =
  "E-Card will appear here once they are generated by TPA. For any urgent assistance, please ";
export const ECARD_SUPPORT_LINK_TEXT = "contact our support team.";
export const FIRST_LETS_ENROLL_INTO_THE_GROUP_MEDICAL_COVER =
  "First let's enroll into the Group medical cover";
export const CANCEL = "Cancel";
export const UNSELECT= "Unselect Plan";
export const CONTINUE = "Continue";
export const CONTINUE_TO_SUMMARY = "Continue to summary";
export const GREAT_NOW_LETS_ADD_YOUR_FAMILY_MEMBERS_YOUD_LIKE_TO_COVER_UNDER_THIS_POLICY =
  "Great! Now let's add your family members you'd like to cover under this policy.";
export const USER_DETAILS_TO_ENROLL_MESSAGE =
  "we would like you to validate your details to enrol into a policy";
export const SELF = "Self";
export const SPOUSE_PARTNERS = "Spouse";
export const SPOUSE_PARTNERS_PAYLOAD = "Spouse/Partner";
export const CHILDREN = "Children";
export const PARENTS = "Parents";
export const SIBBLINGS = "Siblings";
export const SCROLL_TEXT = "Scroll to explore and enroll into the policies";
export const BACK = "Back";
export const DOWNLOAD = "Download";
export const ENROLLMENT_HEADING =
  "Complete your benefit enrolment for the current policy year";
export const DASHBOARD_DATA = {
  OFFER_TEXT: "Your first Wellness offer Enjoy 15% discount",
  BENEFITS_TEXT:
    "Discover a world of benefits and resources designed for your total well-being",
  WELCOME_TEXT: "What would you like to do?",
};
export const ALERT_MESSAGES = {
  GENERIC_ERROR: "Something went wrong. Please try again.",
};
export const PLEASE_WAIT_A_MOMENT_TO_PERSONALISED_PLANS_FOR_YOU_AND_FAMILY_MEMBERS =
  "Please wait a moment! to have personalised plans for you and your family members";
export type NavItem = {
  label: string;
  key: string;
  path: string | string[];
  external?: boolean;
  href?: string;
};

export const NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", key: "dashboard", path: "/" },
  // { label: "Wellness", key: "wellness", path: "" },
  { label: "Claims Corner", key: "claims-corner", path: "/claims-corner" },
  ...(import.meta.env.VITE_FF_CLAIM_INTIMATION_MANAGEMENT === "true"
    ? [{ label: "Claim Submission", key: "claims-intimation", path: "/claims-intimation" }]
    : []),
  { label: "E-card", key: "e-card", path: "/e-card" },
  {
    label: "Quick Links",
    key: "quick-links",
    path: [
      "/hospital",
      "/my-documents",
      "/policy-features",
      "/work-in-progress",
    ],
  },
  { label: "FAQs", key: "faqs", path: "/faqs" },
  { label: "Support", key: "support", path: ["/support", "/customer-care"] },
  {
    label: "Wellness",
    key: "wellness-link",
    path: "",
    external: true,
    // href: "https://www.evexia.in/user/login",
  },
  {
    label: "Policy Porting",
    key: "policy-porting",
    path: "",
    external: true,
    href: "https://www.iirmwellness.co.in",
  },
];

export const SUPPORT_HELP_OPTIONS = [
  {
    id: 1,
    icon: EmailIcon,
    title: "Email Support",
    subtext: "benfits@acmecorp.com",
  },
  {
    id: 2,
    icon: CallIcon,
    title: "Call Support",
    subtext: "18000-123-4567",
  },
];

export const SUPPORT_QUICK_LINKS_DATA = [
  {
    id: 1,
    question: "Policy Document",
    subtitle: "Download your policy document",
    answer:
      "Access and download your complete policy documentation including terms and conditions, coverage details, and benefit summaries.",
  },
  {
    id: 2,
    question: "Claim Forms",
    subtitle: "Download reimbursement forms",
    answer:
      "Download the necessary claim and reimbursement forms. Please fill out the forms completely and submit along with required medical documents.",
  },
  {
    id: 3,
    question: "Hospital Networks",
    subtitle: "Find cashless hospitals near by you",
    answer:
      "Browse our extensive network of cashless hospitals across India. Search by location to find network hospitals near you for hassle-free cashless treatment.",
  },
];

export const SUPPORT_REQUEST_DATA = [
  {
    date: "24/04/2025",

    fields: [
      { label: "Policy Number", value: "GMC-2024-EMP-001234" },
      { label: "Support Type", value: "Ticket" },
      { label: "Email", value: "rajesh123@gmail.com" },
      { label: "Phone", value: "+91 98765 43210" },
      { label: "Topic", value: "Claims" },
    ],
    description:
      "On April 24, 2025, policyholder Rajesh Kumar initiated an escalation regarding a pending claim under policy GMC-2024-EMP-001234. The inquiry concerns a reimbursement request of 25,000 which has exceeded standard processing times, prompting the customer to seek immediate resolution. The support team has flagged this under the Claims topic and will review the submitted medical documents before contacting the user.",
  },
  {
    date: "20/04/2025",
    fields: [
      { label: "Policy Number", value: "GMC-2024-EMP-005678" },
      { label: "Support Type", value: "Schedule Call Back" },
      { label: "Email", value: "priya.sharma@gmail.com" },
      { label: "Phone", value: "+91 99887 76655" },
      { label: "Topic", value: "Policy Coverage" },
      { label: "Requested Data", value: "14 Jan '27" },
      { label: "Schedule Time", value: "12:00 PM - 02:00 PM" },
    ],
    description:
      "Employee Priya Sharma reached out on April 20, 2025, requesting clarification on the coverage details of her group health policy GMC-2024-EMP-005678. She inquired about maternity benefits, pre-existing disease waiting periods, and the process for adding dependents to her policy. The support team will provide a detailed response with policy documentation within 48 hours.",
  },
];

export const HEADER_DETAILS = {
  FAQS: "FAQs",
  HELP: "Help",
  CUSTOMER_CARE: "Customer Care",
};
export const MEDICAL_COVER = {
  HEADER: {
    ENROLL_MESSAGE: (userName: string) =>
      `${userName}, please enroll into the new policies provided by the company`,
    PREFIX: "Enrolment window open for ",
    TITLE: "Group Medical Cover, Personal Accident, Term life",
    SUBTITLE: "Comprehensive health coverage for you and your family",
  },
  POLICY_BENEFITS: [
    {
      id: 1,
      text: "Cashless Treatment at a wide network of empaneled hospitals",
    },
    {
      id: 2,
      text: "Covers Family Members (spouse, children, parents – based on eligibility)",
    },
    {
      id: 3,
      text: "No or Low Premium as it is sponsored or subsidized by your employer",
    },
    {
      id: 4,
      text: "Valid for the Policy Year (renewed annually)",
    },
  ],
  BUTTON: {
    LABEL: "Enroll Now",
    EDIT_LABEL: "Edit enrollment",
    VIEW_LABEL: "View enrollment",
    TEXT: "Closes by 12 Sep 2025",
  },
} as const;
export const SUM_INSURED = "Sum Insured";
export const PREMIUM_PER_FAMILY = "Premium per family";
export const PREMIUM_PER_LIFE = "Premium per Life";
export const TOTAL_PREMIUM = "Total Premium";
export const COMPANY_PAYS = "Company contribution";
export const MY_PAY = "My Pay";
export const DISABLED = "disabled";
export const ACTIVE = "active";
export const HOVERED = "hovered";
export const BALANCE = "Balance";
export const DEPENDENTS = "Dependents";
export const EXPIRES = "Expires";
export const PROVIDED_BY = "Provided by";
export const FREQUENTLY_ASKED_QUESTIONS = "Frequently Asked Questions";
export const VIEW_ENROLLMENT_SUMMARY = "View enrollment summary";
export const MEMBERS_SELECTED = "Members Selected";
export const YOUR_SELECTED_PLANS = "Your Selected Plans";
export const MEMBERS_COVERED = "Members Covered";
export const CONFIRM_ENROLLMENT = "Confirm Enrolment";
export const HOSPITAL_NETWORK = "Hospital Network";
export const CLICKED = "clicked";
export const NO_FAQS_AVAILABLE = "No FAQs available";

// Verify Identity Flow
export const VERIFY_IDENTITY = {
  TITLE: "Enrolment Confirmation Verification",
  DESCRIPTION: "Choose how you want to receive your OTP for verification",
  ALTERNATE_AUTH: "Use another way to authenticate",
  OTP_SENT_MESSAGE: "We've sent a 6-digit OTP to",
  RESEND_OTP: "Resend OTP",
  DIDNT_RECEIVE_OTP: "Didn't receive OTP?",
  VERIFY_OTP: "Verify OTP",
  BACK: "Back",
};

export const VERIFICATION_OPTIONS = {
  MOBILE: {
    ID: 1,
    TITLE: "Mobile Number",
    METHOD: "mobile" as const,
  },
  EMAIL: {
    ID: 2,
    TITLE: "Email Id",
    METHOD: "email" as const,
  },
  BOTH: {
    ID: 3,
    TITLE: "Both",
    SUBTEXT: "Receive OTP on both channels",
    METHOD: "both" as const,
  },
};

export const getVerificationOptions = ({
  mobileNumber,
  email,
  CallIcon,
  EmailIcon,
  BothIcon,
}: {
  mobileNumber: string;
  email: string;
  CallIcon: string;
  EmailIcon: string;
  BothIcon: string;
}) => [
  {
    id: VERIFICATION_OPTIONS.MOBILE.ID,
    icon: CallIcon,
    title: VERIFICATION_OPTIONS.MOBILE.TITLE,
    subtext: mobileNumber,
    method: VERIFICATION_OPTIONS.MOBILE.METHOD,
    backgroundColor: "#FEF9F5",
  },
  {
    id: VERIFICATION_OPTIONS.EMAIL.ID,
    icon: EmailIcon,
    title: VERIFICATION_OPTIONS.EMAIL.TITLE,
    subtext: email,
    method: VERIFICATION_OPTIONS.EMAIL.METHOD,
    backgroundColor: "#F4F8FD",
  },
  {
    id: VERIFICATION_OPTIONS.BOTH.ID,
    icon: BothIcon,
    title: VERIFICATION_OPTIONS.BOTH.TITLE,
    subtext: VERIFICATION_OPTIONS.BOTH.SUBTEXT,
    method: VERIFICATION_OPTIONS.BOTH.METHOD,
    backgroundColor: "#FBF8EA",
  },
];

// Change Password
export const CHANGE_PASSWORD = {
  TITLE: "Change your password",
  CURRENT_PASSWORD_LABEL: "Current Password",
  NEW_PASSWORD_LABEL: "New Password",
  CONFIRM_PASSWORD_LABEL: "Re-enter New Password",
  CURRENT_PASSWORD_PLACEHOLDER: "Enter current password",
  NEW_PASSWORD_PLACEHOLDER: "Enter new password",
  CONFIRM_PASSWORD_PLACEHOLDER: "Re-enter new password",
  VALIDATION_TEXT: "Must have:",
  VALIDATION_REQUIREMENTS:
    "8+ chars • Uppercase • Lowercase • Number • Special char",
  CANCEL_BUTTON: "Cancel",
  UPDATE_BUTTON: "Update Password",
};
export const POLICY_ENROLLMENT_FLOW = {
  BASE_POLICY:
    "Here are the peronalised plans for you. Please select one plan from the ",
  ADD_ON(policyName: string | undefined) {
    return `Would you like to add the ${
      policyName ?? "--"
    } add-on policy to your selection?`;
  },
  PARENTAL_POLICY:
    "We noticed that you would like to cover parents in your coverage, Please select if your interested ",
};
export const PREMIUM = "Total Premium";
export const COMPANY_CONTRIBUTION = "Company contribution";
export const YOUR_CONTRIBUTION = "Your contribution";

export const POLICY_ENROLLMENT_SUCCESS = {
  SUCCESS_TITLE: "You have successfully enrolled into the Group medical cover",
  ENROL_POLICY: "Would you like to enrol into other policies?",
  PERSONAL_ACCIDENT_TITLE: "Group Personal Accident",
  PERSONAL_ACCIDENT_DESCRIPTION:
    "Comprehensive health coverage for you and your family",
  TERM_LIFE_TITLE: "Group Term Life",
  TERM_LIFE_DESCRIPTION: "Life Insurance coverage for financial security",
  ENROLL_LATER: "will enroll later",
  DASHBOARD: "Dashboard",
  NOT_FOUND: "No policies available for enrollment.",
};

export const LOGOUT = "Logout";
export const LOGO_ALT_MESSAGE = "IIRMLOGO";
export const TOAST_DEFAULT_AUTO_HIDE_DURATION = 4000;
export const PAGE_SIZE_OPTIONS = [5, 10, 20];
export const NOT_AVAILABLE = "N/A";
export const NO_DATA_AVAILABLE = "No data available";
export const NO_DATA_FOUND = "No data found";
export const SUBMIT = "Submit";
export const SELECT = "Select";
export const SELECTED = "✔ Selected";
export const RESET = "Reset";
export const EDIT = "Edit";
export const ADD = "Add";
export const UPDATE = "Update";
export const ERROR_MESSAGE = "Error occurred while setting data";
export const SUCCESS_MESSAGE = "Data set successfully";
export const PASSWORD = "password";
export const TEXT = "text";
export const SEARCH = "Search";
export const INVALID_DATE = "Invalid date";
export const NEXT = "Next";
export const PROCEED = "Proceed";
export const SAVE = "Save";
export const DELETE = "Delete";
export const SAVE_EXIT = "Save & Exit";
export const VALIDATION_ERROR_MESSAGE =
  "Please fill all the required fields in the form before proceeding";
export const ENTER_DETAILS = "Enter details";
export const COMPLETED = "completed";
export const LOAD_MORE = "Load more";
export const REMOVE_SECTION_CONFIRMATION_MESSAGE =
  "Are you sure you want to remove this section? This action cannot be undone.";
export const UNAUTHORIZED = "Unauthorized";
export const LOGIN = "Log in";
export const LOGIN_IWH = "Continue to OTP Verification";
export const SEND_OTP = "Send OTP";
export const INSURER_BENEFITS_PORTAL = "Insurance Benefits Portal";
export const TIME_FORMATS = {
  HOUR_MINUTE_SECOND: "HH:mm:ss",
};
export const TIME_TYPES = {
  HOURS: "hours",
  MINUTES: "minutes",
  SECONDS: "seconds",
};
export const DATE_FORMATS = {
  DATE_MONTH_YEAR: "DD/MM/YYYY",
  YEAR_MONTH_DATE: "YYYY-MM-DD",
  YEAR: "YYYY",
  DAY_SHORT_MONTH_YEAR: "DD MMM YYYY",
  SHORT_MONTH_YEAR: "MMM YYYY",
};
export const DATE_FIELD_TYPES = {
  DATE: "date",
  YEAR: "year",
  DATE_TIME: "dateTime",
  TIME: "time",
};
export const RANGE_PICKER_TYPE = {
  DATE_RANGE: "daterange",
  TIME_RANGE: "timerange",
};
export const CHIP_IMAGE = "Chip Image";
export const MEMBERS_ADDED = "Members Added";
export const MY_INSURANCES = "My insurances";
export const ACTIVE_CLAIMS = "Active claims";
export const ACTIVE_POLICIES = "Active policies";

export const POLICY_TYPE_MAPPING = {
  "Group Mediclaim Policy": "Medical Cover",
  "Group Personal Accident Policy": "Personal Accident",
  "Group Term Life Insurance (GTL)": "Term Life",
};

export const POLICY_NAME_MAPPING = {
  GMC: "Group Medical Cover",
  GPA: "Group Personal Accident",
  GTL: "Group Term Life",
};

export const GROUP = "Group";
export const NO_POLICIES_FOUND = "No policies found";

export const DASHBOARD = "Dashboard";
export const RESET_PASSWORD = "Reset password";
export const FORGOT_PASSWORD = "Create password / Forgot password?";
export const ENROLLED = "Enrolled";
export const NOT_ENROLLED = "Not enrolled";
export const SHOW_SUMMARY = "Show summary";
export const ENROLL_NOW = "Enroll now";
export const EXPAND = "Expand";
export const COLLAPSE = "Collapse";
export const SAVE_EXIT_MODAL_MESSAGE =
  "Your progress has been saved as a draft, but the enrollment is still pending. Do you want to continue?";

export const ENROLLMENT_CONFIRMATION = {
  TITLE:
    "Congratulations! Your Enrolment Has Been Successfully Submitted A confirmation email with all your submitted details will be sent shortly to your registered email ID.",
  FEATURES_TITLE:
    "You can continue using this portal to explore a wide range of features",
  FEATURES: [
    {
      id: 1,
      title: "Access personal insurance plans",
    },
    {
      id: 2,
      title: "Avail wellness benefits for family",
    },
    {
      id: 3,
      title: "Track claims & download documents",
    },
    {
      id: 4,
      title: "Check coverage & book services",
    },
  ],
  BUTTON: "Go to Dashboard",
};
export const FAMILY_MEMBERS_MANAGEMENT = "Family Members Management";
export const ADD_DEPENDENT = "Add Dependent";
export const DATE_OF_BIRTH = "Date Of Birth";
export const GENDER = "Gender";
export const POLICY_ITEMS_TITLE = "Choose Your Plan";
export const ADD_POLICY_BUTTON = "Add Policy";
export const DECLARATION_DATA = {
  title: "Disclaimer and Consents",
  points: [
    {
      checked: true,
      content:
        "I confirm that the information provided is accurate and complete. I understand the terms and conditions of the selected plans and agree to the premium deductions from my salary in 3 instaIments, i acknowledge that any false information may result in claim rejection or policy cancellation.",
    },
    {
      checked: true,
      content:
        "I have read and understood the above declaration and agree to the terms and conditions of the selected insurance plans.",
    },
  ],
};

export const STANDARD_DECLARATION_TEXT =
  "I have read and understood the above declaration and agree to the terms and conditions of the selected insurance plans.";

export const AGE_EXTENSION_DIALOGS = {
  STUDYING_SON: {
    TITLE: "Age Extension for Studying Son",
    PRIMARY_MESSAGE:
      "We notice that your son's age exceeds the standard limit. However, we are allowing this under the assumption that your son is currently studying.",
    SECONDARY_MESSAGE:
      "Please note that you may be required to provide proof of your son's educational status during the enrollment verification process.",
  },
  UNMARRIED_DAUGHTER: {
    TITLE: "Age Extension for Unmarried Daughter",
    PRIMARY_MESSAGE:
      "We notice that your daughter's age exceeds the standard limit. However, we are allowing this under the assumption that your daughter is currently unmarried.",
    SECONDARY_MESSAGE:
      "Please note that you may be required to provide proof of your daughter's marital status during the enrollment verification process.",
  },
  ACTIONS: {
    CANCEL: "Cancel",
    CONFIRM: "Confirm",
  },
};

export const BOTTOM_FOOTER = {
  PLANS_SELECTED: "Plan(s) selected",
  MEMBERS_COVER: "Members covered",
  TOTAL_PREMIUM: "Total premium",
  COMPANY_PAYS: "Company contribution",
  YOUR_PAY: "Your contribution",
};

export const TOAST_MESSAGES = {
  PASSWORDS_MISMATCH: "Passwords do not match",
  LOGIN_SUCCESS: "Logged in successfully",
  EMAIL_REQUIREMENT: "Email is required to send reset link",
  EMAIL_SENT_SUCCESS:
    "Password reset email has been successfully sent to the provided email address",
  ERROR: "Error resetting password",
  RESET_SUCCESSFUL: "Password successfully reset please do, login",
  EMAIL_SENT_ERROR: "Error sending reset email",
  IDENTIFIERS_MISSING:
    "Required identifiers missing. Please try enrolling again later.",
  ENROLLMENT_SAVE: "Enrolment progress saved successfully",
  ENROLLMENT_SUBMIT: "Enrolment submitted successfully",
  ENROLLMENT_SAVE_FAIL:
    "Unable to save enrollment without valid employee and policy information.",
};

// Email OTP Scenarios - matches backend service constants
export const EMAIL_OTP_SCENARIOS = {
  LOGIN: "LOGIN",
  TWO_FACTOR_AUTH: "TWO_FACTOR_AUTH",
  ENROLLMENT_VERIFICATION: "ENROLLMENT_VERIFICATION",
} as const;

export type EmailOTPScenario =
  (typeof EMAIL_OTP_SCENARIOS)[keyof typeof EMAIL_OTP_SCENARIOS];

export const SIGNIN = {
  SIGNIN: "Sign in",
  FAQS: "FAQs",
  EMPLOYEE_LOGIN: "Employee Login",
  SIGNIN_TO_YOUR_PORTAL: "Sign in to your portal",
  FORGOT_PASSWORD: "Forgot Password",
  SEND_RESET_LINK: "Send reset link",
  PASSWORD_LINK_SENT: "Password link sent",
  CHECK_INBOX: "Please check your Inbox",
  CHANGE_EMAIL: "Change Email",
  DIDNT_RECEIVE_EMAIL: "Didn't receive the email?",
  CLICK_TO_RESEND: "Click to Resend",
  PASSWORD_RESET: "Password Reset",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  PRIVACY_POLICY: "Privacy Policy",
  REPORT_GRIEVANCE: "Report Grievance",
  BANNER_WELCOME_TITLE: "Welcome to Insurance and Wellness Hub",
  BANNER_WELCOME_SUBTITLE:
    "Complete healthcare coverage for you and your family",
  PASSWORD_RESET_SUCCESS_MESSAGE: "Your Password has been Successfully Reset.",
};

export const HOSPITALNETWORK = {
  BACK_TO_DASHBOARD: "Back to Dashboard",
  HEADING: "Hospital Network",
  NETWORK_HOSPITALS_BUTTON: "Hospital Network",
  EXCLUDED_HOSPITALS_BUTTON: "Excluded Hospitals",
  EXPORT_BUTTON: "Export to Excel",
  SEARCH_HOSPITAL: "Search by Keyword",
  FILTERS: "Filters:",
  SEARCH_PLACEHOLDER: "Search by hospital name or address",
  APPLY_FILLTER_BUTTON: "Search",
  CLEAR_ALL_BUTTON: "Clear",
  TOAST_MESSAGES: HOSPITAL_EXPORT_TOAST_MESSAGES,
};
export const HOSPITAL_CARDS = {
  PREVIOUS_BUTTON: "Previous",
  NEXT_BUTTON: "Next",
  NO_RESULTS: "No hospitals found for selected filters.",
};

export const MY_DOCUMENTS = {
  TITLE: "My Documents",
  SUB_TITLE: "Manage and download your uploaded documents",
};

export const NO_DOCUMENTS_FOUND =
  "Your policy documents will be available here soon.";
export const NO_DOCUMENT_AVAILABLE =
  "There are no documents available at the moment.";
export const DOCUMENTS_WILL_APPEAR_HERE =
  "Policy-related documents will appear here once they are uploaded.";
export const DOCUMENTS_SUPPORT_MESSAGE =
  "For any urgent assistance, please contact our support team.";

// Landing Page Content
export const LANDING_HERO = {
  TITLE: "Your Corporate Insurance Benefits —",
  TITLE_HIGHLIGHT: "Made Simple",
  SUBTITLE: "Access health and protection plans sponsored by your employer. Enrol dependents, explore coverages, and get support when you need it.",
  PRIMARY_BUTTON: "Get Started",
  SECONDARY_BUTTON: "Need Help? Contact Support",
  IMAGE_ALT: "Happy family protected by corporate insurance",
  TRUST_BADGES: [{ label: "Fast" }, { label: "Secure" }, { label: "Insured" }],
  FLOATING_BADGE: {
    TITLE: "IRDAI Compliant",
    SUBTITLE: "Secured & Protected",
  },
  STATS_BADGE: {
    NUMBER: "85K+",
    LABEL: "Lives Covered",
  },
};

export const LANDING_PORTAL_FEATURES = {
  TITLE: "What is the Integrated Benefits Portal?",
  SUBTITLE: [
    { text: 'One unified place to manage your employer-sponsored insurance, tap into holistic ' },
    { text: 'health & wellness programs', bold: true },
    { text: ', and buy ' },
    { text: 'personal retail insurance', bold: true },
    { text: ' — health, motor, term and travel — with end-to-end assistance from our IRDAI-licensed advisors.' },
  ],
  FEATURES: [
    {
      title: "Guided Enrolment",
      description:
        "Simple, step-by-step dependent addition & coverage selection.",
    },
    {
      title: 'View Benefits',
      description: 'See what your employer covers and what you may top-up.',
    },
    {
      title: 'Health & Wellness Access',
      description: 'Preventive check-ups, teleconsults, fitness & mental wellness.',
    },
    {
      title: 'Personal Insurance Assistance',
      description: 'Buy retail health, motor, term & travel cover with advisor help.',
    },
    {
      title: 'Anytime Access',
      description: 'Mobile-friendly access for you and your dependents.',
    },
    {
      title: 'Support at Every Step',
      description: 'Claims, enrolment, and policy guidance from insurance experts.',
    },
  ],
};

export const LANDING_BENEFITS_OVERVIEW = {
  TITLE: "Insurance Benefits Offered by Your Employer",
  SUBTITLE: "Your employer partners with leading insurers and India Insure to provide comprehensive, cost‑effective protection for you and your family.",
  IMAGE_ALT: "Healthcare professional",
  BENEFITS: [
    {
      name: "Health Insurance",
      code: "GHI",
      description: "Cashless hospitalization across network hospitals.",
    },
    {
      name: "Personal Accident",
      code: "GPA",
      description: "Protection against accidental injuries and disability.",
    },
    {
      name: "Term Life",
      code: "GTL",
      description: "Financial security for your family in unforeseen events.",
    },
    {
      name: "Optional Top-Ups",
      code: "+",
      description: "Increase coverage at corporate-negotiated rates.",
    },
    {
      name: "Wellness Services",
      code: "WEL",
      description: "Access preventive care and wellness programs.",
    },
  ],
};

export const LANDING_WELLNESS_SERVICES = {
  BADGE: 'BEYOND INSURANCE',
  TITLE: 'Health & Wellness Services',
  SUBTITLE: 'Stay healthy year-round with curated wellness programs available to you and your family — preventive care, expert consults, mental wellbeing and fitness — all in one place.',
  SERVICES: [
    {
      title: 'Annual Health Check-ups',
      description: 'Free preventive screenings at partner diagnostic centres across country.',
    },
    {
      title: 'Doctor Teleconsultation',
      description: '24/7 access to certified general physicians and specialists, online.',
    },
    {
      title: 'Mental Wellness & EAP',
      description: 'Confidential counseling, therapy and Employee Assistance Programs.',
    },
    {
      title: 'Fitness & Nutrition',
      description: 'Discounted gym partners, personalised diet plans and fitness coaching.',
    },
  ],
  CTA: 'Explore Wellness Programs',
};

export const LANDING_PERSONAL_INSURANCE = {
  BADGE: 'PERSONAL COVER',
  TITLE: 'Personal Insurance — Powered by India Insure',
  SUBTITLE: 'Extend protection beyond what your employer provides. Compare and buy retail insurance products with assistance from our licensed advisors.',
  PRODUCTS: [
    {
      title: 'Personal Health Insurance',
      description: 'Top-up your corporate cover with individual or family floater plans.',
    },
    {
      title: 'Term Life Insurance',
      description: 'High-cover, low-premium protection for your family\'s future.',
    },
    {
      title: 'Motor Insurance',
      description: 'Car & two-wheeler policies with instant quotes from leading insurers.',
    },
    {
      title: 'Travel Insurance',
      description: 'Domestic & international cover for trips, studies and business travel.',
    },
  ],
  CTA_CARD: 'Get a Quote',
  TRUST_BADGES: [
    'IRDAI-licensed broker',
    'Best-price comparison',
    'End-to-end claims support',
  ],
  CTA_ADVISOR: 'Talk to an Advisor',
};

export const LANDING_ENROLLMENT_STEPS = {
  TITLE: "How Enrolment Works",
  SUBTITLE: "Complete your enrolment in 6 simple steps",
  STEPS: [
    {
      number: 1,
      title: "Login to the Portal",
      description: "Access with your employee credentials",
    },
    {
      number: 2,
      title: "Review Your Benefits",
      description: "Explore available coverage options",
    },
    {
      number: 3,
      title: "Add Dependents",
      description: "Include family members in your plan",
    },
    {
      number: 4,
      title: "Select Optional plan",
      description: "Enhance coverage at group rates",
    },
    {
      number: 5,
      title: "Submit Enrolment",
      description: "Confirm your selections",
    },
    {
      number: 6,
      title: 'Receive Confirmation',
      description: 'Get instant enrolment receipt',
    },
  ],
};

export const LANDING_ACTION_BANNERS = {
  BANNERS: [
    {
      id: 'enrol',
      title: 'Ready to Enrol?',
      subtitle: 'Start your enrolment journey in minutes',
      cta: 'Get Started',
      action: '/login',
    },
    {
      id: "support",
      title: "Need Help with Claims or Coverage?",
      subtitle: "Our support team is here to assist you",
      cta: "Contact Support",
      action: "support",
    },
    {
      id: 'learn',
      title: 'Want to Explore Your Benefits?',
      subtitle: 'Learn more about what your employer offers',
      cta: 'Learn More',
      action: '/login',
    },
  ],
};

export const LANDING_BROKER_SECTION = {
  BADGE_TEXT: "Powered by India Insure",
  TITLE: "Your Trusted Benefits Partner",
  DESCRIPTION:
    "India Insure is a leading IRDAI-licensed insurance broker specializing in employee benefits, claims support, and corporate health solutions.",
  IMAGE_ALT: "Professional support team ready to help",
  IMAGE_CAPTION: {
    TITLE: "Expert Support Team",
    SUBTITLE: "Always here to help you",
  },
  METRICS_TITLE: "Our Experience",
  METRICS: [
    { value: "2+", label: "Decades of Experience" },
    { value: "100+", label: "Corporate Clients" },
    { value: "85,000+", label: "Lives Covered" },
  ],
  SUPPORT_TITLE: "How We Support You",
  SUPPORT_CAPABILITIES: [
    { label: "Claims Advisory & Assistance" },
    { label: "Hospital Coordination" },
    { label: "Policy & Coverage Guidance" },
    { label: "Dedicated Employee Helpdesk" },
  ],
  TRUST_TITLE: "Why Trust Us",
  TRUST_ELEMENTS: [
    { label: "IRDAI Licensed Broker" },
    { label: "Data Privacy Compliant" },
    { label: "24/7 Support Access" },
  ],
  FOOTER_TEXT:
    "We help employees understand their benefits and navigate the claims journey with confidence.",
  CTA_BUTTON: "Contact Support",
};

export const LANDING_FOOTER = {
  LOGO_TEXT: "II",
  BRAND_NAME: "India Insure",
  BRAND_SUBTITLE: "Risk Management & Insurance Broking",
  QUICK_LINKS: [
    { label: "Terms & Conditions" },
    { label: "Privacy Policy" },
    { label: "Report Grievance" },
  ],
  REGULATORY_INFO: [
    { text: "Composite Broker IRDAI Licence No. 101", hasDot: true },
    { text: "Valid till 29.01.2027", hasDot: false },
    { text: "CIN No: U67120TG1999PTC031412", hasDot: false },
  ],
  COPYRIGHT:
    "India Insure Risk Management & Insurance Broking Services Pvt. Ltd.",
};
