// Generated by Copilot
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type ThemeMode = "light" | "dark" | "system";

interface ThemeModeContextValue {
    themeMode: ThemeMode;
    setThemeMode: (mode: ThemeMode) => void;
    /** Resolved mode — "light" or "dark" after applying system preference */
    resolvedMode: "light" | "dark";
}

const STORAGE_KEY = "ibp:theme-mode";

const ThemeModeContext = createContext<ThemeModeContextValue>({
    themeMode: "light",
    setThemeMode: () => undefined,
    resolvedMode: "light",
});

function getSystemPreference(): "light" | "dark" {
    return window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
}

export function ThemeModeProvider({ children }: { children: ReactNode }) {
    const [themeMode, setThemeModeState] = useState<ThemeMode>(() => {
        const stored = localStorage.getItem(STORAGE_KEY) as ThemeMode | null;
        return stored ?? "light";
    });

    const [systemPref, setSystemPref] = useState<"light" | "dark">(
        getSystemPreference,
    );

    // Track OS preference changes
    useEffect(() => {
        const mq = window.matchMedia("(prefers-color-scheme: dark)");
        const handler = (e: MediaQueryListEvent) =>
            setSystemPref(e.matches ? "dark" : "light");
        mq.addEventListener("change", handler);
        return () => mq.removeEventListener("change", handler);
    }, []);

    const resolvedMode: "light" | "dark" =
        themeMode === "system" ? systemPref : themeMode;

    function setThemeMode(mode: ThemeMode) {
        setThemeModeState(mode);
        localStorage.setItem(STORAGE_KEY, mode);
    }

    return (
        <ThemeModeContext.Provider value={{ themeMode, setThemeMode, resolvedMode }}>
            {children}
        </ThemeModeContext.Provider>
    );
}

export function useThemeMode() {
    return useContext(ThemeModeContext);
}
