// Generated by Copilot
// Mock data for HRPortalDashboard page.
import {
  Users,
  FileText,
  TrendingUp,
  TriangleAlert,
  AlertCircle,
  Activity,
  UserPlus,
  UserMinus,
  Banknote,
} from "lucide-react";

// ─── Alert Banner ─────────────────────────────────────────────────────────────
export const ALERTS = [
  {
    id: 1,
    type: "warning",
    message: "87 employees pending enrollment",
    action: "Review now →",
    Icon: TriangleAlert,
  },
  {
    id: 2,
    type: "error",
    message: "15 policies expiring soon",
    action: "Renew →",
    Icon: AlertCircle,
  },
  {
    id: 3,
    type: "info",
    message: "Claims up 18% this month",
    action: "View details →",
    Icon: TrendingUp,
  },
  {
    id: 4,
    type: "warning",
    message: "42 docs pending verification",
    action: "Review →",
    Icon: FileText,
  },
];

export const ALERT_COLORS: Record<
  string,
  { bg: string; border: string; icon: string }
> = {
  warning: { bg: "#fffbeb", border: "#fde68a", icon: "#d97706" },
  error: { bg: "#fef2f2", border: "#fecaca", icon: "#dc2626" },
  info: { bg: "#eff6ff", border: "#bfdbfe", icon: "#2563eb" },
};

// ─── KPI Strip ────────────────────────────────────────────────────────────────
export const KPI_ITEMS = [
  {
    label: "Total Employees",
    value: "1,247",
    change: "+5.2%",
    positive: true,
    Icon: Users,
    accent: "#2563eb",
  },
  {
    label: "Active Claims",
    value: "34",
    change: "+21%",
    positive: false,
    Icon: Activity,
    accent: "#ef4444",
  },
  {
    label: "Inception Premium",
    value: "₹1.35 Cr",
    change: "+8.4%",
    positive: true,
    Icon: Banknote,
    accent: "#8b5cf6",
  },
  {
    label: "Addition Premium",
    value: "₹18.6 L",
    change: "+12%",
    positive: true,
    Icon: UserPlus,
    accent: "#10b981",
  },
  {
    label: "Deletion Premium",
    value: "₹4.2 L",
    change: "-3%",
    positive: false,
    Icon: UserMinus,
    accent: "#f59e0b",
  },
];

// ─── Chart Data ───────────────────────────────────────────────────────────────
export const CLAIMS_TREND = [
  { m: "Oct", v: 28 },
  { m: "Nov", v: 35 },
  { m: "Dec", v: 42 },
  { m: "Jan", v: 38 },
  { m: "Feb", v: 51 },
  { m: "Mar", v: 44 },
];

export const ENROLMENT_TREND = [
  { m: "Oct", v: 820 },
  { m: "Nov", v: 855 },
  { m: "Dec", v: 880 },
  { m: "Jan", v: 910 },
  { m: "Feb", v: 950 },
  { m: "Mar", v: 980 },
];

// ─── Top Claims ───────────────────────────────────────────────────────────────
export const TOP_CLAIMS = [
  {
    name: "Rahul Kumar",
    type: "Employee",
    amount: "₹4.85L",
    hospital: "Apollo Hospital",
  },
  {
    name: "Apollo Hospital",
    type: "Hospital",
    amount: "₹4.20L",
    hospital: "Apollo Hospital",
  },
  {
    name: "Priya Sharma",
    type: "Employee",
    amount: "₹3.90L",
    hospital: "Fortis Healthcare",
  },
  {
    name: "Fortis Healthcare",
    type: "Hospital",
    amount: "₹3.50L",
    hospital: "Fortis Healthcare",
  },
  {
    name: "Amit Patel",
    type: "Employee",
    amount: "₹3.15L",
    hospital: "Max Hospital",
  },
];

// ─── Policy Overview ──────────────────────────────────────────────────────────
export interface Policy {
  id: string;
  name: string;
  policyNo: string;
  policyPeriod: string;
  enrollmentPeriod: string;
  dotColor: string;
  totalLives: number;
  sumInsured: string;
  netPremium: string;
  activeClaims: number;
  enrolledCount: number;
  totalCount: number;
  enrollmentPct: number;
  claimUtilPct: number;
  additions: number;
  deletions: number;
  accentColor: string;
  enrollBarColor: string;
  claimBarColor: string;
}

export const POLICIES: Policy[] = [
  {
    id: "ghi",
    name: "Group Health Insurance",
    policyNo: "GHI-2025-001",
    policyPeriod: "01 Jan 2025 – 31 Dec 2025",
    enrollmentPeriod: "01 Jan – 31 Jan 2025",
    dotColor: "#10b981",
    totalLives: 410,
    sumInsured: "₹4.5 Cr",
    netPremium: "₹82.0 L",
    activeClaims: 24,
    enrolledCount: 410,
    totalCount: 465,
    enrollmentPct: 88,
    claimUtilPct: 45,
    additions: 18,
    deletions: 7,
    accentColor: "#10b981",
    enrollBarColor: "#10b981",
    claimBarColor: "#3b82f6",
  },
  {
    id: "gpa",
    name: "Group Personal Accident",
    policyNo: "GPA-2025-002",
    policyPeriod: "01 Jan 2025 – 31 Dec 2025",
    enrollmentPeriod: "01 Jan – 15 Jan 2025",
    dotColor: "#f59e0b",
    totalLives: 380,
    sumInsured: "₹2.0 Cr",
    netPremium: "₹18.5 L",
    activeClaims: 9,
    enrolledCount: 342,
    totalCount: 380,
    enrollmentPct: 90,
    claimUtilPct: 28,
    additions: 12,
    deletions: 3,
    accentColor: "#f59e0b",
    enrollBarColor: "#10b981",
    claimBarColor: "#f59e0b",
  },
  {
    id: "gtl",
    name: "Group Term Life",
    policyNo: "GTL-2025-003",
    policyPeriod: "01 Jan 2025 – 31 Dec 2025",
    enrollmentPeriod: "01 Jan – 20 Jan 2025",
    dotColor: "#8b5cf6",
    totalLives: 395,
    sumInsured: "₹12.0 Cr",
    netPremium: "₹34.2 L",
    activeClaims: 5,
    enrolledCount: 316,
    totalCount: 395,
    enrollmentPct: 80,
    claimUtilPct: 12,
    additions: 9,
    deletions: 11,
    accentColor: "#8b5cf6",
    enrollBarColor: "#10b981",
    claimBarColor: "#8b5cf6",
  },
];

export const TT_STYLE = {
  contentStyle: {
    borderRadius: 8,
    border: "1px solid #e5e7eb",
    fontSize: 12,
    boxShadow: "0 4px 16px rgba(0,0,0,.08)",
    padding: "6px 10px",
  },
};
