// Generated by Copilot
// Mock data for HRPortalFinance (CD Manage) page.
import { Banknote, ArrowDownCircle, Clock, Calendar } from "lucide-react";

export interface Account {
  id: string;
  name: string;
  tagColor: string;
  policyNo: string;
  depositBalance: string;
  pendingClaims: string;
  utilised: string;
  utilPct: number;
  lastUpdated: string;
}

export const ACCOUNTS: Account[] = [
  { id: "GMC", name: "Group Mediclaim Cover",  tagColor: "#2563eb", policyNo: "GHI-2025-001", depositBalance: "₹25.00L", pendingClaims: "₹4,20,500", utilised: "₹18.45L", utilPct: 74, lastUpdated: "15 Feb 2026" },
  { id: "GPA", name: "Group Personal Accident",tagColor: "#f59e0b", policyNo: "GPA-2025-001", depositBalance: "₹14.50L", pendingClaims: "₹1,84,700", utilised: "₹8.96L",  utilPct: 62, lastUpdated: "10 Feb 2026" },
  { id: "GTL", name: "Group Term Life",         tagColor: "#10b981", policyNo: "GTL-2025-001", depositBalance: "₹9.00L",  pendingClaims: "₹79,000",   utilised: "₹3.79L",  utilPct: 42, lastUpdated: "28 Jan 2026" },
];

// ─── Spark Lines ──────────────────────────────────────────────────────────────
export const SPARK_UP   = [5, 8, 6, 10, 9, 14, 12, 16, 18].map((v, i) => ({ i, v }));
export const SPARK_MID  = [8, 6, 10, 8, 12, 10, 14, 13, 16].map((v, i) => ({ i, v }));
export const SPARK_WARN = [4, 6, 5, 8, 7, 9, 8, 10, 9].map((v, i) => ({ i, v }));
export const SPARK_SCH  = [10, 9, 11, 10, 12, 11, 13, 12, 14].map((v, i) => ({ i, v }));

// ─── KPI Card Definitions ─────────────────────────────────────────────────────
export const FINANCE_KPI_ITEMS = [
  {
    label: "Total Deposit Balance", value: "₹48.50L",    change: "+18.0L",    changeSub: "vs last qtr",
    changeColor: "#10b981", Icon: Banknote,        iconBg: "#dbeafe", iconColor: "#2563eb",
    spark: SPARK_UP,   sparkColor: "#3b82f6",
  },
  {
    label: "Utilised Amount",       value: "₹31.20L",    change: "+6.2L",     changeSub: "vs last mth",
    changeColor: "#ef4444", Icon: ArrowDownCircle, iconBg: "#ede9fe", iconColor: "#8b5cf6",
    spark: SPARK_MID,  sparkColor: "#8b5cf6",
  },
  {
    label: "Pending Claims",        value: "₹6.84L",     change: "2 pending", changeSub: "awaiting approval",
    changeColor: "#f59e0b", Icon: Clock,           iconBg: "#fef3c7", iconColor: "#f59e0b",
    spark: SPARK_WARN, sparkColor: "#f59e0b",
  },
  {
    label: "Last Deposit Date",     value: "15 Feb 2026", change: "On schedule", changeSub: "next due in 12d",
    changeColor: "#10b981", Icon: Calendar,        iconBg: "#d1fae5", iconColor: "#10b981",
    spark: SPARK_SCH,  sparkColor: "#10b981",
  },
];
