// Generated by Copilot
// Mock data for HRPortalInsights (Risk Watch) page.
import { Users, FileText, Building2, Shield } from "lucide-react";

export type RiskId = "people" | "claim" | "hospital" | "policy";
export type DetailTab = "claims" | "age" | "relation" | "tenure" | "high-risk";

export interface RiskCard {
  id: RiskId;
  label: string;
  metric: string;
  metricSub: string;
  pct: number;
  level: string;
  color: string;
  levelColor: string;
  trend: string;
  trendUp: boolean;
  Icon: React.ElementType;
}

export const RISK_CARDS: RiskCard[] = [
  {
    id: "people",
    label: "People Risk",
    metric: "438",
    metricSub: "Total Claims",
    pct: 72,
    level: "Medium",
    color: "#3b82f6",
    levelColor: "#f59e0b",
    trend: "+3.2%",
    trendUp: true,
    Icon: Users,
  },
  {
    id: "claim",
    label: "Claim Risk",
    metric: "13.8%",
    metricSub: "Rejection Rate",
    pct: 68,
    level: "Medium",
    color: "#8b5cf6",
    levelColor: "#f59e0b",
    trend: "-1.4%",
    trendUp: false,
    Icon: FileText,
  },
  {
    id: "hospital",
    label: "Hospital Risk",
    metric: "48",
    metricSub: "Partner Hospitals",
    pct: 45,
    level: "Low",
    color: "#10b981",
    levelColor: "#10b981",
    trend: "+2.1%",
    trendUp: true,
    Icon: Building2,
  },
  {
    id: "policy",
    label: "Policy Risk",
    metric: "74.7%",
    metricSub: "Avg Utilisation",
    pct: 81,
    level: "High",
    color: "#f59e0b",
    levelColor: "#ef4444",
    trend: "+5.8%",
    trendUp: true,
    Icon: Shield,
  },
];

export const DETAIL_TABS: { id: DetailTab; label: string }[] = [
  { id: "claims", label: "Claims vs Lives" },
  { id: "age", label: "Age Band" },
  { id: "relation", label: "Relation" },
  { id: "tenure", label: "Tenure" },
  { id: "high-risk", label: "High Risk Employees" },
];

export const CLAIMS_VS_LIVES = [
  { m: "Apr", claims: 28, lives: 1080 },
  { m: "May", claims: 35, lives: 1095 },
  { m: "Jun", claims: 42, lives: 1102 },
  { m: "Jul", claims: 38, lives: 1110 },
  { m: "Aug", claims: 51, lives: 1118 },
  { m: "Sep", claims: 44, lives: 1125 },
  { m: "Oct", claims: 60, lives: 1130 },
  { m: "Nov", claims: 55, lives: 1135 },
  { m: "Dec", claims: 48, lives: 1140 },
  { m: "Jan", claims: 66, lives: 1155 },
  { m: "Feb", claims: 59, lives: 1168 },
  { m: "Mar", claims: 72, lives: 1185 },
];

export const AGE_BAND = [
  { band: "18–30", c: 95 },
  { band: "31–40", c: 142 },
  { band: "41–50", c: 118 },
  { band: "51+", c: 83 },
];

export const RELATION = [
  { rel: "Self", c: 220 },
  { rel: "Spouse", c: 120 },
  { rel: "Child", c: 68 },
  { rel: "Parent", c: 30 },
];

export const TENURE = [
  { t: "0–1 yr", c: 48 },
  { t: "1–3 yr", c: 120 },
  { t: "3–5 yr", c: 142 },
  { t: "5+ yr", c: 128 },
];

export const HIGH_RISK_EMP = [
  {
    id: "EMP003",
    name: "Amit Patel",
    dept: "Engineering",
    claims: 5,
    amount: "₹82,400",
  },
  {
    id: "EMP009",
    name: "Rohit Desai",
    dept: "Operations",
    claims: 4,
    amount: "₹71,200",
  },
  {
    id: "EMP001",
    name: "Rahul Sharma",
    dept: "Sales",
    claims: 4,
    amount: "₹64,800",
  },
  {
    id: "EMP008",
    name: "Kavita Iyer",
    dept: "Finance",
    claims: 3,
    amount: "₹58,500",
  },
  {
    id: "EMP006",
    name: "Deepa Menon",
    dept: "HR",
    claims: 3,
    amount: "₹44,200",
  },
  {
    id: "EMP012",
    name: "Anitha Raj",
    dept: "Sales",
    claims: 2,
    amount: "₹32,100",
  },
];
