// Generated by Copilot
// Shared policy-type constants used across multiple HR portal pages.

export type PolicyTypeId = "gmc" | "pa" | "gtl";

export const POLICY_TYPE_LABELS: Record<
  PolicyTypeId,
  { label: string; short: string; color: string }
> = {
  gmc: { label: "Group Medical Cover", short: "GMC", color: "#2563eb" },
  pa: { label: "Personal Accident", short: "PA", color: "#f59e0b" },
  gtl: { label: "Group Term Life", short: "GTL", color: "#10b981" },
};

export const POLICY_CODES: Record<
  PolicyTypeId,
  {
    code: string;
    name: string;
    si: string;
    employees: number;
    status: string;
  }[]
> = {
  gmc: [
    {
      code: "GHI-2025-001",
      name: "Group Health Plan A",
      si: "₹5 Lakh",
      employees: 486,
      status: "Active",
    },
    {
      code: "GHI-2025-002",
      name: "Group Health Plan B",
      si: "₹3 Lakh",
      employees: 612,
      status: "Active",
    },
    {
      code: "GHI-2025-003",
      name: "Group Health Plan C",
      si: "₹7 Lakh",
      employees: 126,
      status: "Active",
    },
  ],
  pa: [
    {
      code: "PA-2025-001",
      name: "PA Basic Cover",
      si: "₹10 Lakh",
      employees: 892,
      status: "Active",
    },
    {
      code: "PA-2025-002",
      name: "PA Enhanced Cover",
      si: "₹20 Lakh",
      employees: 332,
      status: "Active",
    },
  ],
  gtl: [
    {
      code: "GTL-2025-001",
      name: "GTL Standard",
      si: "₹25 Lakh",
      employees: 748,
      status: "Active",
    },
    {
      code: "GTL-2025-002",
      name: "GTL Enhanced",
      si: "₹50 Lakh",
      employees: 476,
      status: "Active",
    },
    {
      code: "GTL-2024-001",
      name: "GTL Legacy Plan",
      si: "₹15 Lakh",
      employees: 23,
      status: "Inactive",
    },
  ],
};
