// Generated by Copilot
// Mock data for HRPortalReports page.
import {
  Users,
  FileText,
  Mail,
  DollarSign,
  TrendingUp,
  UserCheck,
  LogIn,
  Activity,
  Calendar,
  Database,
} from "lucide-react";

export interface ReportItem {
  id: string;
  name: string;
  description: string;
  date: string;
  stat: string;
  statLabel: string;
  Icon: React.ElementType;
  accent: string;
}

export interface CategoryDef {
  id: string;
  label: string;
  description: string;
  Icon: React.ElementType;
  color: string;
  reports: ReportItem[];
}

export const CATEGORIES: CategoryDef[] = [
  {
    id: "employees",
    label: "Employee Reports",
    description: "Employee data, enrollment, and demographic reports.",
    Icon: Users,
    color: "#3b82f6",
    reports: [
      {
        id: "demography",
        name: "Demography Report",
        description:
          "Age, gender, and city distribution across the enrolled workforce.",
        date: "25 Feb 2026",
        stat: "1,185",
        statLabel: "employees",
        Icon: Activity,
        accent: "#3b82f6",
      },
      {
        id: "enrollment",
        name: "Enrollment Report",
        description:
          "View enrollment status by employee across all active policies.",
        date: "28 Feb 2026",
        stat: "1,185",
        statLabel: "records",
        Icon: UserCheck,
        accent: "#8b5cf6",
      },
      {
        id: "emp-diff",
        name: "Employee Difference Report",
        description:
          "Compare base roster vs endorsement additions and deletions.",
        date: "20 Feb 2026",
        stat: "42",
        statLabel: "changes",
        Icon: TrendingUp,
        accent: "#f59e0b",
      },
      {
        id: "login-cred",
        name: "Login Credential Report",
        description:
          "Employees with missing or unset portal login credentials.",
        date: "01 Mar 2026",
        stat: "22",
        statLabel: "missing",
        Icon: LogIn,
        accent: "#ef4444",
      },
    ],
  },
  {
    id: "claims",
    label: "Claims Reports",
    description: "Claim performance, TAT, and status reports.",
    Icon: FileText,
    color: "#8b5cf6",
    reports: [
      {
        id: "claims-tat",
        name: "Claims TAT Report",
        description: "Turn-around time analysis for claims processing.",
        date: "01 Mar 2026",
        stat: "5.2",
        statLabel: "avg days",
        Icon: Calendar,
        accent: "#8b5cf6",
      },
      {
        id: "claims-status",
        name: "Claim Status Report",
        description: "Status-wise breakdown of all claims across policies.",
        date: "02 Mar 2026",
        stat: "438",
        statLabel: "claims",
        Icon: FileText,
        accent: "#3b82f6",
      },
      {
        id: "claims-hospital",
        name: "Claims by Hospital",
        description: "Hospital-wise claim utilization and approval rates.",
        date: "28 Feb 2026",
        stat: "12",
        statLabel: "hospitals",
        Icon: Database,
        accent: "#10b981",
      },
      {
        id: "claims-rejection",
        name: "Rejection Analysis",
        description: "Analysis of rejected claims with reason codes.",
        date: "25 Feb 2026",
        stat: "13.8%",
        statLabel: "rejection rate",
        Icon: TrendingUp,
        accent: "#ef4444",
      },
    ],
  },
  {
    id: "communication",
    label: "Communication Reports",
    description: "Email and communication tracking reports.",
    Icon: Mail,
    color: "#10b981",
    reports: [
      {
        id: "email-log",
        name: "Email Delivery Log",
        description: "Track email delivery status for all sent communications.",
        date: "01 Mar 2026",
        stat: "2,340",
        statLabel: "emails sent",
        Icon: Mail,
        accent: "#10b981",
      },
      {
        id: "notif-report",
        name: "Notification Report",
        description: "Push and SMS notification delivery summary.",
        date: "27 Feb 2026",
        stat: "1,892",
        statLabel: "delivered",
        Icon: Activity,
        accent: "#3b82f6",
      },
    ],
  },
  {
    id: "finance",
    label: "Finance Reports",
    description: "Premium payments and financial tracking reports.",
    Icon: DollarSign,
    color: "#f59e0b",
    reports: [
      {
        id: "cd-statement",
        name: "CD Account Statement",
        description: "Policy-wise deposit balance and utilization summary.",
        date: "15 Feb 2026",
        stat: "₹48.5L",
        statLabel: "total deposit",
        Icon: DollarSign,
        accent: "#f59e0b",
      },
    ],
  },
];
