// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export {
  KPIGrid,
  KPICard,
  KPILabel,
  KPIValue,
  SectionCard,
  SectionTitle,
  StyledTable,
  StyledTh,
  StyledTd,
  StatusBadge,
  SearchBox,
  ActionButton,
  PrimaryButton,
  TabBar,
  TabItem,
} from "../HRPortal/styles";

export { PolicyTypeChip } from "../HRPortalClaims/styles";

export const EnrollStatusBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "enrollStatus",
})<{ enrollStatus: string }>(({ theme, enrollStatus }) => ({
  display: "inline-flex",
  alignItems: "center",
  padding: `2px ${theme.spacing(1.25)}`,
  borderRadius: 20,
  fontSize: theme.typography.fontSizes.xxs,
  fontWeight: theme.typography.fontWeights.semiBold,
  backgroundColor:
    enrollStatus === "Enrolled"
      ? theme.palette.background.tabsSelected
      : theme.palette.background.tableHeader,
  color:
    enrollStatus === "Enrolled"
      ? theme.palette.neutral.green
      : theme.palette.text.grey,
  whiteSpace: "nowrap",
}));

export const EndorsementTypeBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "addType",
})<{ addType: string }>(({ theme, addType }) => {
  const map: Record<string, string> = {
    Inception: theme.palette.secondary.selected,
    Addition: theme.palette.neutral.green,
    Deletion: theme.palette.text.error,
    Correction: theme.palette.text.yellow,
  };
  const color = map[addType] ?? theme.palette.text.grey;
  return {
    display: "inline-flex",
    alignItems: "center",
    padding: `2px ${theme.spacing(1.25)}`,
    borderRadius: 20,
    fontSize: theme.typography.fontSizes.xxs,
    fontWeight: theme.typography.fontWeights.semiBold,
    backgroundColor: theme.palette.background.tableHeader,
    color,
    whiteSpace: "nowrap",
  };
});
