// Generated by Copilot
import { useState } from "react";
import { Box, Checkbox, Typography } from "@mui/material";
import { CheckSquare } from "lucide-react";
import {
    SectionCard,
    SectionTitle,
    PrimaryButton,
    ActionButton,
} from "../../pages/HRPortal/styles";
import {
    InviteInput,
    InviteFieldLabel,
    PermissionGrid,
    PermissionRow,
    PermissionLabel,
    AllowAllButton,
    EmployeeActionRow,
    SectionDivider,
} from "./styles";

// ─── Types ────────────────────────────────────────────────────────────────────
interface Permission {
    id: string;
    label: string;
    description: string;
}

const PERMISSIONS: Permission[] = [
    { id: "dashboard", label: "Dashboard", description: "View analytics and KPIs" },
    { id: "orders", label: "Orders", description: "Manage orders and transactions" },
    { id: "notifications", label: "Notifications", description: "Send and receive alerts" },
    { id: "messages", label: "Messages", description: "Internal messaging system" },
    { id: "launcher", label: "Launcher", description: "Access app launcher" },
    { id: "publisher", label: "Publisher", description: "Publish content and updates" },
    { id: "published", label: "Published", description: "View published content" },
    { id: "stock", label: "Stock", description: "Manage stock and inventory" },
];

// ─── Component ────────────────────────────────────────────────────────────────
export function SettingsEmployeeTab() {
    const [inviteEmail, setInviteEmail] = useState("");
    const [inviteFullName, setInviteFullName] = useState("");
    const [permissions, setPermissions] = useState<Record<string, boolean>>(
        Object.fromEntries(PERMISSIONS.map((p) => [p.id, false])),
    );

    const allGranted = PERMISSIONS.every((p) => permissions[p.id]);

    function togglePermission(id: string) {
        setPermissions((prev) => ({ ...prev, [id]: !prev[id] }));
    }

    function allowAll() {
        setPermissions(Object.fromEntries(PERMISSIONS.map((p) => [p.id, true])));
    }

    function handleReset() {
        setInviteEmail("");
        setInviteFullName("");
        setPermissions(Object.fromEntries(PERMISSIONS.map((p) => [p.id, false])));
    }

    const canCreate = inviteEmail.trim().length > 0 && inviteFullName.trim().length > 0;

    return (
        <SectionCard sx={{ maxWidth: 680 }}>
            <SectionTitle>Invite Employee</SectionTitle>

            {/* Invite form */}
            <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
                <Box>
                    <InviteFieldLabel>Email address</InviteFieldLabel>
                    <InviteInput
                        type="email"
                        value={inviteEmail}
                        onChange={(e) => setInviteEmail(e.target.value)}
                        placeholder="employee@corp.com"
                    />
                </Box>
                <Box>
                    <InviteFieldLabel>Full name</InviteFieldLabel>
                    <InviteInput
                        value={inviteFullName}
                        onChange={(e) => setInviteFullName(e.target.value)}
                        placeholder="Enter full name"
                    />
                </Box>
            </Box>

            <SectionDivider />

            {/* Access Restrictions */}
            <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 0.5 }}>
                <Typography sx={{ fontSize: 13, fontWeight: 600, color: "#444444" }}>
                    Access Restrictions
                </Typography>
                {!allGranted && (
                    <AllowAllButton onClick={allowAll}>
                        <CheckSquare size={13} />
                        Allow all
                    </AllowAllButton>
                )}
            </Box>
            <Typography sx={{ fontSize: 12, color: "#555555", mb: 0.5 }}>
                Select the modules this employee can access.
            </Typography>

            <PermissionGrid>
                {PERMISSIONS.map((perm) => (
                    <PermissionRow
                        key={perm.id}
                        onClick={() => togglePermission(perm.id)}
                        sx={{
                            borderColor: permissions[perm.id] ? "#338CE5" : undefined,
                            backgroundColor: permissions[perm.id] ? "#F2F6FF" : undefined,
                        }}
                    >
                        <Checkbox
                            checked={permissions[perm.id]}
                            onChange={() => togglePermission(perm.id)}
                            size="small"
                            onClick={(e) => e.stopPropagation()}
                            sx={{
                                p: 0,
                                color: "#EAEAEA",
                                "&.Mui-checked": { color: "#338CE5" },
                            }}
                        />
                        <Box>
                            <PermissionLabel sx={{ fontWeight: permissions[perm.id] ? 600 : 400 }}>
                                {perm.label}
                            </PermissionLabel>
                            <Typography sx={{ fontSize: 11, color: "#555555" }}>
                                {perm.description}
                            </Typography>
                        </Box>
                    </PermissionRow>
                ))}
            </PermissionGrid>

            <EmployeeActionRow>
                <PrimaryButton
                    sx={{
                        cursor: canCreate ? "pointer" : "not-allowed",
                        opacity: canCreate ? 1 : 0.5,
                    }}
                >
                    Create
                </PrimaryButton>
                <ActionButton sx={{ cursor: "pointer" }} onClick={handleReset}>
                    Reset
                </ActionButton>
            </EmployeeActionRow>
        </SectionCard>
    );
}

export default SettingsEmployeeTab;
