// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";

export const InviteInput = styled("input")(({ theme }) => ({
    width: "100%",
    padding: "10px 14px",
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xss,
    outline: "none",
    boxSizing: "border-box",
    color: theme.palette.neutral.mediumDark,
    backgroundColor: theme.palette.background.paper,
    fontFamily: "inherit",
    "&:focus": {
        borderColor: theme.palette.secondary.selected,
    },
}));

export const InviteFieldLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.medium,
    marginBottom: theme.spacing(0.75),
}));

export const PermissionGrid = styled(Box)(({ theme }) => ({
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: theme.spacing(1),
    marginTop: theme.spacing(1.5),
}));

export const PermissionRow = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1.25),
    padding: theme.spacing(1.25, 1.5),
    borderRadius: theme.shape.borderRadii.medium,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    backgroundColor: theme.palette.background.paper,
    cursor: "pointer",
    userSelect: "none" as const,
    "&:hover": {
        backgroundColor: theme.palette.background.tableHeader,
    },
}));

export const PermissionLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    color: theme.palette.neutral.medium,
    flex: 1,
}));

export const AllowAllButton = styled(Box)(({ theme }) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: theme.spacing(0.5),
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.secondary.selected,
    cursor: "pointer",
    "&:hover": {
        textDecoration: "underline",
    },
}));

export const EmployeeActionRow = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(3),
    paddingTop: theme.spacing(2.5),
    borderTop: `1px solid ${theme.palette.neutral.tableBorder}`,
}));

export const SectionDivider = styled(Box)(({ theme }) => ({
    height: 1,
    backgroundColor: theme.palette.neutral.tableBorder,
    margin: theme.spacing(2.5, 0),
}));
