// Generated by Copilot
import React, { useState } from "react";
import { Box } from "@mui/material";
import { Check } from "lucide-react";
import {
    SectionCard,
    SectionTitle,
    PrimaryButton,
    ActionButton,
} from "../../pages/HRPortal/styles";
import {
    FieldLabel,
    FieldHint,
    ProfileInput,
    EmailFieldWrap,
    VerifyButton,
    ProfileActionRow,
} from "./styles";

interface SettingsProfileTabProps {
    initialUsername?: string;
    initialEmail?: string;
}

export function SettingsProfileTab({
    initialUsername = "",
    initialEmail = "",
}: SettingsProfileTabProps) {
    const [username, setUsername] = useState(initialUsername);
    const [email, setEmail] = useState(initialEmail);

    const hasChanged =
        username !== initialUsername || email !== initialEmail;

    function handleCancel() {
        setUsername(initialUsername);
        setEmail(initialEmail);
    }

    return (
        <SectionCard sx={{ maxWidth: 680 }}>
            <SectionTitle>Profile</SectionTitle>

            {/* Username */}
            <Box sx={{ mb: 2.5 }}>
                <FieldLabel>Username</FieldLabel>
                <ProfileInput
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    placeholder="Enter username"
                />
            </Box>

            {/* Email */}
            <Box sx={{ mb: 1 }}>
                <FieldLabel>Email address</FieldLabel>
                <EmailFieldWrap>
                    <ProfileInput
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        placeholder="Enter email"
                        style={{ paddingRight: 80 }}
                    />
                    <VerifyButton>Verify</VerifyButton>
                </EmailFieldWrap>
                <FieldHint>We&apos;ll send you a verification email</FieldHint>
            </Box>

            {/* Actions */}
            <ProfileActionRow>
                <PrimaryButton
                    sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: 0.75,
                        cursor: hasChanged ? "pointer" : "not-allowed",
                        opacity: hasChanged ? 1 : 0.5,
                    }}
                    onClick={hasChanged ? undefined : (e) => e.preventDefault()}
                >
                    <Check size={14} /> Save
                </PrimaryButton>
                <ActionButton
                    sx={{ cursor: "pointer" }}
                    onClick={handleCancel}
                >
                    Cancel
                </ActionButton>
            </ProfileActionRow>
        </SectionCard>
    );
}

export default SettingsProfileTab;
