// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";

export const FieldLabel = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.medium,
    marginBottom: theme.spacing(0.75),
}));

export const FieldHint = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xs,
    color: theme.palette.text.grey,
    marginTop: theme.spacing(0.75),
}));

export const ProfileInput = styled("input")(({ theme }) => ({
    width: "100%",
    padding: "10px 14px",
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xss,
    outline: "none",
    boxSizing: "border-box",
    color: theme.palette.neutral.mediumDark,
    backgroundColor: theme.palette.background.paper,
    fontFamily: "inherit",
    "&:focus": {
        borderColor: theme.palette.secondary.selected,
    },
}));

export const EmailFieldWrap = styled(Box)(() => ({
    position: "relative",
}));

export const VerifyButton = styled(Box)(({ theme }) => ({
    position: "absolute",
    right: 14,
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.secondary.selected,
    cursor: "pointer",
    "&:hover": {
        textDecoration: "underline",
    },
}));

export const ProfileActionRow = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(3),
}));
