export enum LookUpValues {
  CONTACT_TYPE_BUSINESS = "CONTACT_TYPE_BUSINESS",
  POLICY_STATUS_RENEWAL = "POLICY_STATUS_RENEWAL",
  MEETING_TYPE_INTERNAL = "MEETING_TYPE_INTERNAL",
  DOCUMENT_TYPE_OTHER_ACTIVITY = "DOCUMENT_TYPE_OTHER_ACTIVITY",
  TRANSACTION_TYPE_CHEQUE = "TRANSACTION_TYPE_CHEQUE",
  TRANSACTION_TYPE_RTGS = "TRANSACTION_TYPE_RTGS",
  CREDIT_TRANSACTION = "CREDIT_TRANSACTION",
  MARTIAL_STATUS_SINGLE = "MARTIAL_STATUS_SINGLE",
  INSURER_BRANCH_TYPE_HQ = "INSURER_BRANCH_TYPE_HQ",
}
