// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, ListItemButton, Typography } from "@mui/material";

// ─── Avatar rectangle (matches the orange gradient card in the reference) ─────
export const ProfileAvatar = styled(Box)(() => ({
  width: 40,
  height: 44,
  borderRadius: 12,
  background: "linear-gradient(135deg, #fb923c 0%, #ea580c 100%)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexShrink: 0,
  boxShadow: "0 2px 8px rgba(234,88,12,0.35)",
}));

export const ProfileAvatarText = styled(Typography)(() => ({
  fontSize: 15,
  fontWeight: 700,
  color: "#fff",
  letterSpacing: "0.04em",
  lineHeight: 1.2,
}));

// ─── Profile button in sidebar header ────────────────────────────────────────
export const ProfileButton = styled(Box, {
  shouldForwardProp: (p) => p !== "open",
})<{ open?: boolean }>(({ open }) => ({
  display: "flex",
  alignItems: "center",
  gap: 12,
  width: "100%",
  padding: "6px 8px",
  borderRadius: 12,
  cursor: "pointer",
  backgroundColor: open ? "rgba(0,0,0,0.05)" : "transparent",
  transition: "background-color 0.15s",
  "&:hover": {
    backgroundColor: "rgba(0,0,0,0.04)",
  },
}));

// ─── Online status dot ────────────────────────────────────────────────────────
export const OnlineDot = styled(Box)(() => ({
  width: 8,
  height: 8,
  borderRadius: "50%",
  backgroundColor: "#10b981",
  flexShrink: 0,
}));

// ─── Portal switch popup ──────────────────────────────────────────────────────
export const PortalMenuPaper = styled(Box)(() => ({
  backgroundColor: "#ffffff",
  borderBottom: "1px solid #e5e7eb",
  overflow: "hidden",
}));

export const PortalRow = styled(Box, {
  shouldForwardProp: (p) => p !== "active" && p !== "accentColor",
})<{ active?: boolean; accentColor?: string }>(
  ({ active, accentColor = "#2563eb" }) => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 12,
    cursor: "pointer",
    backgroundColor: active ? `${accentColor}10` : "transparent",
    transition: "background-color 0.15s",
    "&:hover": {
      backgroundColor: active ? `${accentColor}14` : "rgba(0,0,0,0.03)",
    },
  }),
);

export const PortalIconCircle = styled(Box, {
  shouldForwardProp: (p) => p !== "active" && p !== "accentColor",
})<{ active?: boolean; accentColor?: string }>(
  ({ active, accentColor = "#2563eb" }) => ({
    width: 40,
    height: 40,
    borderRadius: "50%",
    backgroundColor: active ? `${accentColor}18` : "#f3f4f6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  }),
);

export const ActiveBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "accentColor",
})<{ accentColor?: string }>(({ accentColor = "#2563eb" }) => ({
  padding: "2px 10px",
  borderRadius: 20,
  fontSize: 15,
  fontWeight: 700,
  backgroundColor: `${accentColor}18`,
  color: accentColor,
  flexShrink: 0,
}));

// ─── User footer inside portal menu ──────────────────────────────────────────
export const PortalMenuFooter = styled(Box)(() => ({
  display: "flex",
  alignItems: "center",
  gap: 10,
  padding: "12px 16px",
  borderTop: "1px solid #e5e7eb",
}));

export const MiniAvatar = styled(Box)(() => ({
  width: 36,
  height: 36,
  borderRadius: "50%",
  background: "linear-gradient(135deg, #fb923c 0%, #ea580c 100%)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexShrink: 0,
}));

// ─── Sidebar nav item — thin override for bottom actions ──────────────────────
export const BottomNavItem = styled(ListItemButton)(() => ({
  borderRadius: "8px",
  padding: "8px 12px",
  minHeight: 38,
  gap: "12px",
  color: "#6b7280",
  "&:hover": {
    backgroundColor: "rgba(249,250,251,0.8)",
    color: "#374151",
  },
  transition: "all 0.15s ease",
}));
