INSERT INTO mstr_service_policy_template_fields (
    field_name,
    field_type,
    claim_type,
    entity_type,
    is_active
)
VALUES
    ('SL NO',                       'STRING', 'GMC', 'tpa_upload', true),
    ('Endorsement Type',             'STRING', 'GMC', 'tpa_upload', true),
    ('Employee Number',              'STRING', 'GMC', 'tpa_upload', true),
    ('Insured Name',                 'STRING', 'GMC', 'tpa_upload', true),
    ('Relation',                     'STRING', 'GMC', 'tpa_upload', true),
    ('Gender',                       'STRING', 'GMC', 'tpa_upload', true),
    ('Date of Birth',                'DATE',   'GMC', 'tpa_upload', true),
    ('Age',                          'NUMBER', 'GMC', 'tpa_upload', true),
    ('Mobile Number',                'STRING', 'GMC', 'tpa_upload', true),
    ('Email',                        'STRING', 'GMC', 'tpa_upload', true),
    ('Designation',                  'STRING', 'GMC', 'tpa_upload', true),
    ('CTC',                          'NUMBER', 'GMC', 'tpa_upload', true),
    ('Marital Status',               'STRING', 'GMC', 'tpa_upload', true),
    ('No of Beneficiaries',          'NUMBER', 'GMC', 'tpa_upload', true),
    ('Claim Status',                 'STRING', 'GMC', 'tpa_upload', true),
    ('Policy Number',                'STRING', 'GMC', 'tpa_upload', true),
    ('Policy Name',                  'STRING', 'GMC', 'tpa_upload', true),
    ('Policy Type',                  'STRING', 'GMC', 'tpa_upload', true),
    ('Policy From',                  'DATE',   'GMC', 'tpa_upload', true),
    ('Policy To',                    'DATE',   'GMC', 'tpa_upload', true),
    ('TPA Code',                     'STRING', 'GMC', 'tpa_upload', true),
    ('TPA Name',                     'STRING', 'GMC', 'tpa_upload', true),
    ('Date of Joining',              'DATE',   'GMC', 'tpa_upload', true),
    ('Date of Exit',                 'DATE',   'GMC', 'tpa_upload', true),
    ('Total Net Premium',            'NUMBER', 'GMC', 'tpa_upload', true),
    ('Total Gross Premium',          'NUMBER', 'GMC', 'tpa_upload', true),
    ('GST Percentage',               'NUMBER', 'GMC', 'tpa_upload', true),
    ('Total SI',                     'NUMBER', 'GMC', 'tpa_upload', true),
    ('Applicable Days',              'NUMBER', 'GMC', 'tpa_upload', true),
    ('Company Code',                 'STRING', 'GMC', 'tpa_upload', true),
    ('Company Name',                 'STRING', 'GMC', 'tpa_upload', true),
    ('Company Annual Premium',       'NUMBER', 'GMC', 'tpa_upload', true),
    ('Company Contact Information',  'STRING', 'GMC', 'tpa_upload', true),
    ('Company Location',             'STRING', 'GMC', 'tpa_upload', true);
