-- Sample data for mstr_ext_application_ref table
-- This demonstrates how to configure external applications for SSO integration
-- Create mstr_ext_application_ref

CREATE TABLE IF NOT EXISTS public.mstr_ext_application_ref
(
    id BIGSERIAL PRIMARY KEY,

    label TEXT NOT NULL,

    verification_token_api_url TEXT NOT NULL,
    verification_token_api_method VARCHAR(10) NOT NULL,
    verification_token_api_payload JSONB,

    magic_url_api_url TEXT NOT NULL,
    magic_url_api_method VARCHAR(10) NOT NULL,
    magic_url_api_payload JSONB,

    container_category TEXT NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    iss TEXT NOT NULL DEFAULT 'iwork',
    email TEXT,
    expires_in VARCHAR(20) NOT NULL DEFAULT '10m',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



-- Insert sample external application configurations
INSERT INTO mstr_ext_application_ref 
(
    label, 
    description, 
    verification_token_api_url, 
    verification_token_api_method, 
    verification_token_api_payload, 
    magic_url_api_url, 
    magic_url_api_method, 
    magic_url_api_payload, 
    container_category, 
    is_active, 
    iss, 
    email, 
    expires_in
)
VALUES 
(
    'iconnect',
    'External Analytics and Reporting Portal',
    'https://servicesapi.isbsindia.in/api/sso/iConnect/verify-user',
    'POST',
    '{
        "userEmail": "{{userEmail}}",
        "appId": "iwork",
        "timestamp": "{{timestamp}}"
    }'::jsonb,
    'https://servicesapi.isbsindia.in/api/sso/iConnect/generate-magic-link',
    'POST',
    '{
        "verificationToken": "{{verificationToken}}",
        "redirectTo": "/dashboard"
    }'::jsonb,
    'iconnect',
    true,
    'iwork',
    'admin@indiainsure.com',
    '10m'
);

INSERT INTO public.mstr_ext_application_ref (
id,
    label,
    description,
    verification_token_api_url,
    verification_token_api_method,
    verification_token_api_payload,
    magic_url_api_url,
    magic_url_api_method,
    magic_url_api_payload,
    container_category,
    is_active,
    created_at,
    updated_at,
    iss,
    email,
    expires_in,
    created_by,
    updated_by
)
VALUES (
	2,
    'poppins', 
    'Poppins SSO integration using JWT and magic link flow',
    'https://servicesapi.isbsindia.in/api/sso/poppins/verify-user',
    'POST',
    '{"email":"<poppins user email>"}',
    'https://servicesapi.isbsindia.in/api/sso/poppins/generate-magic-link',
    'POST',
    '{"verificationToken":"<POPPINS_VERIFICATION_JWT>"}',
    'Poppins', 
    true,
    NOW(),
    NOW(),
    'iwork',
    'iwork.poppins@indiainsure.com',
    300,
    '1',
    '1'
);


INSERT INTO public.mstr_ext_application_ref
(
    label,
    description,
    verification_token_api_url,
    verification_token_api_method,
    verification_token_api_payload,
    magic_url_api_url,
    magic_url_api_method,
    magic_url_api_payload,
    container_category,
    iss,
    admin_email,
    expires_in,
    created_by,
    updated_by,
    auth_type,
    step1_response_token_key,
    step2_response_data_key
)
VALUES
(
    'ecard',
    'Good Health TPA E-Card Integration',

    -- Login API
    'https://webace.goodhealthtpa.in:8081/mbt-prod/validateCredentials',
    'POST',
    '{
        "userName": "{{userName}}",
        "password": "{{password}}",
        "encrptedKey": "{{encrptedKey}}"
    }'::jsonb,

    -- E-Card API
    'https://webace.goodhealthtpa.in:8081/mbt-prod/download/GetFamilyMemberECard',
    'POST',
    '{
        "policyNumber": "{{policyNumber}}",
        "policyCommencementDate": "{{policyCommencementDate}}",
        "policyValideUpdate": "{{policyValideUpdate}}",
        "tpaId": "{{tpaId}}"
    }'::jsonb,

    'ecard',
    'ibp',
    'admin@indiainsure.com',
    '10m',
    1,
    1,
    'SESSION',
    'sessionToken',
    'ECARD_DOWNLOAD_URL'
);


--Alter scripts

ALTER TABLE mstr_ext_application_ref
ADD COLUMN created_by INTEGER;

ALTER TABLE mstr_ext_application_ref
ADD COLUMN updated_by INTEGER;

ALTER TABLE mstr_ext_application_ref
ALTER COLUMN email TYPE VARCHAR(55);

--changing id column from BIGSERIAL to SERIAL

SELECT MAX(id) FROM mstr_ext_application_ref;

ALTER TABLE mstr_ext_application_ref
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE mstr_ext_application_ref
ALTER COLUMN id TYPE INTEGER;

DROP SEQUENCE IF EXISTS mstr_ext_application_ref_id_seq;

ALTER TABLE mstr_ext_application_ref
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.mstr_ext_application_ref
DROP COLUMN email;

ALTER TABLE public.mstr_ext_application_ref
ALTER COLUMN iss DROP DEFAULT;

UPDATE public.mstr_ext_application_ref
SET label = LOWER(label),
    updated_at = NOW()
WHERE id = 2;


-- Determines the authentication strategy
ALTER TABLE mstr_ext_application_ref 
ADD COLUMN auth_type VARCHAR(20) NOT NULL DEFAULT 'JWT';
-- 'JWT'     = generate JWT internally → use in both steps as Bearer
-- 'SESSION' = no JWT; step 1 is credential-based → step 1 response token used as Bearer in step 2
-- What key to extract from step 1 response
ALTER TABLE mstr_ext_application_ref 
ADD COLUMN step1_response_token_key VARCHAR(100) NOT NULL DEFAULT 'verificationToken';
-- existing apps: 'verificationToken'
-- good health:   'sessionToken'
-- What key to extract from step 2 response
ALTER TABLE mstr_ext_application_ref 
ADD COLUMN step2_response_data_key VARCHAR(100) NOT NULL DEFAULT 'magicLink';
-- existing apps: 'magicLink'
-- good health:   'ECARD_DOWNLOAD_URL'

-- Update iConnect payload templates to match actual code
UPDATE mstr_ext_application_ref 
SET 
    verification_token_api_payload = '{"email": "{{userEmail}}"}'::jsonb,
    magic_url_api_payload = '{"verificationToken": "{{step1Token}}", "expiresInSeconds": "{{expiresIn}}"}'::jsonb,
    updated_at = NOW()
WHERE label = 'iconnect';

-- Update Poppins payload templates to match actual code
UPDATE mstr_ext_application_ref
SET
    verification_token_api_payload = '{"email": "{{userEmail}}"}'::jsonb,
    magic_url_api_payload = '{"verificationToken": "{{step1Token}}", "expiresInSeconds": "{{expiresIn}}"}'::jsonb,
    updated_at = NOW()
WHERE label = 'poppins';


-- ── Good Health TPA: clean up all previous ecard entries and insert final one ──

DELETE FROM public.mstr_ext_application_ref WHERE label IN ('ecard', 'ecard-tpaid', 'hospital-info', 'tpa-claims');


-- Good Health TPA E-Card (SESSION flow)
-- Step 1: Login via validateCredentials → returns sessionToken
-- Step 2: GetEcard via TPA ID, sessionToken sent as Bearer header
INSERT INTO public.mstr_ext_application_ref (
    label,
    description,
    auth_type,
    verification_token_api_url,
    verification_token_api_method,
    verification_token_api_payload,
    magic_url_api_url,
    magic_url_api_method,
    magic_url_api_payload,
    container_category,
    is_active,
    iss,
    expires_in,
    step1_response_token_key,
    created_by,
    updated_by
) VALUES (
    'ecard-tpaid',
    'Good Health TPA - Login then Get E-Card by TPA ID',
    'SESSION',
    'https://webace.goodhealthtpa.in:8081/mbt-prod/validateCredentials',
    'POST',
    '{
        "userName": "IIRMHO",
        "password": "IIRMHO",
        "encrptedKey": "W{dH:}4eX!@hT%cBSY)!-7$#L6HC2"
    }'::jsonb,
    'https://webserv.goodhealthtpa.in/api/Intermediary/GetEcard',
    'POST',
    '{
        "UserName": "IIRMHO",
        "Password": "IIRMHO",
        "PolicyNo": "",
        "EmployeeNo": "",
        "TPAId": "{{tpaId}}"
    }'::jsonb,
    'ecard',
    true,
    'ibp',
    '10m',
    'sessionToken',
    1,
    1
);