// Generated by Copilot
import { useState } from "react";
import { Box, Collapse, Typography } from "@mui/material";
import { ChevronRight } from "lucide-react";
import {
  HOSPITALS,
  RANK_STYLES,
  INIT_BG,
  INIT_TEXT,
  fmtINR,
  fmtL,
} from "../../pages/HRPortalHospitals/data";
import { RankCard, RankBadge, DrilldownPanel, BreakdownBar } from "./styles";
import {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
} from "../../pages/HRPortal/styles";
import { useLocalization } from "@ui/ui-lib";

const TOP_N = 6;

export function HospitalClaimsTab() {
  const { localizationData } = useLocalization();
  const [_selectedId, _setSelectedId] = useState<string | null>(null);

  const _top6 = [...HOSPITALS]
    .sort((a, b) => b.totalClaims - a.totalClaims)
    .slice(0, TOP_N);
  const _selected = HOSPITALS.find((h) => h.id === _selectedId) ?? null;
  const _grandTotal = _top6.reduce((s, h) => s + h.totalAmount, 0);

  const _handleSelect = (id: string) => {
    _setSelectedId((prev) => (prev === id ? null : id));
  };

  return (
    <Box>
      <Box sx={{ mb: 3 }}>
        <Typography sx={{ fontSize: 20, fontWeight: 700, color: "#111827" }}>
          Claims by Hospital
        </Typography>
        <Typography sx={{ fontSize: 13, color: "#6b7280", mt: 0.25 }}>
          Top {TOP_N} hospitals by claims volume · Click a card to drill down
        </Typography>
      </Box>

      <SectionCard sx={{ p: 0, overflow: "hidden" }}>
        {/* ── Top-6 ranked cards ──────────────────────────────────────── */}
        <Box
          sx={{
            p: 2.5,
            display: "grid",
            gridTemplateColumns: "repeat(3, 1fr)",
            gap: 2,
          }}
        >
          {_top6.map((h, idx) => {
            const _s = RANK_STYLES[idx] ?? RANK_STYLES[3];
            const _active = _selectedId === h.id;
            const _pct = Math.round((h.totalAmount / _grandTotal) * 100);

            return (
              <RankCard
                key={h.id}
                borderColor={_s.border}
                bgColor={_s.bg}
                active={_active}
                onClick={() => _handleSelect(h.id)}
              >
                {/* Card header */}
                <Box
                  sx={{
                    display: "flex",
                    alignItems: "flex-start",
                    justifyContent: "space-between",
                    mb: 2,
                  }}
                >
                  <Box
                    sx={{ display: "flex", alignItems: "center", gap: 1.25 }}
                  >
                    <RankBadge rankBg={_s.rankBg}>{idx + 1}</RankBadge>
                    <Box
                      sx={{
                        width: 30,
                        height: 30,
                        borderRadius: "8px",
                        backgroundColor: INIT_BG[h.initials] ?? "#f3f4f6",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                      }}
                    >
                      <Typography
                        sx={{
                          fontSize: 10,
                          fontWeight: 700,
                          color: INIT_TEXT[h.initials] ?? "#374151",
                        }}
                      >
                        {h.initials}
                      </Typography>
                    </Box>
                    <Box sx={{ minWidth: 0 }}>
                      <Typography
                        sx={{
                          fontSize: 12.5,
                          fontWeight: 700,
                          color: "#111827",
                          lineHeight: 1.2,
                        }}
                      >
                        {h.name}
                      </Typography>
                      <Typography sx={{ fontSize: 10.5, color: "#6b7280" }}>
                        {h.city}
                      </Typography>
                    </Box>
                  </Box>
                  <ChevronRight
                    size={14}
                    color={_active ? "#2563eb" : "#d1d5db"}
                    style={{
                      transform: _active ? "rotate(90deg)" : "none",
                      transition: "transform 0.2s",
                      flexShrink: 0,
                    }}
                  />
                </Box>

                {/* Stats */}
                <Box
                  sx={{
                    display: "grid",
                    gridTemplateColumns: "1fr 1fr",
                    gap: 1.5,
                    mb: 1.5,
                  }}
                >
                  <Box>
                    <Typography
                      sx={{ fontSize: 10, color: "#9ca3af", mb: 0.25 }}
                    >
                      Total Claims
                    </Typography>
                    <Typography
                      sx={{
                        fontSize: 17,
                        fontWeight: 700,
                        color: _s.numColor,
                        lineHeight: 1,
                      }}
                    >
                      {h.totalClaims}
                    </Typography>
                  </Box>
                  <Box>
                    <Typography
                      sx={{ fontSize: 10, color: "#9ca3af", mb: 0.25 }}
                    >
                      Total Amount
                    </Typography>
                    <Typography
                      sx={{
                        fontSize: 13,
                        fontWeight: 700,
                        color: "#374151",
                        lineHeight: 1,
                      }}
                    >
                      {fmtL(h.totalAmount, localizationData?.data)}
                    </Typography>
                  </Box>
                </Box>

                {/* Progress bar */}
                <Box sx={{ mb: 0.5 }}>
                  <Box
                    sx={{
                      display: "flex",
                      justifyContent: "space-between",
                      mb: 0.5,
                    }}
                  >
                    <Typography sx={{ fontSize: 9.5, color: "#9ca3af" }}>
                      Share of top-6
                    </Typography>
                    <Typography
                      sx={{ fontSize: 9.5, fontWeight: 600, color: "#374151" }}
                    >
                      {_pct}%
                    </Typography>
                  </Box>
                  <BreakdownBar pct={_pct} />
                </Box>

                <Typography sx={{ fontSize: 9, color: "#9ca3af", mt: 0.75 }}>
                  Top condition: {h.topDisease}
                </Typography>
              </RankCard>
            );
          })}
        </Box>

        {/* ── Drilldown panel ──────────────────────────────────────────── */}
        <Collapse in={Boolean(_selected)} unmountOnExit>
          {_selected && (
            <DrilldownPanel>
              {/* Panel header */}
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 2, mb: 2.5 }}
              >
                <Box
                  sx={{
                    width: 38,
                    height: 38,
                    borderRadius: "10px",
                    backgroundColor: "#dbeafe",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexShrink: 0,
                  }}
                >
                  <Typography
                    sx={{ fontSize: 11, fontWeight: 700, color: "#2563eb" }}
                  >
                    {_selected.initials}
                  </Typography>
                </Box>
                <Box sx={{ flex: 1 }}>
                  <Typography
                    sx={{ fontSize: 15, fontWeight: 700, color: "#111827" }}
                  >
                    {_selected.name} — Claim Breakdown
                  </Typography>
                  <Typography sx={{ fontSize: 12, color: "#6b7280" }}>
                    {_selected.city}, {_selected.state} · {_selected.type}
                  </Typography>
                </Box>
                <Box sx={{ display: "flex", gap: 3 }}>
                  {[
                    {
                      label: "Total Claims",
                      value: String(_selected.totalClaims),
                    },
                    {
                      label: "Total Amount",
                      value: fmtL(_selected.totalAmount, localizationData?.data),
                    },
                    { label: "Avg Claim", value: fmtINR(_selected.avgAmount, localizationData?.data) },
                    { label: "Approval", value: `${_selected.approvalRate}%` },
                  ].map(({ label, value }) => (
                    <Box key={label} sx={{ textAlign: "right" }}>
                      <Typography sx={{ fontSize: 10, color: "#9ca3af" }}>
                        {label}
                      </Typography>
                      <Typography
                        sx={{ fontSize: 14, fontWeight: 700, color: "#111827" }}
                      >
                        {value}
                      </Typography>
                    </Box>
                  ))}
                </Box>
              </Box>

              {/* Breakdown table */}
              <Box
                sx={{
                  borderRadius: "10px",
                  border: "1px solid #e5e7eb",
                  overflow: "hidden",
                }}
              >
                <StyledTable>
                  <thead>
                    <tr>
                      <StyledTh>Condition</StyledTh>
                      <StyledTh style={{ textAlign: "right" }}>Claims</StyledTh>
                      <StyledTh style={{ textAlign: "right" }}>Amount</StyledTh>
                      <StyledTh style={{ textAlign: "right" }}>
                        Avg Days
                      </StyledTh>
                      <StyledTh>Share</StyledTh>
                    </tr>
                  </thead>
                  <tbody>
                    {_selected.claimBreakdown.map((b) => {
                      const _pct = Math.round(
                        (b.count / _selected.totalClaims) * 100,
                      );
                      return (
                        <tr key={b.condition}>
                          <StyledTd sx={{ fontWeight: 500, color: "#374151" }}>
                            {b.condition}
                          </StyledTd>
                          <StyledTd
                            style={{ textAlign: "right" }}
                            sx={{ fontWeight: 700, color: "#111827" }}
                          >
                            {b.count}
                          </StyledTd>
                          <StyledTd style={{ textAlign: "right" }}>
                            {fmtINR(b.amount, localizationData?.data)}
                          </StyledTd>
                          <StyledTd style={{ textAlign: "right" }}>
                            {b.avgDays}d
                          </StyledTd>
                          <StyledTd sx={{ minWidth: 140 }}>
                            <Box
                              sx={{
                                display: "flex",
                                alignItems: "center",
                                gap: 1,
                              }}
                            >
                              <BreakdownBar pct={_pct} sx={{ flex: 1 }} />
                              <Typography
                                sx={{
                                  fontSize: 11,
                                  fontWeight: 600,
                                  color: "#374151",
                                  minWidth: 28,
                                }}
                              >
                                {_pct}%
                              </Typography>
                            </Box>
                          </StyledTd>
                        </tr>
                      );
                    })}
                  </tbody>
                </StyledTable>
              </Box>
            </DrilldownPanel>
          )}
        </Collapse>
      </SectionCard>
    </Box>
  );
}

export default HospitalClaimsTab;
