// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box } from "@mui/material";

export const RankCard = styled(Box, {
  shouldForwardProp: (p) =>
    p !== "borderColor" && p !== "bgColor" && p !== "active",
})<{ borderColor?: string; bgColor?: string; active?: boolean }>(
  ({ borderColor = "#e5e7eb", bgColor = "#fff", active }) => ({
    textAlign: "left",
    padding: "16px",
    borderRadius: "14px",
    border: `2px solid ${active ? "#2563eb" : borderColor}`,
    backgroundColor: active ? "#eff6ff" : bgColor,
    cursor: "pointer",
    transition: "all 0.18s",
    boxShadow: active ? "0 4px 16px rgba(37,99,235,0.12)" : "none",
    "&:hover": {
      boxShadow: active
        ? "0 4px 16px rgba(37,99,235,0.12)"
        : "0 2px 8px rgba(0,0,0,0.06)",
    },
  }),
);

export const RankBadge = styled(Box, {
  shouldForwardProp: (p) => p !== "rankBg",
})<{ rankBg?: string }>(({ rankBg = "#6b7280" }) => ({
  width: 20,
  height: 20,
  borderRadius: "50%",
  backgroundColor: rankBg,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 10,
  fontWeight: 700,
  color: "#fff",
  flexShrink: 0,
}));

export const DrilldownPanel = styled(Box)(({ theme }) => ({
  borderTop: `1px solid ${theme.palette.neutral.tableBorder}`,
  padding: theme.spacing(2.5, 3),
  backgroundColor: "#fafafa",
}));

export const BreakdownBar = styled(Box, {
  shouldForwardProp: (p) => p !== "pct",
})<{ pct?: number }>(({ pct = 0 }) => ({
  height: 6,
  borderRadius: 3,
  backgroundColor: "#e5e7eb",
  position: "relative" as const,
  overflow: "hidden",
  "&::after": {
    content: '""',
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    width: `${pct}%`,
    backgroundColor: "#3b82f6",
    borderRadius: 3,
    transition: "width 0.4s ease",
  },
}));
