// Generated by Copilot
import React, { useEffect } from "react";
import { capitalizeFirst } from "../../utils";
import { Box, Drawer } from "@mui/material";
import {
    useLocalization,
    formatAmountWithCurrency,
    type LocalizationConfig,
} from "@ui/ui-lib";
import {
    X,
    User,
    Shield,
    CheckCircle2,
    Building2,
    FileText,
    Calendar,
    Banknote,
    CreditCard,
} from "lucide-react";
import {
    DrawerHeader,
    DrawerHeaderLeft,
    DrawerClaimIconBox,
    DrawerMetaLabel,
    DrawerClaimNo,
    DrawerHeaderRight,
    DrawerCloseBtn,
    ClaimStatusBadge,
    ClaimTypeBadge,
    TATBadge,
    QuickStripRoot,
    QuickStripItem,
    QuickStripLabel,
    QuickStripValue,
    TimelineRoot,
    TimelineSection,
    TimelineIconCol,
    TimelineIconCircle,
    TimelineConnector,
    TimelineCardRoot,
    TimelineCard,
    TimelineCardHeader,
    TimelineCardHeaderLeft,
    TimelineCardTitle,
    TimelineCardDateChip,
    TimelineCardBody,
    DetailGrid,
    DetailDt,
    DetailDd,
    SectionBadge,
    ProviderCardSection,
    ProviderCard,
    ProviderCardHeader,
    ProviderCardTitle,
    ProviderCardBody,
    ProviderItem,
    ProviderIconBox,
    ProviderItemLabel,
    ProviderItemValue,
    type ClaimStatus,
} from "./styles";

// ─── Types ────────────────────────────────────────────────────────────────────
export type { ClaimStatus };

export interface ClaimRecord {
    id: string;
    empId: string;
    empName: string;
    dept: string;
    relation: string;
    tpaId: string;
    claimType: "Cashless" | "Reimbursement";
    claimDate: string;
    claimAmount: string;
    claimAmountExact: string;
    settledAmount: string;
    settledAmountExact: string;
    status: ClaimStatus;
    tat: number;
}

// ─── Mock enrichment helpers ──────────────────────────────────────────────────
const MOCK_HOSPITALS = [
    { name: "Apollo Hospitals", city: "Chennai" },
    { name: "Fortis Healthcare", city: "Delhi" },
    { name: "Max Super Speciality Hospital", city: "Delhi" },
    { name: "Manipal Hospitals", city: "Bangalore" },
    { name: "Narayana Health", city: "Bangalore" },
    { name: "Kokilaben Dhirubhai Ambani Hospital", city: "Mumbai" },
    { name: "Medanta – The Medicity", city: "Gurugram" },
    { name: "AIIMS", city: "New Delhi" },
];

const MOCK_AILMENTS: Record<string, string> = {
    Self: "Coronary Artery Disease",
    Spouse: "Acute Appendicitis",
    Child: "Viral Fever with Respiratory Distress",
    Parent: "Orthopedic Surgery – Knee Replacement",
};

const MALE_NAMES = new Set([
    "Rahul", "Arun", "Karan", "Vijay", "Suresh", "Ramesh",
    "Nikhil", "Harish", "Sanjay", "Mahesh", "Vikram", "Arjun",
    "Rohit", "Deepak", "Anil",
]);

function buildDetail(c: ClaimRecord, localization?: LocalizationConfig) {
    const hashNum = parseInt(c.id.replace(/\D/g, ""), 10);
    const hospital = MOCK_HOSPITALS[hashNum % MOCK_HOSPITALS.length];

    const parseDateStr = (s: string): Date => {
        const [day, mon, yr] = s.split(" ");
        return new Date(`${mon} ${day}, ${yr}`);
    };
    const addDays = (d: Date, n: number): string =>
        new Date(d.getTime() + n * 86_400_000).toLocaleDateString("en-IN", {
            day: "2-digit",
            month: "short",
            year: "numeric",
        });

    const admDate = parseDateStr(c.claimDate);

    const firstName = c.empName.split(" ")[0];
    const empGender: "Male" | "Female" = MALE_NAMES.has(firstName) ? "Male" : "Female";
    let depGender: "Male" | "Female";
    if (c.relation === "Spouse") depGender = empGender === "Male" ? "Female" : "Male";
    else if (c.relation === "Child") depGender = "Male";
    else if (c.relation === "Parent") depGender = empGender === "Male" ? "Male" : "Female";
    else depGender = empGender;

    // Parse a formatted currency string (e.g. "₹85,000" or "Rs 85,000") → 85000
    const rawAmt = parseInt(c.claimAmountExact.replace(/[^0-9]/g, ""), 10) || 0;
    const notPayable = Math.round(rawAmt * 0.007);
    const cashlessAmt = c.claimType === "Cashless" ? Math.round(rawAmt * 0.9) : 0;
    const fmtINR = (n: number) => `${formatAmountWithCurrency(n, localization)}`;

    const isPaid = c.status === "Paid";
    const isDenied = c.status === "Rejected" || c.status === "Denied";
    const policyNumber = `OG-2025-8403-${c.empId.replace(/\D/g, "").padStart(4, "0")}`;

    return {
        beneficiaryName: c.relation === "Self" ? c.empName : `Dependent of ${c.empName}`,
        proposerName: c.empName,
        proposerNumber: c.empId,
        relation: c.relation,
        gender: depGender,
        insuranceCo: "Bajaj Allianz General Insurance Co. Ltd.",
        policyNumber,
        policyPeriod: "01/04/2025 To 31/03/2026",
        tpaId: c.tpaId,
        groupName: "IIRM Corporate Private Limited",
        claimNumber: c.id,
        cashlessStatus: isPaid ? "Approved" : isDenied ? "Denied" : c.status,
        denialDate: isDenied ? addDays(admDate, 5) : "—",
        admissionDate: c.claimDate,
        dischargeDate: addDays(admDate, 2),
        reportedDate: c.claimDate,
        providerName: `${hospital.name}, ${hospital.city}`,
        ailment: MOCK_AILMENTS[c.relation] ?? "General Medical Condition",
        claimExtension: "—",
        estimatedAmount: c.claimAmountExact,
        cashlessAmount: fmtINR(cashlessAmt),
        billReceivedDate: isPaid ? addDays(admDate, 10) : "—",
        finalBillAmount: c.claimAmountExact,
        notPayable: fmtINR(notPayable),
        serviceTax: fmtINR(0),
        deductionReasons: notPayable > 0 ? "Non-medical expenses deducted" : "—",
        paymentDate: isPaid ? addDays(admDate, 18) : "—",
        amountPaidToProvider: isPaid ? c.settledAmountExact : fmtINR(0),
        cheqNo: isPaid ? `CHQ-BJ-${c.empId.replace(/\D/g, "")}-25` : "—",
        tdsAmount: "—",
        paidOn: isPaid ? addDays(admDate, 18) : null,
        hospital: hospital.name,
        city: hospital.city,
        department: c.dept,
        diagnosis: MOCK_AILMENTS[c.relation] ?? "General Medical Condition",
        rawAmount: rawAmt,
    };
}

// ─── Sub-components ───────────────────────────────────────────────────────────
function Row({ label, value }: { label: string; value: string }) {
    return (
        <Box sx={{ display: "contents" }}>
            <DetailDt>{label}</DetailDt>
            <DetailDd>{value}</DetailDd>
        </Box>
    );
}

interface SectionProps {
    iconBg: string;
    icon: React.ReactNode;
    title: string;
    date?: string | null;
    badge?: { label: string; bg: string; color: string; border: string };
    showConnector?: boolean;
    children: React.ReactNode;
}

function Section({
    iconBg,
    icon,
    title,
    date,
    badge,
    showConnector = true,
    children,
}: SectionProps) {
    return (
        <TimelineSection>
            <TimelineIconCol>
                <TimelineIconCircle iconBg={iconBg}>{icon}</TimelineIconCircle>
                {showConnector && <TimelineConnector />}
            </TimelineIconCol>
            <TimelineCardRoot>
                <TimelineCard>
                    <TimelineCardHeader>
                        <TimelineCardHeaderLeft>
                            <TimelineCardTitle>{title}</TimelineCardTitle>
                            {date && (
                                <TimelineCardDateChip>
                                    <Calendar size={11} />
                                    {date}
                                </TimelineCardDateChip>
                            )}
                        </TimelineCardHeaderLeft>
                        {badge && (
                            <SectionBadge
                                badgeBg={badge.bg}
                                badgeColor={badge.color}
                                badgeBorder={badge.border}
                            >
                                {badge.label}
                            </SectionBadge>
                        )}
                    </TimelineCardHeader>
                    <TimelineCardBody>
                        <DetailGrid>{children}</DetailGrid>
                    </TimelineCardBody>
                </TimelineCard>
            </TimelineCardRoot>
        </TimelineSection>
    );
}

// ─── ClaimDetailDrawer ────────────────────────────────────────────────────────
export interface ClaimDetailDrawerProps {
    claim: ClaimRecord | null;
    open: boolean;
    onClose: () => void;
}

export function ClaimDetailDrawer({ claim, open, onClose }: ClaimDetailDrawerProps) {
    const { localizationData } = useLocalization();

    useEffect(() => {
        const handler = (e: KeyboardEvent) => {
            if (e.key === "Escape") onClose();
        };
        window.addEventListener("keydown", handler);
        return () => window.removeEventListener("keydown", handler);
    }, [onClose]);

    if (!claim) return null;

    const d = buildDetail(claim, localizationData?.data);

    const isPaid = claim.status === "Paid";
    const isRejected = claim.status === "Rejected" || claim.status === "Denied";

    const typeBadge =
        claim.claimType === "Cashless"
            ? { label: "Cashless", bg: "#F5F3FF", color: "#7C3AED", border: "#EDE9FE" }
            : { label: "Reimbursement", bg: "#F0FDFA", color: "#0D9488", border: "#CCFBF1" };

    const paidBadge = isPaid
        ? { label: "Paid", bg: "#DCFCE7", color: "#16A34A", border: "#BBF7D0" }
        : { label: "Pending", color: "#555555", bg: "#F1F5F9", border: "#E2E8F0" };

    const sectionBadge2 = typeBadge;
    const sectionBadge3 = paidBadge;

    const providerItems = [
        { label: "Hospital", value: d.hospital, icon: Building2, iconColor: "#7C3AED", iconBg: "#F5F3FF" },
        { label: "City", value: d.city, icon: CreditCard, iconColor: "#2563EB", iconBg: "#EFF6FF" },
        { label: "Department", value: d.department, icon: FileText, iconColor: "#0D9488", iconBg: "#F0FDFA" },
        { label: "Diagnosis", value: d.diagnosis, icon: Shield, iconColor: "#D97706", iconBg: "#FFFBEB" },
        { label: "Claim Amount", value: d.finalBillAmount, icon: Banknote, iconColor: "#059669", iconBg: "#ECFDF5" },
        { label: "TAT / Age", value: `${claim.tat} days`, icon: Calendar, iconColor: "#DC2626", iconBg: "#FEF2F2" },
    ];

    return (
        <Drawer
            anchor="right"
            open={open}
            onClose={onClose}
            PaperProps={{
                sx: {
                    width: { xs: "100vw", sm: "min(90vw, 680px)" },
                    display: "flex",
                    flexDirection: "column",
                    bgcolor: "#F8F9FB",
                },
            }}
        >
            {/* ── Header ── */}
            <DrawerHeader>
                <DrawerHeaderLeft>
                    <DrawerClaimIconBox>
                        <FileText size={15} color="#FFFFFF" />
                    </DrawerClaimIconBox>
                    <Box>
                        <DrawerMetaLabel>Claim Details</DrawerMetaLabel>
                        <DrawerClaimNo>{claim.id}</DrawerClaimNo>
                    </Box>
                </DrawerHeaderLeft>
                <DrawerHeaderRight>
                    <ClaimStatusBadge claimStatus={claim.status}>{claim.status}</ClaimStatusBadge>
                    <ClaimTypeBadge claimType={claim.claimType}>{claim.claimType}</ClaimTypeBadge>
                    <TATBadge tat={claim.tat}>{claim.tat}d</TATBadge>
                    <DrawerCloseBtn onClick={onClose}>
                        <X size={15} />
                    </DrawerCloseBtn>
                </DrawerHeaderRight>
            </DrawerHeader>

            {/* ── Quick Info Strip ── */}
            <QuickStripRoot>
                {[
                    { label: "Employee", value: claim.empName },
                    { label: "ID", value: claim.empId },
                    { label: "Hospital", value: d.hospital },
                    { label: "Amount", value: claim.claimAmount },
                    { label: "TPA", value: claim.tpaId },
                ].map((item) => (
                    <QuickStripItem key={item.label}>
                        <QuickStripLabel>{item.label}</QuickStripLabel>
                        <QuickStripValue>{item.value}</QuickStripValue>
                    </QuickStripItem>
                ))}
            </QuickStripRoot>

            {/* ── Scrollable Body ── */}
            <Box sx={{ flex: 1, overflowY: "auto" }}>
                <TimelineRoot>
                    {/* ── 1. Member Information ── */}
                    <Section
                        iconBg="linear-gradient(135deg, #3B82F6, #1D4ED8)"
                        icon={<User size={18} color="#FFFFFF" />}
                        title="Member Information"
                        showConnector
                    >
                        <Row label="Name of Beneficiary" value={d.beneficiaryName} />
                        <Row label="Name of Insurance Co" value={d.insuranceCo} />
                        <Row label="Name of Proposer / Employee" value={d.proposerName} />
                        <Row label="Policy Number" value={d.policyNumber} />
                        <Row label="Proposer / Employee Number" value={d.proposerNumber} />
                        <Row label="Policy Period" value={d.policyPeriod} />
                        <Row label="Relation" value={capitalizeFirst(d.relation)} />
                        <Row label="TPA ID" value={d.tpaId} />
                        <Row label="Gender" value={d.gender} />
                        <Row label="Group Name" value={d.groupName} />
                    </Section>

                    {/* ── 2. Cashless / Claim Details ── */}
                    <Section
                        iconBg={
                            claim.claimType === "Cashless"
                                ? "linear-gradient(135deg, #38BDF8, #2563EB)"
                                : "linear-gradient(135deg, #2DD4BF, #0D9488)"
                        }
                        icon={<Shield size={18} color="#FFFFFF" />}
                        title={`${claim.claimType} Reported on`}
                        date={d.reportedDate}
                        badge={sectionBadge2}
                        showConnector
                    >
                        <Row label="Claim Number" value={d.claimNumber} />
                        <Row label="Claim Extension" value={d.claimExtension} />
                        <Row label={`${claim.claimType} Status`} value={d.cashlessStatus} />
                        <Row label="Estimated / Reported Amount" value={d.estimatedAmount} />
                        {isRejected && (
                            <Row label={`${claim.claimType} Denial Date`} value={d.denialDate} />
                        )}
                        {!isRejected && <Row label={`${claim.claimType} Denial Date`} value={d.denialDate} />}
                        <Row label={`${claim.claimType} Amount`} value={d.cashlessAmount} />
                        <Row label="Date of Admission" value={d.admissionDate} />
                        <Row label="Date of Discharge" value={d.dischargeDate} />
                        <Row label="Name of Provider" value={d.providerName} />
                        <Row label="" value="" />
                        <Row label="Ailment" value={d.ailment} />
                        <Row label="" value="" />
                    </Section>

                    {/* ── 3. Claim Paid ── */}
                    <Section
                        iconBg={
                            isPaid
                                ? "linear-gradient(135deg, #4ADE80, #16A34A)"
                                : "linear-gradient(135deg, #D1D5DB, #9CA3AF)"
                        }
                        icon={<CheckCircle2 size={18} color="#FFFFFF" />}
                        title="Claim Paid on"
                        date={d.paidOn}
                        badge={sectionBadge3}
                        showConnector
                    >
                        <Row label="Bill Received Date" value={d.billReceivedDate} />
                        <Row label="Date of Payment to Provider" value={d.paymentDate} />
                        <Row label="Final Bill Amount" value={d.finalBillAmount} />
                        <Row label="Amount Paid to Provider" value={d.amountPaidToProvider} />
                        <Row label="Not Payable Expenses" value={d.notPayable} />
                        <Row label="Cheq No of Payment to Provider" value={d.cheqNo} />
                        <Row label="Service Tax Amount" value={d.serviceTax} />
                        <Row label="TDS Amount" value={d.tdsAmount} />
                        <Row label="Deduction Reasons" value={d.deductionReasons} />
                        <Row label="" value="" />
                    </Section>

                    {/* ── 4. Provider & Financials ── */}
                    <ProviderCardSection>
                        <TimelineIconCol>
                            <TimelineIconCircle iconBg="linear-gradient(135deg, #A78BFA, #7C3AED)">
                                <Building2 size={18} color="#FFFFFF" />
                            </TimelineIconCircle>
                        </TimelineIconCol>
                        <Box sx={{ flex: 1, pb: 1 }}>
                            <ProviderCard>
                                <ProviderCardHeader>
                                    <ProviderCardTitle>Provider &amp; Financials</ProviderCardTitle>
                                </ProviderCardHeader>
                                <ProviderCardBody>
                                    {providerItems.map((item) => (
                                        <ProviderItem key={item.label}>
                                            <ProviderIconBox iconColor={item.iconColor} iconBg={item.iconBg}>
                                                <item.icon size={13} />
                                            </ProviderIconBox>
                                            <Box sx={{ minWidth: 0 }}>
                                                <ProviderItemLabel>{item.label}</ProviderItemLabel>
                                                <ProviderItemValue>{item.value}</ProviderItemValue>
                                            </Box>
                                        </ProviderItem>
                                    ))}
                                </ProviderCardBody>
                            </ProviderCard>
                        </Box>
                    </ProviderCardSection>
                </TimelineRoot>
            </Box>
        </Drawer>
    );
}

export default ClaimDetailDrawer;
