// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Typography } from "@mui/material";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { ibpTheme as _theme } from "@ui/ui-lib";

// ─── Drawer Header ─────────────────────────────────────────────────────────────
export const DrawerHeader = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing(2, 3),
    backgroundColor: theme.palette.background.paper,
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    flexShrink: 0,
}));

export const DrawerHeaderLeft = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1.5),
}));

export const DrawerClaimIconBox = styled(Box)(({ theme }) => ({
    width: 32,
    height: 32,
    borderRadius: theme.shape.borderRadii.medium,
    backgroundColor: theme.palette.secondary.selected,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
}));

export const DrawerMetaLabel = styled(Typography)(({ theme }) => ({
    fontSize: "11px",
    color: theme.palette.text.grey,
    fontWeight: theme.typography.fontWeights.medium,
}));

export const DrawerClaimNo = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.palette.neutral.mediumDark,
    fontFamily: "monospace",
    lineHeight: 1.25,
}));

export const DrawerHeaderRight = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1.5),
}));

export const DrawerCloseBtn = styled(Box)(({ theme }) => ({
    width: 32,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.shape.borderRadii.medium,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    color: theme.palette.text.grey,
    cursor: "pointer",
    "&:hover": {
        backgroundColor: "#FEF2F2",
        color: theme.palette.text.error,
    },
}));

// ─── Claim Status / Type / TAT Badges ─────────────────────────────────────────
export type ClaimStatus =
    | "Paid"
    | "Outstanding"
    | "Rejected"
    | "Closed"
    | "Denied"
    | "Processing";

export const ClaimStatusBadge = styled(Box, {
    shouldForwardProp: (p) => p !== "claimStatus",
})<{ claimStatus: ClaimStatus }>(({ theme, claimStatus }) => {
    const map: Record<ClaimStatus, { bg: string; color: string; border: string }> = {
        Paid: {
            bg: theme.palette.background.tabsSelected,
            color: theme.palette.neutral.green,
            border: theme.palette.neutral.tableBorder,
        },
        Outstanding: {
            bg: theme.palette.background.tableHeader,
            color: theme.palette.text.yellow,
            border: theme.palette.neutral.tableBorder,
        },
        Rejected: {
            bg: theme.palette.background.tableHeader,
            color: theme.palette.text.error,
            border: theme.palette.neutral.tableBorder,
        },
        Closed: {
            bg: theme.palette.background.tableHeader,
            color: theme.palette.text.grey,
            border: theme.palette.neutral.tableBorder,
        },
        Denied: {
            bg: theme.palette.background.tableHeader,
            color: theme.palette.text.error,
            border: theme.palette.neutral.tableBorder,
        },
        Processing: {
            bg: theme.palette.background.tabsSelected,
            color: theme.palette.secondary.selected,
            border: theme.palette.neutral.tableBorder,
        },
    };
    const c = map[claimStatus] ?? {
        bg: theme.palette.background.tableHeader,
        color: theme.palette.text.grey,
        border: theme.palette.neutral.tableBorder,
    };
    return {
        display: "inline-flex",
        alignItems: "center",
        padding: `${theme.spacing(0.375)} ${theme.spacing(1.5)}`,
        borderRadius: theme.shape.borderRadii.medium,
        fontSize: theme.typography.fontSizes.xs,
        fontWeight: theme.typography.fontWeights.semiBold,
        backgroundColor: c.bg,
        color: c.color,
        border: `1px solid ${c.border}`,
        whiteSpace: "nowrap" as const,
    };
});

export const ClaimTypeBadge = styled(Box, {
    shouldForwardProp: (p) => p !== "claimType",
})<{ claimType: "Cashless" | "Reimbursement" }>(({ theme, claimType }) => ({
    display: "inline-flex",
    alignItems: "center",
    padding: `${theme.spacing(0.375)} ${theme.spacing(1.5)}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semiBold,
    backgroundColor:
        claimType === "Cashless"
            ? theme.palette.background.tabsSelected
            : theme.palette.background.tableHeader,
    color:
        claimType === "Cashless"
            ? theme.palette.secondary.selected
            : theme.palette.text.grey,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    whiteSpace: "nowrap" as const,
}));

export const TATBadge = styled(Box, {
    shouldForwardProp: (p) => p !== "tat",
})<{ tat: number }>(({ theme, tat }) => ({
    display: "inline-flex",
    alignItems: "center",
    padding: `${theme.spacing(0.375)} ${theme.spacing(1.5)}`,
    borderRadius: theme.shape.borderRadii.medium,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.bold,
    backgroundColor:
        tat <= 14
            ? theme.palette.background.tabsSelected
            : theme.palette.background.tableHeader,
    color:
        tat <= 14
            ? theme.palette.neutral.green
            : tat <= 30
            ? theme.palette.text.yellow
            : theme.palette.text.error,
    whiteSpace: "nowrap" as const,
}));

// ─── Quick Info Strip ──────────────────────────────────────────────────────────
export const QuickStripRoot = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(4),
    padding: theme.spacing(1.5, 3),
    backgroundColor: theme.palette.background.paper,
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    flexShrink: 0,
    overflowX: "auto",
}));

export const QuickStripItem = styled(Box)(({ theme }) => ({
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    gap: theme.spacing(0.25),
}));

export const QuickStripLabel = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    color: theme.palette.text.grey,
    fontWeight: theme.typography.fontWeights.medium,
}));

export const QuickStripValue = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
    whiteSpace: "nowrap" as const,
}));

// ─── Timeline Layout ───────────────────────────────────────────────────────────
export const TimelineRoot = styled(Box)(({ theme }) => ({
    padding: theme.spacing(3),
}));

export const TimelineSection = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(2),
}));

export const TimelineIconCol = styled(Box)(() => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
}));

export const TimelineIconCircle = styled(Box, {
    shouldForwardProp: (p) => p !== "iconBg",
})<{ iconBg: string }>(({ iconBg }) => ({
    width: 40,
    height: 40,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    background: iconBg,
}));

export const TimelineConnector = styled(Box)(({ theme }) => ({
    width: 1,
    flexGrow: 1,
    backgroundColor: theme.palette.neutral.tableBorder,
    marginTop: theme.spacing(0.5),
}));

export const TimelineCardRoot = styled(Box)(({ theme }) => ({
    flex: 1,
    paddingBottom: theme.spacing(3),
}));

export const TimelineCard = styled(Box)(({ theme }) => ({
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape.borderRadii.large,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    overflow: "hidden",
}));

export const TimelineCardHeader = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing(1.75, 2.5),
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    backgroundColor: theme.palette.background.tableHeader,
}));

export const TimelineCardHeaderLeft = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
}));

export const TimelineCardTitle = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
}));

export const TimelineCardDateChip = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(0.5),
    fontSize: "11px",
    color: theme.palette.secondary.selected,
    fontWeight: theme.typography.fontWeights.medium,
}));

export const TimelineCardBody = styled(Box)(({ theme }) => ({
    padding: theme.spacing(2, 2.5),
}));

// ─── Detail Grid (label / value dl-pairs) ─────────────────────────────────────
export const DetailGrid = styled(Box)(() => ({
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    columnGap: 24,
}));

export const DetailDt = styled(Typography)(({ theme }) => ({
    fontSize: "11px",
    fontWeight: theme.typography.fontWeights.medium,
    color: theme.palette.text.grey,
    paddingTop: theme.spacing(0.75),
    paddingBottom: theme.spacing(0.75),
    paddingRight: theme.spacing(2),
    lineHeight: 1.4,
}));

export const DetailDd = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.medium,
    color: theme.palette.neutral.mediumDark,
    paddingTop: theme.spacing(0.75),
    paddingBottom: theme.spacing(0.75),
    lineHeight: 1.4,
    wordBreak: "break-word" as const,
}));

// ─── Section Badge (dynamic bg/color/border) ───────────────────────────────────
export const SectionBadge = styled(Box, {
    shouldForwardProp: (p) =>
        p !== "badgeBg" && p !== "badgeColor" && p !== "badgeBorder",
})<{ badgeBg: string; badgeColor: string; badgeBorder: string }>(
    ({ badgeBg, badgeColor, badgeBorder, theme }) => ({
        padding: `${theme.spacing(0.25)} ${theme.spacing(1.5)}`,
        borderRadius: 20,
        fontSize: theme.typography.fontSizes.xs,
        fontWeight: theme.typography.fontWeights.semiBold,
        backgroundColor: badgeBg,
        color: badgeColor,
        border: `1px solid ${badgeBorder}`,
        whiteSpace: "nowrap" as const,
    }),
);

// ─── Provider Card (bottom standalone) ────────────────────────────────────────
export const ProviderCardSection = styled(Box)(({ theme }) => ({
    display: "flex",
    gap: theme.spacing(2),
}));

export const ProviderCard = styled(Box)(({ theme }) => ({
    flex: 1,
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape.borderRadii.large,
    border: `1px solid ${theme.palette.neutral.tableBorder}`,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    overflow: "hidden",
}));

export const ProviderCardHeader = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    padding: theme.spacing(1.75, 2.5),
    borderBottom: `1px solid ${theme.palette.neutral.tableBorder}`,
    backgroundColor: theme.palette.background.tableHeader,
}));

export const ProviderCardTitle = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
}));

export const ProviderCardBody = styled(Box)(({ theme }) => ({
    padding: theme.spacing(2, 2.5),
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: theme.spacing(2),
}));

export const ProviderItem = styled(Box)(({ theme }) => ({
    display: "flex",
    alignItems: "flex-start",
    gap: theme.spacing(1.25),
}));

export const ProviderIconBox = styled(Box, {
    shouldForwardProp: (p) => p !== "iconColor" && p !== "iconBg",
})<{ iconColor: string; iconBg: string }>(({ iconColor, iconBg }) => ({
    width: 28,
    height: 28,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    backgroundColor: iconBg,
    color: iconColor,
}));

export const ProviderItemLabel = styled(Typography)(({ theme }) => ({
    fontSize: "10px",
    color: theme.palette.text.grey,
    fontWeight: theme.typography.fontWeights.medium,
}));

export const ProviderItemValue = styled(Typography)(({ theme }) => ({
    fontSize: theme.typography.fontSizes.xss,
    fontWeight: theme.typography.fontWeights.semiBold,
    color: theme.palette.neutral.mediumDark,
    lineHeight: 1.3,
    marginTop: 2,
}));
