// Generated by Copilot
import { useState, useMemo } from "react";
import { Box, Typography, IconButton } from "@mui/material";
import {
  Search,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ArrowUpDown,
  X,
  SlidersHorizontal,
  BarChart2,
  Calendar,
  Download,
} from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { ALL_REPORTS, CATEGORIES } from "../HRReports/data";
import { FilterSelect } from "../ReportFilterSelect";
import { ReportBadge } from "../ReportBadge";
import {
  StickyFilterBar,
  FilterBarInner,
  BreadcrumbRow,
  ChartCard,
  StatPill,
  PaginationBtn,
} from "./styles";
import {
  SectionCard,
  StyledTable,
  StyledTh,
  StyledTd,
  SearchBox,
  ActionButton,
} from "../../pages/HRPortal/styles";

// ─── Sort icon ─────────────────────────────────────────────────────────────────
function _SortIcon({
  col,
  sortCol,
  sortDir,
}: {
  col: string;
  sortCol: string | null;
  sortDir: "asc" | "desc";
}) {
  if (sortCol !== col)
    return <ArrowUpDown size={11} color="#d1d5db" style={{ marginLeft: 3 }} />;
  return sortDir === "asc" ? (
    <ChevronUp size={11} color="#2563eb" style={{ marginLeft: 3 }} />
  ) : (
    <ChevronDown size={11} color="#2563eb" style={{ marginLeft: 3 }} />
  );
}

// ─── Constants ─────────────────────────────────────────────────────────────────
const PAGE_SIZE = 10;
const POLICY_YEAR_OPTIONS = ["FY 2025–26", "FY 2024–25", "FY 2023–24"];
const POLICY_OPTIONS = [
  "All Policies",
  "GHI-2025-001",
  "GPA-2025-001",
  "GTL-2025-001",
];
const DEPT_OPTIONS = [
  "All Departments",
  "Engineering",
  "Sales",
  "HR",
  "Finance",
  "Operations",
  "Marketing",
  "IT",
];
const DATE_OPTIONS = [
  "This Year",
  "This Month",
  "Last 3 Months",
  "Last 6 Months",
];

// ─── Props ─────────────────────────────────────────────────────────────────────
interface ReportDetailViewProps {
  reportId: string;
  onBack: () => void;
}

export function ReportDetailView({ reportId, onBack }: ReportDetailViewProps) {
  const _report = ALL_REPORTS.find((r) => r.id === reportId)!;
  const _cat = CATEGORIES.find((c) => c.id === _report.categoryId)!;

  const [_policyYear, _setPolicyYear] = useState("FY 2025–26");
  const [_policyNo, _setPolicyNo] = useState("All Policies");
  const [_department, _setDepartment] = useState("All Departments");
  const [_dateRange, _setDateRange] = useState("This Year");
  const [_tableSearch, _setTableSearch] = useState("");
  const [_sortCol, _setSortCol] = useState<string | null>(null);
  const [_sortDir, _setSortDir] = useState<"asc" | "desc">("asc");
  const [_page, _setPage] = useState(1);

  const _handleSort = (key: string) => {
    if (_sortCol === key) {
      _setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      _setSortCol(key);
      _setSortDir("asc");
    }
    _setPage(1);
  };

  const _filteredRows = useMemo(() => {
    let rows = [..._report.rows];
    if (_tableSearch.trim()) {
      const q = _tableSearch.toLowerCase();
      rows = rows.filter((r) =>
        Object.values(r).some((v) => String(v).toLowerCase().includes(q)),
      );
    }
    if (_sortCol) {
      rows.sort((a, b) => {
        const av = a[_sortCol] ?? "";
        const bv = b[_sortCol] ?? "";
        const an = Number(av);
        const bn = Number(bv);
        if (!isNaN(an) && !isNaN(bn))
          return _sortDir === "asc" ? an - bn : bn - an;
        return _sortDir === "asc"
          ? String(av).localeCompare(String(bv))
          : String(bv).localeCompare(String(av));
      });
    }
    return rows;
  }, [_report.rows, _tableSearch, _sortCol, _sortDir]);

  const _totalPages = Math.max(1, Math.ceil(_filteredRows.length / PAGE_SIZE));
  const _pageRows = _filteredRows.slice(
    (_page - 1) * PAGE_SIZE,
    _page * PAGE_SIZE,
  );

  const _thStyle = {
    fontSize: 11,
    fontWeight: 600,
    color: "#6b7280",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    whiteSpace: "nowrap" as const,
  };

  return (
    <Box>
      {/* Sticky filter bar */}
      <StickyFilterBar>
        <BreadcrumbRow>
          <Box
            component="span"
            onClick={onBack}
            sx={{ cursor: "pointer", "&:hover": { color: "#374151" } }}
          >
            Reports
          </Box>
          <ChevronRight size={12} />
          <Box
            component="span"
            onClick={onBack}
            sx={{ cursor: "pointer", "&:hover": { color: "#374151" } }}
          >
            {_cat.label}
          </Box>
          <ChevronRight size={12} />
          <Box component="span" sx={{ color: "#374151", fontWeight: 600 }}>
            {_report.name}
          </Box>
        </BreadcrumbRow>

        <FilterBarInner>
          <SlidersHorizontal
            size={13}
            color="#9ca3af"
            style={{ flexShrink: 0 }}
          />

          <FilterSelect
            value={_policyYear}
            onChange={(v) => {
              _setPolicyYear(v);
              _setPage(1);
            }}
            options={POLICY_YEAR_OPTIONS}
            icon={Calendar}
          />
          <FilterSelect
            value={_policyNo}
            onChange={(v) => {
              _setPolicyNo(v);
              _setPage(1);
            }}
            options={POLICY_OPTIONS}
          />
          <FilterSelect
            value={_department}
            onChange={(v) => {
              _setDepartment(v);
              _setPage(1);
            }}
            options={DEPT_OPTIONS}
          />
          <FilterSelect
            value={_dateRange}
            onChange={(v) => {
              _setDateRange(v);
              _setPage(1);
            }}
            options={DATE_OPTIONS}
            icon={Calendar}
          />

          <Box sx={{ ml: "auto" }}>
            <SearchBox>
              <Search size={12} color="#9ca3af" />
              <input
                value={_tableSearch}
                onChange={(e) => {
                  _setTableSearch(e.target.value);
                  _setPage(1);
                }}
                placeholder="Search records…"
                style={{ width: 180 }}
              />
              {_tableSearch && (
                <IconButton
                  size="small"
                  onClick={() => _setTableSearch("")}
                  sx={{ p: 0 }}
                >
                  <X size={11} color="#9ca3af" />
                </IconButton>
              )}
            </SearchBox>
          </Box>

          <ActionButton
            sx={{ display: "flex", alignItems: "center", gap: 0.75 }}
          >
            <Download size={12} /> Export
          </ActionButton>
        </FilterBarInner>
      </StickyFilterBar>

      {/* Content */}
      <Box sx={{ pt: 3 }}>
        {/* Title + summary stats */}
        <Box
          sx={{
            display: "flex",
            alignItems: "flex-start",
            justifyContent: "space-between",
            gap: 3,
            mb: 3,
            flexWrap: "wrap",
          }}
        >
          <Box sx={{ display: "flex", alignItems: "flex-start", gap: 2 }}>
            <Box
              sx={{
                width: 40,
                height: 40,
                borderRadius: "12px",
                backgroundColor: _report.accent,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <_report.icon size={20} color={_report.accentText} />
            </Box>
            <Box>
              <Typography
                sx={{ fontSize: 17, fontWeight: 700, color: "#111827" }}
              >
                {_report.name}
              </Typography>
              <Typography sx={{ fontSize: 13, color: "#6b7280", mt: 0.25 }}>
                {_report.description}
              </Typography>
            </Box>
          </Box>

          <Box
            sx={{
              display: "flex",
              alignItems: "stretch",
              gap: 1.5,
              flexWrap: "wrap",
            }}
          >
            {_report.summaryStats.map((s) => (
              <StatPill key={s.label}>
                <Typography sx={{ fontSize: 10.5, color: "#9ca3af", mb: 0.5 }}>
                  {s.label}
                </Typography>
                <Typography
                  sx={{ fontSize: 15, fontWeight: 700, color: "#111827" }}
                >
                  {s.value}
                </Typography>
              </StatPill>
            ))}
          </Box>
        </Box>

        {/* Chart */}
        {_report.chartData && (
          <ChartCard>
            <Box
              sx={{ display: "flex", alignItems: "center", gap: 1, mb: 2.5 }}
            >
              <BarChart2 size={15} color="#9ca3af" />
              <Typography
                sx={{ fontSize: 13, fontWeight: 600, color: "#374151" }}
              >
                {_report.chartLabel}
              </Typography>
            </Box>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={_report.chartData} barSize={20}>
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="#f0f0f0"
                  vertical={false}
                />
                <XAxis
                  dataKey="label"
                  tick={{ fontSize: 11, fill: "#9ca3af" }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  tick={{ fontSize: 11, fill: "#9ca3af" }}
                  axisLine={false}
                  tickLine={false}
                />
                <Tooltip
                  contentStyle={{
                    borderRadius: 10,
                    border: "1px solid #e5e7eb",
                    fontSize: 12,
                    boxShadow: "0 4px 12px rgba(0,0,0,.06)",
                  }}
                  cursor={{ fill: "rgba(0,0,0,.03)" }}
                />
                <Bar
                  dataKey="value"
                  fill={_cat.chartColor}
                  radius={[4, 4, 0, 0]}
                />
              </BarChart>
            </ResponsiveContainer>
          </ChartCard>
        )}

        {/* Table card */}
        <SectionCard sx={{ p: 0, overflow: "hidden" }}>
          <Box sx={{ overflowX: "auto" }}>
            <StyledTable>
              <thead>
                <tr>
                  {_report.columns.map((col) => (
                    <StyledTh
                      key={col.key}
                      style={{
                        ..._thStyle,
                        textAlign:
                          col.align === "right"
                            ? "right"
                            : col.align === "center"
                            ? "center"
                            : "left",
                        cursor: col.sortable ? "pointer" : "default",
                      }}
                      onClick={() => col.sortable && _handleSort(col.key)}
                    >
                      <Box
                        component="span"
                        sx={{ display: "inline-flex", alignItems: "center" }}
                      >
                        {col.label}
                        {col.sortable && (
                          <_SortIcon
                            col={col.key}
                            sortCol={_sortCol}
                            sortDir={_sortDir}
                          />
                        )}
                      </Box>
                    </StyledTh>
                  ))}
                </tr>
              </thead>
              <tbody>
                {_pageRows.length === 0 ? (
                  <tr>
                    <td
                      colSpan={_report.columns.length}
                      style={{ textAlign: "center", padding: "48px 0" }}
                    >
                      <Search
                        size={20}
                        color="#e5e7eb"
                        style={{ display: "block", margin: "0 auto 8px" }}
                      />
                      <Typography sx={{ fontSize: 13, color: "#9ca3af" }}>
                        No records match "{_tableSearch}"
                      </Typography>
                    </td>
                  </tr>
                ) : (
                  _pageRows.map((row, ri) => (
                    <tr key={ri}>
                      {_report.columns.map((col) => {
                        const _val = String(row[col.key] ?? "—");
                        const _isId =
                          col.key.includes("_id") ||
                          col.key === "claim_no" ||
                          col.key === "claim_id";
                        return (
                          <StyledTd
                            key={col.key}
                            style={{
                              textAlign:
                                col.align === "right"
                                  ? "right"
                                  : col.align === "center"
                                  ? "center"
                                  : "left",
                            }}
                          >
                            {col.badge ? (
                              <ReportBadge value={_val} />
                            ) : (
                              <Box
                                component="span"
                                sx={
                                  _isId
                                    ? {
                                        fontFamily: "monospace",
                                        fontSize: 11,
                                        color: "#6b7280",
                                      }
                                    : {}
                                }
                              >
                                {_val}
                              </Box>
                            )}
                          </StyledTd>
                        );
                      })}
                    </tr>
                  ))
                )}
              </tbody>
            </StyledTable>
          </Box>

          {/* Pagination */}
          {_filteredRows.length > PAGE_SIZE && (
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                px: 2.5,
                py: 1.5,
                borderTop: "1px solid #f3f4f6",
                bgcolor: "rgba(249,250,251,0.4)",
              }}
            >
              <Typography sx={{ fontSize: 11, color: "#9ca3af" }}>
                Showing{" "}
                <Box
                  component="span"
                  sx={{ fontWeight: 600, color: "#374151" }}
                >
                  {Math.min((_page - 1) * PAGE_SIZE + 1, _filteredRows.length)}–
                  {Math.min(_page * PAGE_SIZE, _filteredRows.length)}
                </Box>{" "}
                of{" "}
                <Box
                  component="span"
                  sx={{ fontWeight: 600, color: "#374151" }}
                >
                  {_filteredRows.length}
                </Box>{" "}
                records
              </Typography>

              <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
                <PaginationBtn
                  disabled={_page === 1}
                  onClick={() => _setPage((p) => Math.max(1, p - 1))}
                  sx={{ transform: "rotate(90deg)" }}
                >
                  <ChevronDown size={13} />
                </PaginationBtn>

                {Array.from({ length: _totalPages }, (_, i) => i + 1).map(
                  (p) => (
                    <PaginationBtn
                      key={p}
                      active={_page === p}
                      onClick={() => _setPage(p)}
                    >
                      {p}
                    </PaginationBtn>
                  ),
                )}

                <PaginationBtn
                  disabled={_page === _totalPages}
                  onClick={() => _setPage((p) => Math.min(_totalPages, p + 1))}
                  sx={{ transform: "rotate(-90deg)" }}
                >
                  <ChevronDown size={13} />
                </PaginationBtn>
              </Box>
            </Box>
          )}
        </SectionCard>

        <Typography
          sx={{ textAlign: "center", fontSize: 11, color: "#d1d5db", mt: 4 }}
        >
          {_report.name} · {_policyYear} · Generated {_report.lastGenerated} ·
          All times in IST
        </Typography>
      </Box>
    </Box>
  );
}

export default ReportDetailView;
