// Generated by Copilot
import { styled } from "@mui/material/styles";
import { Box, Button } from "@mui/material";

export const StickyFilterBar = styled(Box)({
  position: "sticky",
  top: 0,
  zIndex: 30,
  backgroundColor: "#fff",
  borderBottom: "1px solid #f1f5f9",
  boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
});

export const FilterBarInner = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 0 10px 0",
  flexWrap: "wrap" as const,
});

export const BreadcrumbRow = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: 4,
  fontSize: 11.5,
  color: "#9ca3af",
  paddingTop: 10,
  paddingBottom: 2,
});

export const ChartCard = styled(Box)({
  backgroundColor: "#fff",
  border: "1px solid #e5e7eb",
  borderRadius: 16,
  padding: "20px 24px",
  marginBottom: 20,
  boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
});

export const StatPill = styled(Box)({
  backgroundColor: "#fff",
  border: "1px solid #e5e7eb",
  borderRadius: 12,
  padding: "10px 18px",
  textAlign: "right" as const,
  boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
});

export const PaginationBtn = styled(Button, {
  shouldForwardProp: (p) => p !== "active",
})<{ active?: boolean }>(({ active }) => ({
  minWidth: 28,
  height: 28,
  padding: 0,
  borderRadius: 8,
  fontSize: 12,
  fontWeight: active ? 700 : 400,
  backgroundColor: active ? "#2563eb" : "transparent",
  color: active ? "#fff" : "#6b7280",
  border: active ? "none" : "1px solid transparent",
  "&:hover": {
    backgroundColor: active ? "#1d4ed8" : "#f9fafb",
    borderColor: active ? "none" : "#e5e7eb",
  },
}));
